### ISSUE TITLE
toevoegen vianen

### ISSUE THREAD

**Issue by compujunk** [heyajohnny/afvalinfo#1]
is het mogelijk om Vianen toe te voegen aan afvalinfo

**Comment by heyajohnny** [comment]
Ik ga proberen om dit voor 16 februari voor je te maken...

**Comment by compujunk** [comment]
thanks

**Comment by heyajohnny** [comment]
Ik heb zojuist Vijfheerenlanden toegevoegd aan afvalinfo.
Daaronder valt o.a. Vianen :)

**Comment by compujunk** [comment]
Thanks, het werkt
