### ISSUE TITLE
Westerkwartier - lost ?

### ISSUE THREAD

**Issue by githubnoobjk** [heyajohnny/afvalinfo#101]
Changed city: xxxx to ...
location: Westerkwartier
now status of all three resources is unknown

so now it is : 
- platform: afvalinfo
  resources:                     #  (at least 1 required)
    - restafval
    - textiel
    - gft
  location: Westerkwartier           #      (required, default = sliedrecht)
  postcode: 9804SC           #     (required, default = 3361AB)
  streetnumber: XX              #    (required, default = 1)
  dateformat: '%d-%m-%Y'        #   (optional, default = %d-%m-%Y) day-month-year
  timespanindays: 365           #   (

**Comment by heyajohnny** [comment]
It works just fine when I use this config:
```sensor:
  - platform: afvalinfo
    resources:
      - gft
      - pbd
      - papier
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: westerkwartier
    postcode: 9804SC
    streetnumber: 2
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365

**Comment by githubnoobjk** [comment]
Works now. Don't know where I went wrong. Sorry for that.
