### ISSUE TITLE
Notificaties

### ISSUE THREAD

**Issue by Rocker20** [heyajohnny/afvalinfo#102]
Allereerst super werk tot op heden. Ik gebruik hem in combinatie met auto-entities zodat de containers ook nog op basis van days until collection date worden gesorteerd. Zo staat altijd de eerstvolgende container vooraan.

Heb je toevallig al nagedacht over notificaties? Anders ga ik dit zelf doen met automatiseringen of node-red

**Comment by heyajohnny** [comment]
Volgens mij is het niet mogelijk om notificaties in een sensor van Home Assistant te plaatsen.

Zelf regel ik mijn notificaties via Node-Red + pushover. De automatiseringen in Home Assistant vind ik echt verschrikkelijk :(

**Comment by Rocker20** [comment]
bedankt voor je snelle reactie! dan ga ik zelf een notificatie schrijven:)

**Comment by heyajohnny** [comment]
Ik ga deze melding sluiten, omdat notificaties niet in een sensor gemaakt kan worden en jullie zelf al de oplossing hebben gevonden :)

**Comment by Rocker20** [comment]
Top!
