### ISSUE TITLE
No dates reported back

### ISSUE THREAD

**Issue by ageurtse** [heyajohnny/afvalinfo#105]
Hello, 

Just installed the intergration through hacs. 
In config.yaml i added below sensor:
>- platform: afvalinfo
    resources:
      - pbd
      - papier
      - restafval
      - gft
      - trash_type_today
      - trash_type_tomorrow
    location: Ximmio
    postcode: xxxxxxx      #almelo
    streetnumber: xx
    locale: 'nl'
    dateformat: '%d-%m-%Y'
    timespanindays: 365

when looking in development states i get this data back:
>year_month_day_date: null
last_update: null
hidden: false
days_until_collection_date: null
is_collection_date_today: false
friendly_name: Afvalinfo Papier
icon: 'mdi:recycle'

becaus of paper, if should be picked up at 19-6-2020

**Comment by heyajohnny** [comment]
Please change 'location: Ximmio' to 'location: Almelo'. It should work then.

**Comment by ageurtse** [comment]
I tryed that also, same issu no dates.

**Comment by ageurtse** [comment]
Worked it out, location is now written in small captions. and zipcode is in capital. 
now it is working.

**Comment by heyajohnny** [comment]
That's strange... 
It shouldn't matter if there are uppercases or not, since i'm converting everything to lowercase.
