### ISSUE TITLE
Doesn't detect 2 containers on the same day

### ISSUE THREAD

**Issue by alexdepalex** [heyajohnny/afvalinfo#106]
For Venlo, there's a summer schedule where the GFT container is collected every week, and the PBD container every other week together with the GFT container. When that's the case, only the date of the first container, which is GFT, will be registerend and the rest ignore.

Because of this, in the current schedule, next collection of the PBD is the 31st of August, which is the first date they stop dual collection.

**Comment by heyajohnny** [comment]
I've just pushed an update. Please let me know if that fixed the issue.

**Comment by alexdepalex** [comment]
lgtm. Thanks for fixing this.
