### ISSUE TITLE
Plastic for mijn afvalwijzer not working

### ISSUE THREAD

**Issue by randy993** [heyajohnny/afvalinfo#109]
Heya,

Just implemented this integration in my HA, but I get no value for the 'plastic'. The data is gathered from mijnafvalwijzer.nl.

I get the following error message in HA; ValueError: Unknown format code 'f' for object of type 'str'
2020-06-25 12:29:59 WARNING (SyncWorker_19) [custom_components.afvalinfo.const.const] Something went wrong while splitting data: AttributeError("'NoneType' object has no attribute 'string'"). This probably means that trash type 'pbd' is not supported on your location.

After a bit of research, I found that the HTML structure probably changed, as the code searches for a span-line-break. However, only for plastic, there is none.

`<p class="restafval">
															<span class="span-line-break">vrijdag 03 juli</span>
															<span class="afvaldescr">Restafval</span>
														</p>`

`<p class="plastic">woensdag 15 juli<br>
																<span class="afvaldescr">plastic verpakkingen</span></p>`

**Comment by heyajohnny** [comment]
I just pushed a fix. If it's true what you posted above then it should be fixed.
I just couldn't find  an address with 'plastic'... Please let me know if it fixes the issue

**Comment by randy993** [comment]
Hmm, did not seem to fox the problem. Thanks for the fast response though. An example adress: https://www.mijnafvalwijzer.nl/nl/6931ej/1/.

**Comment by heyajohnny** [comment]
Then the last version should fix your issue. Please let me know if it's fixed.

**Comment by randy993** [comment]
Working like a charm!
