### ISSUE TITLE
Would be nice when you could add Westerkwartier

### ISSUE THREAD

**Issue by githubnoobjk** [heyajohnny/afvalinfo#11]
Our garbage collector is Renewi. Paper, glass and such is collected by Hoeksema's Regionale Milieudiensten :)

**Comment by heyajohnny** [comment]
I'll implement it in the next release. 

Memo to myself: 
-https://westerkwartier.afvalalert.nl/
Aduard
Boerakker
Briltil
De Wilp
Den Ham
Den Horn
Doezum
Enumatil
Ezinge
Feerwerd
Garnwerd
Grijpskerk
Grootegast
Jonkersvaart
Kommerzijl
Kornhorn
Lauwerzijl
Leek
Lettelbert
Lucaswolde

**Comment by heyajohnny** [comment]
I've added Westerkwartier :)
