### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by twelling** [heyajohnny/afvalinfo#113]
Hi suddenly receive this error on two HA instances with afvalinfo 0.5.20 :

Log Details (ERROR)
Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/suez.py:63
Integration: afvalinfo (documentation)
First occurred: 12:06:25 AM (7 occurrences)
Last logged: 6:07:31 AM

Error occurred while fetching data: SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')

Systeminfo:
arch | x86_64
chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.50
python_version | 3.7.7
supervisor | 228
timezone | Europe/Amsterdam
version | 0.112.4
virtualenv | false

**Comment by GitHubxtsnl** [comment]
I also have this issue, running:
Home Assistant 0.112.4
afvalinfo v0.5.20

`Log Details (ERROR)
Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/suez.py:63
Integration: afvalinfo (documentation)
First occurred: July 10, 2020, 7:42:45 PM (70 occurrences)
Last logged: 5:11:44 PM

Error occurred while fetching data: SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')
`

**Comment by heyajohnny** [comment]
The certificate of Suez is invalid I think... I just pushed an update, ignoring an invalid SSL certificate for the Suez URL. 
Please let me know if version Afvalinfo v0.5.21 fixes this issue.

**Comment by twelling** [comment]
Thank you! Works perfectly now again! Groeten!

**Comment by GitHubxtsnl** [comment]
Yes, de update is working, I'm getting data again. Great work!
