### ISSUE TITLE
incorrect "afvaltype" for Blink GFT

### ISSUE THREAD

**Issue by dvdhout** [heyajohnny/afvalinfo#114]
Hi,
Many thanks for your great work!
I'm getting an warning in my homeassistant logfile on the 'gft' garbage type for the blink location.
I think the afvaltype for the 'GFT' should be changed from 78 to 75 in the blink.py file on line 51?
Kind regards,
Dennis

**Comment by heyajohnny** [comment]
Can you please share an address or a screenshot of the 'afvalstroom'. With my test addresses I only see GFT as 78....
![image](https://user-images.githubusercontent.com/20553716/88329992-08042a80-cd2b-11ea-9a45-f9793e2174a4.png)

**Comment by dvdhout** [comment]
Hi,
https://mijnblink.nl/adres/5751MP:1
![image](https://user-images.githubusercontent.com/13355792/88331559-7649ec80-cd2d-11ea-89af-49f6d7f9fbc2.png)

**Comment by heyajohnny** [comment]
Sorry for letting you wait so long, but I had a little time off...
I just pushed a fix where I've added afvalstroom 75 to Blink. This should fix your issue.
Please let me know if all works as expected, after the update ;)

**Comment by dvdhout** [comment]
Hi!
No worries, time off is way more important than in incorrect GFT reference ;-)
I tested it and everything seems to be working fine now!
Thanks a bunch!
