### ISSUE TITLE
Collection date Papier

### ISSUE THREAD

**Issue by willsmarthome** [heyajohnny/afvalinfo#117]
First!:
Great sensor, it's working perfect.

Question:
I'am missing the de collection date for Papier
Is it possible to insert manual and frequenty for collection Paper?

**Comment by heyajohnny** [comment]
I'm sorry, that's not possible. :( This sensor stick to the facts that are coming from the waste collectors. 
Maybe I can add 'Papier' for your location to the sensor if it's available from the waste collector. (It's possible that I've missed it somehow). If you could give me a 'location', 'postcode', 'streetnumber' near you, I can look into it.

**Comment by willsmarthome** [comment]
OK, no problemo.
If you can add it to my location.
Papier is collected on de last wednesday of the month.
Midden Drenthe, 9413 AA, 6

Thanks!

Regards,
Martin

**Comment by heyajohnny** [comment]
I'm sorry. Your municipality doesn't provide the information for 'Papier' as far as I can see [here](https://www.middendrenthe.nl/website/!suite86.scherm0325?mPag=6523&mAlle=J).
Maybe you can use [this](https://github.com/mampfes/hacs_waste_collection_schedule) integration to schedule it manually.

**Comment by heyajohnny** [comment]
I'm closing this issue since I can't fix your issue in this sensor/integration... :(
