### ISSUE TITLE
none result

### ISSUE THREAD

**Issue by berg78** [heyajohnny/afvalinfo#119]
Hi,

i have added your addon, but i keep getting a none result for all the sensors, here is my configuraiton.yaml
(changed the postcode en streetnumber before posting it here).

sensor:
  - platform: afvalinfo
    resources:
      - pbd
      - gft
      - papier
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: beekdaelen
    postcode: 6365BH       
    streetnumber: 99              
    dateformat: '%d-%m-%Y'        
    locale: 'nl'
    timespanindays: 365
    
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"
      restaval_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_restafval', 'days_until_collection_date') }}"

**Comment by heyajohnny** [comment]
I can't seem to find any results on your location from these official waste collectors in Beekdaelen:
https://www.rwm.nl/inwoners/afvalwijzer?zipcode=6365BH&houseNumber=99&addition=&submit=
https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public.aspx?pc=6365BH&nr=99&t=

**Comment by berg78** [comment]
> I can't seem to find any results on your location from these official waste collectors in Beekdaelen:
> https://www.rwm.nl/inwoners/afvalwijzer?zipcode=6365BH&houseNumber=99&addition=&submit=
> https://www.rd4info.nl/NSI/Burger/Aspx/afvalkalender_public.aspx?pc=6365BH&nr=99&t=
> 
> but I can find something for streetnumber 74... https://www.mijnafvalwijzer.nl/nl/6365BH/74/
> I can push an update to let Beekdaelen work with mijnafvalwijzer, but then again, it doesn't work for your streetnumber 99

That's right, because i changed it to a random postcode for this post, the correct postcode should be 6365CS 24
i can find my afvalkalender on: 
https://www.rwm.nl/inwoners/afvalwijzer?zipcode=6365CS&houseNumber=24&addition=&submit=

**Comment by heyajohnny** [comment]
I've just pushed a fix. Can you please let me know if it solves your issue? ;)

**Comment by berg78** [comment]
Hi,
Yes is works now! 

thanks and keep up the good work!
