### ISSUE TITLE
Please add RAD hoeksche waard

### ISSUE THREAD

**Issue by bartandeweg** [heyajohnny/afvalinfo#12]
Would be nice if RAD Hoeksche Waard can be added to the code.

**Comment by remkolems** [comment]
Yes please!

See official site at https://www.radhw.nl/

e.g. 
![image](https://user-images.githubusercontent.com/45675902/75026958-17dac280-549e-11ea-96b2-0739e5d283da.png)

![image](https://user-images.githubusercontent.com/45675902/75027409-d4348880-549e-11ea-9eb4-e73ea1bb3541.png)

**Comment by bartandeweg** [comment]
Closing this as there is an new integration: @remkolems see: https://github.com/Johnwulp/rad-afval
