### ISSUE TITLE
Only partial data

### ISSUE THREAD

**Issue by TheFes** [heyajohnny/afvalinfo#120]
Hello,

I live in 'gemeente' Tilburg, and we have 2 double-rollcontainers for our trash.
They are picked up on Mondays

Next Monday (14th September) the Paper/PMD (PBM in your integration) is scheduled.
The week after, the Restafval/GFT is scheduled

I've installed the integration yesterday via HACS, but it only shows the 21st of September, not the one of the 14th.

Information on afvalwijzer.nl
![image](https://user-images.githubusercontent.com/28803438/92872658-88c7d480-f406-11ea-9af4-dc8a0efbaedf.png)

Sensors in HA
![image](https://user-images.githubusercontent.com/28803438/92872785-a9902a00-f406-11ea-9b56-f510f48610c3.png)

Nothing in my logs (level: warning)

**Comment by heyajohnny** [comment]
I've just pushed a fix. Please let me know if it fixes your issue ;)

**Comment by TheFes** [comment]
Thanks, seems to be working fine now!
![image](https://user-images.githubusercontent.com/28803438/93203312-8215c600-f754-11ea-9b7b-44e0b6051313.png)
