### ISSUE TITLE
Afvalwijzer gaat verdwijnen

### ISSUE THREAD

**Issue by miit86** [heyajohnny/afvalinfo#121]
hoi,

Ik heb begrepen dat json.mijnafvalwijzer.nl gaat verdwijnen. Blijft deze wel werken voor de gemeentes die afvalwijzer gebruiken?

Greetz

Michel

**Comment by heyajohnny** [comment]
Hoi Michel,

Bedankt voor de info. 
Deze sensor maakt geen gebruik van de json.mijnafvalwijzer.nl, maar leest de mijnafvalwijzer.nl webpagina uit, dus dit zou gewoon moeten blijven werken 👍

**Comment by xirixiz** [comment]
Klopt @miit86. Ik heb het component dat ik gemaakt heb (https://github.com/xirixiz/homeassistant-afvalwijzer) gewijzigd naar api.mijnafvalwijzer.nl maar werd helaas teruggefloten door de provider. In het verleden heb ik ook de website "gescraped", maar jouw code ziet er veel netter uit (mijn complimenten voor dit component!). Ik heb daarom de brutale vraag of ik delen van jouw code mag gebruiken in een nieuw component? Dan gaat het alleen om mijnafvalwijzer, meer niet, de andere afvalverwerkers laat ik met rust.

**Comment by heyajohnny** [comment]
@xirixiz 
Bedankt voor het compliment! Uiteraard mag je gewoon mijn code gebruiken :)

> gewijzigd naar api.mijnafvalwijzer.nl maar werd helaas teruggefloten door de provider.
Waarom mag je eigenlijk de api.mijnafvalwijzer.nl niet meer gebruiken?

**Comment by xirixiz** [comment]
Ik heb altijd meer aan de ops kant gezeten en ben daardom ook niet echt een programmeur, maar jouw code is echt heel erg helder en netjes opgebouwd (mijn mening althans) waardoor ik daar weer meer van geleerd heb 👍 .

Maar goed, de api is eigenlijk aleen bedoeld voor betalende en geverifieerde afnemers. Het ligt niet aan de dataverstrekker maar aan de gemeenten die de data niet publiekelijk beschikbaar willen stellen via de api. Heel erg vreemd natuurlijk aangezien het geen persoonsgegevens bevat en de data via de website wel beschikbaar is gesteld.

Lang verhaal kort, de api key is achterhaald, die heb ik vervolgens gebruikt in het component, en dat is dus niet toegestaan. De API key wordt aangepast en de beveiliging aangescherpt.

Wel wordt er onderzocht naar mogelijkheden om het toch aan te bieden in json format, maar eerlijk gezegd heb ik daar niet echt vertrouwen in.

**Comment by xirixiz** [comment]
Ik ga je na het weekend wat koffie geven, dan kan je fris de week starten 😃

**Comment by heyajohnny** [comment]
@xirixiz 
Bedankt voor de update! 👍 

Python is niet mijn standaard taal, dus ik kan hier en daar wat dingen omslachtig gedaan hebben :(  maar ik probeer mijn code wel altijd goed leesbaar te maken.

Probeer je code zo te maken dat je na enkele jaren nog kan begrijpen wat je ooit gemaakt hebt. 
Je kan beter wat beter leesbare code hebben, dan dat je met zo min mogelijk code iets schrijft. 
Dat is althans mijn uitgaanspunt als ik iets maak. 

En natuurlijk hier en daar wat commentaar kan nooit kwaad.

Succes verder met je HA component/integration

**Comment by xirixiz** [comment]
Thanks @heyajohnny! De koffie komt er nog aan hoor, en bedankt voor de tip!

Ik heb het nu hierin "gepropt", maar neem het over een tijd nog wel een keer allemaal onder de loep. Ik wacht het even af of de toegang tot de api nog terugkeert. Hoe dan ook ga ik het nog een keer herschrijven, ik leer toch steeds weer bij dan 😅.

https://github.com/xirixiz/python-afvalwijzer-afvalstoffendienst/blob/master/Afvaldienst/AfvaldienstScraper.py

Nogmaals bedankt, ik heb jouw naam genoemd in de README en code, en de koffie komt de komende dagen ergens 👍
