### ISSUE TITLE
Today/Tomorrow sensor is being reset every minute

### ISSUE THREAD

**Issue by P-Verbrugge** [heyajohnny/afvalinfo#124]
I noticed that the today and tomorrow sensors are being reset every minute. It get's the state unknown before it switches it back to none or the actual trash.

Because of the issue above it's not possible to make an automation that triggers on the state change, as it would be fired every minute.

Would it be possible to load the state from HA and compare it with the new state before changing it? That way the state will not change every minute but only when it is actually changed.

**Comment by heyajohnny** [comment]
I'll try to look into it this week

**Comment by heyajohnny** [comment]
I just pushed a fix. I think this will solve your issue. Can you please let me know if your issue is solved? ;)

**Comment by Smiggel** [comment]
> I just pushed a fix. I think this will solve your issue. Can you please let me know if your issue is solved? ;)

Nice! It seems te be ok now. 👍 Thank you!

**Comment by P-Verbrugge** [comment]
> I just pushed a fix. I think this will solve your issue. Can you please let me know if your issue is solved? ;)

Nice! It seems te be ok now. 👍 Thank you!
