### ISSUE TITLE
add gemeente montferland please

### ISSUE THREAD

**Issue by wilfriedbaars** [heyajohnny/afvalinfo#128]
Hello,

I miss gemeente Montferland. my location is Loil in this gemeente.

look forward te add this in Home assistant

thanks

Wilfried

**Comment by heyajohnny** [comment]
Note to myself: http://www.montferland.afvalwijzer.net/introductie.aspx
7038 CN 1

**Comment by wilfriedbaars** [comment]
http://www.montferland.afvalwijzer.net/kalender.aspx
6942PK 39

**Comment by heyajohnny** [comment]
Sorry for the wait :( 
I've just added Montferland :) Please let me know if all works as expected.

**Comment by wilfriedbaars** [comment]
Thanks Johnny,

I try to install but failure. Can i contact in Direct message ? i will buy the coffee.

duplicated mapping key at line 110, column -19:
      platform: afvalinfo

**Comment by heyajohnny** [comment]
How nice... They just changed something in the last 5 days... I'll look into it, this weekend

**Comment by heyajohnny** [comment]
I'm sorry but I can't seem to fix it :( They did some strange security thing that makes the session cookie not work anymore.
I can get it to work in PostMan, but when I use the same parameters in Python or C# it just doesn't work... Even with adjusted parameters and the use of different libraries it just makes it invalid somehow...

**Comment by heyajohnny** [comment]
Note to myself:
1: get adm_id + adr_id
http://afvalwijzer.afvaloverzicht.nl/Login.ashx?Username=GSD&Password=gsd$2014&Postcode=7037BG&Huisnummer=1
http://afvalwijzer.afvaloverzicht.nl/Login.ashx?Username=GSD&Password=gsd$2014&Postcode=6942PK&Huisnummer=39
2: this year
http://afvalwijzer.afvaloverzicht.nl/OphaalDatums.ashx?ADM_ID=3&Username=GSD&Password=gsd$2014&ADR_ID=12508&Jaar=2020&Date=2020-12-10&Type=Topdagen
3: next year
http://afvalwijzer.afvaloverzicht.nl/OphaalDatums.ashx?ADM_ID=3&Username=GSD&Password=gsd$2014&ADR_ID=12508&Jaar=2021&Date=2020-12-10&Type=Topdagen

**Comment by heyajohnny** [comment]
When searching the internet I found another way to make Montferland work in afvalinfo.
I've just pushed a new version with support for Montferland. Please let me know if all works as expected?

**Comment by heyajohnny** [comment]
No news is good news, so I'm closing this issue :)
