### ISSUE TITLE
Could you add Havelte?

### ISSUE THREAD

**Issue by daandupau** [heyajohnny/afvalinfo#13]

**Comment by heyajohnny** [comment]
Note to myself:
http://afvalkalender.rova.nl/nl/7971PP/3/
Gemeente westerveld:
Havelte
Darp
Frederiksoord
Diever
Nijensleek
Havelterberg
Dwingeloo
Geeuwenbrug
Boschoord
Vledder
Zorgvlied
Wittelte
Uffelte
Lhee
Lheebroek
Wilhelminaoord
Vledderveen
Leggeloo
Wapserveen
Eemster
Doldersum
Wapse
Dieverbrug 
Westeinde

**Comment by heyajohnny** [comment]
Havelte is added :)
