### ISSUE TITLE
Afvalinfo and HACS

### ISSUE THREAD

**Issue by RobinV72** [heyajohnny/afvalinfo#131]
Hey,

I am new at this, but finding my way way quickly. I recently installes hacks and i stumbled on this great add-on. I installed it via HACS and all seems ok, but further is see only  'afvalinfo' in de HACS integrations and i can't locate the entity to make a card. do i have to add the platform to the config Yaml?
I know its a bit of a noob question, but could you push me in the right direction?

thanks in advance.

**Comment by heyajohnny** [comment]
Hey RobinV72,

You need to add something like this to your configuration.yaml:
```
sensor:
  - platform: afvalinfo
    resources:
      - gft
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: leeuwarden
    postcode: 8921js
    streetnumber: 12
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

**Comment by RobinV72** [comment]
hey,
I did that with noi succes, but your respond gave me some new insights and now i was able to fix it. Thank you very much!
