### ISSUE TITLE
id_name seems not to work

### ISSUE THREAD

**Issue by steelshome** [heyajohnny/afvalinfo#132]
in the code I do see the following:

   id_name = config.get(CONF_ID)

but when trying to populate the value : 

home assistant is returning an error related to the configuration:

Invalid config for [sensor.afvalinfo]: [id_name] is an invalid option for [sensor.afvalinfo]. Check: sensor.afvalinfo->id_name. (See ?, line ?). 

i did check  if the id_name works in the code , and it did
changed line:

   vol.Optional(CONF_ID, default = ""): cv.string,  to    vol.Optional(CONF_ID, default = "MyName"): cv.string,

someone noticed this already or it is intended to be like this ?

groetjes
Andre'

**Comment by steelshome** [comment]
good morning

I use the following configuration:

- platform: afvalinfo
  resources:
    - pbd
    - gft
    - papier
    - trash_type_today
    - trash_type_tomorrow
  location: Apeldoorn
  postcode:  ;-)
  streetnumber:  ;-)
  id_name: Containers1   => changed to id: Containers1 (And working)


but did some more checking and when change the **id_name** to ** id**  it works


my bad....  was focussed on the id_name and didn;t see from code it accepts only id.




the errors are reported by validating the configuration via the GUI (  http://<ip>:8123/config/server_control )

![image](https://user-images.githubusercontent.com/72737827/95829239-47dd1b80-0d36-11eb-9221-afcc430511b3.png)

**Comment by steelshome** [comment]
thanks for your quick responds, but from code I did not see id is mapped to id_name.
still trying to understand ;-)

you may close item while it is  now working with multiple "IDs"  currently.

**Comment by steelshome** [comment]
will do some more checking when adding more " id's"

**Comment by heyajohnny** [comment]
Good to hear :) Good luck with your setup 👍
