### ISSUE TITLE
Schinveld - Gemeente Beekdaelen

### ISSUE THREAD

**Issue by Veldkornet** [heyajohnny/afvalinfo#134]
For Postcode [6451](https://postcodebijadres.nl/6451), it falls under gemeente Beekdaelen. This uses RD4.
However, according to your website it uses MijnAfvalWijzer

This results in the following error:
`2020-10-17 12:20:55 ERROR (SyncWorker_60) [custom_components.afvalinfo.const.const] Error occurred while fetching data: 'Not Found'`

**Comment by heyajohnny** [comment]
I've just pushed a fix for your issue. Pleas let me know if your issue is fixed after you've updated 'afvalinfo'.

**Comment by Veldkornet** [comment]
Yup, now it's working, thanks!
