### ISSUE TITLE
Next Date and Type Sensor

### ISSUE THREAD

**Issue by Veldkornet** [heyajohnny/afvalinfo#135]
Is it possible to add a next_date sensor with the date that the next item will be collected (of any type) as well as a next_type sensor with which type will be collected next (regardless oh how many days there are still.

Alternatively, if you have an example of how to do this with a template, that will also work.

**Comment by heyajohnny** [comment]
I've just added a template  at the end of the '[README](https://github.com/heyajohnny/afvalinfo/)' page. I think this will solve your problem.

**Comment by Veldkornet** [comment]
Awesome, thanks!
