### ISSUE TITLE
support for gemeente 'Rozenburg ZH'

### ISSUE THREAD

**Issue by lkeijser** [heyajohnny/afvalinfo#136]
Actually it's Deelgemeente Rozenburg (the actual gemeente is Rotterdam). Info is provided by Irado, same as for Capelle ad IJssel and Schiedam. Thanks!

**Comment by lkeijser** [comment]
I thought I'd give it a shot and created https://github.com/heyajohnny/afvalinfo/pull/137

**Comment by heyajohnny** [comment]
Thank you! I've just make a new release with your code :)
