### ISSUE TITLE
middendrenthe does not work

### ISSUE THREAD

**Issue by ewieldra** [heyajohnny/afvalinfo#143]
Hi,

I'm unable to collect any info,  i use the following code in configuration.yaml

  - platform: afvalinfo
    resources:
      - gft
      - pbd
      - restafval
    location: middendrenthe
    postcode: 9421SX
    streetnumber: 150

Thanks

Best regards,

Emiel

**Comment by heyajohnny** [comment]
Please change the location from: **middendrenthe** to: **midden-drenthe**
Let me know if it fixes the issue ;)

**Comment by ewieldra** [comment]
I feel stupid

Solved the problem
