### ISSUE TITLE
no data Epe

### ISSUE THREAD

**Issue by hugostegeman** [heyajohnny/afvalinfo#145]

**Comment by heyajohnny** [comment]
I think they recently shut down https://afvalkalender.circulus-berkel.nl/
Probably need to replace it with https://mijn.circulus-berkel.nl/afvalkalender/

**Comment by jkottier** [comment]
@heyajohnny, seems Circulus Berkel has moved its waste info to another website/api.
If you're interested I've created a first test version for the new Circulus Berkel website that seems to work just fine.

However, the update you've commited for mijnafvalwijzer seems to do the trick as well for Circulus Berkel in Apeldoorn and above mentioned address.

**Comment by heyajohnny** [comment]
@jkottier 
I saw that they moved to a different site, but the icons they use are the same as in the old site, so I think they still use the old one and made some sort of conversion / layer for the new site which uses the data from the old site.

Thanks for mentioning that for MijnAfvalwijzer... I'll look into it somewhere today

**Comment by heyajohnny** [comment]
I think it should be fixed. I changed the URL to the trashapi URL and it should be fixed. Please let me know if all works as expected

**Comment by hugostegeman** [comment]
Yeah its working again.
Thanks a lot for the fix.
