### ISSUE TITLE
Afhaaldagen voor mijn adres (Assen, afvalwijzer) niet correct

### ISSUE THREAD

**Issue by QuaySo** [heyajohnny/afvalinfo#147]
Ik zie sinds een paar dagen dat de afhaaldagen voor GFT niet correct worden getoond. Naar mijn idee heeft dit te maken met de jaarovergang van 2020 naar 2021.
In mijn situatie gaat het om GFT. Dit jaar wordt die volgens de afvalwijzer niet meer opgehaald, maar in homeassisant staat de datum 21 december weergegeven. Op deze datum in 2021 wordt er wel GFT opgehaald.

Een paar dagen geleden stond er bij GFT 7 december, wat ook correspondeert met de datum in 2021.

Zie ook de schermafdrukken die ik erbij heb gemaakt om het voorbeeld te verduidelijken. Het zou mooi zijn als dit opgelost kan worden. 

![afvalwijzer](https://user-images.githubusercontent.com/36159002/101483692-d4801080-3958-11eb-8b89-40986aecdd8c.PNG)

**Comment by QuaySo** [comment]
Ik weet niet of afvalwijzer.nl de website heeft aangepast en nu een keuze biedt die eerder niet mogelijk was. Je kiest nu immers voor een jaar: 2020 of 2021

Hierdoor is dit deel van de code (jaar is het jaar van de huidige datum) niet meer valide:

                day = date.split()[1]
                month = MONTH_TO_NUMBER[date.split()[2]]
                # the year is always this year because it's a 'jaaroverzicht'
                year = datetime.today().year

**Comment by heyajohnny** [comment]
I've just pushed a fix. Please let me know if all works as expected ;)

**Comment by QuaySo** [comment]
Just installed the update and it works as expected. Thanks for this fix!

**Comment by xirixiz** [comment]
Actually I don't think this api will serve all mijnafvalwijzer locations. I've tried a couple, but no data is retrieved.

I tried something in Sprudel and Waalwijk, but for both there is no data available. However when I pick something random in Asse, then I do receive data.

https://trashapi.azurewebsites.net/trash?Location=Waalwijk&ZipCode=5146BN&HouseNumber=14
https://trashapi.azurewebsites.net/trash?Location=Assen&ZipCode=9401CC&HouseNumber=50

```
2020-12-10 09:03:31 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afvalinfo_gft fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()                                                                                                                                                                                                           File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update                                                                                                                                                raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run                                                                                                                                                                  result = self.fn(*self.args, **self.kwargs)                                                                                                                                                                                                File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper                                                                                                                                                             result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 481, in update
    self.data.update()                                                                                                                                                                                                                         File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 331, in update
    self.data = MijnAfvalWijzerAfval().get_data(                                                                                                                                                                                               File "/config/custom_components/afvalinfo/location/mijnafvalwijzer.py", line 32, in get_data                                                                                                                                                   if "gft" in resources and data["name"].lower() == "gft":                                                                                                                                                                                 TypeError: string indices must be integers
```

I use this url for api calls, but 2021 hasn't been added yet. This is every year the same case. "ophaaldagennext" in json needs to be updated with values, which only can be done by the company behind mijnafvalwijzer.

https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=<postcode>&street=&huisnummer=<huisnummer>&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=<today>&langs=nl

Anyway, my two cents.

**Comment by xirixiz** [comment]
I think https://trashapi.azurewebsites.net shows only presents data if the data for 2021 already has been added:

In Assen that's the case, but for the other example of Waalwijk
https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=9401CC&street=&huisnummer=50&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2021-01-01&langs=nl

https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=5142CN&street=&huisnummer=1&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2021-01-01&langs=nl

**Comment by heyajohnny** [comment]
@xirixiz It looks like the https://trashapi.azurewebsites.net is working now.

**Comment by xirixiz** [comment]
Yes it does 👍

**Comment by heyajohnny** [comment]
I'm closing this issue, since all the problems are fixed ;)
