### ISSUE TITLE
DeAfvalApp states all sensors unknown

### ISSUE THREAD

**Issue by dbrouwer1979** [heyajohnny/afvalinfo#148]
All sensors for DeAfvalApp are stated unknown since update to 0.118.3 of HomeAssistant.
It occurs with all other afval sensors integrations as well.
Could you please resolve?

**Comment by heyajohnny** [comment]
Do you live in one of these 'gemeente'?
Buren, Culemborg, Maasdriel, Neder-Betuwe, Tiel, West Betuwe, West Maas en Waal, Zaltbommel

**Comment by dbrouwer1979** [comment]
> Do you live in one of these 'gemeente'?
> Buren, Culemborg, Maasdriel, Neder-Betuwe, Tiel, West Betuwe, West Maas en Waal, Zaltbommel

Yes, Buren

**Comment by heyajohnny** [comment]
DeAfvalApp removed all the Avri related 'gemeentes'. I've just pushed a fix. Please let me know if it works as expected ;)

**Comment by dbrouwer1979** [comment]
> DeAfvalApp removed all the Avri related 'gemeentes'. I've just pushed a fix. Please let me know if it works as expected ;)

Nice, it works now!
Thank you!
What was the fix applied?

**Comment by heyajohnny** [comment]
Well... I'm working on a more robust API (but it's still in an early stage) for all the waste collectors in the Netherlands.
I just changed the URL to my new API and in my new API I already changed the Avri gemeentes from DeAfvalApp to the Ximmio waste collector. So that was the fix.
