### ISSUE TITLE
Update for sensor.afvalinfo_papier fails (Omrin)

### ISSUE THREAD

**Issue by ariekraakjr** [heyajohnny/afvalinfo#149]
Edit: Corrected date from 4 jan to 2 jan 2021.

Aangezien deze implementatie alleen Nederlandse afvalinfo geeft doe ik het even in het nederlands. 

Ik zit in het Omrin gebied(Leeuwarden) en sinds een paar updates geleden krijg ik vaker dan eerst de melding dat de sensor niet ge-update kan worden.
De ophaaldag in de GUI staat op 'onbekend'.
Volgens de kalender van omrin zou de papierbak 2 januari 2021 geleegd moeten worden(< 30 dagen)
Ik krijg deze melding ook regelmatig met gft en rest.

Homeassistant v 0.118.4
installatie via HACS
 
  - platform: afvalinfo
    resources:
      - papier
      - gft
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: Leeuwarden
    postcode: ######
    streetnumber: ##
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 30

##### +-30  minuten na legen van logfile 
Logger: homeassistant.helpers.entity
Source: custom_components/afvalinfo/sensor.py:487
First occurred: 10:24:06 (40 occurrences)
Last logged: 10:43:35

Update for sensor.afvalinfo_papier fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 487, in update
    collection_date = datetime.strptime(
TypeError: strptime() argument 1 must be str, not None
######

**Comment by heyajohnny** [comment]
I've just pushed a fix. Please let me know if it all works as expected

**Comment by ariekraakjr** [comment]
Dat is snel :-)
Ik krijg geen foutmeldingen meer in de logfile.
Ik krijg echter geen ophaaldatum te zien. Waarschijnlijk komt dit doordat Omrin het volgende jaar nog niet publiceert op de gebruikte https://www.omrin.nl/bij-mij-thuis/afval-regelen/afvalkalender
Als je zelf wil testen kun je 8918LA 1 gebruiken. (niet mijn adres)

**Comment by heyajohnny** [comment]
Het klopt inderdaad dat er nog geen gegevens voor volgend jaar zijn. Dan lijkt alles weer te werken en sluit ik dit issue.
