### ISSUE TITLE
error message Westerkwartier

### ISSUE THREAD

**Issue by githubnoobjk** [heyajohnny/afvalinfo#15]
Thank you for adding Westerkwartier. However when I check configuration an error says:
Platform error sensor.afvalinfo - No module named 'custom_components.afvalinfo.location.westerkwartier'

I reinstalled and restarted several times. 

Besides that: when I copy the lines for time and date format the configuration check says :
Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/sensors.yaml", line 219, column 3
expected <block end>, but found '<scalar>'
  in "/config/sensors.yaml", line 226, column 36

**Comment by heyajohnny** [comment]
Thanks for letting me know! Git and I forgot to add the westerkwartier location file :(
It should be working now.

**Comment by heyajohnny** [comment]
Please let me know if it's working :)
