### ISSUE TITLE
Suez isn't working

### ISSUE THREAD

**Issue by 19jm81** [heyajohnny/afvalinfo#150]
Keep getting unknown:

# Afval sensor
    id: Eusebiusbinnensingel
    resources:         
    - gft
    - pbd
    - papier
    - restafval
    - textiel
    - trash_type_today
    - trash_type_tomorrow
    location: arnhem 
    postcode: 6811BW  
    streetnumber: 5

**Comment by heyajohnny** [comment]
Looks like there are no pickup dates for your location:
![image](https://user-images.githubusercontent.com/20553716/102060949-185c9500-3df3-11eb-8d01-9e9bd518add3.png)

But... If you select streetnumber '5 1' on the official Suez site I get results.
![image](https://user-images.githubusercontent.com/20553716/102061335-9faa0880-3df3-11eb-9b9e-d9b89279109d.png)


Try using:
`streetnumber: 5:1`

**Comment by 19jm81** [comment]
Great!! That did the trick!

**Comment by heyajohnny** [comment]
No prob ;)
