### ISSUE TITLE
TypeError: String indices must be integeres

### ISSUE THREAD

**Issue by TheGabeMan** [heyajohnny/afvalinfo#151]
Hi
Not sure if this happened after updating HA to 2020.12, but I noticed the following in the HA log:

Logger: homeassistant.helpers.entity
Source: custom_components/afvalinfo/location/trashapi.py:34
First occurred: 12:44:36 AM (4 occurrences)
Last logged: 12:44:46 AM

`Update for sensor.afvalinfo_gft fails
Update for sensor.afvalinfo_restafval fails
Update for sensor.afvalinfo_today fails
Update for sensor.afvalinfo_tomorrow fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 264, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 196, in update
    self.data = TrashApiAfval().get_data(
  File "/config/custom_components/afvalinfo/location/trashapi.py", line 34, in get_data
    if "gft" in resources and data["name"].lower() == "gft":
TypeError: string indices must be integers`

The sensors now all give status "unknown".

I also updated HACS to the latest version but that doesn't seem to matter.

My configuration yaml looks like this:
`  - platform: afvalinfo
    resources: # (at least 1 required)
      - gft
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: maastricht # (required, default = sliedrecht) name of the 'gemeente'
    postcode: xxxxxx # (required, default = 3361AB)
    streetnumber: xxx # (required, default = 1)
    dateformat: "%d-%m-%Y" # (optional, default = %d-%m-%Y) day-month-year
    locale: "nl" # (optional, default = 'en')
    timespanindays: 14 # (optional, default = 365) number of days to look into the future
`
( I changed my postcode and streetnumber of course to correct values)

**Comment by heyajohnny** [comment]
Can you please provide me a postcode and streetnumber that has this problem (doesn't have to be yours of course), so I can reproduce the issue.

**Comment by TheGabeMan** [comment]
6228GG 
nr: 177

**Comment by heyajohnny** [comment]
I can't reproduce it either... Looks just fine at the moment. 
Maybe the official rd4 site was offline / had problems for some time. Please let me know if the problem occurs again. If not, I'll close the issue in a couple of days.

**Comment by heyajohnny** [comment]
Yesterday evening I saw a lot of errors on my API. When I investigated it, I saw that all the errors came from rd4 and when I visited their site, it states that it was offline for maintenance... So it is possible that the errors will come back in the coming days.

**Comment by TheGabeMan** [comment]
Ok, then it is best to close this issue I think
