### ISSUE TITLE
Papier waarde "unknown" pas volgend jaar weer papier ophalen

### ISSUE THREAD

**Issue by joopy** [heyajohnny/afvalinfo#152]
Het viel me op dat ik nu unknown waarde krijg bij papier ophalen.
Zou het kunnen kloppen dat het komt omdat er dit jaar geen papier meer wordt opgehaald?

https://www.irado.nl/bewoners/afvalkalender
postcode huisnummer in vlaardingen geeft:
donderdag 7 januari online

**Comment by heyajohnny** [comment]
Het was inderdaad een probleem met de datum van volgend jaar.
Ik heb zojuist een fix doorgevoerd en hij zou de data van volgend jaar weer moeten tonen.
Kun je nog even laten weten of het probleem is verholpen?

**Comment by joopy** [comment]
Yes werkt! ik heb geen nieuwe software gedownload denk ik? Was op de backend een issue?

**Comment by heyajohnny** [comment]
Ja, dat klopt. Een backend issue 😟 
Backend is nog niet zo oud en er veranderd een hoop in afval land, zo aan het einde van het jaar.

**Comment by joopy** [comment]
fixed!
