### ISSUE TITLE
Only partial waste info from TrashAPI -  Gemeente Maastricht

### ISSUE THREAD

**Issue by BTielbeek** [heyajohnny/afvalinfo#154]
Hi, 
I live in Maastricht and I've found that for my address I would only get information about the next _restafval_ and _gft_ pickup date, but none of the other trash types (even though I'm pretty sure only _papier_ , _restafval_ , _gft_ and _kerstboom_ apply to my municipality). I've tried to debug the issue myself,  but it seems TrashAPI is simply only returning information regarding the next _gft_ and _restafval_ pickup dates, and nothing else. I've tried a couple different postcal codes/house numbers near me but they all seem to have the same issue.

**Actual Trash pickup dates**
![Screenshot_20201219-063830__01](https://user-images.githubusercontent.com/75924721/102691156-c65caa80-420a-11eb-9da7-300a3da831e5.jpg)

**TrashAPI info for my address**
[{"date":"2020-12-21T00:00:00","name":"Restafval","daysTillDate":2},{"date":"2020-12-22T00:00:00","name":"Gft","daysTillDate":3}]

**Comment by heyajohnny** [comment]
It seems that it only returns dates for this year, that's the problem.
What's the URL of the screenshot you posted?

**Comment by BTielbeek** [comment]
> It seems that it only returns dates for this year, that's the problem.
Ah that makes sense, i was wondering if that had something to do with it.

> What's the URL of the screenshot you posted?
I don't know the direct URL, but it's from the "Milieu App" that's published by Besteuitafval.nl, which according to their site is: "Samenwerking van reinigingsdiensten rd4 en gemeenschappelijke regeleing geul en maas" (no idea how to translate that).

link to the app: https://www.besteuitafval.nl/milieu-app

**Comment by heyajohnny** [comment]
I can't find an easy solution for now... The rd4 site is a bit of a hell to make it programmatically change the year and I cannot read the API of the app at this moment, since I don't have a rooted phone at the moment. It's just too much work for now :(
So I'm closing this issue... You'll get the dates for 2021 on the first day of the new year.
Sorry I can't help you any further
