### ISSUE TITLE
Gemeente Eemsdelta

### ISSUE THREAD

**Issue by MartinWierenga** [heyajohnny/afvalinfo#155]
Please add gemeente Eemsdelta (Delfzijl)

**Comment by heyajohnny** [comment]
Note to myself:
De gemeente Eemsdelta is een toekomstige Nederlandse gemeente in de provincie Groningen, die op 1 januari 2021 zal worden opgericht na een bestuurlijke fusie van de gemeenten Appingedam, Delfzijl en Loppersum.

**Comment by heyajohnny** [comment]
I'll fix this in the beginning of the new year, since I don't know the waste collectors yet... The website currently says this:
`Vanaf maandag 4 januari 2021 gaat de website www.eemsdelta.nl online met de nieuwe informatie van de gemeente Eemsdelta. `

**Comment by MartinWierenga** [comment]
waste collection is available on the website but it seems not for full year yet. Contacted Eemsdelta but they can't say why it isn't or when it will be available. Also paper and carton collection is not on their website yet.

**Comment by heyajohnny** [comment]
I'll try to add Eemsdelta this weekend.

**Comment by heyajohnny** [comment]
I've just added Eemsdelta with the supported trash types: 'gft', 'papier' and 'pbd'.
Please let me know if all works as expected ;)

**Comment by heyajohnny** [comment]
I'm closing this issue, since no news is good news :)
