### ISSUE TITLE
Please add Mook en Middelaar 

### ISSUE THREAD

**Issue by pa3dso** [heyajohnny/afvalinfo#156]
Hey,
Please could you add Mook en Middelaar 
As of 1-1-2021 this community will be served by DAR from Nijmegen.
Tnx

**Comment by heyajohnny** [comment]
Note to myself:
https://afvalkalender.dar.nl/
6585 BT 1

**Comment by heyajohnny** [comment]
I've just pushed an update. 
The dates (starting from 01-01-2021) for Mook en Middelaar should work.
Please let me know if all works as expected ;)

**Comment by heyajohnny** [comment]
No news is good news... I'm closing the issue, since 6585 BT 1 is working just fine ;)

**Comment by pa3dso** [comment]
Yes tnx. Works fine for this postcal code.
