### ISSUE TITLE
Incorrect pickup date

### ISSUE THREAD

**Issue by michelotten** [heyajohnny/afvalinfo#157]
I noticed an incorrect pickup date for my paper trash today.
It's showing pickup 22-12-2020 for paper, while first pickup is planned for 7th of January.
It might have something to do with year end, as I noticed that actually on 22-12-202**1** there is a pickup of paper planned.

Data is being taken from ROVA, Zwolle. If you need my postal code and house number, I can provide it to you in a personal message.

**Comment by heyajohnny** [comment]
Hello, thx for pointing it out!
I've just pushed a fix. Please let me know if the issue is fixed ;)

**Comment by michelotten** [comment]
Thanks, but I don't see an update on GitHub of in HACS. Does that take some time?

**Comment by heyajohnny** [comment]
No, you won't see it. It's a backend fix... It should work without updating anything in HACS

**Comment by michelotten** [comment]
I've restarted Home Assistant. It pulled new data and it's fixed. Thanks a lot!
