### ISSUE TITLE
RD4 (Heerlen) broken?

### ISSUE THREAD

**Issue by Koal4** [heyajohnny/afvalinfo#159]
Hi,

Helaas krijg ik sinds vorige week ongeveer geen nieuwe data meer voor regio Heerlen (6412).

![image](https://user-images.githubusercontent.com/10795027/103270829-23015780-49b9-11eb-939b-4f71d129107c.png)

Voor die tijd heeft het zonder issue gewerkt. Kan het zijn dat er in de plugin / website iets kapot is? 

thanks

**Comment by Ivo-tje** [comment]
Heb hetzelfde, lijkt eerder alsof hij 2021 nog niet kan lezen. De inzameldata leken langzaam weg te vallen...

**Comment by Ivo-tje** [comment]
Oke! Hier plopt 2021 er net bij!

**Comment by Koal4** [comment]
Apart

Hier (nog) niks. Heb hem zelfs herstart maar helaas.

**Comment by heyajohnny** [comment]
De data voor 2021 zal waarschijnlijk pas op 1 januari verschijnen. Misschien voor sommige adressen al eerder, als er dit jaar geen ophaaldagen meer zijn. Het zou ontzettend veel werk zijn (waar ik momenteel even geen tijd voor heb) om de dagen van volgend jaar te kunnen tonen.

**Comment by Koal4** [comment]
Hoeft ook niet hoor :) 
Bedankt voor de bevestiging dan wachten we nog wel een paar dagen...thanks

**Comment by heyajohnny** [comment]
Als het goed is werken de datums weer voor dit jaar. Maak er een mooi jaar van!!!
Ik sluit dit issue.

**Comment by Koal4** [comment]
> Als het goed is werken de datums weer voor dit jaar. Maak er een mooi jaar van!!!
> Ik sluit dit issue.

Yes klopt. 
Zijn gisteren terug gekomen.

Bedankt en beste wensen!
