### ISSUE TITLE
Gemeente Hoeksche Waard haalt geen data op?

### ISSUE THREAD

**Issue by rriempie** [heyajohnny/afvalinfo#160]
Handige plugin voor het afval!
Ik krijg alleen geen data door voor de gemeente Hoeksche Waard. Alle statussen zijn 'onbekend' Enig idee?

**Comment by heyajohnny** [comment]
De API/URL is gewijzigd voor 2021. Ik zal binnenkort kijken of ik dit weer recht kan trekken.

**Comment by rriempie** [comment]
He Johnny,

Bedankt voor je reactie.
Ik wacht geduldig af.
Fijne jaarwisseling!


Groet,

Ramon Riemersma

**Comment by BlueEllob** [comment]
Hallo Johnny

ik heb exact hetzelfde voor de gemeente het Hogeland (Bedum).
We gaan per 1-1-2021 over op Omrin.

Ik heb ook 'afvalbeheer' geprobeerd maar met hetzelfde resultaat, waarschijnlijk dus ook de API.

groeten,

Stefhan

**Comment by heyajohnny** [comment]
@rriempie Ik heb zojuist een update doorgevoerd. Als je deze binnenhaalt zou Hoeksche Waard weer moeten werken.

**Comment by heyajohnny** [comment]
@BlueEllob Zou je hier een nieuw issue voor aan willen maken? En heb je ook nog een voorbeeld adres (hoeft uiteraard niet je eigen adres te zijn). Alvast bedankt!

**Comment by rriempie** [comment]
> @rriempie Ik heb zojuist een update doorgevoerd. Als je deze binnenhaalt zou Hoeksche Waard weer moeten werken.

YES, werkt nu perfect! Thanks!

**Comment by heyajohnny** [comment]
@rriempie Mooi! Dan sluit ik dit issue...
@BlueEllob Bedankt voor het melden in een nieuw issue!
