### ISSUE TITLE
please add montferland

### ISSUE THREAD

**Issue by jerwij** [heyajohnny/afvalinfo#161]
Dear johnny,

Is it possible to add gemeente Montferland to the code?

Best regards,
Jeroen

**Comment by heyajohnny** [comment]
Ehhh... It's already there an it should work...

**Comment by jerwij** [comment]
I See. My bad. I was only looking in the locations folder and did't read the readme.

**Comment by heyajohnny** [comment]
No problem and Thnx for the tip :)

**Comment by jerwij** [comment]
Is the trashapi yours? pbd is missing in the JSON:
[
    {
        "date": "2021-01-12T00:00:00",
        "name": "Restafval",
        "daysTillDate": 4
    },
    {
        "date": "2021-01-16T00:00:00",
        "name": "Papier",
        "daysTillDate": 8
    },
    {
        "date": "2021-01-18T00:00:00",
        "name": "Gft",
        "daysTillDate": 10
    }
]

**Comment by heyajohnny** [comment]
Yes it's mine :) It makes updating the code so much easier. They've changed the naming from "Plastic, Metaal en Drankenkartons" to "PMD".I've just added the "PMD" to match it with pbd.

Please let me know if it works.

**Comment by jerwij** [comment]
I see it now in the JSON file! Thnx!

**Comment by jerwij** [comment]
I still get an errormessage(PMD is now showing with an date, so that one is fixed):

Logger: homeassistant.components.rest.sensor
Source: components/rest/sensor.py:256
Integration: rest (documentation, issues)
First occurred: 16:59:25 (51 occurrences)
Last logged: 17:25:27

REST result could not be parsed as JSON

**Comment by heyajohnny** [comment]
Strange. Works just fine with this address:
location: montferland
postcode: 7037AW
streetnumber: 63

**Comment by jerwij** [comment]
Last days I get an "404 Not found" status of the service. Possibly someting went wrong by adding new destricts?

**Comment by jerwij** [comment]
And fixed  👍
