### ISSUE TITLE
Gemeente Het Hogeland / Omrin

### ISSUE THREAD

**Issue by BlueEllob** [heyajohnny/afvalinfo#163]
Hallo Johnny

Voor de gemeente "het hogeland (bedum, winsum)" werkt Afvalinfo niet meer, per 1-1-2021 zijn ze overgegaan naar Omrin.

Ik heb het al werkend gekregen door "het hogeland (de marne, eemsmond)" te gebruiken, die zaten al eerder bij Omrin.
Als voorbeeld kun je gebruiken 9781AH nr 1  (https://www.omrin.nl/bij-mij-thuis/afval-regelen/afvalkalender)

Je zou evt. beide nu kunnen samenvoegen tot "het hogeland', de gehele gemeente is nu gelijk.

Groeten Stefhan

**Comment by heyajohnny** [comment]
Hoi Stefhan, ik heb zojuist de gesplitste gemeentes samengevoegd tot de gemeente "het hogeland".
Bedankt voor het melden en kun je nog even laten weten of het na het updaten werkt? Alvast bedankt ;)

**Comment by BlueEllob** [comment]
Hallo Johnny.

Zo te zien klopt het helemaal, dank je!

Gr. Stefhan
