### ISSUE TITLE
Unknown waarde bij alle afvalinfo sensors

### ISSUE THREAD

**Issue by M1sterGlass** [heyajohnny/afvalinfo#164]
Geen idee sinds wanneer, maar krijg de volgende foutmelding. Ik heb via HACS de Afvalinfo integratie al eens opnieuw geinstalleerd en herstart. 

Error occurred. Please check the address with postcode: '6133XE' and huisnummer: '1' on the website of your local waste collector in the gemeente: 'sittard-geleen'. It's probably a faulty address or the website of the waste collector is unreachable.
If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

De state van sensor.afvalinfo_restafval is unknown, hieronder staan de overige attributen.
      year_month_day_date: null
      last_update: '03-01-2021 19:27'
      hidden: true
      days_until_collection_date: null
      is_collection_date_today: false
      friendly_name: Afvalinfo Restafval
      icon: 'mdi:recycle'

Niet mijn postcode, maar dezelfde data wordt getoond voor mijn postcode. 
https://trashapi.azurewebsites.net/trash?Location=sittard-geleen&ZipCode=6133XE&HouseNumber=1

        0 |  
        date | "2021-01-04T00:00:00"
        name | "Restafval"
        daysTillDate | 1
        1 |  
        date | "2021-01-09T00:00:00"
        name | "Papier"
        daysTillDate | 6
        2 |  
        date | "2021-01-11T00:00:00"
        name | "Gft"
        daysTillDate | 8
        3 |  
        date | "2021-01-12T00:00:00"
        name | "Pbd"
        daysTillDate | 9
        4 |  
        date | "2021-01-15T00:00:00"
        name | "Kerstboom"
        daysTillDate |

**Comment by M1sterGlass** [comment]
Sensor heeft tussen 20:28 en 21:28 wel de juiste waarde weergegeven.
<img width="270" alt="Afvalinfo" src="https://user-images.githubusercontent.com/56590900/103491039-7bed4780-4e20-11eb-9103-682d0d80ca6c.png">

**Comment by heyajohnny** [comment]
Werkt hier prima met de volgende config:
```- platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: sittard-geleen
    postcode: 6133XE
    streetnumber: 1
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"
```

**Comment by berg78** [comment]
Zelfde issue, met de laatste update, als ik hem terugzet naar 5.27 werkt hij wel weer.

**Comment by heyajohnny** [comment]
Hmmm... Ik denk dat het komt omdat de nieuwste versie van Home Assistant webscraping niet meer toe laat. Gelukkig ben ik daar bijna geheel van afgestapt. Ik zal binnenkort een update hiervoor doorvoeren.

**Comment by heyajohnny** [comment]
Bij mij werkt de nieuwste versie (2020.12.2) van Home Assistant ook gewoon prima.
Ik kan op het moment niet vinden wat de oorzaak zou kunnen zijn, maar ik laat het issue nog wel open staan.

**Comment by heyajohnny** [comment]
@M1sterGlass Heb je nog steeds geen data? Kan ook zijn dat de lokale afvalverwerker even offline is geweest oid in verband met het nieuwe jaar.

**Comment by M1sterGlass** [comment]
Na dagen zoeken heb ik de oorzaak gevonden. De afvalinfo sensor werkt goed, maar dit wordt bij mijn veroorzaakt door een bug in de DNS resolver van mijn router. Het domein trashapi.azurewebsites.net geeft soms een timeout (en ook alleen dit domein?) en als ik handmatig even een record aanmaak dan werkt de sensor goed. Bedankt voor het meekijken en dit issue mag voor mij gesloten worden. 

Bedankt @heyajohnny

**Comment by heyajohnny** [comment]
Oke, goed om te horen dat het probleem is opgelost 👍 
Ik sluit dit issue...
