### ISSUE TITLE
Toevoegen Middelburg Vlissingen

### ISSUE THREAD

**Issue by Ruma0613** [heyajohnny/afvalinfo#166]
Hallo

Kan u de afvalwijzer middelburg vlissingen toevoegen aub.

**Comment by heyajohnny** [comment]
Mddelburg en Vlissingen is zojuist toegevoegd. Kun je laten weten of alles werkt? (Wellicht heb ik ergens een mapping over het hoofd gezien)

**Comment by heyajohnny** [comment]
Geen nieuws is goed nieuws. Ik sluit dit issue
