### ISSUE TITLE
Gemeente Westland

### ISSUE THREAD

**Issue by robgardien** [heyajohnny/afvalinfo#167]
In Home Assistant staan alle assets voor de gemeente Westland op onbekend

**Comment by heyajohnny** [comment]
Ik heb helaas een trieste mededeling... Westland heeft besloten om de API in 2021 niet meer te gebruiken en over te stappen op deze pagina: https://www.gemeentewestland.nl/afval/huisvuil.html

Aangezien er alleen iets met wijknamen in staan (en er echt postcodes benodigd zijn voor afvalinfo), kan ik Westland helaas niet ondersteunen voor 2021.

Het enige wat je nog kan doen is een vraag bij Westland indienen voor een goede digitale afvalkalender op postcode niveau. 
Ik heb zojuist ook Westland verwijderd in het lijstje met ondersteunende gemeentes.
