### ISSUE TITLE
Gemeente westland toevoegen 

### ISSUE THREAD

**Issue by robgardien** [heyajohnny/afvalinfo#169]
Zou gemeente westland weer toegevoegd kunnen worden? Volgende week word de postcode functionaliteit weer hersteld. Alvast bedankt!

**Comment by heyajohnny** [comment]
Als dat er weer in zit, zou het wel moeten lukken. Ik zal volgende week, of de week erna kijken of het mogelijk is.

**Comment by robgardien** [comment]
Ik zag net dat de postcodechecker weer werkt: https://www.gemeentewestland.nl/afval/huisvuil.html

Zou je gemeente Westland weer toe kunnen voegen?

**Comment by robgardien** [comment]
De directe url is: https://huisvuilkalender.gemeentewestland.nl/

**Comment by robgardien** [comment]
De URL die gebruikt word voor de query lijkt hetzelfde gebleven: https://huisvuilkalender.gemeentewestland.nl/huisvuilkalender/Huisvuilkalender/get-huisvuilkalender-ajax

**Comment by heyajohnny** [comment]
Ik heb westland weer toegevoegd. Als je nog even kunt laten weten of alles werkt, zou dat mooi zijn ;)

**Comment by robgardien** [comment]
Bedankt voor het opnieuw toevoegen van Westland! Ik zag dat de sensoren voor papier, GFT en restafval alle drie op 27-01 staan, weet jij waar dat aan zou kunnen liggen?

**Comment by heyajohnny** [comment]
Er zat nog een bug in. Nu zou het moeten werken

**Comment by robgardien** [comment]
Bedankt! Het lijkt nu goed te werken,  top!
