### ISSUE TITLE
Gemeente uithoorn

### ISSUE THREAD

**Issue by TNAJanssen** [heyajohnny/afvalinfo#170]

**Comment by heyajohnny** [comment]
De gemeente Uithoorn heeft besloten om dit jaar niet gebruik te maken van een postcode indeling, maar een wijk indeling. Hierdoor kan ik Uithoorn helaas niet toevoegen. Je zou aan de gemeente kunnen vragen of ze misschien nog van plan zijn om dit te veranderen.
