### ISSUE TITLE
Voor de gemeente Renkum wijkt de GFT ophaaldatum sterk  af

### ISSUE THREAD

**Issue by BadiaJunkie** [heyajohnny/afvalinfo#171]
Van de ophaaldagen klopt de GFT voor de gemeente Renkum (ACV) niet daar staat nu vrijdag 4 juni 2021 genoemd als de eerst volgende ophaaldatum, de overige zoals PMD en restafval kloppen wel,  Enig idee?

**Comment by heyajohnny** [comment]
Heb je toevallig een voorbeeld adres?

**Comment by BadiaJunkie** [comment]
dat zou dan 6865xd 123 zijn.

**Comment by heyajohnny** [comment]
De datum voor GFT werd niet in chronologische volgorde aangeleverd. ACV lijkt hier zelf ook problemen mee te hebben 🤣 
![image](https://user-images.githubusercontent.com/20553716/105016782-59277980-5a43-11eb-8fa8-b5c1156c7eea.png)

Maar het probleem is volgens mij opgelost. Als je dit nog zou kunnen bevestigen, dan zou dat top zijn 👍

**Comment by BadiaJunkie** [comment]
Nu klopt het wel, thanks!!
