### ISSUE TITLE
Ophaal textiel onbekend

### ISSUE THREAD

**Issue by Damazinho** [heyajohnny/afvalinfo#173]
In onze gemeente (Simpelveld) wordt door RD4 de BEST-tas opgehaald. Normaliter viel deze gewoon onder het kopje van Textiel binnen afvalinfo, echter na de laatste keer ophalen blijft de status van de volgende ophaal op onbekend staan, terwijl bij RD4 (in de app) de volgende datum wel al bekend is: 16 maart.

**Comment by heyajohnny** [comment]
Als het goed is moet het nu gefixt zijn.

**Comment by Damazinho** [comment]
Yes, dankjewel! 👍🏻👍🏻
