### ISSUE TITLE
Geen data / unknown

### ISSUE THREAD

**Issue by berg78** [heyajohnny/afvalinfo#174]
Had het het laatst al keertje in andere post aangegeven, maar toen had ik geen tijd om er  verder in te duiken.

Vandaag toch nog maar eens afvalinfo geupdate en dan krijg ik geen data:

Kijg de waarde unknown bij 
paper_days_until_collection, restaval_days_until_collection en Afvalinfo Restafval.

Dit is wanneer ik de afvalwijzer naar de laatste versie update.

config file:

sensor:
  - platform: afvalinfo
    resources:
      - pbd
      - kerstboom
      - gft
      - papier
      - textiel
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: beekdaelen
    postcode: 6365CS    
    streetnumber: 24             
    dateformat: '%d-%m-%Y'        
    locale: 'nl'
    timespanindays: 365
    
  - platform: template
    sensors:
      #Afvalwijzer
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"
      restaval_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_restafval', 'days_until_collection_date') }}"

**Comment by heyajohnny** [comment]
Beekdaelen is blijkbaar overgestapt van RD4 naar RWM. Alleen werkte de oude RD4 ook nog, soort van... Waardoor ik geen foutmelding in mijn tests kreeg.

Beekdaelen zou nu weer moeten werken.

**Comment by berg78** [comment]
Yes,

wat een service. Thanks!

**Comment by NielsFeenstra** [comment]
Geldt dit ook voor de gemeente Leeuwarden?

**Comment by heyajohnny** [comment]
@NielsFeenstra Nee, Omrin heeft een storing zie ik.

**Comment by heyajohnny** [comment]
Dit issue is opgelost en ga hem sluiten
