### ISSUE TITLE
Niet zichtbaar

### ISSUE THREAD

**Issue by robgeerts** [heyajohnny/afvalinfo#175]
Ben redelijk nieuw met HACS.
Heb AfvalInfo geinstalleerd en is zichtbaar bij Integratie onder HACS.
Maar kan deze niet vinden als ik hem wil toevoegen via Instellingen -> Integratie toevoegen?

**Comment by heyajohnny** [comment]
Dat hoeft volgens mij niet. 
Je kan gewoon het voorbeeld op de README pagina van afvalinfo kopieren, plakken (en je adresgegevens aanpassen) in je configuration.yaml file

**Comment by robgeerts** [comment]
Die readme direct kopieren gaat niet, dan krijg je parse errors.
Anyway, heb het aangepast en die config staat er nu in, als test:

`sensor:
  - platform: afvalinfo
    resources:
        - gft
    location: sliedrecht
    postcode: 3361AB
    streetnumber: 1`

Nu zou ik hem als entiteit sensor moeten kunnen toevoegen zou je zeggen?
Want in die lijst is hij niet zichtbaar.

**Comment by heyajohnny** [comment]
[Hier](https://github.com/heyajohnny/afvalinfo/blob/master/example/configuration.yaml) heb je een voorbeeld configuration.yaml

**Comment by heyajohnny** [comment]
Ik sluit dit issue... Volgens mij moet je er wel uitkomen zo. Zo niet, kun je altijd nog comments in dit issue zetten
