### ISSUE TITLE
Beekdaelen is blijkbaar overgestapt van RD4 naar RWM. Alleen werkte de oude RD4 ook nog, soort van... Waardoor ik geen foutmelding in mijn tests kreeg.

### ISSUE THREAD

**Issue by RuudKerckhoffs** [heyajohnny/afvalinfo#176]
Beekdaelen is blijkbaar overgestapt van RD4 naar RWM. Alleen werkte de oude RD4 ook nog, soort van... Waardoor ik geen foutmelding in mijn tests kreeg.

Beekdaelen zou nu weer moeten werken.

_Originally posted by @heyajohnny in https://github.com/heyajohnny/afvalinfo/issues/174#issuecomment-765527527_

**Comment by RuudKerckhoffs** [comment]
Hallo Johnny,

helaas werkt het nu, voor mij niet meer, voor de plaats Schimmert 6333EK Huisnr 48, doet RD4 de inzameling, in Beekdaelen. 
Er zijn 2 verschillende afvalverwerkers in de gemeente Beekdaelen.
Hierbij de link waar eea beschreven staat voor de gemeente beekdaelen. Zou je een oplossing kunnen bieden.
https://www.beekdaelen.nl/afvalinzameling

Dank Ruud

**Comment by heyajohnny** [comment]
Als het goed is moet hij weer werken. Ik doe eerst een check in 1 afvalverwerker, mocht er geen resultaat zijn, check ik de ander. Kun je laten weten of het weer werkt?

**Comment by RuudKerckhoffs** [comment]
Hoi Johnny,

Het werkt dank!!

Met vriendelijke groet / Kind regards,

Ruud Kerckhoffs
