### ISSUE TITLE
Bloemendaal (Meerlanden) stopped working

### ISSUE THREAD

**Issue by RobRobM** [heyajohnny/afvalinfo#177]
Hi, 

First of all thanks for all the hard work!

Gemeente Bloemendaal stopped working 1 (maybe 2) weeks ago.

I hope you can get it working again.

Thanks!

**Comment by smartworkxpro** [comment]
Same here for Aalsmeer, Meerlanden

**Comment by heyajohnny** [comment]
It looks like Meerlanden changed the website / API... It affects the following 'gemeentes':
"aalsmeer", "bloemendaal", "diemen", "haarlemmermeer", "heemstede", "hillegom", "lisse", "noordwijk"

I'll try to fix it in a couple of days

**Comment by smartworkxpro** [comment]
Thanks for the quick reply (of dank je in NL ;-))

**Comment by heyajohnny** [comment]
I think it should be fixed now... Please let me know if it's fixed

**Comment by smartworkxpro** [comment]
It works again, thanks a lot.

**Comment by RobRobM** [comment]
Thanks for your fast fix. Got reminded of pbd pick-up today. I would have missed it otherwise :-)

Thanks a lot.
