### ISSUE TITLE
Gemeente Weert

### ISSUE THREAD

**Issue by Piem-el** [heyajohnny/afvalinfo#178]
Hi!!! Top werk dit, zou het ook graag willen gaan gebruiken! Zou je gemeente Weert toe willen voegen a.u.b.?

Alvast bedankt!

Grs Pim

**Comment by heyajohnny** [comment]
De gemeente Weert heeft er helaas voor gekozen om op wijk niveau de ophaaldagen te tonen. Helaas kan ik deze wijken niet koppelen aan postcodes, die afvalinfo vereist. 
[Afvalkalender Weert](https://www.weert.nl/huisvuil-duobak-en-ophaaldagen)

Het enige wat je zou kunnen doen is een vraag bij de gemeente Weert uit te zetten om de ophaaldagen op postcode niveau toegankelijk te maken.

Voor nu sluit ik dit issue :(
