### ISSUE TITLE
Gemeente Landsmeer

### ISSUE THREAD

**Issue by EdmarS** [heyajohnny/afvalinfo#179]
Mooi initiatief, dit!
Kan mijn gemeente Landsmeer toegevoegd worden? Helpt het als ik specifieke data aanlever? Laat maar weten wat ik hiervoor kan doen.

**Comment by heyajohnny** [comment]
De gemeente Landsmeer heeft er helaas voor gekozen om op wijk niveau de ophaaldagen te tonen. Helaas kan ik deze wijken niet koppelen aan postcodes, die afvalinfo vereist.
[Afvalkalender Landsmeer](https://www.landsmeer.nl/afvalinzameling/)

Het enige wat je zou kunnen doen is een vraag bij de gemeente Landsmeer uit te zetten om de ophaaldagen op postcode niveau toegankelijk te maken.

Voor nu sluit ik dit issue :(
