### ISSUE TITLE
Hoe moet het met toevoeging?

### ISSUE THREAD

**Issue by csfolmer** [heyajohnny/afvalinfo#181]
Hoi ik woon in vlaardingen, maar met mijn postcode huisnummer (en toevoeging) doet hij het "nog" niet
ook niet bij afvalinfo.nl, krijg de melding 

> Nog geen doorverwijzing naar uw kalender mogelijk: https://www.irado.nl/bewoners/afvalkalender
> Gemeente: Vlaardingen
> URL: https://www.irado.nl/bewoners/afvalkalender

dit` al reeds doorgegeven.
Maar vroeg me af hij je bij home assistant de huis nummer toevoeging in de config moet zetten

**Comment by heyajohnny** [comment]
Huisnummer toevoeging wordt momenteel niet ondersteund. Wellicht dat ik dit in de toekomst nog toe zal voegen

**Comment by csfolmer** [comment]
Oké thanks.
Zie namelijk op de website dat zonder toevoeging de afval kalender niet verschijnt, ik moet een keuze maken wbt huisnummer toevoeging

**Comment by heyajohnny** [comment]
Ik heb zojuist een nieuwe versie gemaakt. Je kan nu via 'streetnumbersuffix' een huisnummertoevoeging ingeven. Laat maar weten of het werkt.

**Comment by heyajohnny** [comment]
Ik sluit dit issue, aangezien er al enige tijd niet gereageerd is ga ik er vanuit dat het naar behoren werkt
