### ISSUE TITLE
HA 2021.3.0 requests version manifest

### ISSUE THREAD

**Issue by pvmil** [heyajohnny/afvalinfo#182]
As described in releasenotes of HA 2021.3.0, a version number is required in the manifest file:
https://www.home-assistant.io/blog/2021/03/03/release-20213/#read-more
Could you please add this? Thanks for this very nice plugin, use it with much pleasure!

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 17:32:12 (2 occurrences)
Last logged: 17:32:13

No 'version' key in the manifest file for custom integration 'afvalinfo'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'afvalinfo'

**Comment by heyajohnny** [comment]
Thanks for pointing it out. I've just added a version number to the manifest.json and it should now work without a warning.
Please let me know if this fixes the warning

**Comment by pvmil** [comment]
Thnx! The warning is gone, good job
