### ISSUE TITLE
Afval eerst volgende geen data

### ISSUE THREAD

**Issue by Ryukenden88** [heyajohnny/afvalinfo#185]
Beste,

Het voorbeeld werkt perfect, maar de eerstvolgende sensor werkt niet. 
Moet er nog iets bij in config.yaml?

 - platform: template
   sensors:
    afvalinfo_next_trash_type_and_date:
      value_template: >
        {% set ns = namespace(minimum=365) %}
        {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
        {%- for l in list %}
        {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
        {%- if days != None and days < ns.minimum %}
        {%- set ns.minimum = days %}
        {%- endif %}
        {%- endfor %}
        {%- for l in list %}
        {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
        {%- if days == ns.minimum %}
        {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
        {%- endif %}
        {%- endfor `%}

**Comment by heyajohnny** [comment]
Deze regel: 
`{% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}`

Zorg ervoor dat deze lijst gelijk is aan wat je in resources gebruikt:
```
resources:                       (at least 1 required)
        - gft
        - kerstboom
        - pbd
        - papier
        - restafval
        - textiel
```

Zorg er ook voor dat 'sensor.afvalinfo_' in overeenkomt met het groen gemarkeerde. Als gebruik maakt van 'id', kan deze namelijk anders (langer) zijn.
`{%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}`
![image](https://user-images.githubusercontent.com/20553716/111028065-8285d580-83f4-11eb-8818-995d5823a7b7.png)

**Comment by Ryukenden88** [comment]
Bedankt voor de reactie,

ik heb de lijst gelijk gemaakt aan de resources en dat heeft al een stuk geholpen.
de sensor_afvalinfo heeft inderdaad een id gekregen van mij namelijk : sensor.afvalinfo_huis

maar als ik dit aanpas in config:

   {%- set days = state_attr('sensor.afvalinfo_huis_' ~l, 'days_until_collection_date')%}

zie ik het volgende:
![Naamloos](https://user-images.githubusercontent.com/77883357/111030001-32ad0b80-8400-11eb-9023-95c4942304ec.png)

**Comment by nickster93** [comment]
Bij mij lijkt ongeveer het zelfde. Mijn entities geven ook niks terug. 

![image](https://user-images.githubusercontent.com/61862374/111209674-9dab3d80-85cc-11eb-9d38-9b68206fb249.png)

sensor:
    - platform: afvalinfo
      id: huis
      resources:
        - gft
        - pbd
        - papier
        - restafval
        - textiel
        - trash_type_today
        - trash_type_tomorrow
      location: xxxx 
      postcode: xxxx
      streetnumber: xxxx
      dateformat: '%d-%m-%Y'
      locale: 'nl'
      timespanindays: 365

**Comment by heyajohnny** [comment]
@Ryukenden88 
Heb je deze ook aangepast?
`{{l}} · {{ states('sensor.afvalinfo_' ~l) }}`

**Comment by heyajohnny** [comment]
@nickster93 
Woon je toevallig in de gemeente Goes?

**Comment by Ryukenden88** [comment]
> @Ryukenden88
> Heb je deze ook aangepast?
> `{{l}} · {{ states('sensor.afvalinfo_' ~l) }}`

ah nee, die had ik over het hoofd gezien.
ik heb het id "huis" weggehaald en hij werkt nu prima.

Denk dat ik hem ook zo maar laat zonder naam zo erg is het niet :)
Bedankt voor de hulp!

**Comment by heyajohnny** [comment]
Geen probleem, dan sluit ik dit issue.
