### ISSUE TITLE
Gemeente Nuenen

### ISSUE THREAD

**Issue by bgroenen** [heyajohnny/afvalinfo#186]
Hi,

Bij mij (woon in gemeente Nuenen) werkt alles behalve de GFT info. Geen idee wat ik kan aanleveren om het te verduidelijken, maar hoor het natuurlijk graag als iik wat kan doen. Super toevoeging aan mijn Home Assistant :)

**Comment by heyajohnny** [comment]
Ik zag dat er een mapping voor GFT mistte voor Nuenen. Zojuist een update doorgevoerd. Zou je kunnen laten weten of het nu werkt?

**Comment by bgroenen** [comment]
Hey,

Ja werkt top nu! En net op tijd, zie dat ik hem morgen aan de straat moet zetten :)

Dank!!

**Comment by heyajohnny** [comment]
Top ;) Dan sluit ik het issue

**Comment by svleuken** [comment]
Kun je kijken of je GFT voor 'laarbeek' ook kunt fixen?

**Comment by heyajohnny** [comment]
@svleuken Ik heb voor 'laarbeek' afvalstroom id 80 toegevoegd. Laat maar weten of het werkt

**Comment by svleuken** [comment]
Geweldig. Net getest en "it works like a charm"
Nogmaals dank
