### ISSUE TITLE
Takken ronde Haarlemmermeer

### ISSUE THREAD

**Issue by ErikVet** [heyajohnny/afvalinfo#187]
De gemeente Haarlemmermeer heeft ook een "takken" ronde,
Deze sensor zie ik niet in Home Assistant.
Zou deze toegevoegd kunnen worden?

**Comment by heyajohnny** [comment]
Dit moet wel kunnen. Ik zal over enkele dagen kijken (als ik wat meer tijd heb) of ik dit geimplementeerd kan krijgen.

**Comment by ErikVet** [comment]
Dat zou mooi zijn
Als je informatie wil hoor ik het wel

Prettige avond
MVG Erik vet

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: heyajohnny ***@***.***>
Verzonden: Monday, March 22, 2021 8:55:07 PM
Aan: heyajohnny/afvalinfo ***@***.***>
CC: ErikVet ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] Takken ronde Haarlemmermeer (#187)


Dit moet wel kunnen. Ik zal over enkele dagen kijken (als ik wat meer tijd heb) of ik dit geimplementeerd kan krijgen.

**Comment by heyajohnny** [comment]
Takken zijn toegevoegd. Nadat je een update van afvalinfo hebt gedaan, zou het moeten werken.

**Comment by ErikVet** [comment]
Goedemiddag,

Ja het werkt,  Bedankt voor de snelle actie.

Groetjes,
Erik

Van: heyajohnny ***@***.***>
Verzonden: zaterdag 27 maart 2021 21:11
Aan: heyajohnny/afvalinfo ***@***.***>
CC: ErikVet ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] Takken ronde Haarlemmermeer (#187)


Takken zijn toegevoegd. Nadat je een update van afvalinfo hebt gedaan, zou het moeten werken.
