### ISSUE TITLE
Papier sensor werkt niet voor de gemeente Raalte

### ISSUE THREAD

**Issue by CasparTheBridge** [heyajohnny/afvalinfo#188]
De sensor.afvalinfo_papier werkt niet voor de gemeente Raalte. Dit is denk ik wel 1 van de basis collecties toch?
Textiel & Kerstboom doen het ook niet. Textiel hebben we hier in de gemeente volgens mij niet, kerstboom wel maar zal de gemeente dan vast niet doorgeven..

Kan ik helpen iets aan informatie aan te leveren voor de papier sensor?

**Comment by heyajohnny** [comment]
Het is echt per gemeente en soms per wijk verschillend wat er opgehaald wordt. Ik zie dat Rova het afval verzorgd in Raalte. Bij een willekeurige postcode in Raalte zie ik geen papier staan:
![image](https://user-images.githubusercontent.com/20553716/112050685-70710900-8b51-11eb-9b7b-309cf08e3522.png)
Ik zou zeggen, kijk even wat voor gegevens je terug krijgt [hier](https://inzamelkalender.rova.nl/). Dezelfde gegevens zou je in afvalinfo terug moeten krijgen. Mocht je daar wel Papier terug krijgen, zou je dan je postcode en huisnummer door kunnen geven, zodat ik het in afvalinfo ook door kan voeren?

**Comment by CasparTheBridge** [comment]
Dank je wel voor de snelle opvolging. Een postcode die je als voorbeeld kan gebruiken is bijvoorbeeld 8141AJ 33a
https://inzamelkalender.rova.nl/nl/8141aj/33/a/

Op de website geeft die inderdaad voor mijn postcode en ook deze postcode wel ook papier aan. Is het hiermee te vinden waarom het mis gaat?

**Comment by heyajohnny** [comment]
Volgens mij moet papier nu werken. Laat maar weten of het gefixt is?

**Comment by CasparTheBridge** [comment]
Gaaf! Dit werkt nu goed 😃👍🏼
