### ISSUE TITLE
Irado api down?

### ISSUE THREAD

**Issue by Dutchone** [heyajohnny/afvalinfo#189]
Goededag,

Mijn stad zit in irado gebied, ik heb meerdere adressen geprobeerd maar ze doen het allemaal niet.

Helaas niet de tijd gehad om buiten irado gebied te testen, als ik er weer achter zit zal ik dat even proberen

**Comment by heyajohnny** [comment]
Heb je wellicht een voorbeeld adres? Heeft het in het verleden wel gewerkt?

**Comment by Dutchone** [comment]
Het heeft in het verleden zeker gewerkt, heb er ook pushberichten op gebouwd in HA

3123AA 37 Schiedam

**Comment by lkeijser** [comment]
Zelfde issue hier. De website van irado is ook gewijzigd, dus wellicht is dat het probleem. Zou graag mee helpen zoeken, maar de nieuwe opzet (trashapi) is wat verwarrend voor mij.

**Comment by lkeijser** [comment]
Zojuist even een oudere versie teruggezet (commit id f4e530d09c621e1fbc8fa45b200445e284ac5fc5) en daarbij heb ik hetzelfde probleem, dus ik ben er vrij zeker van dat het komt door de wijziging bij irado.nl

**Comment by lkeijser** [comment]
Ik heb het (in de oude versie) in const/const.py aangepast :

```
--- /tmp/afvalinfo/const/const.py	2021-03-25 18:57:12.000000000 +0100
+++ const/const.py	2021-03-25 19:07:26.576524735 +0100
@@ -47,8 +47,8 @@
         "https://inzamelkalender.hvcgroep.nl/rest/adressen/{0}/kalender/{1}"
         ],
     "irado": [
-        "https://www.irado.nl/bewoners/afvalkalender",
-        "https://www.irado.nl/bewoners/afvalkalender"],
+        "https://www.irado.nl/afvalkalender",
+        "https://www.irado.nl/afvalkalender"],
     "katwijk": ["https://afval.katwijk.nl/nc/afvalkalender/?tx_windwastecalendar_pi1%5Baction%5D=search"],
     "middendrenthe": [
         "https://www.middendrenthe.nl/website/!suite86.scherm0325?mPag=6523&mAlle=J",
@@ -157,4 +157,4 @@
 
 _LOGGER = logging.getLogger(__name__)
 
-MIN_TIME_BETWEEN_UPDATES = timedelta(hours=1)
\ No newline at end of file
+MIN_TIME_BETWEEN_UPDATES = timedelta(hours=1)

```

en nu werkt het daarin weer. 

Hopelijk kun je daar wat mee. Ga ik er even voor 't gemak vanuit dat die azure site waar trashapi naar verwijst van jou is ;)

**Comment by PanjaTuig** [comment]
Hier werkt hij ook niet (ook irado)
heeft het altijd gedaan! (sins een week niet meer)
Frieslandlaan 
Vlaardingen

**Comment by heyajohnny** [comment]
@lkeijser Thnx! Zojuist aangepast en lijkt volgens mij weer te werken. Laat maar weten of alles weer werkt.

**Comment by quintenooms** [comment]
Hoi hoi,
Ook bij ons een aantal dagen hetzelfde probleem maar zojuist inderdaad weer een nieuwe datum verschenen. Ontzettend bedankt!

(Ook in Vlaardingen)

**Comment by heyajohnny** [comment]
Top, dan lijkt het weer te werken. Ik sluit het issue

**Comment by Dutchone** [comment]
Snel opgelost! Bedankt!
