### ISSUE TITLE
Mijn adres doet het niet meer

### ISSUE THREAD

**Issue by Sholofly** [heyajohnny/afvalinfo#191]
Hallo,
Allereerst bedankt voor dit topcomponent!

Mijn adres doet het niet meer:

```
Error occurred. Please check the address with postcode: '8097PC' and huisnummer: '19' on the website of your local waste collector in the gemeente: 'oldebroek'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working
```
https://www.mijnafvalwijzer.nl/nl/8097PC/19/A/ Doet het nog wel...
Ik heb mijn suffix ook toegevoegd aan de config, maar daarvoor deed hij het ook al niet.

**Comment by heyajohnny** [comment]
Bedankt voor het melden! Ik had blijkbaar een hoop locaties kapot gemaakt met de 'takken' update en was te lui om even alle tests te laten draaien. Als het goed is moet je weer data krijgen. Exuses voor het ongemak

**Comment by Sholofly** [comment]
Geen probleem man, life of a developer ;) Bedankt voor de snelle fix!
Ik zie wel dat onze takkeninfo het niet doet terwijl deze wel in de API
zit. Zie je nog kans om daar een keer naar te kijken?
[image: image.png]

Op zo 28 mrt. 2021 om 10:03 schreef heyajohnny ***@***.***>:

**Comment by heyajohnny** [comment]
Takken zouden het nu moeten doen

**Comment by Sholofly** [comment]
Top, thanks!

Op zo 28 mrt. 2021 om 18:56 schreef heyajohnny ***@***.***>:
