### ISSUE TITLE
Afvalinfo werkt niet bij gewijzigde ophaaldag in Uden

### ISSUE THREAD

**Issue by hmmbob** [heyajohnny/afvalinfo#192]
Komende zaterdag wordt het GFT in Uden opgehaald, in plaats van op maandag (=2e paasdag). Het lijkt erop dat afvalinfo daarop crasht:

```
Error occurred. Please check the address with postcode: '540xxx' and huisnummer: 'xx' 
on the website of your local waste collector in the gemeente: 'uden'. It's probably a 
faulty address or the website of the waste collector is unreachable. If the address is 
working on the website of the local waste collector and this error still occured, 
please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo 
with details of the location that isn't working
```

Ik wil je best de postcode en huisnummer op een andere manier delen, maar hier op Github zetten lijkt me niet handig :)

Dit is hoe het er op de gemeentewebsite nu uitziet:
![image](https://user-images.githubusercontent.com/33529490/112946600-04386b80-9136-11eb-969c-e12bf71be347.png)

Aangezien hij lijkt te struikelen over de gewijzigde data, een snippet HTML voor de GFT:

```html
<tr><th class="icon-gft" scope="row"><p>GFT+E</p></th>
<td><del>Maandag  5 april</del> <ins>Zaterdag  3 april</ins>
<br>Maandag 12 april<br>Maandag 19 april<br></td></tr>
```

Dit is de snippet voor de restafval, soortgelijk opgebouwd (maar nog een aantal ophaalrondes weg):

```html
<tr><th class="icon-restafval" scope="row"><p>Restafval</p></th>
<td>Donderdag  1 april<br>Donderdag 22 april<br>
<del>Donderdag 13 mei</del> <ins>Zaterdag 15 mei</ins><br></td></tr>
```

**Comment by heyajohnny** [comment]
Wellicht is een adres niet nodig. Ik heb een kleine aanpassing gedaan in de code. Zou je kunnen laten weten of het nu weer werkt?

**Comment by hmmbob** [comment]
Jep, werkt weer!

Dank je wel! :)
