### ISSUE TITLE
FR: Add diftar sensors

### ISSUE THREAD

**Issue by Sholofly** [heyajohnny/afvalinfo#193]
Hi there, there's some extra information about number of collections for restafval in the mijnafvalwijzer API (Diftar). Maybe you can add some extra sensors?
- Last collection date
- Total collections this year

Steps to access this data:

1)  Do a GET call to https://www.mijnafvalwijzer.nl/nl/{zipcode}/{nr}/{addition}/diftar
      - retrieve the Afvalwijzer-cookie
2)  Do a POST call to https://www.mijnafvalwijzer.nl/site/diftarlogin with:
     - cookie from 1
     - form-data => access_code = {personal accesscode (parameter in sensor settings?)}  
3)  Do a post call to https://www.mijnafvalwijzer.nl/site/diftargettransactions, optional with 
     - cookie from 1
     - form-data => startDate: {DD-MM-yyyy}, endDate: {DD-MM-yyyy}

**Comment by heyajohnny** [comment]
Do you have an example zipcode and number that uses diftar, because mijnafvalwijzer has locations with different trash types and options.

**Comment by Sholofly** [comment]
Yeah, it's 8097pc 19a

Op di 20 apr. 2021 22:06 schreef heyajohnny ***@***.***>:

**Comment by heyajohnny** [comment]
I need to test it somehow and filter the data in the page, so I need a 'toegangscode'/'accesscode'. If you're willing to send it to me by mail, it would be great.

**Comment by heyajohnny** [comment]
I'm closing the issue since I'm not able to implement this without an accesscode

**Comment by Sholofly** [comment]
Hi @heyajohnny Sorry for not following up on this. Had some other priorities. I am able to share an access code with you. Can you reopen this one and tell me how I can share my code with you?

**Comment by heyajohnny** [comment]
I'll reopen the issue. The easiest way is to send it in an email. You can send it to:
heyajohnny [at] gmail [dot] com

**Comment by Sholofly** [comment]
I've sent you an email. Thanks a lot!

Op do 24 mrt. 2022 20:39 schreef heyajohnny ***@***.***>:

**Comment by heyajohnny** [comment]
I've looked a bit at the site and what you want is:
- Last collection date. (That would be 23-03-2022)
- Total collections this year. (That would be 3)

The only question I have is: Is diftar only used for 'Restafval' or also for other types of waste?

![image](https://user-images.githubusercontent.com/20553716/162636472-70bb5c71-818a-4699-bee9-0e9d7c7b82fd.png)

**Comment by Sholofly** [comment]
For my city: yes, but in general, I don't know.

**Comment by heyajohnny** [comment]
I've just added support for diftar.
You need to update afvalinfo and add the 'diftarcode' in your configuration.yaml
![image](https://user-images.githubusercontent.com/20553716/172382770-8a1434dc-76de-4bfb-9f43-4cd66881a6a1.png)
![image](https://user-images.githubusercontent.com/20553716/172382251-eca03cde-2366-4561-bc66-0cf636e16696.png)

**Comment by Sholofly** [comment]
Works like a charm! TY!

**Comment by bramstroker** [comment]
This is great, exactly what I was looking for. Thanks a lot!
