### ISSUE TITLE
PMD in zakken Zwolle

### ISSUE THREAD

**Issue by arne913** [heyajohnny/afvalinfo#195]
Hoi, volgens mij zit er een verschil in 'PMD' of 'PMD in zakken', sinds afgelopen april wordt dat hier zo opgehaald. De sensor pmd werkt nu niet. (8021B)

**Comment by arne913** [comment]
Correctie: sensor pbd

**Comment by heyajohnny** [comment]
Zojuist een update doorgevoerd. Zou nu weer moeten werken
