### ISSUE TITLE
Gemeente Eemsdelta

### ISSUE THREAD

**Issue by JBSDM** [heyajohnny/afvalinfo#197]
Ik heb onderstaande configuratie gebruikt voor de Gemeente Eemsdelta:

```
platform: afvalinfo
resources:
  - gft
  - kerstboom
  - pbd
  - papier
  - restafval
  - textiel
  - trash_type_today
  - trash_type_tomorrow
location: eemsdelta
postcode: 
streetnumber: 
streetnumbersuffix: ""
dateformat: "%d-%m-%Y"
locale: "nl"
timespanindays: 365
```

Na deze config krijg ik onderstaande terug van een entiteit:

```
year_month_day_date: null
last_update: '29-04-2021 19:19'
hidden: true
days_until_collection_date: null
is_collection_date_today: false
friendly_name: Afvalinfo PBD
icon: 'mdi:recycle'
```

Doe ik iets verkeerd of werkt deze Home Assistant integratie niet goed samen met mijn gemeente?

**Comment by hmmbob** [comment]
Misschien een gekke vraag, maar in je daadwerkelijke config heb je wel een postcode en huisnummer opgegeven?

**Comment by JBSDM** [comment]
Uiteraard, die zijn om privacy redenen weggelaten.

**Comment by hmmbob** [comment]
Too, just checking 🤷🏻

**Comment by JBSDM** [comment]
```2021-04-29 19:52:57 ERROR (SyncWorker_22) [custom_components.afvalinfo.const.const] Error occurred. Please check the address with postcode: 'XXXXX' and huisnummer: 'XX' on the website of your local waste collector in the gemeente: 'eemsdelta'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working```

Dit krijg ik in de logging trouwens.

**Comment by heyajohnny** [comment]
En? Werkt je adres wel bij de lokale afvalverwerker?
https://www.eemsdelta.nl/mijn-afvalkalender

**Comment by JBSDM** [comment]
Jazeker, ik krijg dan netjes alles dagen dat er opgehaald wordt terug.

**Comment by heyajohnny** [comment]
Ik heb net een update doorgevoerd. Een URL was gewijzigd bij Eemsdelta. Zou je kunnen laten weten of het nu wel werkt? Alvast bedankt

**Comment by JBSDM** [comment]
Sorry, voor mijn mond gepraat. Hij doet het:)! Hij geeft alleen voor de Grijze container de verkeerde datum weer:


![image](https://user-images.githubusercontent.com/9931252/117156391-e8238c00-adbd-11eb-9577-65d5a4e8a13f.png)

**Comment by heyajohnny** [comment]
Dat is vreemd. Ik filter namelijk op de tekst 'Grijze container' en daarvan pakt hij de eerste die in het heden of de toekomst ligt.
![image](https://user-images.githubusercontent.com/20553716/117341330-42961880-aea2-11eb-843e-069b0241e130.png)
Met mijn voorbeeld postcode huisnummer werkt het prima:
9933TD, 101
`{[
  {
    "date": "2021-05-12T00:00:00",
    "name": "Pbd",
    "daysTillDate": 6
  },
  {
    "date": "2021-05-31T00:00:00",
    "name": "Papier",
    "daysTillDate": 25
  },
  {
    "date": "2021-06-02T00:00:00",
    "name": "Gft",
    "daysTillDate": 27
  }
]}`

Wellicht kun je nog wat informatie geven, of een voorbeeld postcode/huisnummer waar de PBD ook niet goed werkt

**Comment by JBSDM** [comment]
Ik heb net jouw voorbeeld postcode even in mijn Home Assistant gezet en krijg het volgende:

![image](https://user-images.githubusercontent.com/9931252/117404428-36de3c80-af0a-11eb-85f8-30f3159b46f7.png)

Hier staat de GFT er verkeerd in. Voor de zekerheid post ik mijn Home Assistant Config nog maar even:

`
platform: afvalinfo
resources:
  - gft
  - pbd
  - trash_type_today
  - trash_type_tomorrow
location: eemsdelta
postcode: 9933TD
streetnumber: 101
streetnumbersuffix: ""
dateformat: "%d-%m-%Y"
locale: "nl"
timespanindays: 365
`

**Comment by hmmbob** [comment]
Ik merk op dat de screenshot van JBSDM en de JSON van heyajohnny dezelfde gegevens bevatten.

**Comment by heyajohnny** [comment]
Ja, ik was denk ik niet helemaal wakker gisterenavond. Ik heb een fix doorgevoerd. Laat maar weten of het nu werkt

**Comment by JBSDM** [comment]
Gaat nu prima! Bedankt:D
