### ISSUE TITLE
Omschrijving van afvalsoort leesbaar

### ISSUE THREAD

**Issue by WHagenauw** [heyajohnny/afvalinfo#198]
Is het ook mogelijk dat bijvoorbeeld als er GFT afval gehaald word, dat er Groene Container komt te staan ipv GFT? Zelfde geld voor restafval in Grijze Container of PBD in Plastic o.i.d.? In het dashboard leest dat beter en zo kan ik het ook met spraak gebruiken door Google het te laten uitspreken, en dan hoort Groene Container toch mooier dan GFT.

**Comment by hmmbob** [comment]
Om met dat laatste te beginnen: ik heb dit met behulp van Frenck gebouwd:

![image](https://user-images.githubusercontent.com/33529490/117426438-305cbe80-af24-11eb-94a3-e1bfcc13ea36.png)


Dan je eerste vraag: dat kan altijd met template sensoren. Zie ook https://github.com/heyajohnny/afvalinfo#attributes

**Comment by heyajohnny** [comment]
@WHagenauw Inderdaad wat hmmbob zegt. Gewoon een template sensor maken.
