### ISSUE TITLE
Mislabeled Restafval

### ISSUE THREAD

**Issue by Warstomper** [heyajohnny/afvalinfo#2]
Je hebt er voor gekozen om restafval onder afvalstroom 92 te labelen. Maar dit klopt eigenlijk niet. Het restafval in de gemeente sliedrecht wordt op centrale plaatsen (ondergrondse containers) verzameld. 

Afvalstroom 92 is bedoeld voor plastic, blik en drankkarton (met zo'n zilverachtige laag er in). Wellicht dat je dit wilt aanpassen? 

Verder super tof dat een mede-Sliedrechter hier werk van heeft gemaakt!

**Comment by heyajohnny** [comment]
Je hebt helemaal gelijk!  

Zojuist heb ik een wijziging doorgevoerd en 'restafval' hernoemd naar 'pbd'. 

> Verder super tof dat een mede-Sliedrechter hier werk van heeft gemaakt!

Thnx! Altijd leuk om je eigen projecten met anderen te kunnen delen ;)
