### ISSUE TITLE
Add "kerstbomen"

### ISSUE THREAD

**Issue by martijndemulder** [heyajohnny/afvalinfo#20]
The integration is working great, but can you make it possible to add "kerstbomen" to the resources?

**Comment by heyajohnny** [comment]
Yeah sure! I hope you understand that it won't be set high in my priority list, since there aren't any "kerstbomen" until somewhere near Christmas. I'll keep the issue open and will inform you when it's implemented.

**Comment by heyajohnny** [comment]
I've just added support for trash type 'kerstboom'.
Beware that it's only supported by +- 50% of the waste collectors.

**Comment by martijndemulder** [comment]
Thanks! I'll check it out this week!Op 17 dec. 2020 14:02 schreef heyajohnny <notifications@github.com>:
I've just added support for trash type 'kerstboom'.
Beware that it's only supported by +- 50% of the waste collectors.

**Comment by heyajohnny** [comment]
And...? 😉

**Comment by martijndemulder** [comment]
It does work, however it doesn't seem to populate it with a pickup date yet.
![image](https://user-images.githubusercontent.com/60365040/103171022-16f68800-4849-11eb-8696-3ef640d43186.png)

I think my waste collector does support it, so i'll wait patiently :)

**Comment by Ivo-tje** [comment]
do you at least get any collection dates in 2021? ;) Since they will not collect them in 2020 and the whole plugin doesn't seem to give us data for 2021 yet....

**Comment by martijndemulder** [comment]
I did get collection dates in 2021 for GFT:
![image](https://user-images.githubusercontent.com/60365040/103273420-90b08200-49bf-11eb-91c1-1c5676a5fde5.png)

But not for the rest like FI PBD:
![image](https://user-images.githubusercontent.com/60365040/103273462-a756d900-49bf-11eb-91fe-ba9c9591201d.png)

Since my span is set to 365, it should be returning something for the other sensors as well, right? Or the information is not released yet via the API?
`  - platform: afvalinfo
    resources:
      - pbd
      - gft
      - papier
      - restafval
      - kerstboom
      - trash_type_today
      - trash_type_tomorrow
    city: helmond
    postcode: 1234AB
    streetnumber: 1234
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365`

**Comment by Ivo-tje** [comment]
ok, 2021 is back here :P But no Christmas tree collection this year due to covid ;)
They will drive through the neighbourhoods to collect them when found, or you put them in the green bin.

**Comment by martijndemulder** [comment]
The data is scheduled in the “Afvalapp” though 😊


Van: Ivo-tje <notifications@github.com>
Verzonden: dinsdag 29 december 2020 10:27
Aan: heyajohnny/afvalinfo <afvalinfo@noreply.github.com>
CC: martijndemulder <martijndemulder@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [heyajohnny/afvalinfo] Add "kerstbomen" (#20)


ok, 2021 is back here :P But no Christmas tree collection this year due to covid ;)
They will drive through the neighbourhoods to collect them when found, or you put them in the green bin.

**Comment by heyajohnny** [comment]
I think you mean 'DeAfvalApp'... They've changed 'Kerstbomen' to 'Kerstboom' for (some) gemeentes.
It should be fixed now ;) Enjoy and may this year be over soon 😆

**Comment by martijndemulder** [comment]
That's wat I meant :) Anyways, it's populated with data now!

![image](https://user-images.githubusercontent.com/60365040/103410954-00fd0600-4b6e-11eb-8d56-0d8d32d1e880.png)

**Comment by heyajohnny** [comment]
Thnx! You too!
