### ISSUE TITLE
Toevoegen gemeente Gennep

### ISSUE THREAD

**Issue by mrlexley** [heyajohnny/afvalinfo#201]
Ik zou graag de gemeente Gennep toegevoegd willen hebben.
Ze werken met twee wijken wat het een beetje lastig maakt. Heb een aanvraag uitstaan of ze een lijst hebben met de benodigde informatie per wijk.

De postcodes van de kern van Gennep zijn 6591xx en 6595xx. Deze twee postcodes zijn wel opgesplitst in meerder dorpen. Alleen de postcodes voor Gennep zijn op de maandag. De rest is op de dinsdag. (Buitengebied Gennep kan afwijken, daarvoor heb ik het overzicht van de gemeente nodig.)

https://www.gennep.nl/inwoners-ondernemers/onderwerpen-a-z_42332/product/afvalkalender_857.html

**Comment by heyajohnny** [comment]
Hoi mrlexley

Ik zou het graag toevoegen, maar als ik niet precies de postcodes weet is het waarschijnlijk zeer onbetrouwbaar. Ik heb zoiets nu ook voor de gemeente steenbergen gedaan en daarbij heeft Timo mij allerlei postcodes gestuurd (van 1 van de 4 verschillende routes), maar dit kost gewoon enorm veel tijd om te implementeren en is eigenlijk niet betrouwbaar genoeg.

Mocht de gemeente betere informatie kunnen verschaffen wil ik Gennep wel toevoegen, maar voor nu ga ik het niet doen. Sorry

**Comment by beecreate** [comment]
Ook ik zou graag Gennep toegevoegd hebben; begrijpend dat dit wat werk kan zijn.

Verduidelijking van de gegevens:


Frequentie: 1x per 2 weken, startend week 2 (en uitzonderingen op feestdagen volgens eerder gelinkte afvalkalender)

**GFT en Restafval**
Maandagen; Kern van Gennep: 
Postcodes
- 6591 xx

Dinsdagen; Buitengebied Gennep en omliggende dorpen
Postcodes
- 6595 xx
- 9596 xx
- 9598 xx
- 9599 xx

**Plastic, Metaal en Drankkartons (PMD)**
Woensdagen
Postcodes:
- 6591 xx
- 6595 xx
- 9596 xx
- 9598 xx
- 9599 xx

**Klein Chemisch Afval**
Elke eerste zaterdag van de maand
Postcodes:
- 6591 xx
- 6595 xx
- 9596 xx
- 9598 xx
- 9599 xx


Indien je de data op een andere manier zou willen ontvangen (bijv per postcode per ophaaldatum), geef dan aub een template csv met wat je ingevuld wil hebben, dan klus ik dat met alle plezier voor je in elkaar. Gennep zelf lijkt er niet heel veel voor aan te willen leveren.

**Comment by ImagineerNL** [comment]
Het nieuwe jaar komt er aan en de nieuwe afvalkalender dus ook.
Nogmaals, @heyajohnny , als je me een template of voorbeeld .csv aan kan leveren heb ik geen enkele moeite om dit jaarlijks voor alle bovengenoemde postcodes in Gennep en omstreken aan te leveren.

Wel zou het fijn zijn als er een kopje onder de readme hier op github kan komen waar je evt opmerkingen per gemeente neerzet. Ik gok zomaar dat wij niet de enige gemeente zijn. En ik heb ook het idee dat mensen die met HA werken ook wel een _beetje_ met een flexibele configuratie aan de slag kunnen

`Gemeente Gennep:   vul bij postcode uw cijfers plus XX in voor de letters en huisnummer altijd 1`

**Comment by heyajohnny** [comment]
Hoi, sorry voor het late reageren.
Hetgeen wat je hierboven op 8 augustus neer hebt gezet is in principe prima. 
Laat maar weten wanneer je de gegevens voor volgend jaar hebt, dan zal ik het zo snel mogelijk toevoegen.

**Comment by ImagineerNL** [comment]
Super, ik hou je op de hoogte

**Comment by ImagineerNL** [comment]
@mrlexley @heyajohnny , Dit issue kan gesloten worden.
De gemeente Gennep zit vanaf 1januari digitaal aangesloten via prezero. Je kan er voor kiezen om de integratie met prezero aan te sluiten; het zit echter ook al in de HA integratie van pippyn
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer

**Comment by mrlexley** [comment]
Thanks :-)

**Comment by heyajohnny** [comment]
Gennep toegevoegd in versie 0.8.9
