### ISSUE TITLE
No ‘version’ key in the manifest file for custom integration

### ISSUE THREAD

**Issue by jeroen-groeneweg** [heyajohnny/afvalinfo#202]
Hi,

In the latest HA upgrade, adding a version for custom components is mandatory.
Could you please ad a version to your integration?

Example:

{
  "name": "Afvalinfo",
  "content_in_root": false,
  "render_readme": true,
  "version": 1.0,
  "domains": ["sensor"],
  "country": ["NL"],
  "homeassistant": "0.100.0"
}

**Comment by heyajohnny** [comment]
I think you need to update Afvalinfo. The version number is already available [here](https://github.com/heyajohnny/afvalinfo/blob/master/custom_components/afvalinfo/manifest.json)

**Comment by jeroen-groeneweg** [comment]
Hi Thanks for the info. I'm running the latest version 0.8.2 My manifest isn't updated through HACS however.

My current manifest:

{
  "domain": "afvalinfo",
  "name": "Afvalinfo",
  "documentation": "https://github.com/heyajohnny/afvalinfo",
  "dependencies": [],
  "codeowners": [
    "@heyajohnny"
  ],
  "requirements": [
    "beautifulsoup4==4.9.0",
    "Babel==2.8.0",
    "python-dateutil==2.8.1"
  ]
}

The errors in my log.

2021-06-28 18:24:40 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'afvalinfo'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'afvalinfo'

I manually pasted the contents of your manifest from the repo so my issue is fixed :) Thanks for the support! Might be worth looking into why the manifest isn't updated through HACS.

**Comment by heyajohnny** [comment]
That's very strange... I've updated Afvalinfo on my own Home Assistant instance a couple of days ago and I see that all the files are nicely replaced:
![image](https://user-images.githubusercontent.com/20553716/123952167-ec2aef00-d9a5-11eb-95d4-a2da013a93e1.png)
And I just did a reinstall through HACS and all the files are again, replaced by new ones:
![image](https://user-images.githubusercontent.com/20553716/123952563-7410f900-d9a6-11eb-8777-394aad9dae75.png)

**Comment by jeroen-groeneweg** [comment]
Thanks for looking into it so much. No idea why my manifest wasn't updated but maybe I'm the odd one out ;) I'll close the issue and keep a close eye on it for future release. Thanks a lot for the integration!
