### ISSUE TITLE
gemeente Echt-Susteren geeft alleen PBD

### ISSUE THREAD

**Issue by IGastel** [heyajohnny/afvalinfo#203]
voor de gemeente Echt-Susteren ontvang ik alleen datums voor de PBD. restafval, GFT en kerstboom geeft als status onbekend.
ik gebruik postcode 6102EB.

groetjes,
Ivo

**Comment by heyajohnny** [comment]
Enkele benamingen zijn aangepast in DeAfvalApp die ik als referentie gebruik.
Zojuist heb ik enkele benamingen aangepast, waardoor het weer zou moeten werken. Laat maar weten of alles weer werkt zoals verwacht.

**Comment by IGastel** [comment]
yup, het werkt zoals verwacht. bedankt!
