### ISSUE TITLE
Werkt niet meer na update?

### ISSUE THREAD

**Issue by liselotte111** [heyajohnny/afvalinfo#204]
Werkte super goed, maar doet het opeens niet meer. Geeft unavailable state bij alle sensoren. Is vermoedelijk bij update misgegaan. Vanuit HACS verwijderd en opnieuw installeren helpt niet

Draai Homeassistant OS 
core-2021.6.6
supervisor-2021.06.6

**Comment by heyajohnny** [comment]
Wat zijn je adresgegevens die je gebruikt en die niet juist werkt? Hoeft uiteraard niet je eigen adres te zijn.

**Comment by heyajohnny** [comment]
Blijkbaar werkt het weer? Ik sluit het issue, mocht er toch nog iets zijn, kan het altijd weer geopend worden

**Comment by liselotte111** [comment]
Ik heb helaas geen melding gekregen van je reactie :( 

Ik gebruikte 3755 AZ. Maar dat werkt niet meer

**Comment by heyajohnny** [comment]
De afvalkalender voor Eemnes zou het weer moeten doen. Laat maar weten of het weer werkt

**Comment by liselotte111** [comment]
Dankje! Ik ga het checken

**Comment by svleuken** [comment]
Zelfde probleem voor 5741HR helaas...
(days_until_collection_date: null)

**Comment by heyajohnny** [comment]
Fixed in issue #211
