### ISSUE TITLE
Can't find sensor

### ISSUE THREAD

**Issue by freggel2** [heyajohnny/afvalinfo#205]
Hello,

I have copied the files in the /custom_components/afvalinfo/ folder to: [homeassistant]/config/custom_components/afvalinfo/
That is, i've created a custom_components folder and added alle the files describes as above.

When I go to HomeAssistant I can't find the sensor. When I run check configuration it says: Platform error sensor.afvalinfo - Integration 'afvalinfo' not found.

What am I doing wrong?

I have also installed hacs but I cannot find the afvalinfo there.

**Comment by heyajohnny** [comment]
You can search for 'afvalinfo' in the HACS store
![image](https://user-images.githubusercontent.com/20553716/125200595-19ac4e00-e26c-11eb-8f73-5763bca08548.png)
or manually add the repository by clicking on the menu icon (in the HACS store) and then 'aangepaste repositories'/'custom repositories'.
![image](https://user-images.githubusercontent.com/20553716/125200675-5710db80-e26c-11eb-8251-bffe544dc948.png)
and copy / paste this in the URL field:
https://github.com/heyajohnny/afvalinfo.git
Please let me know if it worked

**Comment by freggel2** [comment]
Thanks.
It works.
Guess I had to wait a little bit longer. I did exactly the steps as described but nothing showed up.
A few days later I've tried it again with the steps as described and it suddenly popped up to install afvalinfo.
But then after a reboot of HA it did'nt show the entity. Wait a little longer, reboot again and then suddenly it appears.

So yeah, it works now thank you very much.
