### ISSUE TITLE
Problemen met mijn config?

### ISSUE THREAD

**Issue by colinquaden** [heyajohnny/afvalinfo#206]
Hallo,

Dit is misschien een vraag totaal overbodig maar goed ik loop hier helaas op vast. ik heb deze config erin gezet. hoe krijg ik dit nou in mijn lovelance UI?

alvast bedankt!

  sensor:
    - platform: afvalinfo
      resources:
        - pbd
        - gft
        - papier
        - restafval
        - trash_type_today
        - trash_type_tomorrow
      location: heerlen
      postcode: 5555PA
      streetnumber: 15

**Comment by colinquaden** [comment]
ohh heey ik heb het gevonden alleen nu de vraag of ik ook kan instellen dat hij alleen aangeeft over hoeveel dagen iets wordt opgehaald?

**Comment by heyajohnny** [comment]
Misschien zoiets als dit maken in je config?

```- platform: template
  sensors:
    afvalinfo_next_trash_type_and_date:
      value_template: >
        {% set ns = namespace(minimum=365) %}
        {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
        {%- for l in list %}
        {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
        {%- if days != None and days < ns.minimum %}
        {%- set ns.minimum = days %}
        {%- endif %}
        {%- endfor %}
        {%- for l in list %}
        {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
        {%- if days == ns.minimum %}
        {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
        {%- endif %}
        {%- endfor %}```

**Comment by colinquaden** [comment]
zo?

sensor:
  - platform: afvalinfo
    resources:
     - pbd
     - gft
     - papier
     - restafval
     - trash_type_today
     - trash_type_tomorrow
    location: 
    postcode: 

sensor:
  - platform: afvalinfo
       afvalinfo_next_trash_type_and_date:
         value_template: >
           {% set ns = namespace(minimum=365) %}
           {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
           {%- for l in list %}
           {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
           {%- if days != None and days < ns.minimum %}
           {%- set ns.minimum = days %}
           {%- endif %}
           {%- endfor %}
           {%- for l in list %}
           {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
           {%- if days == ns.minimum %}
           {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
           {%- endif %}
           {%- endfor %}

**Comment by colinquaden** [comment]
zo?

> sensor:
  - platform: afvalinfo
    resources:
     - pbd
     - gft
     - papier
     - restafval
     - trash_type_today
     - trash_type_tomorrow
    location: 
    postcode: 

sensor:
  - platform: afvalinfo
       afvalinfo_next_trash_type_and_date:
         value_template: >
           {% set ns = namespace(minimum=365) %}
           {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
           {%- for l in list %}
           {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
           {%- if days != None and days < ns.minimum %}
           {%- set ns.minimum = days %}
           {%- endif %}
           {%- endfor %}
           {%- for l in list %}
           {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
           {%- if days == ns.minimum %}
           {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
           {%- endif %}
           {%- endfor %}

**Comment by colinquaden** [comment]
ik heb de config zo kan dit werken?
`sensor:
  - platform: afvalinfo
    resources:
     - pbd
     - gft
     - papier
     - restafval
     - trash_type_today
     - trash_type_tomorrow
    location: heerlen
    postcode: 3322AS
afvalwijzer:
   afvalinfo_next_trash_type_and_date:
    value_template: >
     {% set ns = namespace(minimum=365) %}
     {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
     {%- for l in list %}
     {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
     {%- if days != None and days < ns.minimum %}
     {%- set ns.minimum = days %}
     {%- endif %}
     {%- endfor %}
     {%- for l in list %}
     {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
     {%- if days == ns.minimum %}
     {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
     {%- endif %}
     {%- endfor %}`

**Comment by colinquaden** [comment]
Hoi zou  je mijn config eens willen bekijken?


![config](https://user-images.githubusercontent.com/65257968/126083726-40b222f5-d91a-45d2-b0ee-aae74ef9e0be.PNG)

**Comment by colinquaden** [comment]
Hey, als ik jou code copy in de config en ik check configuration dan krijg ik een error. als ik ipv sensors: -> afvalinfo gebruik krijg ik geen error zie de foto 
![config 2](https://user-images.githubusercontent.com/65257968/126083817-eae5f377-27ee-4ae4-a6d1-48a92407c905.PNG)

**Comment by heyajohnny** [comment]
Je moet nog een regel boven 'sensors:' zetten, namelijk
- platform: template

Zoals in deze afbeelding, dan zou het moeten werken:
![image](https://user-images.githubusercontent.com/20553716/126381594-30489d43-ff97-4567-92bd-7caac550eeda.png)

**Comment by heyajohnny** [comment]
Ik ga er vanuit dat alles weer werkt en sluit dit issue
