### ISSUE TITLE
No unique ID

### ISSUE THREAD

**Issue by funnyavocado** [heyajohnny/afvalinfo#207]
Hi there,

After updating hass to 2021.7.4 i got this error in my dashbaord: 
![image](https://user-images.githubusercontent.com/83071606/127332057-95130b7f-15aa-4ea8-86fe-2c3f08b384b6.png)

It worked before and havn't changed anything in the configuration.yaml file.

Do i miss something here?

**Comment by freggel2** [comment]
It's working again. At least mine is. I've had the same issue yesterday. Today everything is up and running.

**Comment by funnyavocado** [comment]
You didn't change anything? because mine still doesn't work. I did restart several times but no luck.

**Comment by heyajohnny** [comment]
![image](https://user-images.githubusercontent.com/20553716/127662755-ee843a44-338d-458d-b5eb-9e3eb7a12a4e.png)
En als je nou zoiets als: 
id: "Dit is een willekeurig id"
tussen de bovenstaande regels in plaatst? Werkt het dan?

**Comment by funnyavocado** [comment]
Well, I just checked yesterday and all of a suddon it works again....don't know how but i'm happy :)
Tnx for the help
