### ISSUE TITLE
venlo werkt niet meer

### ISSUE THREAD

**Issue by Ryukenden88** [heyajohnny/afvalinfo#208]
Hallo,

Zoals de titel zegt, venlo herkent mijn huisnummer en adres opeen niet meer.
Is dit bekent of een oplossing hiervoor?

danku

**Comment by heyajohnny** [comment]
Venlo gebruikt ineens een heel andere pagina/systeem. Ik zal binnenkort kijken of dit weer gefixt kan worden

**Comment by Ryukenden88** [comment]
super, ik zal dit topic in de gaten houden.

**Comment by heyajohnny** [comment]
Ik heb een update doorgevoerd. Venlo zou het weer moeten doen. Laat maar weten of alles weer werkt.

**Comment by Ryukenden88** [comment]
Alles doet het weer, super!
