### ISSUE TITLE
Gemeente noardeast fryslan

### ISSUE THREAD

**Issue by miedotje** [heyajohnny/afvalinfo#209]
De gemeente noardeast fryslan werkt niet voor mij. Hij geeft aan onbekend. Wanneer ik een andere gemeente probeer met een andere adres werkt het wel. Werkt de gemeente nog wel?

**Comment by miedotje** [comment]
![image](https://user-images.githubusercontent.com/71238555/127773153-c17e8a42-0bd3-40fd-bae9-8422e0a9e1cd.png)

**Comment by heyajohnny** [comment]
Dan woon je waarschijnlijk niet in het oude Dantumadeel. Helaas is er voor het overige gedeelte van de gemeente nog geen kalender beshikbaar op postcode niveau.
https://www.noardeast-fryslan.nl/afvalkalender
