### ISSUE TITLE
Add Alkmaar

### ISSUE THREAD

**Issue by scorp-id** [heyajohnny/afvalinfo#21]
It's very cool that you added HVC already, but in the list i see that Alkmaar is missing. Could you please add that?

**Comment by heyajohnny** [comment]
Maybe you can point me to the right direction...
As far as I can see, Alkmaar uses https://inzamelkalender.stadswerk072.nl/ and not HVC.

**Comment by scorp-id** [comment]
Hmm, you are totally right! I thought it was the same since hvc collects our garbage. But the calender goes through the stadswerk072 site.

The URL where you can find data is f.e. https://inzamelkalender.stadswerk072.nl/adres/1823HM:7

**Comment by heyajohnny** [comment]
Thank you! I've just added Alkmaar :) Enjoy!

**Comment by scorp-id** [comment]
Thanks for the quick response!
