### ISSUE TITLE
Whats wrong with my confic 

### ISSUE THREAD

**Issue by twanjaarsveld** [heyajohnny/afvalinfo#213]
Hi Johnny,

Ik heb een probleem met het werkend krijgen van jouw intergratie
op de standaard postcode etc doet die het prima, maar zodra ik mijne toevoeg krijg ik hem niet meer werkend 
hier onder mijn confic 

sensor:
  - platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: utrecht
    postcode: 3761CL
    streetnumber: 53
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %}

**Comment by heyajohnny** [comment]
Hoi twanjaarsveld,

Ik haal in dit geval de data uit 'mijnafvalwijzer'. Deze geeft aan dat het adres niet bekend is en dat je contact op zou kunnen zoeken met je gemeente.
![image](https://user-images.githubusercontent.com/20553716/131229662-f15755fc-13f9-4737-8512-6992696c6e78.png)
Maar... wat blijkt: Het adres is helemaal geen adres uit Utrcht, maar uit Soest.
De afvaldata van Soest haal ik van 'rnm' https://inzamelschema.rmn.nl/adres/3761CL:53
Maar... Er zijn helemaal geen inzameldagen voor dit adres 😢 Helaas kan ik je hier dan ook niet mee verder helpen.

**Comment by twanjaarsveld** [comment]
Johnny,
Bedankt voor je hulp 
volgens de rmn site zijn dit de dagen dat ze het ophalen https://inzamelschema.rmn.nl/adres/3761CL:53:B
zag dat mijn adres niet volledig was ingevuld 
zou de onderstaande confic goed zijn ?


sensor:

platform: afvalinfo
resources:

gft
kerstboom
pbd
papier
restafval
textiel
trash_type_today
trash_type_tomorrow
location: soest
postcode: 3761CL
streetnumber: 53B
streetnumbersuffix: ""
dateformat: "%d-%m-%Y"
locale: "nl"
timespanindays: 365

**Comment by heyajohnny** [comment]
Ik denk dat je bij streetnumber: 53 in moet vullen en bij streetnumbersuffix: 'B' . Dan zou het volgens mij moeten werken.

**Comment by heyajohnny** [comment]
Sorry voor het lange wachten. Ik heb zojuist een fix doorgevoerd. Laat maar weten of alles werkt zoals verwacht

**Comment by twanjaarsveld** [comment]
Geen nieuws is zeker goed nieuws! 
Heb er alleen effe niet meer naar gekeken, maar alles werkt nu perfect!! Bedankt!!!
