### ISSUE TITLE
I don't understand het helemaal

### ISSUE THREAD

**Issue by tseuntjens** [heyajohnny/afvalinfo#215]
:-)
![image](https://user-images.githubusercontent.com/82415775/132302102-6a7dc75c-f44c-4093-ae40-05b95196632c.png)

Afval info wel geinstalleerd via HACS, maar geen Card geeft hij aan. Ben nog niet zo lang bezig met HA, maar vaak kom ik er wel uit.. maar nu dus niet. Dus iemand hellup???

**Comment by heyajohnny** [comment]
Volgens mij heb je het bovenstaande niet in je 'configuration.yaml' gezet, maar in een 'lovelace' kaart oid...
Het bovenstaande moet je plaatsen in het bestand 'configuration.yaml'. Die staat in de hoofdmap van je Home Assistant installatie.
![image](https://user-images.githubusercontent.com/20553716/132511233-85a19f04-17d9-4ed4-be5c-a5a8e15a4a91.png)

**Comment by heyajohnny** [comment]
Ik sluit dit issue, omdat het eigenlijk geen issue is en volgens mij heb je het vast al opgelost ;)
