### ISSUE TITLE
Avri werkt niet meer

### ISSUE THREAD

**Issue by supergroover** [heyajohnny/afvalinfo#216]
Hallo,

Het lijkt erop dat "Avri" niet meer werkt in mijn gemeente 6658AK

`Error occurred. Please check the address with postcode: '6658AK' and huisnummer: 'XX' on the website of your local waste collector in the gemeente: 'west maas en waal'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working`

Het huisnummer heb ik in bovenstaande log even aangepast naar XX.

In de Avri app lijkt het nog te werken.

**Comment by heyajohnny** [comment]
Heb je nog steeds problemen? Al mijn tests gaan gewoon goed.
Ik weet dat sommige afvalverwerkers laat in de avond/nacht nog weleens een update uitvoeren, waardoor het er tijdelijk uit kan liggen. Laat maar even weten als je nog steeds problemen ondervindt. Zo ja, laat dan ook even weten of je iets van een huisnummertoevoeging gebruikt. Daar wil het ook nog weleens fout gaan.
![image](https://user-images.githubusercontent.com/20553716/134764444-cccea175-87f7-4e3c-b913-0359fc0c1c3a.png)

**Comment by supergroover** [comment]
Gisterenavond heb ik voor de laatste keer geprobeerd en toen werkte het niet. Nu heb ik naar aanleiding van je bericht nog eens getest en nu werkt het.
