### ISSUE TITLE
Gemeente Opsterland

### ISSUE THREAD

**Issue by HFeenstra** [heyajohnny/afvalinfo#218]
Is the site for the gemeente Opsterland offline?

Log also states: check the address and postal code in the website of your local waste collector in the gemeente: 'opsterland'. It's probably a faulty address or the website of the waste collector is unreachable.

Have they changed the website address for your integration?

**Comment by heyajohnny** [comment]
There was an URL changed @ the waste collector 'Omrin'. I've updated the URL and it should be up and running.
Please let me know if all works as expected.

**Comment by HFeenstra** [comment]
Well hello, that was a quick fix. Heel hartelijk bedankt!
It’s working fine.
