### ISSUE TITLE
Gemeente Westland

### ISSUE THREAD

**Issue by ghost** [heyajohnny/afvalinfo#219]
De gemeente westland geeft nu de error unknown, vermoeden is dat de url is veranderd

**Comment by dvscheijndel** [comment]
> De gemeente westland geeft nu de error unknown, vermoeden is dat de url is veranderd

Hier hetzelfde, nieuwe URL is https://westland.ximmio.com/modules/6fc75608-126a-4a50-9241-a002ce8c8a6c/kalender/

**Comment by heyajohnny** [comment]
Zojuist een update doorgevoerd. Zou je kunnen laten weten of alles weer werkt, zoals verwacht?

**Comment by heyajohnny** [comment]
Top! Dan sluit ik het issue
