### ISSUE TITLE
Please add Utrecht

### ISSUE THREAD

**Issue by QkulleQ** [heyajohnny/afvalinfo#22]
Hi @heyajohnny,

Could you please Utrecht?
Here is the link where the data can be found: https://www.mijnafvalwijzer.nl/
Thanks!

**Comment by heyajohnny** [comment]
I've added Utrecht. Enjoy!

**Comment by QkulleQ** [comment]
> I've added Utrecht. Enjoy!

Thank you very much, it's working!
