### ISSUE TITLE
Gemeente: Oegstgeest

### ISSUE THREAD

**Issue by kayaozalp** [heyajohnny/afvalinfo#220]
Thank you for the great work.
Is it possible to add Oegstgeest?
Unfortunately they only share it in a PDF anually:
https://www.oegstgeest.nl/inwoners/alles-over-afval/afvalkalender

**Comment by heyajohnny** [comment]
I've already done it for one part of a 'gemeente' and it costed me a tremendous amount of time and I won't do it again for these lazy 'gemeentes'.

What I need to do is really error sensitive:
-Reading the pdf (they can decide to change the pdf style or data and it could happen multiple times a year)
-Somehow converting 'wijk' to 'postcode' + 'number'
-Adding the exception dates 'pinksteren', 'pasen' etc...

I'm sorry, but it's not worth it. You can ask your 'gemeente' if they could provide the collection dates in a 'postcode' + 'huisnummer' format, then I'll be happy to add it.
