### ISSUE TITLE
Location isn't working

### ISSUE THREAD

**Issue by schol478** [heyajohnny/afvalinfo#222]
Error occurred. Please check the address with postcode: '63XXXX' and huisnummer: 'XX' on the website of your local waste collector in the gemeente: 'landgraaf'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

The sensor is working, but the logs still showing this error

**Comment by Rikkie80** [comment]
I have the same issue with Veldhoven (seems that it occurred after upgrading to 2021.10.7).
![image](https://user-images.githubusercontent.com/42078225/139863472-21161aab-1d7a-4364-961c-9d461ace354b.png)

**Comment by Rikkie80** [comment]
Not sure what happened but everything seems to be working again...
