### ISSUE TITLE
toevoegen edam-volendam

### ISSUE THREAD

**Issue by VD-94** [heyajohnny/afvalinfo#224]
hallo,

is het mogelijk om de gemeente edam-volendam toe te voegen? het gaat dan voornamelijk over oosthuizen.

dit is de link voor afvalinfo.nl
https://www.afvalinfo.nl/afvalkalender/gemeente/0385/edam-volendam

mvg.

**Comment by heyajohnny** [comment]
Voor dit jaar is het helaas niet meer mogelijk. Mocht het al lukken om de huidige [PDF](https://www.edam-volendam.nl/sites/default/files/2021-05/Afvalkalender%202021.pdf) te lezen, wat ik al niet zeker weet, zou ik handmatig de datums in afvalinfo moeten zetten. Al die moeite is het niet waard voor nog iets meer dan een maand in dit jaar. Vaak veranderen gemeentes in het nieuwe jaar ook van systeem...

Ik zal aan het begin van volgend jaar kijken wat deze gemeente op dat moment aanbied en waarschijnlijk zal ik Edam-volendam dan toevoegen.

**Comment by heyajohnny** [comment]
Ook dit jaar gaat Edam Volendam niet lukken, omdat er alleen een pdf beschikbaar [is](https://www.edam-volendam.nl/afvalkalender-0)
