### ISSUE TITLE
Add "VET goed" as a resource for Meppel

### ISSUE THREAD

**Issue by coolnr** [heyajohnny/afvalinfo#225]
Hi, there is a resource missing for my community, Meppel, which is called VET goed.

Are you able to add?

https://speciaal.meppel.nl/afvalkalender.html

**Comment by heyajohnny** [comment]
Ik zal binnenkort kijken of ik dit toe kan voegen.

**Comment by heyajohnny** [comment]
Ik zie dat VET-goed (vetten, elektrische apparaten, textiel) gewoon zou moeten werken. 
De datum wordt getoond onder de resource 'textiel'
