### ISSUE TITLE
Afvalinfo not working yet

### ISSUE THREAD

**Issue by JPtheSoulless** [heyajohnny/afvalinfo#226]
Great idea to add the collection of the dumpsters!

I've tried to add the integration to my HA but I'm not getting any responds yet. Could you help me out?

First of all: I'm not sure what you mean by: 

> Install:
> Copy the files in the /custom_components/afvalinfo/ folder to: [homeassistant]/config/custom_components/afvalinfo/
Isn't that the same folder? 

I've downloaded the integration and the folders are in here now: /config/custom_components/afvalinfo. Do I still need to replace them?

I've added the following to the /config/configuration.yaml file:
```
#Afvalinfo
sensor:
  - platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: noardeast fryslan
    postcode: 9101VX
    streetnumber: 40
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{l}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %}`
```

But I'm not getting any responds yet:
![image](https://user-images.githubusercontent.com/71972019/143048018-a6dd9983-43be-40a0-854e-bc3d4cbc7a28.png)

Any ideas why?

**Comment by heyajohnny** [comment]
Your address is sadly not supported. 
You can check it [here](https://www.omrin.nl/afvalkalender)
Probably your address is somewhere in this [pdf](https://www.noardeast-fryslan.nl/sites/default/files/2021-05/Routes%20Inzameling%20Huishoudelijk%20Afval%202020.pdf)
The only thing you could do is asking your 'Gemeente' to digitalize their waste calendar for next year.

**Comment by JPtheSoulless** [comment]
Ooh allright. Thanks for the quick responds.

Tought it was supported because it was in the list of gemeentes:
![image](https://user-images.githubusercontent.com/71972019/143317978-187dbce0-d97b-4a1c-bf1c-79ef0201131e.png)

I'll get in touch with my gemeente but I'm not very hopefull haha.
