### ISSUE TITLE
PBD not listed 

### ISSUE THREAD

**Issue by PaulGordijn** [heyajohnny/afvalinfo#228]
Hoi,

De afvalwijzer werkt goed hier ,alleen bij de pbd geeft hij unknown
Nu heb ik al bij de afvalwijzer wijk bij Duurstede gekeken maar daar spreekt men over PMD
Ik heb zelf geprobeerd eea aan te passen maar maar met mijn beperkte kennis is het me niet gelukt de datum zichtbaar te krijgern

**Comment by heyajohnny** [comment]
Zou je misschien een postcode en huisnummer kunnen geven, waarbij de PBD/PMD ontbreekt? Hoeft uiteraard niet je eigen adres te zijn, maar dat is wat makkelijker zoeken voor mij.

**Comment by PaulGordijn** [comment]
Hoi,
bedankt voor de snelle reactie

postcode is 3961XZ   wijk bij duurstede  huisnummer 88

________________________________
Van: heyajohnny ***@***.***>
Verzonden: vrijdag 26 november 2021 09:29
Aan: heyajohnny/afvalinfo ***@***.***>
CC: Paul Gordijn ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] PBD not listed (Issue #228)


Zou je misschien een postcode en huisnummer kunnen geven, waarbij de PBD/PMD ontbreekt? Hoeft uiteraard niet je eigen adres te zijn, maar dat is wat makkelijker zoeken voor mij.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fheyajohnny%2Fafvalinfo%2Fissues%2F228%23issuecomment-979781913&data=04%7C01%7C%7C4649cadb79394c713f2d08d9b0b6d6d1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735121596521225%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yNxJgrLk1q9yxX5YqPPgoLs1Z19ojeHCmchGX3zjpmQ%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALUCWSVCQGS6GWSS27HUAJTUN5AN5ANCNFSM5IWB3X6Q&data=04%7C01%7C%7C4649cadb79394c713f2d08d9b0b6d6d1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735121596531219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e1AAy4ExOn4lWlg7BdO7wGq6hzq8Ct%2B%2FW7QxLlK7j6M%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4649cadb79394c713f2d08d9b0b6d6d1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735121596531219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DQ%2BClEF%2FMtyb29P0XLsQOIlZ0Fan8f3kDFfVqwPhO0o%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4649cadb79394c713f2d08d9b0b6d6d1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735121596541213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7HmT5%2FRcYrEW5MIbZU11iS7bleI30IaJQ%2FlPAWW2psA%3D&reserved=0>.

**Comment by heyajohnny** [comment]
Ik heb een update doorgevoerd, waardoor 'gkbp' wordt gezien als pbd. 
Je zou nu de pbd data moeten zien.

**Comment by PaulGordijn** [comment]
Hij doet het bedankt 🙂

________________________________
Van: heyajohnny ***@***.***>
Verzonden: vrijdag 26 november 2021 10:08
Aan: heyajohnny/afvalinfo ***@***.***>
CC: Paul Gordijn ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] PBD not listed (Issue #228)


Ik heb een update doorgevoerd, waardoor 'gkbp' wordt gezien als pbd.
Je zou nu de pbd data moeten zien.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fheyajohnny%2Fafvalinfo%2Fissues%2F228%23issuecomment-979805960&data=04%7C01%7C%7C0827c18d6ddb4ff0130608d9b0bc61c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735145395116262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zzVMK5IJ8t%2FFdKbsy2x9FnNYZS%2F94SjaaOWBTxcm4WM%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALUCWSS4TDU2MU3YCMZHBWDUN5FCVANCNFSM5IWB3X6Q&data=04%7C01%7C%7C0827c18d6ddb4ff0130608d9b0bc61c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735145395116262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UVjStBpx1JgmshKkbDTwLOLWX6%2B6Hwtx91jCPBM7%2F8I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C0827c18d6ddb4ff0130608d9b0bc61c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735145395126255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=M2%2FTPTDX2hoEn8OHEnCN0D3U026gRqhTFYiVGD%2Bl6OQ%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C0827c18d6ddb4ff0130608d9b0bc61c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735145395126255%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aDYxi%2F64cEX%2F6Lx2BpuWNMra8%2BTe%2BZAm2fR48tlfmYA%3D&reserved=0>.
