### ISSUE TITLE
Possible error with "Drimmelen"

### ISSUE THREAD

**Issue by bafplus** [heyajohnny/afvalinfo#230]
I got this in my log today:

Error occurred. Please check the address with postcode: '4844VP' and huisnummer: '24' on the website of your local waste collector in the gemeente: 'drimmelen'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

I dont know if its a one time error since the website uses a plain calendar but maybe worth checking.

**Comment by heyajohnny** [comment]
Did you get the dates for the waste collection of your address?
You'll get this error when the waste collector is unreachable or your internet connection is down 
(or when your address isn't supported, but that's not the case I see). 
If you don't see this error constantly, there's no need to worry
