### ISSUE TITLE
500 Error on request

### ISSUE THREAD

**Issue by Metal-Eagle** [heyajohnny/afvalinfo#234]
Goedemiddag heyajohnny,

Ik krijg vanaf begin deze week een foutmelding op de backend het lijkt in de hele gemeente Heerenveen (Omrin) te zitten.

### Voorbeeld:

url: https://trashapi.azurewebsites.net/trash?Location=Heerenveen&ZipCode=8448JB&HouseNumber=50

Settings in Home assistant:
```
platform: afvalinfo
id: "home"
resources:
  - gft
  - papier
  - restafval
  - textiel
  - trash_type_today
  - trash_type_tomorrow
location: Heerenveen
postcode: 8448JB
streetnumber: 50
```

**Comment by heyajohnny** [comment]
Omrin had een aanpassing in de JSON gemaakt. Zojuist een fix doorgevoerd. Zou je kunnen laten weten of alles weer werkt?

**Comment by Metal-Eagle** [comment]
Heb net even een test gedaan maar hij blijft helaas dezelfde foutmelding houden.

**Comment by heyajohnny** [comment]
Er was een aanpassing in de JSON gemaakt door Omrin, die ik in een ander adres tegen kwam, maar voor jouw adres zijn er helemaal geen ophaaldagen. zie [Omrin](https://www.omrin.nl/afvalkalender). Hier kan ik helaas niets aan doen.

**Comment by Metal-Eagle** [comment]
Klopt, ik had in het voorbeeld een voorbeeld aders toegevoegd, deze blijken inderdaad geen ophaaldagen te hebben.
Heb net met het juiste aders getest en alles lijkt weet te werken.

Bedankt voor je snelle hulp!
