### ISSUE TITLE
Foutmelding afvalinfo

### ISSUE THREAD

**Issue by Ricardo1320-del** [heyajohnny/afvalinfo#235]
Sinds vanavond krijg ik onderstaande foutmelding in mijn log van Home Assistant. Voor die tijd werkte het perfect, heb site van mij afvalverwerker ook gecontroleerd, deze geeft wel netjes data door over ophaaldagen.

`
Error occurred. Please check the address with postcode: '<postcode>' and huisnummer: '<nummer>' on the website of your local waste collector in the gemeente: '<gemeentenaam>'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working`

Afvalverwerker is: Twente Mileu

**Comment by Waling1961** [comment]
Hier dezelfde foutmelding

Gemeente: Noardeast Fryslan
Afvalverwerker: Omrin

**Comment by mannerisms** [comment]
Ook in gemeente: den haag

Thanks!

**Comment by Epione69** [comment]
Hier ook dezelfde melding,

Gemeente Heerlen
Afvalverwerker Rd4

Alleen de ophaal dagen in 2021 zijn nog zichtbaar, de data uit 2022 is vermeld als "onbekend"
deze zijn wel te vinden in de afvalkalender dan de verwerker.

BvD

**Comment by heyajohnny** [comment]
@Ricardo1320-del Ik kan niets geks vinden... Wellicht dat je een adres door kan geven die niet meer werkt.
@mannerisms Den Haag heeft een aanpassing in de JSON gemaakt. Ik heb zojuist een fix doorgevoerd.
@Waling1961 Helaas moet ik deze gemeente dan laten vallen, want zo te zien bieden ze geen postcode informatie meer aan.

**Comment by willsmarthome** [comment]
> Hier ook dezelfde melding,
> 
> Gemeente Heerlen Afvalverwerker Rd4
> 
> Alleen de ophaal dagen in 2021 zijn nog zichtbaar, de data uit 2022 is vermeld als "onbekend" deze zijn wel te vinden in de afvalkalender dan de verwerker.
> 
> BvD

Ik krijg bij de gemeente Midden-Drenthe vanaf ophaal data 2022 de melding onbekend.

**Comment by heyajohnny** [comment]
@willsmarthome In 2022 stapt de gemeente over op MijnAfvalWijzer. Ik zal dit binnenkort mee aanpassen.

**Comment by kireque** [comment]
@heyajohnny 
Gilze / Rijen lijkt ook niet goed te gaan. Entiteiten blijven leeg...
Is dat iets dat in de code opgelost moet worden?

**Comment by Gepstra** [comment]
De Friese Meren staat ook op onbekend.

**Comment by heyajohnny** [comment]
@willsmarthome Midden-Drenthe zou het weer moeten doen

**Comment by heyajohnny** [comment]
@kireque zojuist getest met deze gegevens en geeft gewoon data terug:
![image](https://user-images.githubusercontent.com/20553716/147889215-f1664cd0-a031-4080-a293-0dd238584f33.png)

**Comment by heyajohnny** [comment]
@Gepstra De Friese Meren is over gegaan naar Afvalkalender. Zojuist een update doorgevoerd en zou weer moeten werken

**Comment by heyajohnny** [comment]
Mochten er nog problemen zijn, graag een nieuw issue openen voor iedere gemeente waar de issue zich voordoet.
Ik sluit daarom dit issue, omdat deze veel te groot en onoverzichtelijk wordt
