### ISSUE TITLE
FR: Gebruik friendly_name in de Today en Tomorrow sensor.

### ISSUE THREAD

**Issue by bafplus** [heyajohnny/afvalinfo#236]
In eerste plaats, top intregratie!

Een hoop gebruikers maken gebruik van de Today en Tomorrow sensor voor het weergeven van de afvalsoort(en) van vandaag of morgen.
In beide sensors wordt de afvalsoort benaming gebruikt die hardcoded is in const.py.
Maar veel gebruikers hebben zelf in HA de friendly_name "overruled" om bv pbd weer te geven als "Plastic" of restafval als "grijze bak".
Behalve in die 2 sensoren, want daar wordt dan weer pbd/restafval gebruikt.
Is het mogelijk dat in de waarde van de state  de friendly_name(s) gebruikt wordt?

Bonuspunten: Bij dagen met meerdere afvalsoorten bv "en" ertussen zetten. Dus "gft pbd" wordt dan "gft en pbd" (of nog beter "GFT en Plastic" ;-) )

Een hoop gebruikers zullen dit zeer waarderen.

**Comment by heyajohnny** [comment]
Ik heb een nieuwe versie gemaakt. Bij de resources heb ik de optie friendly_name toegevoegd. Ik kreeg het niet voor elkaar om de later "overruled" friendly_name te gebruiken, dus heb ik voor deze optie gekozen.
![image](https://user-images.githubusercontent.com/20553716/152530420-99dab10f-8832-4aeb-b573-3f2cbe43b31c.png)

Bij de Today en Tomorrow sensoren krijg je nu de friendly_name(s) gescheiden door een ", " (en niet " en " ) om het in meerdere talen bruikbaar te houden. Je krijgt dan bijvoorbeeld: "Groente Fruit en Tuinafval, Restafval"

Mocht er geen friendly_name gebruikt worden, dan pakt hij automatisch de resource "type"

Ik hoop dat je hier wat mee kunt. Laat maar weten of alles werkt zoals verwacht

**Comment by bafplus** [comment]
Top! Maar is dit hetzelfde effect als friendly_name gebruiken in costumize.yaml en heb je jouw code nu aangepast zodat hij die friendly_name gebruikt voor de state van today/tomorrow?

**Comment by heyajohnny** [comment]
> en heb je jouw code nu aangepast zodat hij die friendly_name gebruikt voor de state van today/tomorrow?

Ja, klopt.
Als je nu een friendly_name gebruikt, dan wordt deze in de today/tomorrow sensor gebruikt.
Mocht je geen friendly_name gebruiken, of nog de oude resource lijst gebruiken, dan wordt gewoon de oude benaming gebruikt, zoals gft, pbd, etc...

**Comment by bafplus** [comment]
heb het even (snel) getest en lijkt te werken maar dat zal de tijd verder uitwijzen.

In mijn cards is het nodig om de iconen (plaatjes) toe te wijzen via costumize.yaml.
Weet jij of dit ook kan in jouw toegevoegde sensor blok of kan dit alleen maar via costumize.yaml?

**Comment by bafplus** [comment]
hmmm...het lijkt erop dat friendly_name niet meer gebruikt wordt vanuit de config, maar wel (weer) als je deze opgeeft in constumize.yaml.

**Comment by heyajohnny** [comment]
Ik zie het inderdaad... Zal hoogstwaarschijnlijk iets met een HA update zijn. Ik zal aankomende week / weekend eens kijken of ik dit verder op kan lossen

**Comment by bafplus** [comment]
En getest :-)

Friendly name in constumize.yaml -> Verandert naam sensor in bv lovelace cards
Friendly name in configuration.yaml -> Waarde today en tomorrow sensor

Dus je aanpassing werkt nogsteeds alleen ziet ha dat niet (meer) voor sensornamen in de lovelace frontend.

**Comment by heyajohnny** [comment]
Hmmm... Volgens mij heb ik het zojuist gefixt.
Als het goed is zorgt de aanpassing ervoor dat de friendly_name in alle sensoren nu wordt meegenomen en niet meer alleen in de today en tomorrow sensors.

Zou je misschien kunnen laten weten of het na de update werkt? Alvast bedankt

**Comment by bafplus** [comment]
Ja blijkbaar want al mn sensoren zijn hernoemd.... sensor.afvalinfo_gft heet nu ineens sensor.afvalinfo_groene_bak bv.
Ook de today en tomorrow sensor heeft nu de friendly name als sensornaam.
Op zich goed (als jet het weet) maar betekend wel dat bij elke verandering aan de friendly name dat HA er een nieuwe sensor van maakt.

**Comment by bafplus** [comment]
Tevens werkt de custom icon niet meer vanuit de configuration.yaml, wel la sje die via customize.yaml opgeeft.

**Comment by bafplus** [comment]
Ook plakt hij er zelf "afvalinfo" voor bij de friendly name. Dus "groene bak" als friendly name wordt "afvalinfo groene bak" in bv een card.

**Comment by heyajohnny** [comment]
Auch... Ik moet dit soort dingen ook niet doen als er nog 2 kinderen om me heen hangen :(
Ik zal later op de avond alles weer werkend maken

**Comment by bafplus** [comment]
anders ff beta/dev branch aanmaken?

Op zo 27 feb. 2022 om 18:36 schreef heyajohnny ***@***.***>:

**Comment by heyajohnny** [comment]
Wellicht is het zo beter.  
"groene bak" als friendly name blijft "groene bak" en  wordt niet "afvalinfo groene bak"

**Comment by bafplus** [comment]
Dat ziet er idd beter uit zo.
En een nieuw logo...:-)
