### ISSUE TITLE
Lovelace cards

### ISSUE THREAD

**Issue by bafplus** [heyajohnny/afvalinfo#237]
Op diverse online socials en fora wordt geregeld gevraagd hoe een automation of lovelace card te maken voor deze integratie.
Afvalinfo levert zelf alleen sensoren en geen (voorbeeld) automatisering of card.

Ik heb daarom getracht een basishandleiding hiervoor te maken met enkele voorbeelden om direct te gebruiken of ter inspiratie.
Wellicht kun jij  er ook iets mee.

https://github.com/bafplus/HA-afvalinfo-card

Is dus meer ter kennisgeving en een aanvulling op deze top integratie ;-)

**Comment by heyajohnny** [comment]
@bafplus Bedankt voor het maken van deze mooie lovelace cards. Ik heb in mijn [README](https://github.com/heyajohnny/afvalinfo/blob/master/README.md) een verwijzing naar je repository gemaakt. Mocht je nog een betere tekst hebben voor de verwijzing in de README, laat het me maar weten, dan pas ik hem aan. Ik zal binnenkort wat tijd vrijmaken om te kijken of ik iets met [issue 236](https://github.com/heyajohnny/afvalinfo/issues/236) kan.

**Comment by bafplus** [comment]
Nice!

Ik zal ook mn best doen alles courant te houden.
