### ISSUE TITLE
Geen pdb data voor 31 december 2021

### ISSUE THREAD

**Issue by BBT-coder** [heyajohnny/afvalinfo#238]
https://trashapi.azurewebsites.net/trash?Location=arnhem&ZipCode=6836VD&HouseNumber=100
pdb wordt niet weergegeven

pdb wordt opgehaald op vrijdag 31 december 2021 maar is niet aanwezig.

Zie: https://inzamelwijzer.prezero.nl/adres/6836VD:100

Wijziging: Was in Engels geschreven.

**Comment by heyajohnny** [comment]
Er mistte nog een afvalstroomId mapping. Zojuist toegevoegd en zou moeten werken. Laat maar weten of het werkt zoals verwacht.

**Comment by BBT-coder** [comment]
Heya Johnny,
Werkt nu zoals verwacht, thanks!
