### ISSUE TITLE
Gemeente herindeling 2022

### ISSUE THREAD

**Issue by heyajohnny** [heyajohnny/afvalinfo#239]
Notitie aan mezelf voor de herindeling van gemeenten in [2022](https://www.rvig.nl/brp/gemeentelijke-herindelingen)

**Comment by hmmbob** [comment]
Ik kan je helpen met de samenvoeging van Uden en Landerd in "Gemeente Maashorst".

Nieuwe site is nog niet online, zal je tzt doorgeven wat ik vind (ik gok dat ze het systeem van Uden overnemen, maar dat is afwachten)

**Comment by roelbbzz** [comment]
afval kalender staat al online voor 2022 op https://www.gemeentemaashorst.nl/inwoners/afval/afvalkalender/

**Comment by hmmbob** [comment]
Nice, die was vanochtend nog niet online

**Comment by roelbbzz** [comment]
website van gemeente land van cuijk is nog niet live.

**Comment by hmmbob** [comment]
> website van gemeente land van cuijk is nog niet live.

Nu wel https://www.gemeentelandvancuijk.nl/afvalkalender/

**Comment by hmmbob** [comment]
Gemeente Maashorst laat nu wel gegevens zien. Op het oog hetzelfde systeem als Land van Cuijk trouwens.

**Comment by heyajohnny** [comment]
Gemeente Maashorst (1991) ontstaat uit de gemeenten:
0856    Uden
1685    Landerd

Gemeente Land van Cuijk (1982) ontstaat uit de gemeenten:
0756    Boxmeer
1684    Cuijk
0786    Grave
0815    Mill en Sint Hubert
1702    Sint Anthonis

Gemeente Dijk en Waard (1980) ontstaat uit de gemeenten:
0398    Heerhugowaard
0416    Langedijk

Gemeente Purmerend (0439) gaat verder na samenvoeging van de gemeenten:
0370    Beemster
0439    Purmerend

**Comment by heyajohnny** [comment]
@hmmbob @roelbbzz 
Beste wensen! Ik heb voor de gemeente Maashorst zojuist een nieuwe versie online gezet

**Comment by hmmbob** [comment]
Geven nog allemaal "unknown" en "none" terug...

**Comment by heyajohnny** [comment]
Heb je wel de location aangepast naar 'maashorst'?
![image](https://user-images.githubusercontent.com/20553716/147888364-ff502545-6657-4b86-bc1e-2931a709f5bd.png)

**Comment by hmmbob** [comment]
Jep. Kan ik je ergens op DMen?

**Comment by heyajohnny** [comment]
Als je Telegram hebt:
![IMG_20220102_212727](https://user-images.githubusercontent.com/20553716/147888637-1326c8ef-3db2-49db-8126-b9ca168238d8.jpg)

**Comment by hmmbob** [comment]
Coole profile pic, maar I'm a fool. Dacht dat het een server side change zou zijn, na update van component werkt het gewoon .......... Sorry about that 😂

**Comment by roelbbzz** [comment]
@heyajohnny net getest en dit werkt. 

beste wensen voor het nieuwe jaar

**Comment by heyajohnny** [comment]
Dijk en Waard is in versie 0.8.7 ook toegevoegd

**Comment by heyajohnny** [comment]
Beemster verwijderd in versie 0.8.8

**Comment by GertJanArts** [comment]
Gaat nog iets niet helemaal goed. GFT zou in Land van Cuijk vandaag opgehaald moeten worden volgens de kalender
![image](https://user-images.githubusercontent.com/20320533/147935630-434b5a79-2efa-409d-aaea-2aca620494a7.png)

**Comment by heyajohnny** [comment]
@GertJanArts Zojuist heb ik de gemeente 'land van cuijk' toegevoegd in versie 0.9.0
Zou je kunnen laten weten of alles werkt zoals verwacht?

**Comment by GertJanArts** [comment]
@heyajohnny Dank je wel voor je werk... helaas werkt het nog niet als verwacht.
Er wordt wel weer info opgehaald, maar die komt niet overeen met de afvalkalender 2022
https://www.gemeentelandvancuijk.nl/afvalkalender/5443CA/1

![image](https://user-images.githubusercontent.com/20320533/148087806-a3aa2515-d91a-44e0-bfd2-9cd255c2cd87.png)

**Comment by heyajohnny** [comment]
hmmm.... Dit adres heeft een vreemde dubbeling in gegevens (restafval) dat voor problemen zorgt. Ik zal morgen kijken of ik dit kan fixen
![image](https://user-images.githubusercontent.com/20553716/148090473-2e0fb8d0-e7da-4c8c-b243-0c333b4a8ce1.png)

**Comment by heyajohnny** [comment]
@GertJanArts Ik heb zojuist een fix doorgevoerd.

**Comment by GertJanArts** [comment]
@heyajohnny Lijkt allemaal te werken! Super bedankt voor het maken en onderhouden van deze mooie functionaliteit!

**Comment by heyajohnny** [comment]
Mooi om te horen! Thnx!
Ik sluit het issue, omdat alle nieuwe gemeentes er nu goed in lijken te zitten.
