### ISSUE TITLE
Could not find a version that satisfies the requirement Babel==2.8.0 (from versions: 2.9.1)

### ISSUE THREAD

**Issue by Dynamix72** [heyajohnny/afvalinfo#240]
After the last home assistant update (beta) i get the following error:

RROR: Could not find a version that satisfies the requirement Babel==2.8.0 (from versions: 2.9.1)
ERROR: No matching distribution found for Babel==2.8.0
2021-12-30 15:33:51 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package Babel==2.8.0: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8f2375e0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/babel/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8f2371c0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/babel/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8f237790>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/babel/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8f209670>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/babel/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f8f2098e0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /simple/babel/

**Comment by hmmbob** [comment]
This is a connection error with the PyPi servers. They've been down yesterday quite regularly as well.

This has nothing to do with `afvalinfo` itself, it's the central server with all Python packages being down/unreachable.

**Comment by heyajohnny** [comment]
If it continues to give the error you can reopen the issue, but as @hmmbob states, it's probably a PyPi issue
