### ISSUE TITLE
Geen Info Gemeente Midden Drenthe

### ISSUE THREAD

**Issue by willsmarthome** [heyajohnny/afvalinfo#241]
Eerder gemeld, maar nog steeds geen info over de ophaal data van de gemeente Midden Drenthe (postcode 9413).

**Comment by heyajohnny** [comment]
Midden Drenthe zou weer moeten werken

**Comment by zoeperman** [comment]
werkt hier weer voor Midden-Drenthe :)

**Comment by willsmarthome** [comment]
IDD Midden Drenthe werkt weer!!
Bedankt!
