### ISSUE TITLE
Tilburg werkt niet meer

### ISSUE THREAD

**Issue by keesvanbemmel** [heyajohnny/afvalinfo#242]
Lijkt aan de trashapi kant te zitten, deze url geeft een 500 error:
https://trashapi.azurewebsites.net/trash?Location=tilburg

(ook als ik ZipCode en HouseNumber toevoeg, nu weggehaald alleen in deze post)

**Comment by heyajohnny** [comment]
Zou je het nogmaals kunnen proberen. Ik heb in de afgelopen uren heel veel gemeentes een update gegeven en bij iedere publish ligt de back-end er enkele seconden uit.

**Comment by keesvanbemmel** [comment]
Nee nog steeds zelfde error. Issue was er volgens mij al om een uur of 14, maar dacht ik wacht nog even met melden want wellicht trekt het vanzelf recht

**Comment by heyajohnny** [comment]
Zojuist getest met de volgende postcode huisnummer combinatie, maar lijkt gewoon te werken:
5017AE, 2

**Comment by keesvanbemmel** [comment]
Ja die wel, zie ik nu ook! [Deze](https://trashapi.azurewebsites.net/trash?Location=tilburg&ZipCode=5026CG&HouseNumber=1) alleen niet.

**Comment by heyajohnny** [comment]
Op dat adres wordt geen afval opgehaald. Als er niets opgehaald wordt, dan kan dat helaas ook niet weergegeven worden :(
![image](https://user-images.githubusercontent.com/20553716/147930935-27389a54-7787-451c-840e-007018b02947.png)

**Comment by keesvanbemmel** [comment]
Die link zocht ik! Ok, dan ligt het daar. FWIW: ze zijn net door de straat komen rijden om op te halen ;) Thanks voor meepuzzelen, ik wacht af tot afvalwijzer het weer doet!
