### ISSUE TITLE
Overbetuwe werkt niet

### ISSUE THREAD

**Issue by phoxy84** [heyajohnny/afvalinfo#243]
via de website werkt het wel en zie ik de afvalophaaldagen wel.

This error originated from a custom integration.

Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/trashapi.py:58
Integration: afvalinfo (documentation, issues) 
First occurred: 09:38:35 (1 occurrences) 
Last logged: 09:38:35

Error occurred. Please check the address with postcode: 'XXXXXX' and huisnummer: 'XXXXX' on the website of your local waste collector in the gemeente: 'overbetuwe'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

**Comment by phoxy84** [comment]
Ik krijg inmiddels weer data door, ik sluit deze.

**Comment by heyajohnny** [comment]
Sinds dit jaar is de afvalverwerking overgegaan op Prezero.
ik heb dit zojuist aangepast :) Mooi om te horen dat het weer werkt

**Comment by phoxy84** [comment]
Helaas werkt de pbd sensor (nog niet)

**Comment by heyajohnny** [comment]
Er mistte nog een mapping voor deze afvalstroom. Het zou nu moeten werken

**Comment by phoxy84** [comment]
Klopt, hij werkt nu. Bedankt
