### ISSUE TITLE
Midden Drenthe werkt niet meer.

### ISSUE THREAD

**Issue by willsmarthome** [heyajohnny/afvalinfo#244]
Na de recente update werkt Midden Drenthe niet meer.

**Comment by heyajohnny** [comment]
Er zijn wat storingen bij 'mijnafvalwijzer' waar ik mijn data vandaan haal. Zojuist getest en ik krijg data terug als ik dit adres gebruik: 9423NA, 1

**Comment by willsmarthome** [comment]
Ze zijn bij mij nu weer terug (9413AA)
