### ISSUE TITLE
Bergen op zoom werkt niet.

### ISSUE THREAD

**Issue by Vabis1010** [heyajohnny/afvalinfo#245]
Na update vanmorgen werkt mijn afval info niet meer. Zegt dat mijn adres gegevens niet kloppen. Meer mensen hier last van?

**Comment by Vabis1010** [comment]
En het werkt weer. Bedankt mensen

**Comment by heyajohnny** [comment]
'mijnafvalwijzer', waar ik data vandaan haal,  heeft af en toe storing. Helaas kan ik hier weinig aan doen

**Comment by Vabis1010** [comment]
Het werkt weer. Bedankt

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
