### ISSUE TITLE
Lingewaard werkt niet

### ISSUE THREAD

**Issue by hpmkruit** [heyajohnny/afvalinfo#246]
Getest met config:
```
location: lingewaard
postcode: 6851GW
streetnumber: 12
```
Via afvalinfo website kom ik ook uit op een pagina van Pre Zero (voorheen SUEZ) en kan ik de kalender ook niet vinden...

**Comment by heyajohnny** [comment]
@hpmkruit Zojuist een update doorgevoerd. Het zou kunnen dat er nog wat mappings missen, omdat ik alleen met het voorbeeld adres getest heb. Zou je kunnen laten weten of alles werkt voor jou adres

**Comment by hpmkruit** [comment]
@heyajohnny Er wordt nu info opgehaald inderdaad. Alle items die op de kalender staan, zie ik nu ook terug in HA met de juiste datum.
