### ISSUE TITLE
Gemeente Diemen werkt niet meer

### ISSUE THREAD

**Issue by CrashyNL** [heyajohnny/afvalinfo#247]
Ik krijg geen datum meer via de plugin

Error in de log:

Error occurred. Please check the address with postcode: 'XXXXAB' and huisnummer: '15' on the website of your local waste collector in the gemeente: 'diemen'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

**Comment by CrashyNL** [comment]
Het lijkt erop dat er wat misgaat aan de Meerlanden Afvalkalender (de site geeft aan dat het adres niet klopt).

**Comment by heyajohnny** [comment]
Meerlanden lijkt weer te werken. Ik sluit dit issue
