### ISSUE TITLE
afvalinfo werkt tijdelijk niet

### ISSUE THREAD

**Issue by TheGamersCubeNL** [heyajohnny/afvalinfo#248]
volgens de website https://www.meerlanden.nl/

Momenteel (vrijdag 7-1) hebben wij last van een internetstoring.

Hierdoor zijn onze contactkanalen voor inwoners (Publieksinformatie) en bedrijven beperkt bereikbaar, zowel telefonisch als per e-mail. Dit heeft langere wachttijden tot gevolg.

Ook de afvalkalender is op dit moment niet te raadplegen.

Houd dit kanaal in de gaten voor updates. Onze excuses voor enig ongemak.

**Comment by heyajohnny** [comment]
Meerlanden lijkt weer te werken. Ik sluit dit issue
