### ISSUE TITLE
Alkmaar - Geen data

### ISSUE THREAD

**Issue by jorneilander** [heyajohnny/afvalinfo#249]
TrashAPI lijkt voor Alkmaar geen informatie meer terug te koppelen:

Voorbeeld van een postcode huisnummer [1824SM 51](https://trashapi.azurewebsites.net/trash?Location=Alkmaar&ZipCode=1824SM&HouseNumber=51&HouseNumberSuffix)

Op [Stadswerk072](https://www.stadswerk072.nl/wanneer) is de informatie wel te vinden.

https://www.stadswerk072.nl/adressen/1824SM:51 geeft `bagid: "0361200000013179"` waarmee op https://www.stadswerk072.nl/rest/adressen/0361200000013179/afvalstromen wel de data op te halen valt.

**Comment by AarvdH** [comment]
Bij mij in Alkmaar ook niet meer sinds gisteren.
Alles gecontrolleerd net als jorneilander. Alles lijkt in de lucht maar krijg geen data meer binnen.
bagid: 
https://www.stadswerk072.nl/rest/adressen/0361200000202179/afvalstromen

**Comment by speenbok** [comment]
Hier sinds een aantal dagen hetzelfde.

https://www.stadswerk072.nl/adressen/1824JD:49 
`bagid:  "0361200000029065"`

Vervolgens:
https://www.stadswerk072.nl/rest/adressen/0361200000029065/afvalstromen
Kom er gelijk achter dat morgen de groene bak aan de beurt is ;)

**Comment by heyajohnny** [comment]
De boefjes hadden stiekem de URL aangepast van  
"https://inzamelkalender.stadswerk072.nl/rest/adressen/......"
naar
"https://stadswerk072.nl/rest/adressen/......"

Ik heb zojuist een update doorgevoerd en het zou weer moeten werken

**Comment by speenbok** [comment]
Werkt weer perfect! Hartelijk dank.

**Comment by jorneilander** [comment]
Same, top @heyajohnny!

**Comment by AarvdH** [comment]
Werkt weer prima! Bedankt
