### ISSUE TITLE
Please add Alphen aan den Rijn

### ISSUE THREAD

**Issue by stefanjohn** [heyajohnny/afvalinfo#25]
Hi,
we use this link:

https://afvalkalender.alphenaandenrijn.nl/

**Comment by heyajohnny** [comment]
Alphen aan den Rijn is added :) Enjoy!

**Comment by stefanjohn** [comment]
for Alphen aan den Rijn, I get "unknown" at every type of carbage.

Hier is the code that I have inserted in config.yaml

Thanks in advance

 sensor:
    - platform: afvalinfo
      resources:                      
        - pbd
        - gft
        - pbd
        - restafval
        - papier
      city: alphenaandenrijn                 
      postcode: ******        
      streetnumber: **                 
      dateformat: '%d-%m-%Y'           
      timespanindays: 365

**Comment by stefanjohn** [comment]
![Capture](https://user-images.githubusercontent.com/61801395/76112908-6e3e1a00-5fe3-11ea-83b5-0f3a3d51f072.PNG)

Nothing again. Do I have also to put the huisnummer in quotes? 
I think something else is the probleem. I have tried every possible combination.
What is your opinion?

Thanks in advance again.
Stefan

**Comment by heyajohnny** [comment]
It works just fine here with these parameters:
![image](https://user-images.githubusercontent.com/20553716/76129736-73619000-6008-11ea-9a4e-0da30d3a611d.png)

What's the result of your address in https://afvalkalender.alphenaandenrijn.nl/ ?
If you don't have any results there you won't get any results in 'afvalinfo'.

I can't really can't help you if i don't know the most important parameters you use:
postcode and streetnumber...

**Comment by stefanjohn** [comment]
![Capture1](https://user-images.githubusercontent.com/61801395/76168272-7b3b4480-616e-11ea-86ae-e670d6237dee.PNG)


When I put your details it is working good. With my adres I get "unknown".

That is really strange.

I hope we can fix this

**Comment by heyajohnny** [comment]
I'm sorry but I'm not going to trial and error a couple of thousand addresses to look which one doesn't work. So I can't help you unless you provide me your address or some other address that doesn't work.

**Comment by stefanjohn** [comment]
But my address is in my code:

Kartuizerslaan 27, 2408KJ

**Comment by heyajohnny** [comment]
I can't look into your code that runs on your machine and you didn't provide your 'postcode' and 'streetnumber' in this issue.

But thanks for providing it now. You used some unsupported 'resources' for your address. I've added some extra error checking and it should be working after you update 'afvalinfo'

Please let me know if your issue is solved...

**Comment by stefanjohn** [comment]
First of all issue is solved! Thanks a lot for that.

I think if you see my comments in github, you can see that I have uploaded a printscreen from my code with my details in it.

I know that you can not look into my code that runs on my machine. 

But thanks again for helping me.

**Comment by heyajohnny** [comment]
Ouch... I missed that screenshot. I assumed it was the postcode and streetnumber I had send to you earlier. Sorry for that, but great to hear it's solved :)
