### ISSUE TITLE
Status "sensor.afvalinfo_pbd" not updating

### ISSUE THREAD

**Issue by martijndemulder** [heyajohnny/afvalinfo#250]
It might have been going on for longer, but I only noticed it last week.
The status for PBD doesn't seem to be updating, other sensors are working just fine.

The current status attributes show me the following:
`year_month_day_date: null
last_update: 22-01-2022 12:49
hidden: true
days_until_collection_date: null
is_collection_date_today: false
icon: mdi:bottle-soda
friendly_name: Afvalinfo PBD
entity_picture: /local/pmd_origineel.png`

The log doesn't show me any errors related to this integration.

**Comment by heyajohnny** [comment]
Can you please give me a location (doesn't have to be your location, but a location that has this issue), so I can reproduce the issue. Thnx!

**Comment by martijndemulder** [comment]
My location is 5704CE (Helmond).
________________________________

**Comment by heyajohnny** [comment]
They've changed the text for the pbd/pmd trash type on the site. I've just pushed an update and it should be working again.

**Comment by martijndemulder** [comment]
It seems to be working again, good job!
