### ISSUE TITLE
Sort date first

### ISSUE THREAD

**Issue by freggel2** [heyajohnny/afvalinfo#252]
Ok, dit is niet echt een groot probleem maar:

Is het mogelijk om het afval te sorteren per datum.

Dus datgene wat als eerste opgehaald moet worden ook als eerst getoond wordt en dan daaropvolgend de volgende datum.

Bij mij staat nu alles door elkaar.

Nu komt 3 februari als eerste te staan en daarna staat 26 januari.

Alvast bedankt voor je antwoord.
Ik bewonder je werk en ben er ontzettend blij mee tot nu toe.

_English translation:

Allright,

this is not something of a issue.
Is it possible to sort the waste date.
So that what should be collected first is also shown first and then the next date.

With me everything is now mixed together.

Now February 3 is the first to be displayed and after that January 26._

**Comment by heyajohnny** [comment]
Hoi @freggel2. [Bafplus ](https://github.com/bafplus/HA-afvalinfo-card) heeft mooie Lovelace cards gemaakt voor Afvalinfo. Ik denk dat het daar wel mee moet lukken.
