### ISSUE TITLE
Please add Sudwest Fryslan

### ISSUE THREAD

**Issue by Mozzzy** [heyajohnny/afvalinfo#253]
Hi,

Could you please add sudwest fryslan?
https://sudwestfryslan.nl/onderwerp/digitale-afvalkalender/

Thanks a lot in advance!

Best regard,
Mozzy

**Comment by heyajohnny** [comment]
Ik heb voor deze gemeente de Nederlandse benaming gebruikt, omdat niemand de officiele naam met speciale tekens normaal in kan typen:
![image](https://user-images.githubusercontent.com/20553716/151559642-b5579e1c-f2df-463c-83d6-4b0dea817195.png)

De gemeente zou moeten werken met location: "zuidwest-friesland"
