### ISSUE TITLE
Ignore Kerstboom

### ISSUE THREAD

**Issue by EvertJob** [heyajohnny/afvalinfo#254]
Hi,

Would it be possible to remove ‘Kerstboom’ 7 or 14 days after pick-up and add it a month before pick up?

**Comment by heyajohnny** [comment]
Hi,
It should automatically be removed when new data is fetched. If not, maybe I can reproduce the issue if you give me the location where this issue occurs

**Comment by EvertJob** [comment]
Sorry for the late reaction, thought I've already replied. It's happening in the location midden-groningen

**Comment by heyajohnny** [comment]
Works as expected for the location 9602TA 1 in midden-groningen
![image](https://user-images.githubusercontent.com/20553716/152698710-a97846a8-a7bb-4fa3-8a16-3046a42cffac.png)

**Comment by EvertJob** [comment]
Yes. But it says ‘Unknow’ and it’s not removed. I was hoping for a deleted or disabled entity.

**Comment by heyajohnny** [comment]
You can make a lovelace-ui dashboard or use the [bafplus](https://github.com/bafplus/HA-afvalinfo-card) cards
