### ISSUE TITLE
How to debug homeassistant 

### ISSUE THREAD

**Issue by betonishard** [heyajohnny/afvalinfo#256]
Hi, thanks for your efforts..

My sensors stay at unknown (gft, rest,etcetc) in homeassistant.

So I noticed as of the 25th of January I saw afvalinfo sensors are not being updated any more. I checked commits, updates etc, nothing that would be interesting to see a cause.

I checked first the api, if data was coming even in. Surely this was the case.

https://trashapi.azurewebsites.net/trash?Location=tilburg&zipcode=5017AE&housenumber=2

resulted in:

`[{"date":"2022-02-08T00:00:00","name":"Gft","daysTillDate":6},{"date":"2022-02-08T00:00:00","name":"Restafval","daysTillDate":6},{"date":"2022-02-15T00:00:00","name":"Papier","daysTillDate":13},{"date":"2022-02-15T00:00:00","name":"Pbd","daysTillDate":13}]`

I reinstalled the HACS plugin to see if it would repopulate. However I don't know where to debug from there.

* When is the api call being done?
* How can I debug this in homeassistant (maybe they have chenged something in the response for instance rest has become rdt or something.

Thanks.

**Comment by heyajohnny** [comment]
The API calls are done when HA starts and then once every hour.
Maybe try some restarts or temporary changing the location and then changing it back.

**Comment by betonishard** [comment]
Hi, I debugged it a bit.

In sensor.py

self._year_month_day_date = str(collection_date).

I added:

_LOGGER.warning(self._year_month_day_date)
This shows a value like this "2022-02-07"

It should update the attribute value of the sensor, but nothing is updated.

I also tried renaming the sensor, but nothing works.
