### ISSUE TITLE
Tomorrow doesn't display correct values anymore

### ISSUE THREAD

**Issue by TheGabeMan** [heyajohnny/afvalinfo#258]
Hi, 
Could it be that after the latest update the sensor.afvalinfo_tomorrow isn't working correctly anymore?

Today, saturday, it says GFT, Restafval, but I'm quite sure they won't be coming on Sunday :-)

I was looking at the changes made in yesterday by Johnny, in "[Added friendly_name to resource types](https://github.com/heyajohnny/afvalinfo/commit/6e7f49866212a7b6fb46102e7e0e8e57d4d181a0)" and noticed that in sensortomorrow.py, there was a change that might explain the issue:

removed:        tomorrow = str((date.today() + timedelta(days=1)).strftime("%Y-%m-%d"))
added:         tomorrow = str((date.today() + timedelta(days=3)).strftime("%Y-%m-%d"))

If tomorrow is 3 days from now, then my current entry "GFT, Restafval", is correct.

**Comment by heyajohnny** [comment]
You're totally right. I used it for debugging to have some trash data, but totally forgot to set the value back to '1'.
Thanks for pointing it out.

I'm going to release a new version in a couple of minutes...

**Comment by hmmbob** [comment]
Ah cool, had the same issue.

![Screenshot_20220205-191741_Home Assistant](https://user-images.githubusercontent.com/33529490/152653947-f0364d27-b94f-42d4-af13-36b5e4009b7f.jpg)

**Comment by hmmbob** [comment]
And fixed by 1.0.1 👍🏻
