### ISSUE TITLE
Add gemeente noardeast fryslan

### ISSUE THREAD

**Issue by yorick22** [heyajohnny/afvalinfo#259]

**Comment by heyajohnny** [comment]
Beste @yorick22 
De gemeente heeft helaas geen kalender op postcode niveau, maar op wijk / kleur niveau, zie [hier](https://www.noardeast-fryslan.nl/afvalkalender-2022)
Hierdoor zou het mij enorm veel tijd kosten om deze wijkindelingen en ophaaldagen om te zetten naar postcode niveau, wat ook nog erg foutgevoelig kan zijn bij de wijken die elkaar kruisen.

Mocht de gemeente in de toekomst wel ophaaldagen op postcode niveau hebben wil ik dit uiteraard toevoegen, maar voor nu moet ik je helaas teleurstellen.

**Comment by yorick22** [comment]
> Beste @yorick22 De gemeente heeft helaas geen kalender op postcode niveau, maar op wijk / kleur niveau, zie [hier](https://www.noardeast-fryslan.nl/afvalkalender-2022) Hierdoor zou het mij enorm veel tijd kosten om deze wijkindelingen en ophaaldagen om te zetten naar postcode niveau, wat ook nog erg foutgevoelig kan zijn bij de wijken die elkaar kruisen.
> 
> Mocht de gemeente in de toekomst wel ophaaldagen op postcode niveau hebben wil ik dit uiteraard toevoegen, maar voor nu moet ik je helaas teleurstellen.

Goedenavond,

Onze gemeente heeft eindelijk een kalender (https://www.offalkalinder.nl/) op postcode niveau geïntroduceerd.
Zou hiermee onze gemeente aan 'Afvalinfo' toegevoegd kunnen worden?

**Comment by heyajohnny** [comment]
Ik zal binnenkort eens kijken.... Even wat aantekeningen maken: 
Noardeast-Fryslân & Dantumadiel
9103 PT 6
https://www.offalkalinder.nl/adressen/9103PT:6
https://www.offalkalinder.nl/rest/adressen/0058200000224843/afvalstromen
Lijkt op afvalkalender.xxxx API...

**Comment by heyajohnny** [comment]
Ik heb de gemeente noardeast-fryslan toegevoegd. Laat maar weten of alles werkt.

**Comment by yorick22** [comment]
Dankjewel!
De GFT en oud papier entity werkt, bij restafval krijg ik echter nog
'UNKNOWN'


Op ma 7 nov. 2022 om 09:23 schreef heyajohnny ***@***.***>:

**Comment by yorick22** [comment]
9101DE 20

**Comment by heyajohnny** [comment]
Ik heb zojuist een aanpassing gedaan. Restafval zou nu moeten werken.

**Comment by yorick22** [comment]
Top, bedankt!
