### ISSUE TITLE
Template 'afvalinfo_next_trash_type_and_date' voorbeeld gaan niet meer werken vanaf HA core 2022.1

### ISSUE THREAD

**Issue by alco28** [heyajohnny/afvalinfo#260]
Bij het gebruik van de voorbeeld templates komt nu een warning naar voren:

`Template warning: 'int' got invalid input 'None' when rendering template '{%- set gft = state_attr('sensor.afvalinfo_gft', 'days_until_collection_date') | int -%} {%- set pbd = state_attr('sensor.afvalinfo_pbd', 'days_until_collection_date') | int -%} {%- set papier = state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') | int -%} {%- set minimum = (gft,pbd,papier)|min -%} {% if gft == minimum %} gft · {{ states('sensor.afvalinfo_gft') }} {% elif pbd == minimum %} pbd · {{ states('sensor.afvalinfo_pbd') }} {% elif papier == minimum %} papier · {{ states('sensor.afvalinfo_papier') }} {% else %} n/a {% endif %}' 

but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1`

![afbeelding](https://user-images.githubusercontent.com/1846650/152821664-ed63db16-dec6-4f78-96a4-d6dff1091c6a.png)

**Comment by heyajohnny** [comment]
That's strange... I won't get this warning/error on the latest dev version: <html>
<body>


core-2022.3.0.dev0
--



</body>
</html>

I'll just wait and see how this evolves... If it really doesn't render please let me know.

**Comment by dwang707** [comment]
Hello,

I also have the error,

bad indentation of a mapping entry at line 5, column 15:
            - type: restafval              (type i ... 
            - 
in Home assistant core-2022.2.9

**Comment by heyajohnny** [comment]
@dwang707 
Don't forget to remove the comments from the example config (everything between and after the parentheses)

**Comment by heyajohnny** [comment]
I'm closing this issue for now... It can always be reopened
