### ISSUE TITLE
Bugje in TwenteMilieu

### ISSUE THREAD

**Issue by AmyAmy** [heyajohnny/afvalinfo#261]
Bij TwenteMilieu verdwijnen ophaaldagen 1 dag te vroeg, de Today sensor werkt daardoor ook altijd leeg.

Dit is eenvoudig op te lossen door bij requests naar `https://twentemilieuapi.ximmio.com/api/GetCalendar` als `startDate` niet de datum van vandaag opgeven, maar de datum van gister.

**Comment by heyajohnny** [comment]
Wellicht zou je de aanvraag bij TwenteMilieu kunnen doen om dit op te lossen. Het voelt niet helemaal lekker om aan mijn kant aan te passen. 

Als ik het hier nu aanpas en ze bij Twentemilieu het probleem oplossen, dan moet ik het vervolgens hier ook weer aanpassen.

**Comment by Rocker20** [comment]
@AmyAmy Ik heb zelf even een sensor gemaakt die iedere dag om 00:15 de status ophaalt van de sensor en deze weg schrijft in een input_text. Hierdoor klopt de informatie wel

**Comment by heyajohnny** [comment]
Ik sluit dit issue, aangezien de fout bij TwenteMilieu zit
