### ISSUE TITLE
Sensor restafval wordt niet bijgewerkt

### ISSUE THREAD

**Issue by GertJanArts** [heyajohnny/afvalinfo#262]
Het lijkt erop alsof het bijwerken van de restafval sensor niet goed wordt bijgewerkt. (gemeente Land van Cuijk)
Core versie 2022.2.7
![1](https://user-images.githubusercontent.com/20320533/154232747-a94035a0-b71d-4840-9f0d-a2bfb3ad50f8.png)

**Comment by heyajohnny** [comment]
Heb je misschien een postcode huisnummer waar dit probleem zich voordoet?

**Comment by GertJanArts** [comment]
Jazeker. 5443CA huisnummer 20

**Comment by heyajohnny** [comment]
Voor dit adres wordt geen restafval opgehaald. 
Zie [hier...](https://www.gemeentelandvancuijk.nl/afvalkalender/5443CA/20)
Mocht er op dit adres wel restafval opgehaald worden, dan is geeft de gemeente dit niet goed door en zou het bij de gemeente aangepast moeten worden. Ik sluit dit issue, omdat de fout bij de gemeente zit.
