### ISSUE TITLE
Add gemeente Ouder-Amstel

### ISSUE THREAD

**Issue by LarsFixt** [heyajohnny/afvalinfo#263]
Is it possible to add the gemeente Ouder-Amstel?
Unfortunately, they only publish a pdf (https://www.ouder-amstel.nl/Home/Afval/Afvalkalender_per_wijk)

**Comment by heyajohnny** [comment]
I'm sorry. For this year I'm not going to add Ouder-Amstel, since they only provide a pdf without postcode areas it will cost me a lot of time to add it and it's also very unreliable, since I need to map the 'wijk' to 'postcode'.
