### ISSUE TITLE
Error reaching the Alkmaar site

### ISSUE THREAD

**Issue by AarvdH** [heyajohnny/afvalinfo#264]
As last time getting the error: 
Error occurred. Please check the address with postcode: '1822RA' and huisnummer: '14' on the website of your local waste collector in the gemeente: 'alkmaar'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working
Maybe they changed again the web adress for Alkmaar? (noughty boys)

**Comment by heyajohnny** [comment]
I've tested it today and it looks fine. 
Might be a bad internet connection or the 'alkmaar' waste collector site was temporary down.

**Comment by AarvdH** [comment]
> I've tested it today and it looks fine. Might be a bad internet connection or the 'alkmaar' waste collector site was temporary down.

Yep, Everything is fine again. next time I will wait a day or so before I report it. Thanks.
