### ISSUE TITLE
gemeente borsele wordt niet meer herkend

### ISSUE THREAD

**Issue by Jojotjo56** [heyajohnny/afvalinfo#265]
Postcode 4441SH huisnummer 28 geeft een unknown result. Dit heeft altijd gewerkt. Andere postcodes in andere plaatsen uitgeprobeerd en deze werken wel.

  - platform: afvalinfo
    resources:
      - pbd
      - papier
      - gft
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: borsele
    postcode: 4441SH
    streetnumber: 28
    locale: "nl"
    timespanindays: 65

**Comment by heyajohnny** [comment]
De gemeente heeft hun site aangepast. Ik heb zojuist een update doorgevoerd en het zou weer moeten werken.

**Comment by Jojotjo56** [comment]
Super, het werkt weer als vanouds. Bedankt!
