### ISSUE TITLE
Sensor prefix is missing

### ISSUE THREAD

**Issue by WouterKr** [heyajohnny/afvalinfo#267]
Hi,

Because of a not running template after installing v1.0.4 I noticed the sensor prefix is missing:

sensor.afvalinfo_gft -> sensor.gft (v1.0.4)

Should it be this way?

Regards,
Wouter

**Comment by TyzzyT** [comment]
I'm having the same issue. Fixed it manually by changing the entity_id's

**Comment by heyajohnny** [comment]
@WouterKr 
Can you please share your configuration. I did change something regarding to the sensor name, but with my test configuration it's working fine

**Comment by Vabis1010** [comment]
> sensor.gft (v1.0.4)

where and how did you fix this?

**Comment by TyzzyT** [comment]
> > sensor.gft (v1.0.4)
> 
> where and how did you fix this?

I changed the entity_id's from the new sensor.gft, etc. entities to sensor.afvalinfo_gft

**Comment by Vabis1010** [comment]
Where do i find these entity id

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by TyzzyT** [comment]
You can find the explanation here: [(https://www.home-assistant.io/docs/configuration/customizing-devices/)]

**Comment by TyzzyT** [comment]
I just updated my test-instance from 1.0.4 to 1.0.5 and can confirm the entity_id keep working and don't change.
Also updated my prod-instance from 1.0.1 to 1.0.5 and can confirm that upgrade path is working too, but it added a _2 to my entity_id's so I had to manually remove all my old entity_id's and manually change the _2 one's and remove the last part.

**Comment by WouterKr** [comment]
@heyajohnny Thank you for the (quick) update  !
No new entities are added :-) after the upgrade and the ones already there are still working.

**Comment by piluxh** [comment]
Strange. I'm on 1.0.5 and I still have the sensor named sensor.gft rather than sensor.afvalinfo_gft, etc.

**Comment by hmmbob** [comment]
Same here, not back to normal behavior when upgrading from 1.0.4 to .5

**Comment by piluxh** [comment]
In the end it did work, but had to wait until the next day (or at least until it ran again or something like that).

**Comment by heyajohnny** [comment]
Most of the above has to do with caching of Home Assistant. The problems should be resolved automatically. I'm closing this issue. If some of you still have these problems please take a look [here](https://github.com/heyajohnny/afvalinfo/issues/268)
