### ISSUE TITLE
Sensoren unavailable

### ISSUE THREAD

**Issue by bluemaster27** [heyajohnny/afvalinfo#268]
Wat is er aan de hand met deze integratie? Heeft altijd prima gewerkt, maar nu alle sensoren unavailable.
Heb al een keer de hele integratie verwijderd en weer geinstalleerd, de code uit het voorbeeld in configuration.yaml gezet en aangepast met mijn eigen gegevens, maar niks.
Kan ook in de developer tools geen enkele werkende afvalinfo sensor terug vinden.

**Comment by hugodejong** [comment]
Ik heb sinds de laatste update het zelfde probleem.

**Comment by woempiej** [comment]
+1 

![Afval](https://user-images.githubusercontent.com/62903344/156043229-3bb65e06-fca1-4209-bf36-5aafdbc77781.PNG)

**Comment by woempiej** [comment]
Oplossing is reeds aanwezig in https://github.com/heyajohnny/afvalinfo/issues/267
![afbeelding](https://user-images.githubusercontent.com/62903344/156048487-895e4888-1b4d-42ef-80ae-7f6579f862fa.png)

sensor.afvalinfo_restafval moet veranderd worden in sensor.restafval

**Comment by bluemaster27** [comment]
> Oplossing is reeds aanwezig in #267 ![afbeelding](https://user-images.githubusercontent.com/62903344/156048487-895e4888-1b4d-42ef-80ae-7f6579f862fa.png)
> 
> sensor.afvalinfo_restafval moet veranderd worden in sensor.restafval

HELD!! Was even zoeken, maar het is gelukt!

**Comment by xtrmenl** [comment]
also need to remove the "afvalinfo_" from other Attributes templates 
like   

- platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.papier', 'days_until_collection_date') }}"
  
  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['gft', 'kerstboom', 'papier', 'pbd', 'restafval','textiel'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{l}} · {{ states('sensor.' ~l) }}
          {%- endif %}
          {%- endfor %}

**Comment by heyajohnny** [comment]
Sorry voor alle problemen... Ik heb zojuist een update gepusht voor de prefix die verdwenen was uit de entity_id, weer terug te zetten.

Ik heb in een eerdere update de naam van de sensor veranderd, maar onder water veranderde ook de entiteit_id van de sensor. Ik wist niet dat dit met elkaar verbonden was.

Ik heb een oplossing gevonden om de naam en entiteit_id te scheiden, dus het zou allemaal weer normaal moeten werken als je hebt geüpdatet naar v1.05

**Comment by woempiej** [comment]
> Sorry voor alle problemen... Ik heb zojuist een update gepusht voor de prefix die verdwenen was uit de entity_id, weer terug te zetten.
> 
> Ik heb in een eerdere update de naam van de sensor veranderd, maar onder water veranderde ook de entiteit_id van de sensor. Ik wist niet dat dit met elkaar verbonden was.
> 
> Ik heb een oplossing gevonden om de naam en entiteit_id te scheiden, dus het zou allemaal weer normaal moeten werken als je hebt geüpdatet naar v1.05


Geen probleem! Ben blij dat de integratie word onderhouden en dat gaat soms gepaard met foutjes.

Ik heb de integratie opnieuw gedownload (v1.05) in HACS maar als ik de .afvalinfo_ er weer tussen zet word de sensor weer "niet beschikbaar. 
Ergens is er iets nog niet helemaal goed volgens mij. Je kan de integratie ook niet downgraden om het probleem weg te nemen.

**Comment by Rocker20** [comment]
Niet weer doen @heyajohnny haha .. sensoren zijn bij mij ook niet gerepareerd, maar ik pas gewoon home assistant, en nodered aan.. en dan werkt het wel weer :) al tijden erg blij met afvalinfo!!!

**Comment by heyajohnny** [comment]
Vreemd dat het niet werkt... Met mijn onderstaande configuratie zet hij voor de sensoren gewoon 'afvalinfo_' (gevolgd door het id: '_test_adres_')
![image](https://user-images.githubusercontent.com/20553716/156246951-4855d12d-7279-42f3-b3cf-b1739018a334.png)

**Comment by Rocker20** [comment]
Bij mij heten ze nu sensor.container... is op zich niet heel erg hoor... heb alles erop aangepast nu en alles werkt weer

**Comment by bluemaster27** [comment]
Bij mij werkt het eigenlijk prima nu, durf niet te updaten. :)

**Comment by Raarrrinator** [comment]
Is de boven beschreven stap van xtrmenl nodig om de sensoren werkend te krijgen?

Ik heb zojuist geupdate naar v1.05 en alle sensoren zijn unavailable.

**Comment by Raarrrinator** [comment]
Oké ik heb het weten te reparen door:

Integratie via HACS te verwijderen
Config te verwijderen via File editor
Na reboot de unavailable sensoren te verwijderen (er was voor sensor ook een _2 aangemaakt)
Integratie opnieuw te installeren via HACS
Config opnieuw geplakt in sensor.yaml

Nu zijn de sensoren terug!

Wat wel opviel was dat today & tomorrow een andere naam hebben gekregen in v1.05 dan in v1.01. Het was nodig Lovelace aan te passen om de sensoren zichtbaar te krijgen.

**Comment by heyajohnny** [comment]
Home Assistant gaat heel raar om met naamswijzigingen van sensoren heb ik gemerkt. Soms blijft er het een en ander in Cache staan, maar dit verschilt ook weer per Home Assistant versie en hoe je alles geconfigureerd hebt.
De naam 'sensor.afvalinfo_trash_type_today' is een samenvoegsel van 'afvalinfo' en de standaard naam van de resource 
![image](https://user-images.githubusercontent.com/20553716/156899053-8312a4d1-39ee-456d-bde9-0c72fb034cc7.png)
Je kan dit eventueel overschrijven door de friendly_name in te stellen.
![image](https://user-images.githubusercontent.com/20553716/156899118-af067971-bd34-4a86-9a0b-4dfc4ec4a7b9.png)
Hierdoor zou de sensor nu 'sensor.afval_voor_vandaag' heten.

**Comment by Vabis1010** [comment]
Vandaag alles opnieuw ingesteld vanuit hacs. Sensoren gelijk zichtbaar. Iconen veranderd. Prima integratie weer. Blij mee

**Comment by heyajohnny** [comment]
Het lijkt erop dat alles het weer doet. Mochten er nog mensen problemen hebben, dan kan dit issue weer geopend worden, of een nieuw issue hiervoor aangemaakt worden.

**Comment by Vabis1010** [comment]
Is nog niet over. Als ik de wasmachine start zijn alle sensoren op niet beschikbaar. Na herstart integratie werkt het weer.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by heyajohnny** [comment]
@Vabis1010  

> Is nog niet over. Als ik de wasmachine start zijn alle sensoren op niet beschikbaar. Na herstart integratie werkt het weer.

Maar als je je laptop 360 graden draait, vervolgens de LED verlichting op blauw zet en het regent 0,1mm per uur, dan doet hij het wel toch?  ;-) 

Ik heb werkelijk geen flauw idee wat je probeerd te zeggen. Werkt het na de herstart wel? Blijft hij het nu doen? En wat heeft de wasmachine er precies mee te maken?

**Comment by Vabis1010** [comment]
Sorry mijn fout. Verkeerde plaats gepost. Jullie integratie werkt uit de kunst nu. Eergisteren geïnstalleerd geen problemen gehad. Effe weekje wachten of automatisering werkt.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
