### ISSUE TITLE
Nieuwe gemeente toevoegen

### ISSUE THREAD

**Issue by odouma** [heyajohnny/afvalinfo#269]
Graag de gemeente noard-east-fryslân toevoegen: www.noardeast-fryslan.nl

**Comment by odouma** [comment]
Ik kwam zonet een oude aanvraag voor het toevoegen van deze gemeente tegen en daar zag ik dat dit niet ging werken omdat ze een eigen ophaaldienst hebben, dit is nog steeds zo.
Is dit nog steeds een probleem of zijn er inmiddels meer mogelijkheden dan Omrim?

**Comment by heyajohnny** [comment]
Helaas maken ze nog steeds gebruik van een soort van [wijkindeling](https://www.noardeast-fryslan.nl/afvalkalender-2022). Ik zou dit moeten gaan mappen naar postcodes, wat veel tijd kost en heel foutgevoelig is. Voor dit jaar zit het er helaas niet in :(

**Comment by rienkhendrik** [comment]
is het al mogelijk om noard east fryslan toe te voegen. hij staat al wel in de lijst bij de intregratie van HACS echter werkt het nog niet.

**Comment by odouma** [comment]
@rienkhendrik 
Ik heb 'm net weer geïnstalleerd en bij mij werkt het wel, dus waarschijnlijk heb je ergens nog een foutje in je configuration.yaml zitten.

**Comment by heyajohnny** [comment]
@rienkhendrik Zou gewoon moeten werken als je bij location 'noardeast-fryslan' gebruikt

**Comment by rienkhendrik** [comment]
Ja hij doet het, bedankt.

Op vr 24 feb. 2023 om 11:15 schreef heyajohnny ***@***.***>:
