### ISSUE TITLE
Please add Reinis

### ISSUE THREAD

**Issue by TerrorSource** [heyajohnny/afvalinfo#27]
Hi,

Can you add Reinis?
It's a local wastecollector for Nissewaard (Spijkenisse and a numberous small villages)
Reinis uses API: https://wasteapi.2go-mobile.com/api/GetCalendar
which is also used for other wastecollectors:
barAfvalbeheer
twentemilieu
hellendoorn
almere

It is working on rooted Toon's so you might be able to extract data from that app:
https://github.com/ToonSoftwareCollective/wastecollection/blob/master/WastecollectionApp.qml

**Comment by heyajohnny** [comment]
I've just added Reinis / Nissewaard. Enjoy :)
