### ISSUE TITLE
Gegevens onjuist

### ISSUE THREAD

**Issue by Tonny56** [heyajohnny/afvalinfo#270]
Ik woon in de plaats Velp, onderdeel van de gemeente Land van Cuijk. Ik heb bij de location land van cijck ingevuld. Uiteraard heb ik ook mijn postcode ingevuld, toch is de informatie onjuist en onvolledig. Doe ik iets verkeerd?

**Comment by heyajohnny** [comment]
Heb je voor mij een postcode en huisnummer, waarbij deze fout voorkomt. Het zou kunnen zijn dat je net in een grensgebied valt of dat er gewoon iets fout is, maar zonder een postcode en huisnummer kan ik hier verder niets over zeggen.

**Comment by Tonny56** [comment]
5363TW 39

Op za 5 mrt. 2022 21:22 schreef heyajohnny ***@***.***>:

**Comment by heyajohnny** [comment]
Volgens de gemeente wordt er volgende week niets opgehaald, dus klopt het dat je geen data in je sensoren krijgt,
![image](https://user-images.githubusercontent.com/20553716/156937068-1bba5884-5216-4cb3-b268-facecad2d5d0.png)

**Comment by heyajohnny** [comment]
Mocht dit niet kloppen zou ik je aanraden om bij de gemeente aan te kloppen. Ik haal alleen de gegevens op die de gemeentes verstrekken en ga er uiteraard vanuit dat deze kloppen. Aangezien ik hier verder niets aan kan doen sluit ik dit issue.
