### ISSUE TITLE
Gegeves niet beschikbaar?

### ISSUE THREAD

**Issue by edegraaff** [heyajohnny/afvalinfo#271]
Ik heb net alles opgewaardeerd, draai 
hacs 1.23
Home Assistant 2022.2.0
Afval info 1.05 

Error: 
2022-03-04 22:03:01 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalinfo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalinfo/sensor.py", line 82, in setup_platform
    resourcesMinusTodayAndTomorrow = [obj["type"] for obj in resources]
  File "/config/custom_components/afvalinfo/sensor.py", line 82, in <listcomp>
    resourcesMinusTodayAndTomorrow = [obj["type"] for obj in resources]

Config:

 - platform: afvalinfo
    id: Thuis in Voorschoten
    resources:
     - type: gft
       friendly_name: Groente Fruit en Tuinafval
     - type: kerstboom
       friendly_name: Kerstboom
     - type: pbd
       friendly_name: Plastic Blik en Drankpakken
     - type: papier
       friendly_name: Papier
     - type:  restafval
       friendly_name: Restafval
     - type: takken
       friendly_name: Takken
     - type: textiel
       friendly_name: Oude kleding
     - trash_type_today
#       friendly_name: Afval voor vandaag
     - trash_type_tomorrow
#       friendly_name: Afval voor morgen
    location: voorschoten
    postcode: XXXXXX
    streetnumber: XXXXX
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365

**Comment by heyajohnny** [comment]
Hmmm.... Vreemd. Al een update geprobeerd naar 2022.3.1?
![image](https://user-images.githubusercontent.com/20553716/156899888-29a1baa7-01a0-4bce-b086-545d1746ec66.png)

**Comment by edegraaff** [comment]
Ik heb hem opgetrokken, probleem blijft.  Ik heb de configuratie aangepast zoals in het voorbeeld op github.. 

sensor:
    - platform: afvalinfo
      id: vakantiehuis                 (optional, default = '') add some extra naming to make identification of multiple afvalinfo sensors easier
      resources:                       (at least 1 required)
        - type: restafval              (type is required)
          friendly_name: Restafval     (friendly_name is optional)
        - type: takken
          friendly_name: Takken
        - type: textiel
          friendly_name: Oude Kleding
        - type: gft
          friendly_name: Groente Fruit en Tuinafval
        - type: kerstboom
          friendly_name: Kerstboom
        - type: pbd
          friendly_name: Plastic Blik en Drankpakken
        - type: papier
          friendly_name: Papier
        - type: trash_type_today
          friendly_name: Afval voor vandaag
        - type: trash_type_tomorrow
          friendly_name: Afval voor morgen
      location: sliedrecht             (required, default = sliedrecht) name of the 'gemeente'
      postcode: 3361AB                 (required, default = 3361AB)
      streetnumber: 1                  (required, default = 1)
      streetnumbersuffix: ''           (optional, default = '')
      dateformat: '%d-%m-%Y'           (optional, default = %d-%m-%Y) day-month-year
      locale: 'nl'                     (optional, default = 'en')
      timespanindays: 365              (optional, default = 365) number of days to look into the future

**Comment by edegraaff** [comment]
In de log zie ik dit
2022-03-06 18:34:17 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalinfo platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/afvalinfo/sensor.py", line 82, in setup_platform
resourcesMinusTodayAndTomorrow = [obj["type"] for obj in resources]
File "/config/custom_components/afvalinfo/sensor.py", line 82, in <listcomp>
resourcesMinusTodayAndTomorrow = [obj["type"] for obj in resources]
TypeError: string indices must be integers

**Comment by heyajohnny** [comment]
Ik hoop dat je dit er niet zo ingeplakt hebt (nou ja, eigenlijk wel, want dat verklaard dan het probleem).... Alle tekst tussen en na de haakjes moet je namelijk weghalen en is alleen bedoeld als commentaar, ter verduidelijking van wat de regel doet, of wat de standaard waarde is mocht je de regel niet gebruiken.
![image](https://user-images.githubusercontent.com/20553716/156937226-31033a9b-7f30-441d-9a22-3ac8a0d6bb92.png)
Pak anders deze [voorbeeld configuratie](https://github.com/heyajohnny/afvalinfo/blob/master/example/configuration.yaml). Deze kan je namelijk wel zo kopieren en plakken.

**Comment by woempiej** [comment]
Werkt op de een of andere manier toch nog niet. Ik krijg geen meldingen die ik ingesteld heb via automations.

**Comment by edegraaff** [comment]
Ik heb de commentaren niet gebruikt zie mijn andere voorbeeld, daarin staat exact mijn config instellingen dis niet heb voorbeeld  er zit een verschil tav de oude situatie bij mij, namelijk: er is bijgekomen -type:  bij mij was het in het verdleden zonder - type: dus - trash_type_tomorrow als voorbeeld even hoe mijn oude config er uit zag.

**Comment by heyajohnny** [comment]
Ik krijg hier je probleem niet gereproduceerd. Maak anders eens een screenshot van je config, want hier kan ik ook niets uit opmaken met al die gekke bullets en vetgedrukte teksten:
![image](https://user-images.githubusercontent.com/20553716/157018798-4cd24722-811e-4b35-9ff4-55cf483077a0.png)

**Comment by woempiej** [comment]
> Werkt op de een of andere manier toch nog niet. Ik krijg geen meldingen die ik ingesteld heb via automations.

Annuleer bericht. Heb de integratie weer aan de gang!

@edegraaff
Wat ik heb gedaan is:
1. Integratie verwijderd
2. Alle entiteiten verwijderd welke betrekking hebben op afvalinfo
3. Config verwijderd (In file editor)
4. Herstart HA
5. Integratie opnieuw gedownload
6. Herstart HA
7. Config opnieuw erin gezet (In file editor) zie hieronder bij config:
-----------------------------------------------------------------------------------------------------------------
sensor:
    - platform: afvalinfo
      resources:
        - type: restafval
          friendly_name: Restafval
        - type: gft
          friendly_name: Groenafval
        - type: pbd
          friendly_name: Plastic
        - type: papier
          friendly_name: Papier
        - type: trash_type_today
          friendly_name: Afval voor vandaag
        - type: trash_type_tomorrow
          friendly_name: Afval voor morgen
      location: Je gemeente
      postcode: Je postcode
      streetnumber: Je huisnummer
      streetnumbersuffix: ''
      dateformat: '%d-%m-%Y'
      locale: 'nl'
      timespanindays: 365
-----------------------------------------------------------------------------------------------------------------

8. Herstart HA
7. Automations TRIGGERS aangepast volgens "Friendly Name" m.b.v. Ontwikkelingshulp (Indien je daar gebruik van maakt)

**Comment by edegraaff** [comment]
![image](https://user-images.githubusercontent.com/12442749/157105559-b300ab76-7cb8-4da3-8e8b-5e0bfcd56672.png)

dit is de beeldscherm afdruk, de pc en huisnummer even geblurd 

check van de yml geeft geen fouten ... 

De optie is om hem helemaal te verwijderen en opnieuw te laden zoals gesuggereerd

alvast bedankt voor meedenken

btw ter info ik draai docker op mijn nas

**Comment by heyajohnny** [comment]
![Screenshot_2022-03-07-21-31-12-762_com android chrome](https://user-images.githubusercontent.com/20553716/157113246-f6722680-c3e7-4767-b062-2d38fce439c7.jpg)

Zo te zien kloppen je tabjes niet. Pak anders de voorbeeld config en pas deze aan naar je eigen adres.

**Comment by heyajohnny** [comment]
@edegraaff Ik neem aan dat alles het ondertussen weer doet? Ik sluit dit issue. Mocht het nog niet werken, kan dit issue altijd weer geopend worden.

**Comment by edegraaff** [comment]
Ik had gisteren geen tijd ik ga nu alles nog een keer nalopen en duimen dat alles dan wel werkt, dus sluit anders maar als ik er niet uit kom ga ik opnieuw zoeken. Heeft altijd gewerkt snap er geen lor van, dus we gaan even schoon aan het werk.
