### ISSUE TITLE
afvalkalender Westland

### ISSUE THREAD

**Issue by steef84** [heyajohnny/afvalinfo#272]
Het valt me zojuist op dat de gemeente Westland niet meer werkt sinds lange tijd van trouwe dienst. Wellicht is er wat veranderd op hun site? Kun je dit checken?

**Comment by heyajohnny** [comment]
Hij lijkt het hier goed te doen met deze postcode en huisnummer: 2675AA 1

**Comment by steef84** [comment]
Helemaal correct. Ik denk dat de site eruit heeft gelegen. Inmiddels zie ik alle data weer.!
