### ISSUE TITLE
Afval kalender v1.0.5 werkt niet meer

### ISSUE THREAD

**Issue by tvunen** [heyajohnny/afvalinfo#273]
Sinds de laatste afval kalender update werkt het helaas niet meer.
Geeft bij bijna alles niet beschikbaar aan, behalve bij restafval en oud papier die lijken wel juist te werken

![image](https://user-images.githubusercontent.com/82120296/157744312-fd85e0f6-85e0-4dbb-a380-f19283a4ada5.png)

**Comment by tvunen** [comment]
Probleem is alweer opgelost, blijkbaar zijn er na de update nieuwe entiteiten aangemaakt voor de diverse type afvalstromen.
Nadat ik deze weer correct had gezet werkte het weer

**Comment by robinwillems** [comment]
Inderdaad, ik hat hetzelfde probleem.

**Comment by heyajohnny** [comment]
Het verschilt een beetje per HA versie en je configuratie of de entiteiten hetzelfde blijven. Helaas kan ik hier niet zoveel aan doen. Gelukkig is het weer opgelost
