### ISSUE TITLE
vervang none met geen in sensortoday.py en sensortomorrow.py

### ISSUE THREAD

**Issue by robinwillems** [heyajohnny/afvalinfo#274]
In sensortoday.py en sensortomorrow.py wordt het woordje none gebruikt als er geen informatie is voor de afvalinfo van vandaag of morgen. Zou het mogelijk dit variabel te maken in de config zodat daar een eigen waarde (bijvoorbeeld geen) in kan worden gezet als het "none" is.

Het gaat om:
        # use a tempState to change the real state only on a change...
        tempState = "none"

Ik pas het nu na iedere update handmatig aan, maar zou mooi zijn als deze verbetering kan worden doorgevoerd.

**Comment by woempiej** [comment]
Persoonlijk zie ik het nut van de sensoren nog niet echt.
Ik denk dat de sensoren beter vervangen kunnen worden door een sensor met "Next trash typ and date", dan heb je namelijk nooit een "none".

Kun je het anders niet zoals hieronder maken?

![Afval](https://user-images.githubusercontent.com/62903344/159781006-71dd190d-24c2-443f-b4ac-3941ab9a58b5.PNG)

**Comment by woempiej** [comment]
Vrrdikkeme, Johnny heeft overal aan gedacht! De sensor is er al zie ik op de <code> pagina (Onderaan).

**Comment by robinwillems** [comment]
> Ik denk dat er een sensor bijgemaakt moet worden in de vorm van "Next trash typ and date", dan heb je namelijk nooit een "none".
> 
> Kun je het anders niet zoals hieronder maken?
> 
> ![Afval](https://user-images.githubusercontent.com/62903344/159781006-71dd190d-24c2-443f-b4ac-3941ab9a58b5.PNG)

Die heb ik natuurlijk al wel ;-)
![image](https://user-images.githubusercontent.com/6528318/159785818-10c35ee7-9665-4bc5-a715-1341aaa8ed83.png)
Alleen als er dus vandaag of morgen geen afval wordt gehaald komt daar het woordje none te staan (in mijn geval heb ik het dus in de code aangepast naar geen). Dat bedoelde ik.

**Comment by heyajohnny** [comment]
@robinwillems  Ik heb zojuist de optie 'notrashtext' toegevoegd in versie 1.0.6. Hierin kan je een willekeurige tekst zetten voor als er geen afval opgehaald wordt in de today of tomorrow sensors. Laat maar weten of alles werkt zoals verwacht
![image](https://user-images.githubusercontent.com/20553716/160296513-70a9bcb0-c5ae-4d40-bd1a-2dab4b6c116a.png)

**Comment by robinwillems** [comment]
Bedankt voor deze update @heyajohnny 
Het werkt als een zonnetje!
![image](https://user-images.githubusercontent.com/6528318/160299119-d698c5dc-e84f-414d-8332-fced18043f4a.png)
