### ISSUE TITLE
Den Ham Twenterand (ROVA) werkt niet meer

### ISSUE THREAD

**Issue by jov58** [heyajohnny/afvalinfo#275]
Hoi,

Voor deze plaats werkt afvalinfo de laatste weken niet meer. Als ik postcode en huisnr invul op de [site van ROVA](https://inzamelkalender.rova.nl/), krijg ik wel de gewenste informatie. Er is iets bij ROVA veranderd denk ik?

**Comment by fishbone-git** [comment]
Venlo is also broken, but this is because the Venlo site changed.  Try entering your postcode at afvalinfo.nl (the site used for this integration).  if that fails, then you can use the "contact us" link on afvalinfo.nl to notify them of the change and hopefully it works again via this integration.

**Comment by heyajohnny** [comment]
@jov58 Twenterand werkt gewoon met postcode huisnummer 7694BD 4 
Mocht je een specifieker adres hebben, dan kan ik dat uiteraard ook testen, maar voor nu lijkt alles het gewoon te doen

**Comment by fishbone-git** [comment]
Interesting, 5912EV doesn't work for me either, integration comes up unavailable and from afvalinfo.nl, also page not found.  5914WK 40 is my specific problem.

**Comment by fishbone-git** [comment]
I found a solution for me.  for some reason, I have a bunch of "hidden" disabled entites.  I had to remove the integration, delete all afval* entities, hidden or not, then reinstall. Misschien werkt het ook for de OP

**Comment by smartworkx75** [comment]
Hi heyajohnny,

uithoorn en aalsmeer werken beide ook niet meer (meerlanden)

**Comment by jov58** [comment]
> @jov58 Twenterand werkt gewoon met postcode huisnummer 7694BD 4 Mocht je een specifieker adres hebben, dan kan ik dat uiteraard ook testen, maar voor nu lijkt alles het gewoon te doen

7694BD 4 doet het hier ook niet.

> I found a solution for me. for some reason, I have a bunch of "hidden" disabled entites. I had to remove the integration, delete all afval* entities, hidden or not, then reinstall. Misschien werkt het ook for de OP

Ah, dat was het! Er zijn wat entity_id's veranderd (b.v. sensor.afvalinfo_today -> sensor.afvalinfo_trash_type_today), had ik blijkbaar gemist. Alles weer OK!

**Comment by heyajohnny** [comment]
@smartworkx75 Gemeente Uithoorn werd nog niet ondersteund. Deze heb ik zojuist toegevoegd.

**Comment by heyajohnny** [comment]
Volgens mij is zo alles in dit issue opgelost. Ik sluit dit issue.
Mocht er toch nog iets zijn, kan altijd een nieuw issue geopend worden.
