### ISSUE TITLE
Gemeente Westerkwartier werkt niet meer voor milieuboer (papier, pbd, textiel)

### ISSUE THREAD

**Issue by sicco92** [heyajohnny/afvalinfo#276]
Sinds een tijdje werkt de integration niet meer goed voor gemeente Westerkwartier. Restafval en GFT worden goed opgehaald, maar alle andere afvaltypen blijven op 'unknown' staan. 

Via afvalinfo.nl krijg ik wel een URL voor dit adres die me weer doorstuurt naar mijnafvalwijzer.nl, waar uiteindelijk wel een werkende afvalkalender te zien is. Daar staan de categorieën:
- milieuboer
- restafval
- kerstbomen
- gft

Testadres: 9351LE 123

**Comment by heyajohnny** [comment]
Onder welke categorie zou milieuboer geschaard kunnen worden? PBD? Textiel? Papier? 
Of een combinatie van deze?

**Comment by sicco92** [comment]
De milieuboer neemt in onze gemeente onder andere PBD, textiel, en papier mee. Ook nog wat andere categorieën, maar die worden niet ondersteund door de integration.

**Comment by heyajohnny** [comment]
Ahhh... Ik had de titel van het issue niet goed gelezen. 
Ik heb zojuist milieuboer / milieubus toegevoegd en gekoppeld aan pbd, textiel en papier.
Laat maar weten of alles werkt zoals verwacht

**Comment by sicco92** [comment]
Geen probleem! Nadat Home Assistant toevallig voor wat anders herstart werd, werkt alles weer zoals het werkt. Dankjewel voor de fix!
