### ISSUE TITLE
Update V1.0.1 -> V1.0.5

### ISSUE THREAD

**Issue by BuurmanG** [heyajohnny/afvalinfo#277]
In HACS is een update beschikbaar van V1.0.1 naar V1.0.5. Ik heb meerdere keren geprobeerd om dit te doen, maar na herstart blijft de melding maar komen. Ik ben nieuw in HA, wat kan ik hieraan doen?
![image](https://user-images.githubusercontent.com/27959906/158678032-c608f120-572b-441b-88b8-50037c8761b7.png)

**Comment by heyajohnny** [comment]
Geen idee... 
Nog een keer herstarten? HACS updaten? Home Assistant Updaten? Of een combinatie van deze.
p.s. Je hoeft uiteraard niet te updaten. De oudere versies blijven gewoon werken

**Comment by woempiej** [comment]
Probeer de integratie eens helemaal te verwijderen. Daarna HA herstarten en de integratie opnieuw downloaden.

**Comment by heyajohnny** [comment]
Ik ga er vanuit dat het probleem is opgelost. Ik sluit het issue. Mocht het nog niet zijn opgelost kan het issue altijd weer heropend worden

**Comment by BuurmanG** [comment]
Helaas is het probleem niet opgelost. Onder het motto "niets zo goed as een frisse reboot" werkelijk van álles geprobeerd! Ook complete dé-installatie, maar niks werkt... ik denk dat ik HA opnieuw moet installeren, maar dat schuif ik nog even vooruit... misschien is er toch nog iemand met de gouden tip?

**Comment by heyajohnny** [comment]
Misschien als je de database file verwijderd:
![image](https://user-images.githubusercontent.com/20553716/160297575-61af90f5-81e0-402c-ae95-a1195d615796.png)

**Comment by BuurmanG** [comment]
Dat ga ik zeker proberen....

**Comment by BuurmanG** [comment]
Ik hen nét HACS versie 1.24.0 geïnstalleerd. Hierna kon ik probleemloos Afvalinfo updaten. Probleem opgelost. Dank voor de hulp.
