### ISSUE TITLE
Geen data gem. Voorst

### ISSUE THREAD

**Issue by WouterKr** [heyajohnny/afvalinfo#281]
Vandaag viel me op dat voor gemeente Voorst er geen data beschikbaar is. 
De link van afvalinfo naar Voorst werkt niet (meer) en heb hiervan al melding gemaakt.
Lijkt erop dat Voorst de kalender nu bij circules heeft?

Hoop dat het kan worden opgelost.

**Comment by heyajohnny** [comment]
De API van Circulus-Berkel is aangepast zie ik.
Notitie voor mezelf:
https://www.circulus.nl/api/visitor.php?address=Bonenkampsweg&city=Voorst&municipality=Voorst&redirect=https%3A%2F%2Fmijn.circulus.nl%2Fdiensten%2F&streetnumber=2&zipcode=7383RR
https://mijn.circulus.nl/inbound-afvalkalender.json

**Comment by robinwillems** [comment]
Ik neem aan dat dit dezelfde reden heeft waarom 7327DA, 118 het niet meer doet?
Of is dat een foute aanname?

**Comment by dobje** [comment]
(Lochem) 7241GN geeft ook problemen Error occurred. Please check the address with postcode: ... ... It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github

**Comment by heyajohnny** [comment]
Ik heb zojuist een fix doorgevoerd voor de nieuwe API van Circulus. Als het goed is zou alles weer moeten werken.

**Comment by WouterKr** [comment]
Dank je wel! Het lijkt allemaal weer te werken.

**Comment by robinwillems** [comment]
Inderdaad, werkt weer. Dank!

**Comment by MLux72** [comment]
Ik heb alleen nog bij restafval unknown staan, enig idee waar dat aan kan liggen? De rest geeft wel een datum

**Comment by heyajohnny** [comment]
@MLux72 Zou je aan kunnen geven op welk adres dit is?

**Comment by MLux72** [comment]
> @MLux72 Zou je aan kunnen geven op welk adres dit is?

7384BM Wilp

**Comment by heyajohnny** [comment]
Restafval had a different name in Wilp. It should be fixed now.

**Comment by MLux72** [comment]
Thanks het werkt weer.

**Comment by heyajohnny** [comment]
Volgens mij werkt het weer bij iedereen. Ik sluit dit issue. Mochten er toch nog problemen zijn, dan kan dit issue altijd weer geopend worden.
