### ISSUE TITLE
Geen data Gemeente Venlo

### ISSUE THREAD

**Issue by funnyavocado** [heyajohnny/afvalinfo#282]
Goedendag,
Ik heb nu al een aantal dagen dat de afval info van Gemeente Venlo niet weergegeven wordt. Er is verder niets veranderd in de configuratie van mijn HA, wellicht een verandering bij de Gemeente of dergelijke?

**Comment by heyajohnny** [comment]
Venlo werkt prima voor de postcode huisnummer combinatie 5912EV 97.

**Comment by funnyavocado** [comment]
vreemd.... dan ga ik even kijken of ik iets gevonden krijg. Alvast bedankt.

**Comment by funnyavocado** [comment]
Mijn fout, Ik heb de config niet geupdate na de laatste update.....

Excuses
