### ISSUE TITLE
Gemeente reimerswaal

### ISSUE THREAD

**Issue by Vabis1010** [heyajohnny/afvalinfo#283]
Gemeente reimerswaal geeft alleen gegevens door voor gft. Geen restafval en geen melding voor vandaag en morgen?

**Comment by heyajohnny** [comment]
Heb je misschien een postcode voor mij?

**Comment by Vabis1010** [comment]
Pontboden in reimerswaal 4416CK
HUISNUMMER 41

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by heyajohnny** [comment]
Volgens de officiele gemeente kalender wordt er (de aankomende tijd) geen restafval opgehaald op dit adres:
![image](https://user-images.githubusercontent.com/20553716/162924144-b3e72564-e7be-4239-9e6c-220746761d15.png)

**Comment by Vabis1010** [comment]
Oke wachten we even af tot na volgend weekend. Raar is dat sensor op onbekend staan. Restafval is vandaag opgehaald. Er kwam niks door.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by Vabis1010** [comment]
als opvolging: melding voor gft afval gemeente reimerswaal word goed doorgegeven.Gegevens voor morgen ook. Restafval blijft een probleem. moet nu de 25e april opgehaald worden maar staat nog altijd op onbekend.

**Comment by bafplus** [comment]
Probleem ligt bij ZRD. In alle agendaś wordt alleen gft en pmd aangegeven maar geen restafval.
![Screenshot 2022-04-23 19 44 06](https://user-images.githubusercontent.com/6432986/164933701-e5001fbd-703f-427f-b871-1c7fade478ac.png)

**Comment by bafplus** [comment]
Als ik hun site mag geloven, combineren zij het plastic en het restafval in "PMD+". Dus feitelijk wordt plastic en restafval op hetzelfde moment opgehaald. Maar hebben zij in de kalender samengevoegd met plastic. .....appart :-)
![Screenshot 2022-04-23 19 47 45](https://user-images.githubusercontent.com/6432986/164933912-cede8b48-636b-43d6-bc1d-57617cdae2b8.png)

**Comment by Vabis1010** [comment]
Opgelost met hulp van bafplus. Bedankt Bart.
