### ISSUE TITLE
Afvalinfo datum onbekend

### ISSUE THREAD

**Issue by freggel2** [heyajohnny/afvalinfo#284]
Hallo Johnny,

mijn status geeft onbekend aan.
Tot aan gisteren werkte het prima maar vanochtend geeft hij onbekend aan.
Dit was laatst ook zo. Toen heb ik alles verwijderd en opnieuw toegevoegd.
Ik heb de code gebruikt exact zoals jij hem beschreven hebt.

Hier is mijn code zoals ik hem gebruikt heb.

  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: kerstboom
        friendly_name: Kerstboom
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: takken
        friendly_name: Takken
      - type: textiel
        friendly_name: Oude Kleding
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: maashorst
    postcode: Mijn postcode
    streetnumber: mijn huisnummer
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
    notrashtext: "geen"
  - platform: template
    sensors:
      paper_days_until_collection:
        value_template: "{{ state_attr('sensor.afvalinfo_papier', 'days_until_collection_date') }}"

  - platform: template
    sensors:
      afvalinfo_next_trash_type_and_date:
        value_template: >
          {% set ns = namespace(minimum=365) %}
          {% set list = ['groente_fruit_en_tuinafval', 'kerstboom', 'plastic_blik_en_drankkartons', 'papier', 'restafval', 'takken', 'oude_kleding'] %}
          {% set friendly_list = ['Groente Fruit en Tuinafval', 'Kerstboom', 'Plastic Blik en Drankkartons', 'Papier', 'Restafval', 'Takken', 'Oude Kleding'] %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days != None and days < ns.minimum %}
          {%- set ns.minimum = days %}
          {%- endif %}
          {%- endfor %}
          {%- for l in list %}
          {%- set days = state_attr('sensor.afvalinfo_' ~l, 'days_until_collection_date')%}
          {%- if days == ns.minimum %}
          {{friendly_list[loop.index0]}} · {{ states('sensor.afvalinfo_' ~l) }}
          {%- endif %}
          {%- endfor %}
          
rdw:
  - plate: nummerplaat
    name: "merk auto"
    dateformat: '%d %b %Y'
    binary_sensors:
      - insured
    sensors:
      - expdate
      - recall
  - plate: nummerplaat
    name: "merk auto"
    dateformat: '%d %b %Y'
    binary_sensors:
      - insured
    sensors:
      - expdate
      - recall
  - plate: nummerplaat
    name: "merk auto"
    binary_sensors:
      - insured
    sensors:
      - expdate
      - recall
  - plate: numerplaat
    name: "mer auto"
    sensors:
      - expdate
          
homeassistant:
  customize:
    sensor.afvalinfo_groente_fruit_en_tuinafval:
      entity_picture: /local/recycle_bin_green_T.png
    sensor.afvalinfo_plastic_blik_en_drankkartons:
      entity_picture: /local/recycle_bin_orange_T.png
    sensor.afvalinfo_restafval:
      entity_picture: /local/recycling_bin_T.png
    sensor.afvalinfo_papier:
      entity_picture: /local/recycle_bin_blue_T.png
    sensor.bmw_expdate:
      friendly_name: "APK Vervaldatum"
    sensor.bmw_insured:
      friendly_name: "Verzekeringsstatus"
    sensor.bmw_recall:

**Comment by hmmbob** [comment]
@heyajohnny ik kan bevestigen dat de sensor momenteel struikelt over de pagina van Maashorst - ik heb hetzelfde probleem. Vermoedelijk omdat er wat wijzigingen in datums actief staan op de Afvalwijzer.

**Comment by freggel2** [comment]
> @heyajohnny ik kan bevestigen dat de sensor momenteel struikelt over de pagina van Maashorst - ik heb hetzelfde probleem. Vermoedelijk omdat er wat wijzigingen in datums actief staan op de Afvalwijzer.

Ok. Dank je voor je reply. Ik wacht geduldig af.

**Comment by heyajohnny** [comment]
Werkt hier zonder problemen...
![image](https://user-images.githubusercontent.com/20553716/163193617-db29d891-041f-4d01-bbb2-b2c97056ab81.png)

**Comment by freggel2** [comment]
Mijn postcode is ook 5403.

Geen idee of het daar aan kan liggen...

**Comment by hmmbob** [comment]
![image](https://user-images.githubusercontent.com/33529490/163207848-954945d2-1bba-4f67-bb6c-318ee131a345.png)

```html
<div id="waste-dates">
            <h3 class="icon-restafval">Restafval</h3>
                <ul>
                            <li>
                                            donderdag 14 april
                                    </li>
                            <li>
                                            donderdag  5 mei
                                    </li>
                            <li>
                                            <del>Donderdag 26 mei</del>
                        <ins>zaterdag 28 mei</ins>
                                    </li>
                    </ul>
            <h3 class="icon-plastic">PBD</h3>
                    <p>Plastic verpakkingen, blik en drinkkartons</p>
                <ul>
                            <li>
                                            dinsdag 19 april
                                    </li>
                            <li>
                                            dinsdag 26 april
                                    </li>
                            <li>
                                            dinsdag  3 mei
                                    </li>
                    </ul>
            <h3 class="icon-oudpapier">Oud papier en karton</h3>
                <ul>
                            <li>
                                            dinsdag 19 april
                                    </li>
                            <li>
                                            dinsdag 17 mei
                                    </li>
                            <li>
                                            dinsdag 21 juni
                                    </li>
                    </ul>
            <h3 class="icon-gft">GFT+E</h3>
                <ul>
                            <li>
                                            <del>Maandag 18 april</del>
                        <ins>zaterdag 16 april</ins>
                                    </li>
                            <li>
                                            maandag 25 april
                                    </li>
                            <li>
                                            maandag  2 mei
                                    </li>
                    </ul>
    </div>
```

**Comment by heyajohnny** [comment]
Ik zie het. Ik heb zojuist een update doorgevoerd en alles zou weer moeten werken.

**Comment by freggel2** [comment]
Thanks. Het werkt inderdaad weer.
