### ISSUE TITLE
Onterechte melding voor ophalen GFT

### ISSUE THREAD

**Issue by GertJanArts** [heyajohnny/afvalinfo#285]
@heyajohnny Onterecht meldt afvalinfo dat morgen het GFT wordt opgehaald. Dat is niet volgens het schema (zie screenshot hieronder)
Het gaat om de afvalkalender van gemeente Land van Cuijk
Bedankt voor je reactie

![1](https://user-images.githubusercontent.com/20320533/163728235-07b4e39c-795d-4b07-9c8e-0680ebbc67fe.png)
![2](https://user-images.githubusercontent.com/20320533/163728272-94af9c66-6d93-4b9f-9903-3914ae4d0261.png)

**Comment by heyajohnny** [comment]
Ik heb zojuist een update doorgevoerd. De volgende keer als er een doorgestreepte datum is, wordt deze niet als ophaaldatum meegenomen.
