### ISSUE TITLE
Please add Boesingheliede

### ISSUE THREAD

**Issue by schusz** [heyajohnny/afvalinfo#29]
Waste collection site of municipality Haarlemmermeer, of which Boesingheliede is a part (buurtschap):
https://afvalkalender.meerlanden.nl/

**Comment by heyajohnny** [comment]
I've just added Meerlanden, including Boesingheliede! Enjoy :) 
And please let me know if it works.

**Comment by heyajohnny** [comment]
Since I don't hear that it's not working, I assume it's working. 
I'll close the issue. If you have any problems, please reopen or create a new issue,

**Comment by schusz** [comment]
Hey Johnny,

Thanks for adding Meerlanden, Boesingheliede.
I haven’t had the chance yet to install and check it. I’ll let you know as soon as I have tested it.

Greetings,
Roel

**Comment by schusz** [comment]
I installed afvalinfo, and added this to configuration.yaml:

  - platform: afvalinfo
    resources:
      - gft
      - restafval
      - trash_type_today
    city: <mycity>
    postcode: <mypostcode>
    streetnumber: <myhousenumber>

And it works!

Thanks Johnny
