### ISSUE TITLE
Error occurred. Please check the address with postcode: 'xxxx' and huisnummer: 'xx'

### ISSUE THREAD

**Issue by arjen-w** [heyajohnny/afvalinfo#291]
Error occurred. Please check the address with postcode: '2665dv' and huisnummer: '2' on the website of your local waste collector in the gemeente: 'lansingerland'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

Manual checking the data in mijnafvalwijzer.nl will provide me a correct calendar.

**Comment by heyajohnny** [comment]
Looks like it's working as normal at the moment...
![image](https://user-images.githubusercontent.com/20553716/167839920-d31aa40f-2339-41db-8cba-f377eff3abbd.png)

**Comment by arjen-w** [comment]
Looking at the time of the event it might be a connectivity issue, don't see it being logged at the moment.
I will close it for now, if I do see it happening again and can check connectivity at the same time I will re-open.

Thnx for checking!
