### ISSUE TITLE
Gemeente Epe geeft geen ophaaldatum voor papier meer

### ISSUE THREAD

**Issue by greenpupa** [heyajohnny/afvalinfo#293]
Voorheen kreeg ik naast restafval, pmd en groen ook de ophaaldag voor papier terug. Nu helaas niet meer.

Hierbij een dummy adres:
https://trashapi.azurewebsites.net/trash?Location=epe&ZipCode=8161CL&HouseNumber=1

**Comment by heyajohnny** [comment]
Ik zie dat het een combinatie van types is:
![image](https://user-images.githubusercontent.com/20553716/167877633-1c7a129d-e928-4611-80d4-323537305b43.png)
Ik heb zojuist een update doorgevoerd, waarbij papier (en textiel) matchen met deze 'glas, papier en best' ophaaldatums.

**Comment by greenpupa** [comment]
Werkt nu weer prima :-). Thx
