### ISSUE TITLE
Question for the future

### ISSUE THREAD

**Issue by AarvdH** [heyajohnny/afvalinfo#294]
Today I was reading the following link about the change of Afval in Alkmaar (1822RA, 14 for me)  Can you please take a look at this? Its concerning a lot of people here end I am really fond of your HACS integration... Thanks !

https://alkmaarcentraal.nl/60111222-hvc-neemt-afvalinzameling-in-alkmaar-op-1-juni-over-van-stadswerk072?utm_source=dlvr.it&utm_medium=facebook

**Comment by AarvdH** [comment]
Hi, today I was looking at the HVC groep website. Now there is the possibility to feed my calendar and so on. For the coming month the Stadwerk072 and HVC calendar are synchroon. When you have the time can you take a look for implementing the new HVC calendar in your integration? And must I do something myself? Are all my little scripts sray functional?
Bij voorbaat dank,
Hans.

**Comment by heyajohnny** [comment]
I've just pushed an update for the migration of Alkmaar to HVC.
If you find anything unusual please let me know. 
I'm closing this issue for now
