### ISSUE TITLE
Gemeente Zwolle

### ISSUE THREAD

**Issue by arne913** [heyajohnny/afvalinfo#298]
In de gemeente Zwolle wordt er onderscheid gemaakt tussen 'pmd' en 'pmd in zakken', en 'gft-afval' en 'gft in emmers'. Op ons adres gaat het om 'pmd in zakken' en 'gft in emmers', maar deze zijn niet toe te voegen als sensor. 

Is er een mogelijkheid om dit wel toe te voegen?

Ik hoor het wel, alvast bedankt!

**Comment by mauritsdej** [comment]
In een eerdere versie van de integratie gebruikte je nog web scraping.
Ik weet niet of je op de hoogte bent dat Zwolle inmiddels ook een API heeft. Wellicht helpt dit.

https://www.rova.nl/api/waste-calendar/upcoming?postalcode=1234AB&houseNumber=12&addition=&take=15

**Comment by heyajohnny** [comment]
@arne913 Heb je wellicht een voorbeeld adres waarbij 'pmd in zakken' en 'gft in emmers' in voorkomt. Bij deze zie ik ze namelijk niet...
![image](https://user-images.githubusercontent.com/20553716/181365068-b0531b5f-8301-41b5-8df1-1878a2f24998.png)

**Comment by mauritsdej** [comment]
@heyajohnny Een voorbeeld:
https://inzamelkalender.rova.nl/nl/8021ER/12/
https://www.rova.nl/api/waste-calendar/upcoming?postalcode=8021ER&houseNumber=12&addition=&take=15

**Comment by heyajohnny** [comment]
Ik heb 'pmd in zakken' aan 'pbd' gekoppeld en 'gft in emmers' aan 'gft'.
Ik zou eventueel ook 'gft in emmers' aan 'takken' kunnen koppelen als je dat logischer lijkt?
Laat maar weten of het zo werkt, zoals je verwacht

**Comment by mauritsdej** [comment]
PMD in zakken gekoppeld aan 'pbd' is een prima oplossing.

'gft in emmers' aan 'gft' koppelen kan verwarring veroorzaken omdat we ook nog een GFT-container hebben...
'takken' wordt in ons gebied niet gebruikt, dus misschien een betere oplossing, dan heb je het tenminste als los te identificeren entiteit.
Ik betwijfel allen een beetje de duidelijkheid naar andere gebruikers...

**Comment by heyajohnny** [comment]
Ik heb nu ook 'gft in emmers' gekoppeld aan 'takken' en heb de README pagina aangepast om dit te verduidelijken.

Het probleem is anders dat ik een wildgroei aan entiteiten krijg, omdat iedere gemeente een, net weer iets andere naamgeving gebruikt.

Ik hoop dat hierbij je issue is opgelost

**Comment by arne913** [comment]
Dit werkt perfect, bedankt! @mauritsdej ook bedankt!
