### ISSUE TITLE
Afval status Onbekend Heerlen

### ISSUE THREAD

**Issue by Epione69** [heyajohnny/afvalinfo#299]
Since 14-06-22 it is not possible to retrieve the afvalstatus in city Heerlen 6413LN. This is from RD4.

Version v1.0.7

**Comment by robsonke** [comment]
Same issue here but with Goes: 4481 CP

**Comment by Epione69** [comment]
For me Afvalinfo is working again !!

**Comment by robsonke** [comment]
Same with me. Sounds like the external service had issues.
