### ISSUE TITLE
Toevoegen : Nieuwstadt

### ISSUE THREAD

**Issue by the-capb1** [heyajohnny/afvalinfo#3]
Hi, is het mogelijk om Nieuwstadt toe te voegen aan afvalinfo?  Thanks.
Gemeente: Echt-Susteren.

**Comment by heyajohnny** [comment]
Ik ga hier de aankomende week mee aan de slag.

**Comment by madirshah** [comment]
Hi, is het mogelijk om **Gemeente: Amsterdam** toe te voegen aan afvalinfo? Thanks.

**Comment by heyajohnny** [comment]
@madirshah Zou je hiervoor een nieuw issue aan willen maken?

**Comment by heyajohnny** [comment]
Zojuist is de gemeente Echt-Susteren toegevoegd :)

**Comment by the-capb1** [comment]
Bedankt :) !
