### ISSUE TITLE
Sensor pbd does not work for DeAfvalApp

### ISSUE THREAD

**Issue by SLaheij** [heyajohnny/afvalinfo#30]
The pbd sensor does not work for DeAfvalApp because DeAfvalApp uses afvaltype plastic instead of pdb. I don't know if it's the case for every locotion but it is for loacation Kerkdriel.

**Comment by heyajohnny** [comment]
In the locations I checked it was called PMD, but in your case it is PLASTIC.
I've just pushed an update.

Please let me know if it's fixed.

**Comment by SLaheij** [comment]
It's fixed now. Thank you very much!
