### ISSUE TITLE
Gemeente Montferland

### ISSUE THREAD

**Issue by woempiej** [heyajohnny/afvalinfo#301]
Hallo,

De website van de gemeente Montferland is iets aangepast. 
Voorheen kwam ik direct op deze pagina:     https://montferland.afvalwijzer.net/aanmelden.aspx
Nu kom ik eerst op deze pagina:     https://www.montferland.info/digitale-afvalwijzer 

Is dit iets wat in het script aangepast dient te worden?

De status van mijn entiteiten zijn nu "Onbekend"

![afbeelding](https://user-images.githubusercontent.com/62903344/174649015-972dffc1-557c-41cb-884e-6f42aef85bd0.png)

![afbeelding](https://user-images.githubusercontent.com/62903344/174649220-e2f52248-5412-407e-b52b-6d2c9a96859a.png)

Home Assistant LOG na een herstart:

![afbeelding](https://user-images.githubusercontent.com/62903344/174651525-9ce9f58e-0c4b-4f8f-9323-e88d07150279.png)

**Comment by heyajohnny** [comment]
Vreemd... Lijkt hier gewoon te werken:
![image](https://user-images.githubusercontent.com/20553716/174670713-ed2a5e12-16ca-45f1-a932-d42e651a5bfa.png)

**Comment by woempiej** [comment]
Inderdaad vreemd. Ben er gisteren nog tot laat mee bezig geweest.
Uiteindelijk heb ik een backup van begin deze maand erin geblazen zonder direct resultaat. Ik kreeg nog steeds de bovengenoemde LOG melding.

Nu werkt alles ineens weer. 

Toch bedankt voor jou reactie Johnny!
