### ISSUE TITLE
Geen afval updates meer

### ISSUE THREAD

**Issue by RobHomey** [heyajohnny/afvalinfo#305]
Sinds vandaag 0:59 komen er geen afval updates meer binnen. Ook niet naar een aantal keer HA opnieuw te hebben opgestart.
<img width="388" alt="Schermafbeelding 2022-07-07 om 09 59 38" src="https://user-images.githubusercontent.com/61829624/177722940-59720622-7b89-4c6f-a02d-7dcb940f9edd.png">
<img width="375" alt="Schermafbeelding 2022-07-07 om 09 59 53" src="https://user-images.githubusercontent.com/61829624/177722985-764c0149-749e-4119-a8e3-a4ea6a7d42c7.png">

Er is niets aan de configuratie aangepast behalve dat er gisteren een update van HA was. Deze heb ik rond 21:00 uur geïnstalleerd en na installatie werkte alles nog.
Wat kan ik doen om er voor te zorgen dat ik weer update voor afval ontvang?

**Comment by WouterKr** [comment]
Middernacht lijkt raar moment te zijn. Ook bij mij geen updates meer sinds 00:00 uur.

**Comment by WouterKr** [comment]
Sinds vannacht worden de gegevens weer bijgewerkt. Hoop dat het een hikje was.
