### ISSUE TITLE
Gemeente Heiloo, Bergen, Castricum en Uitgeest

### ISSUE THREAD

**Issue by ThijsBorst** [heyajohnny/afvalinfo#310]
Deze gemeenten zijn van de afvalwijzer afgestapt en hebben nu Mijn Afvalzaken (https://mijnafvalzaken.nl/). Dit zorgt er helaas voor dat voor deze gemeenten afvalwijzer niet meer werkt.

**Comment by heyajohnny** [comment]
Notitie voor mezelf:
![image](https://user-images.githubusercontent.com/20553716/181364450-36958af4-c6a9-4638-8c28-92f676e68ca8.png)

**Comment by heyajohnny** [comment]
Ik heb de gemeenten 'Castricum', 'Heiloo' en 'Uitgeest' aangepast naar MijnAfvalzaken.
De gemeente 'Bergen' is nog gewoon op HVC aangesloten.

Laat maar weten of alles werkt zoals verwacht

**Comment by ThijsBorst** [comment]
Ik zal het gaan testen

**Comment by ThijsBorst** [comment]
Ik heb geen rare dingen gevonden @heyajohnny. Ziet er goed uit!
