### ISSUE TITLE
Future Request "Dagen volgende ophaal moment"

### ISSUE THREAD

**Issue by woempiej** [heyajohnny/afvalinfo#312]
Is het mogelijk om een sensor in te bouwen voor het waarnemen van het volgende ophaal moment?

![afbeelding](https://user-images.githubusercontent.com/62903344/180066473-bba35165-36e3-4a3a-8af5-9017fe4f7947.png)

Dit zodat ik deze kan gebruiken voor de "Auto entiteit card" zodat de bovenste, de eerstvolgende is. Dan staan ze niet willekeurig zoals nu.

![afbeelding](https://user-images.githubusercontent.com/62903344/180066886-b261a143-949d-4f95-82d9-698eadbe728c.png)

Is voor het visuele plaatje...

**Comment by heyajohnny** [comment]
En als je 'attribute: sensor.afvalinfo_next_trash_type_and_date' aanpast naar 'attribute: year_month_day_date'? 
Laat maar weten of dat werkt...

Zie [hier](https://github.com/thomasloven/lovelace-auto-entities#sorting-entities) voor de 'auto-entities' documentatie.
![image](https://user-images.githubusercontent.com/20553716/180637470-2d82689b-2fb4-498d-8347-2c53deda2de4.png)
