### ISSUE TITLE
Missing option for keukenafval

### ISSUE THREAD

**Issue by labrag12** [heyajohnny/afvalinfo#313]
Gemeente Horst aan de Maas is using keukenafval, but i'm not able to add this.
GTF is not used in this gemeente. please give an hint how i can add this.

**Comment by woempiej** [comment]
Hallo,

Hoe heb je "grof tuin afval" gedefinieerd in jou configuration.yaml? 

![afbeelding](https://user-images.githubusercontent.com/62903344/180296343-7b59f199-04a6-4956-b879-d778b3b9dd3d.png)

Kun je hier niet gewoon "keukenafval" aan toevoegen?

**Comment by woempiej** [comment]
Bijvoorbeeld i.p.v. kerstboom

![afbeelding](https://user-images.githubusercontent.com/62903344/180297462-7519b546-3b5d-4c1e-a2c4-5d3fc23cf899.png)

**Comment by heyajohnny** [comment]
@labrag12 Als ik het goed begrijp zou 'keukenafval' onder 'gft' geschaard kunnen worden?
Laat maar weten of mijn aanname correct is...

**Comment by heyajohnny** [comment]
@labrag12 I've added 'keukenafval' under 'gft' and 'Grof tuinafval' under 'takken'. This should fix your issue. If not, please let me know

**Comment by labrag12** [comment]
hi thank you , all is working now.
Sorry for the late reaction, we had a short holiday.
