### ISSUE TITLE
Gemeente Oldebroek werkt niet meer

### ISSUE THREAD

**Issue by patrickdewitNL** [heyajohnny/afvalinfo#316]
Gemeente Oldebroek lijkt niet meer te willen werken, ondanks dat de gegevens invullen op mijnafvalwijzer wel de juiste data geeft:

`  - platform: afvalinfo
    resources:
      - gft
      - papier
      - restafval
      - trash_type_today
      - trash_type_tomorrow
    location: oldebroek
    postcode: 8094AR
    streetnumber: 600
    locale: "nl"`

Config:

`Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/trashapi.py:75
Integration: afvalinfo ([documentation](https://github.com/heyajohnny/afvalinfo), [issues](https://github.com/heyajohnny/afvalinfo/issues))
First occurred: 11:26:30 (1 occurrences)
Last logged: 11:26:30

Error occurred. Please check the address with postcode: '8094AR' and huisnummer: '600''' on the website of your local waste collector in the gemeente: 'oldebroek'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working`

**Comment by heyajohnny** [comment]
Oldebroek lijkt hier zonder problemen te werken:
![image](https://user-images.githubusercontent.com/20553716/181361212-2f0bc8e5-3e9f-4cc6-9b0e-8826444c52bc.png)

**Comment by heyajohnny** [comment]
Ik zie dat er na middernacht veel errors optreden... Waarschijnlijk is mijnafvalwijzer dan tijdelijk niet bereikbaar en krijg je geen data. Ik kan hier verder weinig aan doen...
![image](https://user-images.githubusercontent.com/20553716/181362987-0dcdb9a1-faa0-4aff-a436-750c8deb57dd.png)
