### ISSUE TITLE
Gemeente Venlo werkt niet meer

### ISSUE THREAD

**Issue by janss028** [heyajohnny/afvalinfo#318]
Sinds vandaag werkt de api niet meer naar de gemeente venlo.
In de logging zie ik:
2022-07-27 10:30:13 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration afvalinfo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-27 10:30:54 ERROR (SyncWorker_6) [custom_components.afvalinfo.const.const] Error occurred. Please check the address with postcode: '5935RE' and huisnummer: '45''' on the website of your local waste collector in the gemeente: 'venlo'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working.

Gisteren werkte alles nog en er zijn geen aanpassingen geweest in de configurartion.yaml.

![image](https://user-images.githubusercontent.com/79377231/181207067-e62cf776-8844-48fb-a9eb-6c4f9b7b2422.png)

![image](https://user-images.githubusercontent.com/79377231/181207216-bf553d19-dffc-4f87-8e9f-d1d34e25b962.png)

Ik heb nog even verder gezocht en kwam issue #282 tegen. Als deze postcode probeer dan werkt het wel.

5912EV 97
![image](https://user-images.githubusercontent.com/79377231/181241348-ce1e3628-9b2c-41c3-bc76-9d8d6e13fd0e.png)

5935RE 45
![image](https://user-images.githubusercontent.com/79377231/181241453-ab3a0dcd-0882-48bd-9145-98cbcc89819c.png)

Gisteren gaf hij aan dat hij morgen (rep. Vandaag) GFT en Restafval zou komen ophalen. Nu geeft hij aan dat alles onbekend is.

**Comment by heyajohnny** [comment]
Lijkt hier weer gewoon te werken:
![image](https://user-images.githubusercontent.com/20553716/181361792-32009494-3f23-4605-93ee-8e1a2b9b2f77.png)

**Comment by janss028** [comment]
Hallo,

Ik heb net HA gerestart maar bij werkt het nog niet. Wat kan eventueel het probleem zijn?

Mvg
Ron Janssen

**Comment by heyajohnny** [comment]
Werkt het toevallig alweer? Ik heb vandaag nog een update van afvalinfo doorgevoerd, wellicht dat na de update het bij jou weer gaat werken. Laat maar weten of dit het probleem heeft opgelost.

**Comment by janss028** [comment]
Hallo,

 

Ik heb even gekeken en zie dat het werkt. Ik heb alleen nog een probleem met de visualisatie.

 



 

Zoals je kunt zien wordt morgen GFT opgehaald en ik verwacht eigenlijk dan een “groene” container.

 



 

 

Dashboard:



type: vertical-stack

cards:

  - type: horizontal-stack

    cards:

      - type: picture-entity

        entity: sensor.afvalinfo_afval_voor_vandaag

        show_state: false

        name: Vandaag

        state_image:

          gft: /local/groen3.png

          papier: /local/blauw3.png

          restafval: /local/grijs3.png

          Groente Fruit en Tuinafval, Restafval: /local/duo3.png

          geen: /local/geen3.png

      - type: picture-entity

        entity: sensor.afvalinfo_afval_voor_morgen

        show_state: false

        name: Morgen

        state_image:

          gft: /local/groen3.png

          papier: /local/blauw3.png

          restafval: /local/grijs3.png

          Groente Fruit en Tuinafval, Restafval: /local/duo3.png

          geen: /local/geen3.png

  - type: glance

    entities:

      - entity: sensor.afvalinfo_groente_fruit_en_tuinafval

        name: GFT

      - entity: sensor.afvalinfo_restafval

        name: Restafval

      - entity: sensor.afvalinfo_papier

        name: Papier

 

 

 

Plaatjes in de www folder



 

Groen3.png



 

Geen3.png



 

Ik heb het vermoeden als er een “true” terugkomt dat het plaatje niet werkt. Bij een “false” werkt het wel.

 

Mvg

Ron

 

 

Van: heyajohnny ***@***.***> 
Verzonden: maandag 1 augustus 2022 22:28
Aan: heyajohnny/afvalinfo ***@***.***>
CC: janss028 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] Gemeente Venlo werkt niet meer (Issue #318)

 

Werkt het toevallig alweer? Ik heb vandaag nog een update van afvalinfo doorgevoerd, wellicht dat na de update het bij jou weer gaat werken. Laat maar weten of dit het probleem heeft opgelost.
