### ISSUE TITLE
Avalex?

### ISSUE THREAD

**Issue by joeblack2k** [heyajohnny/afvalinfo#319]
Error occurred. Please check the address with postcode: '2264JV' and huisnummer: '70''' on the website of your local waste collector in the gemeente: 'leidschendam'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

**Comment by heyajohnny** [comment]
Leidschendam is geen gemeente.
Probeer 'leidschendam' eens te veranderen naar 'leidschendam-voorburg'
