### ISSUE TITLE
Den Ham werkt niet

### ISSUE THREAD

**Issue by jov58** [heyajohnny/afvalinfo#32]
Als ik een geldige postcode/huisnummer uit Den Ham invul, krijg ik in HA 'Unknown' te zien. Iets uit Vriezenveen werkt wel. Beide plaatsen zijn uit dezelfde gemeente Twenterand en de geteste adressen werken wel in de invulkalender van ROVA. Komt dit misschien door de spatie in de plaatsnaam?

**Comment by heyajohnny** [comment]
Ik heb net een fix doorgevoerd.

Er is ook een Den Ham in Westerkwartier. Ik heb Den Ham in Westerkwartier hernoemd naar "Den Ham_"

Den Ham in Twenterand is gewoon "Den Ham" gebleven.
