### ISSUE TITLE
Papier sensor werkt niet meer voor de gemeente Raalte

### ISSUE THREAD

**Issue by CasparTheBridge** [heyajohnny/afvalinfo#321]
De papier sensor heeft een jaar goed gewerkt maar sinds een aantal maanden werkt deze helaas niet meer goed, ik denk dat dit gestopt is te werken sinds versie v1.0.7

De overige data komt wel goed binnen.
Papier is nog steeds wel beschikbaar als data om op te halen: https://inzamelkalender.rova.nl/nl/8141aj/33/a/

Is er eventueel andere informatie die ik kan aanleveren?

Mogelijk is de fix die bij dit issue was gemaakt er weer uitgegaan? https://github.com/heyajohnny/afvalinfo/issues/188

**Comment by heyajohnny** [comment]
Ze hebben bij Rova blijkbaar besloten om 'papier' voortaan 'pd' te noemen. Ik heb zojuist een nieuwe versie gepushed. Laat maar weten of de papier sensor weer werkt.

**Comment by CasparTheBridge** [comment]
Pfff, tja op die manier houden ze iedereen lekker bezig 😪
Super dat je dit zo snel hebt opgepakt, ik ga het graag bekijken. Dank je wel!

**Comment by CasparTheBridge** [comment]
Kan het misschien zijn dat het pushen van de nieuwe versie niet helemaal goed is gegaan? Ik zie nog geen nieuwe versie beschikbaar :)

**Comment by heyajohnny** [comment]
Back-end fix, zo hoeft er geen nieuwe front-end uitgerold te worden.
Dus hij zou al moeten werken.

**Comment by CasparTheBridge** [comment]
Ik zie het nu. Klopt inderdaad, ik heb de data weer voor papier.
Dank je wel!
