### ISSUE TITLE
Please update: Krimpen aan den IJssel

### ISSUE THREAD

**Issue by Antonvink** [heyajohnny/afvalinfo#323]
The 'gemeente' Krimpen aan den IJssel no longer uses afvalwijzer for collecting trash but is beginning this year switched to Cyclus.

See following url for an example address: https://afvalkalender.cyclusnv.nl/adres/2923AN:1

Thanks in advance.

**Comment by heyajohnny** [comment]
I've just pushed an update. Please let me know if all works as expected

**Comment by Antonvink** [comment]
Thank you very much, this issue has been resolved!
