### ISSUE TITLE
Few sensors available for afvalinfo

### ISSUE THREAD

**Issue by githubnoobjk** [heyajohnny/afvalinfo#324]
Ik krijg alleen waarden voor de sensor: sensor.afvalinfo_plastic_blik_en_drankkartons en de sensor 
sensor.afvalinfo_papier maar niet voor restafval en gft(2).

Mijn gemeente is Westerkwartier. De afgeleide sensoren zoals : sensor.afvalinfo_afval_voor_vandaag werken wel

**Comment by heyajohnny** [comment]
Sorry voor mijn late reactie. Heb je dit probleem nog steeds
Voor mijn testadres werken de sensors prima: (9351le 123)
Mocht je nog steeds problemen hebben, zou je mij dan een postcode + huisnummer kunnen geven waar dit probleem in voor komt?

**Comment by githubnoobjk** [comment]
Bedankt voor je reactie. Excuses zijn natuurlijk niet nodig. Je bent aan mij niets verplicht :) 
Helaas doet ook je test-adres het bij mij niet.
Ik heb afvalinfo verwijderd en opnieuw handmatig geinstalleerd. Via HACS bleef de download eindeloos doorgaan.
HACS ziet de integratie na download en restart van de server wel.
Ik heb geen idee waar het misgaat. In de logging zie ik niets, dus weet ook niet of de integratie loopt. De waarden (states) geven wel een update-tijd weer. Wat opvalt is dat de updatetijd voor [sensor.afvalinfo_groente_fruit_en_tuinafval] 14:21 uur is en de updatetijd voor [sensor.afvalinfo_afval_voor_vandaag]15:10 uur is (actuele tijd)
Dit is de bestandsstructuur : 
![image](https://user-images.githubusercontent.com/53235543/200328841-34c61c4a-65d0-42f4-a6e5-4cdb30c20690.png)
Dit is de code in sensors.yaml:
`- platform: afvalinfo
  resources:
    - type: gft
      friendly_name: Groente Fruit en Tuinafval
    - type: kerstboom
      friendly_name: Kerstboom
    - type: pbd
      friendly_name: Plastic Blik en Drankkartons
    - type: papier
      friendly_name: Papier
    - type: restafval
      friendly_name: Restafval
    - type: takken
      friendly_name: Takken
    - type: textiel
      friendly_name: Oude Kleding
    - type: trash_type_today
      friendly_name: Afval voor vandaag
    - type: trash_type_tomorrow
      friendly_name: Afval voor morgen
  diftarcode: ""
  location: westerkwartier
  postcode: 9351le
  streetnumber: 123
  streetnumbersuffix: ""
  dateformat: "%d-%m-%Y"
  locale: "nl"
  timespanindays: 365
  notrashtext: "geen"`

**Comment by heyajohnny** [comment]
> Wat opvalt is dat de updatetijd voor [sensor.afvalinfo_groente_fruit_en_tuinafval] 14:21 uur is en de updatetijd voor [sensor.afvalinfo_afval_voor_vandaag]15:10 uur is (actuele tijd)

De sensoren voor vandaag/morgen worden vaker ge-updated dan de verschillende afvaltype sensors, dus dat kan kloppen.
De bestandsstructuur klopt ook gewoon:
![image](https://user-images.githubusercontent.com/20553716/201035484-1234df26-ac6f-4b5e-814a-ea2869efb997.png)

> Dit is de code in sensors.yaml:
Je bedoelt zeker configuration.yaml?
De waardes die je hebt gepost kloppen, ik kan alleen niet zien of de tabs goed staan. Zo ziet het er bij mij uit:
![image](https://user-images.githubusercontent.com/20553716/201036584-e4e16059-0454-4fb6-9e4d-4a894ade6a2e.png)


Ik kan verder niets vreemds zien. Ik zou zeggen. Probeer de boel nog een keer te verwijderen en opnieuw te installeren en kopieer en plak desnoods de configuratie uit het [voorbeeld](https://github.com/heyajohnny/afvalinfo/blob/master/example/configuration.yaml)

**Comment by githubnoobjk** [comment]
Iik krijg nu inderdaad waarden omdat ik hem in configuration heb gezet.
Blijkbaar begrijp ik toch nog lang niet alles van Home Assistant.
Ik dacht dat de code ook in sensors.yaml kon omdat er sensors worden aangemaakt. 

In ieder geval heel erg bedankt voor je hulp.
