### ISSUE TITLE
Gemeente Maassluis toevoegen

### ISSUE THREAD

**Issue by nl0pvm** [heyajohnny/afvalinfo#327]
Zou je gemeente Maassluis willen toevoegen?

```
De grijze en oranje minicontainer wordt in de oneven weken geleegd en de groene minicontainer wordt in de even weken geleegd.
Hieronder staat op welke dag en in welke wijk dit gebeurt. 
Informatie over de inzameling van oud papier en karton leest u [hier](https://www.maassluis.nl/afval-oud-papier-en-karton).

Maandag: Drevenbuurt, Molenwijk, Zeeheldenbuurt, Dichtersbuurt en Wijk 't Hoofd
Dinsdag: Vogelwijk
Woensdag: Weverskade, Wilgenrijk, Vertowijk en Maasdijk
Donderdag: Sluispolder Oost, Zuidbuurt, Oranjewijk, Dalenbuurt, Componistenwijk en Koningshoek
Vrijdag: binnenstad/centrum
```

source: https://www.maassluis.nl/afval-huishoudelijk-afval

**Comment by jonteriele** [comment]
Plus 1! 
Zou top zijn als deze wordt toegevoegd.

**Comment by heyajohnny** [comment]
Ik wacht nog even tot begin volgend jaar voor het toevoegen van Maassluis. Wellicht dat ze dan nog op een ander systeem overstappen.

**Comment by wolfpins** [comment]
Zou fijn zijn als het zou lukken

**Comment by heyajohnny** [comment]
Ik ga hier binnenkort mee aan de slag. Dit implementeer ik dan ook gelijk voor de missende gemeentes met soortgelijke wijk informatie.

Houd er wel rekening mee dat deze kalender niet klopt op feestdagen, maar dat klopt op de site van de gemeente waar ik de informatie vandaan haal uiteraard ook niet.

Waarschijnlijk komt er een attribuut bij, genaamd: 'neighbourhood'

Ik laat weten wanneer ik dit ga implementeren

**Comment by heyajohnny** [comment]
Ik heb zojuist een nieuwe versie gemaakt (v1.0.10). Maassluis zou nu moeten werken.

**Comment by heyajohnny** [comment]
Ik neem aan dat maassluis nu goed werkt. Mocht dit niet het geval zijn, dan kan ik het issue altijd weer openen.

**Comment by wolfpins** [comment]
Hij geeft precies verkeerd om aan oneven weken grijze bak  even weken groene bak.

**Comment by heyajohnny** [comment]
@wolfpins welke wijk is dit?

**Comment by wolfpins** [comment]
Drevenbuurt, maar volgens mij is het zo voor heel Maassluis de ophaaldag klopt wel. Verzonden vanuit Mail voor Windows Van: heyajohnnyVerzonden: zondag 29 januari 2023 20:23Aan: heyajohnny/afvalinfoCC: wolfpins; MentionOnderwerp: Re: [heyajohnny/afvalinfo] Gemeente Maassluis toevoegen (Issue ***@***.*** welke wijk is dit?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by heyajohnny** [comment]
Ik had ze inderdaad omgewisseld (facepalm), maar ze zouden nu goed moeten staan. Wellicht dat je even je HA opnieuw moet opstarten voordat hij de nieuwe data weer ophaalt.

**Comment by wolfpins** [comment]
Bedankt Verzonden vanuit Mail voor Windows Van: heyajohnnyVerzonden: zondag 29 januari 2023 22:02Aan: heyajohnny/afvalinfoCC: wolfpins; MentionOnderwerp: Re: [heyajohnny/afvalinfo] Gemeente Maassluis toevoegen (Issue #327) Ik had ze inderdaad omgewisseld (facepalm), maar ze zouden nu goed moeten staan. Wellicht dat je even je HA opnieuw moet opstarten voordat hij de nieuwe data weer ophaalt.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by jonteriele** [comment]
Bedankt @heyajohnny. 

Voor de wijk Wilgenrijk is dit ook nog omgekeerd. Woensdag 1 feb komt de grijze bak.

Daarnaast vroeg ik me af. Ik zie nog geen data voor papier en karton. Kan dat kloppen?

**Comment by wolfpins** [comment]
Hij staat inderdaad nog niet goed ,

**Comment by heyajohnny** [comment]
hmm... Hij zou nu goed moeten staan. Kan iemand dat bevestigen?

**Comment by jonteriele** [comment]
Yes, Wilgenrijk klopt nu. 1 feb grijze bak! 👌🏼

**Comment by heyajohnny** [comment]
@jonteriele 

> Daarnaast vroeg ik me af. Ik zie nog geen data voor bijv. papier en karton. Kan dat kloppen?
Zoals je aan deze illustratie kan zien is dit eigenlijk niet te doen met de informatie die de gemeente Maassluis nu verstrekt... Enkele wijken zijn gelijk in het overzicht, maar de meerderheid komt niet overeen, of slechts gedeeltelijk.
![image](https://user-images.githubusercontent.com/20553716/215601651-39ee75e6-2c23-4664-959f-36bc69741f85.png)

**Comment by jonteriele** [comment]
@heyajohnny dat snap ik, jammer.

Als ik het goed begrijp zou het papier (gewoon) in het zelfde format als de rest moeten worden geplaatst. 
Ik gok dat dit een vraag aan de gemeente is wat een meerjarenplan gaat zijn.

**Comment by heyajohnny** [comment]
@jonteriele Ja daar komt het wel op neer. Ik woon niet in de gemeente maassluis, dus ik heb geen idee of bijvoorbeeld Drevenbuurt zich bevindt in Steendijkpolder Noord. Wellicht overlappen ze elkaar, geen idee. Maar omdat er hele andere namen voor de buurten worden gebruikt bij het ophalen van papier dan bij het overige afval kan ik hier niet zoveel mee, helaas.

**Comment by Dennisd80** [comment]
Molenwijk lijkt nu ook omgedraaid te zijn, gft word de 20e geleegd en de grijzbak de 27e, staat nu andersom. Bestaat er ook een mogenlijkheid om cleanprofs (bak reiniging) toe te voegen?

**Comment by heyajohnny** [comment]
@Dennisd80 Ik zie het. Er zat inderdaad nog een bug in de code. Als het goed is zou het nu goed moeten blijven gaan. Cleanprofs wordt waarschijnlijk dit jaar nog toegevoegd. Je mag er alvast een issue voor aanmaken als je dat wil?

**Comment by Dennisd80** [comment]
Super, bedankt voor het snelle fixen. Ik zal straks even een issue aanmaken voor de cleanprofs intergratie

**Comment by Dennisd80** [comment]
Mhh het lijkt weer omgedraaid te zijn voor de molenwijk

**Comment by heyajohnny** [comment]
Ahh, nu snap ik waarom ik er zoveel problemen mee heb...
Hij ziet zondag als eerste dag (dag 0) van de week, maar qua weeknummers is dat niet het geval, dan is maandag de eerste dag van de week.

![image](https://user-images.githubusercontent.com/20553716/219977866-c61196c4-b812-49d6-83fd-ac9db5dca3cb.png)
![image](https://user-images.githubusercontent.com/20553716/219977970-f2608d9c-1db5-4271-9425-378604d0878f.png)

Ik denk dat ik het nu gefixt heb (Fingers crossed)
