### ISSUE TITLE
PBD/PMD werkt niet voor gemeente Katwijk

### ISSUE THREAD

**Issue by YarneThatsMe** [heyajohnny/afvalinfo#328]
Vrij recent is de gemeente Katwijk overgestapt van GFT en Rest, naar GFT, Rest en PBD/PMD. Ik heb sinds de aankondiging de sensor in HASS geactiveerd, maar deze staat de toevoeging van de sensor op "onbekend". Moet ik hiervoor nog iets wijzigen? Of ligt het aan de afvalinfo integratie?

Ik heb gewoon het voorbeeld overgenomen (en uiteraard naar mijn adres aangepast).

Als er nog info ontbreekt hoor ik het graag!

**Comment by heyajohnny** [comment]
Ik zie dat de URL is gewijzigd en dat daar ook PMD bij is gekomen. De oude URL die ik nog gebruik heeft nog geen PMD data. Ik zal binnenkort eens kijken of ik dit om kan bouwen naar de nieuwe URL

**Comment by heyajohnny** [comment]
Ik heb zojuist een update doorgevoerd. Als het goed is zou PMD nu ook moeten werken.

**Comment by YarneThatsMe** [comment]
Ik kan bevestigen dat het werkt, bedankt!
