### ISSUE TITLE
Info op scherm blijft draaien 

### ISSUE THREAD

**Issue by Puchrider** [heyajohnny/afvalinfo#329]
Hallo
Ik heb home assistent draaien op mijn NAS.
Hierop draait Afvalinfo.
Sinds een week worden de juiste datums niet weergegeven op het scherm, en blijft de blauwe ronde pijl maar draaien.
Heeft tot nu toe altijd correct gewerkt. 
Ben niet zelf degene die dit systeem onderhoud. Dit doet iemand voor mij via de PC.
Misschien wat tips of info hoe dit op te lossen.

**Comment by heyajohnny** [comment]
In welke gemeente woon je?

**Comment by Puchrider** [comment]
Hallo JohnnyIk woon in Schinveld, gemeente Beekdaelen.Groetjes Peter JoostenSent from Android deviceOp 27 nov. 2022 20:53 schreef heyajohnny ***@***.***>:
In welke gemeente woon je?

**Comment by heyajohnny** [comment]
Ik heb gisteren een update voor afvalverwerker RD4 (waar Beekdaelen ook onder valt) doorgevoerd. Waarschijnlijk zal je nu weer data binnen moeten krijgen.

**Comment by Puchrider** [comment]
Klopt.

Dankjewel Johnny

Groetjes Peter Joosten.

Op ma 28 nov. 2022 09:44 schreef heyajohnny ***@***.***>:
