### ISSUE TITLE
Ontbrekende module: bs4

### ISSUE THREAD

**Issue by jov58** [heyajohnny/afvalinfo#33]
Na installatie van HACS en (als eerste) Afvalinfo, kreeg ik een foutmelding dat module **bs4** ontbrak. Na wat speurwerk bleek de oplossing te zijn het volgende aan configuration.yaml toe te voegen (boven de afvalinfo sensor):

```
  - platform: scrape
     resource: https://www.home-assistant.io
     select: ".current-version h1"
```

Wellicht handig om op te nemen in de installatie info.

**Comment by heyajohnny** [comment]
Ik heb zojuist een aanpassing in de code gedaan in de requirements. Waarschijnlijk is jouw oplossing dan niet meer nodig. Zou je dit misschien willen testen?

**Comment by jov58** [comment]
Ik weet te weinig van HA om zeker te zijn dat dit een goede test is, maar ik heb het volgende gedaan:

- platform scrape uit configuration.yaml verwijderd
- platform afvalinfo uit configuration.yaml verwijderd
- Afvalinfo via HACS verwijderd
- HA opnieuw opgestart
- Afvalinfo via HACS geinstalleerd
- platform afvalinfo aan configuration.yaml toegevoegd
- HA opnieuw opgestart

Ik zie nu geen meldingen over bs4 meer.

**Comment by heyajohnny** [comment]
Andere componenten gebruiken hetzelfde principe als ik nu heb doorgevoerd.

Ik ga er vanuit dat het is opgelost en sluit de issue. Bedankt voor het testen!
