### ISSUE TITLE
Status "unknown"

### ISSUE THREAD

**Issue by renejorissen** [heyajohnny/afvalinfo#330]
hallo,

Het lijkt erop dat alle sensoren vanaf december de status unknown teruggeven voor afvalverwerker RD4. Is dit een bekend issue?

<img width="921" alt="afvalinfo" src="https://user-images.githubusercontent.com/39612564/203998520-e8521808-fe80-4152-984b-9a25c9257e04.png">

**Comment by RayMoonen** [comment]
Same here.
When I go to the URL (http://trashapi.azurewebsites.net/trash?Location={0}&ZipCode={1}&HouseNumber={2}&HouseNumberSuffix={3}&DiftarCode={4}) and enter my address it only gives back 'GFT' date, so I guess there's something going on with the API or the trash collector information.

**Comment by GertJanArts** [comment]
@heyajohnny same here for 'restafval' (Land van Cuijk)
![1](https://user-images.githubusercontent.com/20320533/204155295-69df0a6b-a0d8-42ef-ba7c-83a24e3f3d5d.png)

**Comment by heyajohnny** [comment]
Ik zag inderdaad dat de API van RD4 is aangepast. Ik heb zojuist een update doorgevoerd. Als het goed is zou alles weer moeten werken t/m het einde van het jaar

**Comment by GertJanArts** [comment]
@heyajohnny dank voor je snelle reactie, maar nu lijkt er helemaal geen data meer binnen te komen.
![1](https://user-images.githubusercontent.com/20320533/204157066-fecaf334-3d2c-46d6-9a99-fcf7c78bc43b.png)

**Comment by heyajohnny** [comment]
Auch... Er was iets fout gegaan bij het publishen. Waarschijnlijk werkt het nu wel.

**Comment by renejorissen** [comment]
Top, lijkt weer te werken. Thanks voor het snelle handelen!!

**Comment by RayMoonen** [comment]
Het werkt weer! Bedankt voor de snelle update!

**Comment by GertJanArts** [comment]
@heyajohnny helaas bij mij nog niet hoor...
![1](https://user-images.githubusercontent.com/20320533/204160759-cf3d3d03-9219-4c78-9a48-f08d2b735db0.png)
