### ISSUE TITLE
Status unknown bij restafval Land van Cuijk

### ISSUE THREAD

**Issue by GertJanArts** [heyajohnny/afvalinfo#331]
@heyajohnny: Er gaat nog iets fout bij het afvalschema van Land van Cuijk. De restafval sensor wordt niet goed weergegeven.
![1](https://user-images.githubusercontent.com/20320533/204164653-a327d380-00f1-434a-bff5-d3fcdad46c51.png)

**Comment by heyajohnny** [comment]
Heb je misschien een postcode huisnummer combinatie waarin dit probleem voorkomt. Bij mijn testadres 5432BW 1 lijkt het goed te werken.

**Comment by GertJanArts** [comment]
@heyajohnny jazeker bijvoorbeeld  5443CA 10

**Comment by heyajohnny** [comment]
Dat is vreemd... Bij mij geeft hij voor de restafval gewoon data terug:
![image](https://user-images.githubusercontent.com/20553716/204233420-034c2e4f-7d06-4a21-86b3-2352109dec34.png)

**Comment by GertJanArts** [comment]
@heyajohnny Dank voor het uitzoeken! Inderdaad vreemd. Het lijkt nu wel te werken... 
![image](https://user-images.githubusercontent.com/20320533/204236688-d8107687-226c-430b-a235-ed1200329fd6.png)
