### ISSUE TITLE
Error with location Venlo

### ISSUE THREAD

**Issue by Skevdude** [heyajohnny/afvalinfo#332]
Having some problems setting this up for the gemeente "venlo".

This is the error i get:

`Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/trashapi.py:75
Integration: afvalinfo (documentation, issues)
First occurred: 00:35:51 (1 occurrences)
Last logged: 00:35:51

Error occurred. Please check the address with postcode: '5924AW' and huisnummer: '22''' on the website of your local waste collector in the gemeente: 'venlo'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working`

Can you please help me?

**Comment by heyajohnny** [comment]
Looks like it's working just fine:
![image](https://user-images.githubusercontent.com/20553716/205328911-cf9eabfd-69b6-4c17-8d17-6f6bbf191a15.png)

Do you still have problems with this address? Sometimes for some locations they daily update/reboot the API so it could be offline for some minutes. Please let me know if it works or not.

**Comment by Skevdude** [comment]
Working now indeed. Thank you for your reply.
