### ISSUE TITLE
Gemeente Landsmeer

### ISSUE THREAD

**Issue by cpprofs** [heyajohnny/afvalinfo#335]
https://landsmeer.afvalinfolijn.nl/login

**Comment by heyajohnny** [comment]
Note to myself:

1121JJ 1:

1:
https://landsmeer.afvalinfolijn.nl/login
POST
![image](https://user-images.githubusercontent.com/20553716/209404358-4dd35672-a845-4799-bf7e-47a6b605920f.png)

2:
https://landsmeer.afvalinfolijn.nl/portaal/kalender
POST
feb 2023 example:
![image](https://user-images.githubusercontent.com/20553716/209404769-1dda2aa4-a392-4779-a552-f15b0063c4cb.png)

**Comment by cpprofs** [comment]
Klopt het trouwens dat je niet meer dan 1 dag in de toekomst terug krijgt met de trashAPI?

**Comment by heyajohnny** [comment]
Per afvaltype krijg je de eerstvolgende ophaaldatum. 
Dus als de ophaaldatums voor gft 02-01-2023 en daarna 09-01-2023 is, krijg je vandaag (29-12-2022) alleen 02-01-2023 terug.
Dit is inderdaad maar 1 dag als je dat bedoeld.

**Comment by heyajohnny** [comment]
@cpprofs Ik heb zojuist landsmeer toegevoegd. Laat maar weten of alles werkt zoals verwacht

**Comment by heyajohnny** [comment]
Momenteel nog niet. Ik heb dit al wel gedeeltelijk geïmplementeerd voor enkele gemeentes waar dit voor mogelijk is, alleen moet ik alle gemeentes weer even nalopen, omdat er nog weleens wat veranderd. Voor landsmeer zou het wel mogelijk moeten zijn om dit te implementeren. Zou je er misschien een nieuw issue voor kunnen aanmaken? Dan kan dit issue met de officiële vraag om landsmeer toe te voegen afgesloten worden.
