### ISSUE TITLE
Gemeente Maashorst stopt met huidige afvalkalender 

### ISSUE THREAD

**Issue by hmmbob** [heyajohnny/afvalinfo#336]
Gaat per 2023 over naar https://www.deafvalapp.nl/calendar/kalender_start.jsp

Volgens die site gebruiken de volgende gemeentes deze app:

- Boekel 
- Echt-Susteren
- Helmond
- Land van Cuijk
- Maashorst
- Terneuzen

Zie https://www.gemeentemaashorst.nl/inwoners/afval/afvalkalender/

**Comment by freggel2** [comment]
> Gaat per 2023 over naar https://www.deafvalapp.nl/calendar/kalender_start.jsp
> 
> Volgens die site gebruiken de volgende gemeentes deze app:
> 
>     * Boekel
> 
>     * Echt-Susteren
> 
>     * Helmond
> 
>     * Land van Cuijk
> 
>     * Maashorst
> 
>     * Terneuzen
> 
> 
> Zie https://www.gemeentemaashorst.nl/inwoners/afval/afvalkalender/

Vandaar dat ik in Home Assistant geen nieuwe datums meer zie. Ik krijg nu bij GFT en papier "unknown" te zien.
Ik dacht, ach dat komt vanzelf goed Update van de afvalkalender en weer door. Maar niet dus.

**Comment by freggel2** [comment]
> Gaat per 2023 over naar https://www.deafvalapp.nl/calendar/kalender_start.jsp
> 
> Volgens die site gebruiken de volgende gemeentes deze app:
> 
>     * Boekel
> 
>     * Echt-Susteren
> 
>     * Helmond
> 
>     * Land van Cuijk
> 
>     * Maashorst
> 
>     * Terneuzen
> 
> 
> Zie https://www.gemeentemaashorst.nl/inwoners/afval/afvalkalender/

Aha, vandaar dat de afvalwijzer niet meer werkt helaas.
Hoe nu verder? Is er een alternatief voor Home Assistant?

**Comment by heyajohnny** [comment]
Ik heb zojuist alles omgezet naar de data van deafvalapp. Hierdoor zullen de laatste ophaaldagen van dit jaar helaas niet meer te zien zijn. De ophaaldagen van volgend jaar zijn nu al wel zichtbaar.

**Comment by hmmbob** [comment]
GFT, PBD en restafval werken, Papier niet:

![image](https://user-images.githubusercontent.com/33529490/209469524-534dc23f-6b85-44d3-93ab-f81da91e31eb.png)
![image](https://user-images.githubusercontent.com/33529490/209469532-9dcd4c8f-b61c-4836-84d2-418e59b9a035.png)

**Comment by freggel2** [comment]
Ooohh dank je. Het werkt weer (bijna) allemaal. Top gedaan.
En inderdaad, zoals hmmbob ook al beschreef, papier blijft op unknown staan.

**Comment by heyajohnny** [comment]
Als het goed is moet papier nu ook werken

**Comment by freggel2** [comment]
> 

Zojuist gecontroleerd op m'n home assistant. Papier werkt ook weer. Onwijs bedankt. I'm gonna buy you a coffee.

**Comment by heyajohnny** [comment]
@freggel2 Thnx! Dan ga ik er vanuit dat het werkt en sluit ik het issue. Mocht het toch niet werken, dan kan het issue altijd weer geopend worden.

**Comment by hmmbob** [comment]
Jep werkt hier ook weer prima! Dank!

**Comment by freggel2** [comment]
> @freggel2 Thnx! Dan ga ik er vanuit dat het werkt en sluit ik het issue. Mocht het toch niet werken, dan kan het issue altijd weer geopend worden.

Enig idee hoe ik je op een andere manier kan bedanken? Ik heb geen creditcard.

**Comment by heyajohnny** [comment]
@freggel2 Je hoeft me verder niet te bedanken. Ik doe dit vrijwillig en ben blij dat ik er soms andere mensen mee kan helpen. Je kan eventueel wat crypto doneren als je wilt. Ik heb zojuist nog wat updates doorgevoerd en in de [Readme](https://github.com/heyajohnny/afvalinfo) heb ik wat crypto adressen toegevoegd, maar voel je vooral niet verplicht om dit te doen. Ik kom niets te kort :)
