### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by petsch9** [heyajohnny/afvalinfo#338]
Hi, i get this error:
Error loading /config/configuration.yaml: 'utf-8' codec can't decode byte 0xb7 in position 2302: invalid start byte

I have homeassistant on a synolegy server
I created the pad [homeassistant]/config/ and copyed the map custom_components in it (downloaded from here) after that i copyed the example yaml to my own config yaml but no luck.
Please help to find what i am doing wrong.

of in het NED.
ik heb een map aangemaakt genaamd config in de root van homeassistant en in deze map het gehele (inclusief map zelf ) custom_components gepaste. In de config yaml de voorbeeld gepaste maar krijg bij config check de melding: Error loading /config/configuration.yaml: 'utf-8' codec can't decode byte 0xb7 in position 2302: invalid start byte
wat al raar is omdat de configuration.yaml in de root staat en niet in de map config.
Ik hoop dat iemand mij kan helpen, ik heb alles op synology nas.

Thanks peter

**Comment by heyajohnny** [comment]
Dit is inderdaad vreemd. Heb je al geprobeerd de configuration.yaml te verplaatsen naar de /config map?

**Comment by heyajohnny** [comment]
Ik ga er vanuit dat het probleem ondertussen is opgelost. Ik sluit dit issue.
