### ISSUE TITLE
Please add Arnhem / Suez

### ISSUE THREAD

**Issue by hansmets** [heyajohnny/afvalinfo#34]
Hi,

Could you add _Arnhem_ (including _Elden_ and _Schaarbergen_) to the code, I did test with this URL that is provided by Suez at https://inzamelwijzer.suez.nl/adres/ . 

On one of the sites of gemeente Arnhem this one was provided as alternative to the standard afvalwijzer. The syntax is identical to "Alphen aan de Rijn" so I used that as a template. I just changed the afvalstroom numbers to the correct one and it is working.

Hans

**Comment by GitHubxtsnl** [comment]
Looking for this feature to for city Arnhem :-) Willing to help testing if requried.

**Comment by FelixHunteler** [comment]
Arnhem +1
Also willing to test voor Arnhem - North/East region (zip 6824PK)  :-)
TIA

**Comment by heyajohnny** [comment]
I've just added Arnhem. Please let me know if it's working... Enjoy :)

**Comment by FelixHunteler** [comment]
ga gelijk aan de slag ;-)
  
  
   je hoort van me; thnx!!
  
  
   
    Op 18 maart 2020 22:49 schreef heyajohnny <notifications@github.com>:
   
   
    
   
   
    
   
   
   I've just added Arnhem. Please let me know if it's working... Enjoy :)

**Comment by FelixHunteler** [comment]
Arnhem shows PBD and GFT :-) Great job.
Can you please add "papier en karton" as resource?

**Comment by hansmets** [comment]
> Arnhem shows PBD and GFT :-) Great job.
> Can you please add "papier en karton" as resource?

It is working for me, but Arnhem has suspended the collection of paper the next few weeks as volunteers are running this service. I had to change the value of _timespanindays_ to  something longer (from 30 to 90 in my case).

**Comment by hansmets** [comment]
Thanks, Johnny, no issues sofar.

**Comment by heyajohnny** [comment]
Oke, thnx! Seems like it's working oke... I'll close the issue.
If there are any problems please reopen the issue or create a new one

**Comment by GitHubxtsnl** [comment]
> I've just added Arnhem. Please let me know if it's working... Enjoy :)

I've also tested the update and the GFT, Pud Papier and PBD work fine, the Rest Afval, Textiel and Vandaag en Vandaag2 do not provide any dates back, see sceenshot below.
![image](https://user-images.githubusercontent.com/43134674/77148050-0978ca00-6a8f-11ea-8a40-ebcc3087b46a.png)

**Comment by heyajohnny** [comment]
@GitHubxtsnl 
Textiel will never show data

According to the site of Suez: 
**Textiel**
Inzameling
U kunt uw textiel droog en in gesloten zakken aanbieden in de speciaal daarvoor bestemde containers of breng het naar de milieustraat in uw gemeente. Ook vinden er enkele malen per jaar aan huis inzamelacties plaats voor textiel. Voorafgaand aan een inzameling worden zakken huis aan huis verspreid.

**Restafval**
_Depending on where you live:_
U kunt uw rest afval kwijt in de ondergrondse container. U heeft hiervoor een Arnhem Afvalpas nodig om de container te openen.
_or:_
Restafval aanbieden in de grijze container. De container moet op de inzameldag om 07.00 uur met gesloten deksel en handvaten richting de weg worden aangeboden.
Wanneer restafval bij u wordt opgehaald, kunt u zien in uw persoonlijke afvalkalender.

Vandaag will only show data if there will be some garbage collection today.
Vandaag2 is probably trash_type_tomorrow and will only show data if there will be some garbage collection tomorrow
