### ISSUE TITLE
Gemeente Zutphen PBD

### ISSUE THREAD

**Issue by mlogemann** [heyajohnny/afvalinfo#340]
De sensor voor plastic metaal en drank werkt niet in de gemeente Zutphen. Andere afvalstromen doen het wel.

**Comment by heyajohnny** [comment]
Ik zie het al. In Zutphen heet het ZWARTKRA (zwarte krat). Ik heb zojuist de pbd gekoppeld hieraan. Als het goed is zou je nu data moeten krijgen voor de pbd sensor.

**Comment by mlogemann** [comment]
Wauw! Wat een snelle service! Bedankt. Het werkt inderdaad.
