### ISSUE TITLE
Meerlanden geen kerstboom datum

### ISSUE THREAD

**Issue by ErikVet** [heyajohnny/afvalinfo#345]
Ik heb geen datum voor het ophalen van de kerstboom meer, hij geeft "onbekend"
op de site van de meerlanden (haarlemmermeer) staat dat ze 11 januari in onze wijk komen (2134VA23)
Naar mijn weten deed ie het in het verleden gewoon.
De rest doet het gewoon.

**Comment by heyajohnny** [comment]
Bedankt voor het melden. Dit heeft er nooit ingezeten, maar ik heb het zojuist toegevoegd.
Zou je kunnen laten weten of het werkt? (En dan gelijk het issue kunnen sluiten (als het werkt)).

**Comment by ErikVet** [comment]
Goeden Avond

Het werkt.
***@***.***
Bedankt voor de snelle actie,
Ik zal de issue in de loop van de avond afsluiten

MVG Erik Vet

Van: heyajohnny ***@***.***>
Verzonden: donderdag 5 januari 2023 11:47
Aan: heyajohnny/afvalinfo ***@***.***>
CC: ErikVet ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] Meerlanden geen kerstboom datum (Issue #345)


Bedankt voor het melden. Dit heeft er nooit ingezeten, maar ik heb het zojuist toegevoegd.
Zou je kunnen laten weten of het werkt? (En dan gelijk het issue kunnen sluiten (als het werkt)).

**Comment by heyajohnny** [comment]
Top! Ik sluit hem zelf wel even

**Comment by ErikVet** [comment]
Ok
Bedankt
Prettige avond

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: heyajohnny ***@***.***>
Verzonden: Thursday, January 5, 2023 5:41:08 PM
Aan: heyajohnny/afvalinfo ***@***.***>
CC: ErikVet ***@***.***>; Author ***@***.***>
Onderwerp: Re: [heyajohnny/afvalinfo] Meerlanden geen kerstboom datum (Issue #345)


Closed #345<https://github.com/heyajohnny/afvalinfo/issues/345> as completed.
