### ISSUE TITLE
Toevoegen jaarkalender TrashAPI

### ISSUE THREAD

**Issue by cpprofs** [heyajohnny/afvalinfo#346]
Hierbij een nieuwe issue om het mogelijk te maken om via de trashapi ook een jaarkalender op te vragen in plaats van alleen de eerst volgende datum per afvaltype.

**Comment by xtrmenl** [comment]
Not hijacking the topic, but I assume you automatically created events from the next pickup dates 
To import them in the local calendar integration
https://www.home-assistant.io/integrations/local_calendar/

I would like to see this as well, to further ease the use of automations (less coding)

**Comment by heyajohnny** [comment]
@cpprofs Ik zal over enkele dagen kijken hoe ik dit kan realiseren. Eerst wil ik nog even enkele gemeentes toevoegen, voordat ik hiermee aan de slag ga.
@xtrmenl I'll see what I can do

**Comment by heyajohnny** [comment]
Ik heb zojuist een update doorgevoerd, waarbij het attribuut 'whole_year_dates' alle datums vanaf nu tot einde van het jaar zou moeten bevatten (mits dit door gemeente ondersteund wordt). Hierbij moet wel de parameter 'getwholeyear' de waarde true bevatten. Zie [Readme](https://github.com/heyajohnny/afvalinfo#readme) voor meer info. Laat maar weten of dit werkt.

**Comment by xtrmenl** [comment]
getest (eerst updaten via hacs, na restart config aanpassen) 

mijn gft sensor geeft nu 
current state 
2023-02-01, 
Whole year dates
2023-02-01, 2023-02-15, 2023-03-01, 2023-03-15, 2023-03-29, 2023-04-12, 2023-04-26, 2023-05-10, 2023-05-24, 2023-06-07, 2023-06-21, 2023-07-05, 2023-07-19, 2023-08-02, 2023-08-16, 2023-08-30, 2023-09-13, 2023-09-27, 2023-10-11, 2023-10-25, 2023-11-08, 2023-11-22, 2023-12-06, 2023-12-20

**Comment by heyajohnny** [comment]
@xtrmenl Kan je hier wat mee, of had je iets anders in gedachten? Ik heb namelijk geen flauw idee hoe dat je de data in de  local_calendar zou moeten krijgen...

**Comment by xtrmenl** [comment]
Ik denk het wel, ik ga even wat experimenteren. Heb al hier en daar wat gelezen wat het wellicht mogelijk maakt 
Dus zet het hier wel neer wat de conclusies zijn

**Comment by heyajohnny** [comment]
Ik sluit het issue. De initiële vraag is voorzien van een oplossing. Mochten er nog variaties  hierop wenselijk zijn, dan kan er altijd een nieuw issue geopend worden.
