### ISSUE TITLE
wijziging afvaldienst gemeente Echt-Susteren

### ISSUE THREAD

**Issue by IGastel** [heyajohnny/afvalinfo#348]
de gemeente Echt-Susteren heeft besloten in al haar wijsheid om van afvaldienst te veranderen.
sinds 1 januari word het afval opgehaald door de firma RWM.  ik weet niet of de firma RWM compatible is met deze integratie.
postcode: 6102EB nr.: 50

met vriendelijke groet,
Ivo

**Comment by heyajohnny** [comment]
Notitie aan mezelf:
[Beek](https://www.rwm.nl/inwoners/gemeente/beek)
[Beekdaelen](https://www.rwm.nl/inwoners/gemeente/beekdaelen)
[Echt-Susteren](https://www.rwm.nl/inwoners/gemeente/echt-susteren)
[Sittard-Geleen](https://www.rwm.nl/inwoners/gemeente/sittardgeleen)
[Stein](https://www.rwm.nl/inwoners/gemeente/stein)

**Comment by heyajohnny** [comment]
Ik heb zojuist een update doorgevoerd. Als het goed is zou echt-susteren weer moeten werken. Laat maar weten of alles werkt zoals verwacht.

**Comment by IGastel** [comment]
Ja! Het werkt weer. Bedankt voor alle tijd en energie die jij moet steken in het maken/ onderhouden en installatiehulp van deze integratie
