### ISSUE TITLE
BAR Ridderkerk heeft nieuwe app

### ISSUE THREAD

**Issue by 0xi3** [heyajohnny/afvalinfo#349]
Hallo,

De BAR in Ridderkerk heeft een nieuwe app. Hierdoor lijkt het dat de datums niet meer worden bijgewerkt. Oud papier geeft nu “onbekend”.

Is het mogelijk om na te kijken of deze nieuwe app nog steeds wordt uitgelezen?

Thanks alvast!

**Comment by heyajohnny** [comment]
Met dit adres in Ridderkerk werkt het nog gewoon: 2983SB 1

**Comment by 0xi3** [comment]
Ik heb het gecheckt, daar werkt het bij mij ook mee. Dan wacht ik wel af tot ie de oud papier data wel aanvult. 

Dank in elk geval.
