### ISSUE TITLE
afvalinfo not working for "het hogeland"

### ISSUE THREAD

**Issue by JW-ZK** [heyajohnny/afvalinfo#350]
Thanks for this amazing HA integration! While it was working perfectly before, it seems that it is currently broken for "het hogeland". Very likely, this is due to a change in the waste collector and/or a change in the way the waste collection info is published by the municipality. It would be awesome if this could be fixed!

**Comment by nagelkem** [comment]
Idem voor Opsterland

**Comment by HuismAndre** [comment]
Idem voor Harlingen.

**Comment by heyajohnny** [comment]
Ik zie dat omrin hun api heeft aangepast. Ik zal morgen kijken of ik dit weer recht kan trekken

**Comment by HuismAndre** [comment]
Top. Alvast bedankt.

**Comment by richardboezerooij** [comment]
Idem voor Leeuwarden.

**Comment by heyajohnny** [comment]
Ik heb zojuist een update doorgevoerd. Kunnen jullie laten weten of alles werkt? Mocht er een afvaltype missen, dan graag even laten weten welk afvaltype je mist en het liefst een postcode + huisnummer(, maar eventueel alleen een gemeente is ook prima).

**Comment by richardboezerooij** [comment]
Het werkt weer, bedankt! (Leeuwarden)

**Comment by fiskie-nl** [comment]
> Ik heb zojuist een update doorgevoerd. Kunnen jullie laten weten of alles werkt? Mocht er een afvaltype missen, dan graag even laten weten welk afvaltype je mist en het liefst een postcode + huisnummer(, maar eventueel alleen een gemeente is ook prima).

Na herstart van HA werkt het hier ook weer perfect (tietjerksteradeel), bedankt!

**Comment by HuismAndre** [comment]
Ook hier alles na een herstart weer prima. Bedankt.

**Comment by alwineizema** [comment]
> > Ik heb zojuist een update doorgevoerd. Kunnen jullie laten weten of alles werkt? Mocht er een afvaltype missen, dan graag even laten weten welk afvaltype je mist en het liefst een postcode + huisnummer(, maar eventueel alleen een gemeente is ook prima).
> 
> Na herstart van HA werkt het hier ook weer perfect (tietjerksteradeel), bedankt!
> 
> Edit: de haaldata komen voor mijn gemeente (tietjerksteradeel) helaas niet meer overeen met de app van Omrin zelf, alles loopt in afvalinfo 1 dag voor op de daadwerkelijke datum (bijvoorbeeld papier op 25-1 terwijl dat op 26-1 wordt gehaald).

Bedankt voor het repareren van de integratie met Omrin! Hij doet het inderdaad weer, maar ook bij mij loopt het schema één dag voor.

**Comment by ariekraakjr** [comment]
Zojuist even de update geinstalleerd. Hier ook een dag verschil.

**Comment by HuismAndre** [comment]
Aah. Nooit naar de daadwerkelijke data gekeken maar inderdaad, ook hier een dag te vroeg.

**Comment by JW-ZK** [comment]
> Ik heb zojuist een update doorgevoerd. Kunnen jullie laten weten of alles werkt? Mocht er een afvaltype missen, dan graag even laten weten welk afvaltype je mist en het liefst een postcode + huisnummer(, maar eventueel alleen een gemeente is ook prima).

Ik zou graag de geupdatete versie installeren - misschien een domme vraag, maar waar kan ik die vinden? Ik zie geen recente veranderingen in de versie op github. Alvast dank!

**Comment by heyajohnny** [comment]
@JW-ZK Als het goed is zie je inderdaad geen veranderingen. Voor deze wijzigingen hoef ik alleen maar de back-end aan te passen, waardoor er geen nieuwe versie voor HA uitgerold hoeft te worden. 

Dit scheelt mij een hoop werk, doordat er geen issues binnenkomen van mensen met oude versies.
Ik zal vanavond even kijken waarom de datum een dag verkeerd loopt. Zal waarschijnlijk wel iets met een UTC en lokale tijd te maken hebben.

**Comment by JW-ZK** [comment]
> @JW-ZK Als het goed is zie je inderdaad geen veranderingen. Voor deze wijzigingen hoef ik alleen maar de back-end aan te passen, waardoor er geen nieuwe versie voor HA uitgerold hoeft te worden.
> 
> Dit scheelt mij een hoop werk, doordat er geen issues binnenkomen van mensen met oude versies. Ik zal vanavond even kijken waarom de datum een dag verkeerd loopt. Zal waarschijnlijk wel iets met een UTC en lokale tijd te maken hebben.

Okay! Helder, dank voor je reply. Het is echter dan zo dat de integratie niet goed lijkt te werken voor "het Hogeland", ook na een herstart van HA. Als je toch de integratie onder handen neemt dan wordt het erg gewaardeerd als je hier ook even na zou kunnen kijken!

**Comment by heyajohnny** [comment]
Ik heb zojuist weer een update doorgevoerd. Ik zou verwachten dat de data nu wel goed moet zijn, (maar in mijn vorige test stond ook alles prima.)

**Comment by richardboezerooij** [comment]
> Ik heb zojuist weer een update doorgevoerd. Ik zou verwachten dat de data nu wel goed moet zijn, (maar in mijn vorige test stond ook alles prima.)

Helaas, na herstart nog steeds een dag te vroeg.

**Comment by ariekraakjr** [comment]
Hier ook nog steeds een dag te vroeg. (Leeuwarden)

**Comment by heyajohnny** [comment]
Hij zou nu goed moeten zijn (fingers crossed)

**Comment by ariekraakjr** [comment]
Hij gaat goed. Koffie?

**Comment by HuismAndre** [comment]
Klopt hier ook weer. Bedankt.

**Comment by richardboezerooij** [comment]
> Hij zou nu goed moeten zijn (fingers crossed)

Hier gaat het ook weer goed. Thanks!

**Comment by heyajohnny** [comment]
> Hij gaat goed. Koffie?
Whisky ;)

Ik sluit het issue, Thnx voor het testen @ariekraakjr @HuismAndre  @richardboezerooij @alwineizema @JW-ZK @nagelkem @fiskie-nl
