### ISSUE TITLE
Haaksbergen toevoegen 2025

### ISSUE THREAD

**Issue by doosterkamp** [heyajohnny/afvalinfo#351]
Postal code 7482 (Haaksbergen) has no results.

**Comment by HFeenstra** [comment]
See #350
Please close this ticket, since this looks like an issue with " Omrin" -  API.
@heyajohnny is trying to fix the issue the coming days

**Comment by doosterkamp** [comment]
@HFeenstra: Checking my postal code on the Omrin site has no results either, as they aren't our waste collector! So this probably is an other issue.

**Comment by heyajohnny** [comment]
I think that Haaksbergen is not going to work for this year. They switched to a pdf with districts and the current API doesn't give any trash data back.
Maybe you can check your address on: https://www.twentemilieu.nl/haaksbergen/afval/afvalkalender

But I think they just went back to nineteen flintstones with their Pdf :(
![image](https://user-images.githubusercontent.com/20553716/213915370-90a53a92-b122-45f9-8f12-4a236326c088.png)
![image](https://user-images.githubusercontent.com/20553716/213915483-54065653-2878-4fd8-9688-5421ffbdebee.png)

**Comment by HFeenstra** [comment]
> I think that Haaksbergen is not going to work for this year. They switched to a pdf with districts and the current API doesn't give any trash data back. Maybe you can check your address on: https://www.twentemilieu.nl/haaksbergen/afval/afvalkalender
> 
> But I think they just went back to nineteen flintstones with their Pdf :( ![image](https://user-images.githubusercontent.com/20553716/213915370-90a53a92-b122-45f9-8f12-4a236326c088.png) ![image](https://user-images.githubusercontent.com/20553716/213915483-54065653-2878-4fd8-9688-5421ffbdebee.png)

Too bad!

**Comment by heyajohnny** [comment]
Maybe the'll change it next year
