### ISSUE TITLE
Ooststellingwerf 8431 Omrin out of sync

### ISSUE THREAD

**Issue by xtrmenl** [heyajohnny/afvalinfo#354]
I noticed today that the afvalkalender is out of sync for 1 day 
So it shows today whereas it should instead state the date of tomorrow
Also future dates are one day early 

Probably something changed from Omrin side

**Comment by heyajohnny** [comment]
Should be fixed now

**Comment by heyajohnny** [comment]
#352

**Comment by xtrmenl** [comment]
Works like a charm ones again. Thanks
