### ISSUE TITLE
het hogeland toevoegen 2024

### ISSUE THREAD

**Issue by JW-ZK** [heyajohnny/afvalinfo#355]
Omdat de vorige threat hierover gesloten is meld deze nogmaals: ook na de laatste update werkt de integratie nog niet goed voor "het hogeland" (ook vieze geit geeft een foutmelding voor mijn adres). Alvast mijn dank!

**Comment by heyajohnny** [comment]
Heb je wellicht een postcode en huisnummer voor mij waarbij het niet goed gaat?

**Comment by heyajohnny** [comment]
Ik zie dat hij het met dit adres niet doet: 9781HJ 4.
En ik ben bang dat het ook niet gaat werken: [Gemeente Het Hogeland](https://hethogeland.nl/afval/afvalkalender)
![image](https://user-images.githubusercontent.com/20553716/214708406-78716736-e17d-41aa-a253-7411c2238e0a.png)
Ik krijg gewoon geen data binnen via de Omrin API, op het bovenstaande adres.

**Comment by bartjackbakker** [comment]
Hallo,

Hier het zelfde probleem met het Hogeland. 
Er staat mij iets bij dat de gemeente voorheen zelf een kalender had en nu doorverwijst naar omrin.

**Comment by heyajohnny** [comment]
Helaas zit het er voor dit jaar niet meer in om 'het hogeland' toe te kunnen voegen. Wellicht dat de gemeente volgend jaar weer een andere beslissing neemt, zodat de data weer beschikbaar is. 

Het enige wat je nog zou kunnen doen is om de gemeente te vragen om de afvalkalender via de Omrin afval-app beschikbaar te maken(, dan zou in theorie hun API weer data moeten bevatten die ik weer in afvalinfo kan gebruiken)

**Comment by heyajohnny** [comment]
Helaas zit het er voor dit jaar niet meer in om 'het hogeland' toe te kunnen voegen. Wellicht dat de gemeente volgend jaar weer een andere beslissing neemt, zodat de data weer beschikbaar is. 

Het enige wat je nog zou kunnen doen is om de gemeente te vragen om de afvalkalender via de Omrin afval-app beschikbaar te maken(, dan zou in theorie hun API weer data moeten bevatten die ik weer in afvalinfo kan gebruiken)

(Voor nu verander ik de issue naam naar 'het hogeland toevoegen 2024')

**Comment by HinkZk** [comment]
Wil iedereen vragen om ook een bericht te sturen aan gemeente@hethogeland.nl met het verzoek om deze data weer te delen met Omrin. Hopelijk zijn er voldoende die een melding willen doen zodat het opnieuw overwogen wordt.

Dank! :)

**Comment by HinkZk** [comment]
Reactie van de gemeente:

--
De Omrin app hebben wij als Gemeente Het Hogeland nooit in gebruik gehad / afgenomen en werkte normaal gesproken ook niet met data van de Gemeente Het Hogeland. Mogelijk had Omrin de data niet goed afgeschermd. We hebben geen voornemens om op korte termijn de app van Omrin in gebruik te nemen.

Ik vertrouw erop u hiermee voldoende geïnformeerd te hebben.

Maar als u nog vragen heeft, aarzel dan niet om contact op te nemen.

Met vriendelijke groet,
--

@heyajohnny, kennelijk is de informatie voor 2022 op een andere verkregen? Kan ik je geen bestand sturen met opmaak zodat we alsnog voor het Hogeland de info hebben? :)

**Comment by heyajohnny** [comment]
@HinkZk 
Dat is jammer. Hiervoor haalde ik de data via hun (Omrin) website op. Deze website werd nog weleens aangepast, waardoor ik ook weer aanpassingen door moest voeren. De laatste keer was enkele weken geleden. Ik heb geprobeerd om de code zo aan te passen dat het weer werkte, maar ze hebben de authorisatie zo aangepast, waardoor ik genoodzaakt was om over te stappen naar hun API. Als de gemeente niet mee wil werken, dan houdt het denk ik voor dit jaar helaas op :(

**Comment by HinkZk** [comment]
Spijtig, had gehoopt dat er nog opties zouden zijn buiten de gemeente om. Maar dan houdt het helaas op.

**Comment by bartjackbakker** [comment]
Persoonlijk denk ik dat het dan helemaal ophoud. De gemeente kennende zijn ze niet erg flexibel en komt er geen betere oplossing.Verzonden vanaf Outlook voor Android

**Comment by heyajohnny** [comment]
Ik zie dat het hogeland wat aanpassingen aan hun site hebben gedaan.
Zojuist heb ik 'gft' en 'restafval' gekoppeld. 'extra gft' heb ik niet gekoppeld, omdat je dat speciaal moet aanmelden bij de gemeente. Laat maar weten of alles weer werkt zoals verwacht, of dat ik misschien nog een afvaltype heb gemist (papier of pbd)

**Comment by bartjackbakker** [comment]
Heey,Geweldig nieuws. Ik heb hem direct getest en constateert dat alles weer naar behoren werkt.Nogmaals dank.Bart Bakker Verzonden vanaf Outlook voor Android

**Comment by heyajohnny** [comment]
@bartjackbakker Bedankt voor het testen. Ik hoop alleen dat ze niet te vaak dit soort aanpassingen zullen doen, maar we zullen zien. Voor nu werkt het weer. Ik sluit dit issue
