### ISSUE TITLE
Afvalinfo werkt niet meer voor gemeente bergen (egmond aan zee)

### ISSUE THREAD

**Issue by Nickerinus** [heyajohnny/afvalinfo#356]
De gemeente bergen/egmond aan zee heeft per 1 januari een nieuwe afvalverwerker genaamd BUCH in plaats van HVC.

Hopelijk kun je deze aanpassen.

Alvast dank.

**Comment by heyajohnny** [comment]
Ik heb zojuist bergen van hvc naar mijnafvalzaken omgezet. Als het goed is zou het weer moeten werken. Laat maar weten of dit ook daadwerkelijk zo is.

**Comment by Nickerinus** [comment]
Hi Johnny,

Hij werkt inderdaad weer.

Bedankt!
