### ISSUE TITLE
Gemeente Barendrecht, Albrandswaard Ridderkerk (BAR) over op andere kalender

### ISSUE THREAD

**Issue by P4tje** [heyajohnny/afvalinfo#357]
De gemeente Albrandswaard is vanaf 1 februari over op een nieuwe afvalkalender, waarbij de oude kalender komt te vervallen:
[https://www.bar-afvalbeheer.nl/afvalkalender-beschikbaar-in-nieuwe-app](url)

Dit is de nieuwe app:
[https://play.google.com/store/apps/details?id=nl.qubz21.burgerportaal.bar.prod](url)

De app is van dezelfde maker als die van RNM:
[https://play.google.com/store/apps/developer?id=21South](url)

Er is ook een online kalender, maar deze lijkt redelijk beperkt (niet mijn adres):
[https://21burgerportaal.mendixcloud.com/p/afvalbeheer/template/3940649674863417](url)

Hopelijk kan deze geïntegreerd worden, ieder geval bedankt voor het ontwikkelen van deze integratie!

**Comment by 0xi3** [comment]
Ik had deze ook toegevoegd een paar weken terug onder gemeente Ridderkerk (valt onder dezelfde app). De bekende datums bleven staan, daarom “werkte” de genoemde postcode toen nog wel. Ophaaldatum voorbij, nieuwe datum heeft “onbekend”.

https://github.com/heyajohnny/afvalinfo/issues/349

**Comment by heyajohnny** [comment]
Test adres: 3171AD 1 a

**Comment by 0xi3** [comment]
Geeft bij alle afvaltypen “onbekend” bij de datum

**Comment by heyajohnny** [comment]
@0xi3 Ja sorry, was eigenlijk bedoeld als notificatie voor mezelf. Barendrecht, Albrandswaard en Ridderkerk vallen inderdaad onder deze afvalverwerker.

**Comment by rononline** [comment]
Maar is het mogelijk om deze toe te voegen? @heyajohnny ??

**Comment by heyajohnny** [comment]
Ik heb zowel naar de app alsook naar de webpagina gekeken, maar dit is eigenlijk niet te doen. Ik zal contact met de afvalverwerker opnemen. Wellicht kunnen ze hun API vrijgeven, of toegankelijk maken voor derden.

**Comment by heyajohnny** [comment]
Kleine update. Zojuist een mail gestuurd naar BAR Afvalbeheer :sweat_smile::

> Beste,

> Ik ben software ontwikkelaar o.a. voor de Home Assistant integration genaamd [‘afvalinfo’](https://github.com/heyajohnny/afvalinfo). Het idee achter deze software is om voor zoveel mogelijk mensen in Nederland een afvalkalender beschikbaar te maken in Home Assistant, zodat zij hierop weer allerlei dingen kunnen automatiseren. Tot voor kort maakte BAR Afvalbeheer gebruik van de Ximmio API, waarbij de ophaaldagen van afval op postcode/huisnummer niveau uit te lezen was. Nu kreeg ik al van enkele mensen de [opmerking](https://github.com/heyajohnny/afvalinfo/issues/357) dat jullie per 1 februari overgestapt zijn naar een andere systeem (21burgerportaal). Nu is mijn vraag of het mogelijk is om de nieuwe API van 21burgerportaal uit te mogen/kunnen lezen, of dat dit wellicht beschikbaar gemaakt zou kunnen worden? 


> Met vriendelijke groet,

> Johnny Visser

**Comment by bolderbast** [comment]
Super, bedankt voor je moeite! Ik heb zelf ook een mail gestuurd, met de volgende inhoud. Hopelijk kunnen ze er wat mee...!

> Goedendag,
> 
> Recent is BAR Afvalbeheer overgestapt naar een nieuw systeem voor (onder andere) het aanbieden van de afvalkalender en daarbij behorende nieuwe mobiele app. Ik heb als inwoner van Albrandswaard op een aantal punten wat feedback, die ik graag wil delen zodat dit kan worden meegenomen om de dienstverlening te verbeteren:
> 
> 1. Integratie via API
> Voorheen was een API beschikbaar die externe softwareontwikkelaars in staat stelde om (onder andere) informatie t.a.v. de vuilnisophaaldagen uit te lezen. Voor mijn Smart Home gebruik ik de software "Home Assistant", en de volgende integratie maakt(e) het mogelijk om zaken te automatiseren m.b.t. de vuilnisophaaldagen: https://github.com/heyajohnny/afvalinfo. Van deze ontwikkelaar heb ik begrepen dat jullie nieuwe systeem (21burgerportaal) geen API aanbiedt. Dit is erg jammer, want daarmee vallen de BAR gemeenten nu in de ~2% van gemeenten waarvoor geen integratie mogelijk is. Niet iets om trots op te zijn, in mijn ogen. Kan dit wellicht (snel) worden aangepast?
> 
> <en dan nog 2 ongerelateerde punten>
> 
> Ik hoop dat jullie iets kunnen met deze feedback.
> 
> -- 
> Met vriendelijke groet / With kind regards,
> Patrick Dijkgraaf

**Comment by rononline** [comment]
Ik zie dat BAR de software 21south.nl is gaan gebruiken. Datzelfde doen ZRD, RMN en Maassluis bijvoorbeeld ook. En die staan wel in de ondersteunde lijst? Missen ze dan bij de BAR een module ofzo?

**Comment by heyajohnny** [comment]
@rononline Dit zijn helaas compleet andere omgevingen/API's/URL's.

**Comment by rononline** [comment]
Ik had ook een mail gestuurd, maar geen antwoord gekregen. Ik gok jullie verder ook niet?

**Comment by bolderbast** [comment]
Nee, ik ook nog niet. Ik heb er zojuist enev een belletje aan gewaagd. De vriendelijke telefoniste zou mijn mail (nogmaals) doorsturen naar de betreffende afdeling met de vraag om zsm te reageren. Fingers crossed!

**Comment by heyajohnny** [comment]
@rononline @bolderbast  Ik heb ook nog niets terug ontvangen.
@bolderbast Heb je naar een specifieke gemeente gebeld?
![image](https://user-images.githubusercontent.com/20553716/221153644-c8877e89-5125-4678-9a02-c9d526867743.png)
Ik kan dan nog wel een andere gemeente proberen te bellen.

**Comment by bolderbast** [comment]
Ik heb Albrandswaard gebeld. Nog niks terug gehoord.

**Comment by heyajohnny** [comment]
Ik heb er nog even over nagedacht en denk dat het beter is om direct de ontwikkelaars van het platform te benaderen. Daaropvolgend heb ik maar gelijk een mail verzonden naar de ontwikkelaars van het platform 21QUBZ/21burgerportaal. Ik denk dat we dan eerder een antwoord kunnen verwachten, in plaats van de gemeenten te benaderen die in dit geval een tussenschakel zijn.

> Beste,

> Mijn naam is Johnny Visser en ik ben software ontwikkelaar voor o.a. de Home Assistant integratie, genaamd ‘afvalinfo’. Het idee achter deze software is om voor zoveel mogelijk mensen in Nederland een afvalkalender beschikbaar te maken in Home Assistant, zodat zij hierop weer allerlei dingen kunnen automatiseren. Tot voor kort maakte B(arendrecht)A(lbrandswaard)R(idderkerk) Afvalbeheer gebruik van de Ximmio API, waarbij de ophaaldagen van afval op postcode/huisnummer niveau uit te lezen was. Nu kreeg ik van enkele mensen de opmerking dat de gemeenten Barendrecht Albrandswaard en Ridderkerk overgestapt zijn op jullie platform 21QUBZ/21burgerportaal. Nu is mijn vraag of hiervoor een API beschikbaar is? Zo ja, zou ik deze dan aan mogen roepen om de afval ophaaldagen van Barendrecht, Albrandswaard en Ridderkerk weer beschikbaar te kunnen maken in mijn Home Assistant integratie.

> Met vriendelijke groet,

> Johnny Visser

**Comment by rononline** [comment]
Ik heb geprobeerd die te benaderen, en kreeg dit antwoord:

```
Goedemorgen,
 
Wij hebben net onderstaande email binnengekregen. Als u als inwoner een op of aanmerking hebt kunt u deze indienen bij de BAR afvalbeheer
 
AECF8E3B63BD480ABA614ED5482089C0.png
 
Met vriendelijke groet,
 
Servicedesk 21South
```

**Comment by heyajohnny** [comment]
Zojuist een mail terug van 21south. Conclusie is dat we contact met BAR op moeten nemen om dit te regelen.

> Beste Johnny,
> 
> BAR is inderdaad overgegaan op de 21south Inwoner App.
> 
> De betreffende data zijn van de BAR (gemeenten) en niet van 21south.
> 
> Deze data kunnen wij niet zomaar ter beschikking stellen, de BAR was naar mijn weten ook niet op de hoogte van het feit dat hun data voor dit doel gebruikt werd.
> 
> Wellicht is het een idee contact met de BAR op te nemen.

**Comment by heyajohnny** [comment]
Nogmaals gemaild naar bar afvalbeheer...

**Comment by bolderbast** [comment]
Nog steeds geen reactie ontvangen. Ik zal binnenkort nog weer eens bellen...

**Comment by bolderbast** [comment]
Vanochtend gebeld en zojuist de volgende reactie ontvangen via email:

_"We hebben op dit moment geen koppeling naar een publieke API. We zijn aan het kijken of we dit als wens door willen geven naar onze software bouwer van 21QUBZ (we hebben ca. 5 personen die soortgelijke wensen hebben)"_

Kortom, hoe meer mensen dit melden bij BAR, hoe meer kans we hebben dat ze dit gaan realiseren.

**Comment by 0xi3** [comment]
I’m in, heb je toevallig een specifiek mailadres van de BAR om dit te melden?

**Comment by bolderbast** [comment]
Nee, helaas. Gewoon info@bar-afvalbeheer.nl.

**Comment by P4tje** [comment]
> Vanochtend gebeld met BAR Afvalbeheer en zojuist de volgende reactie ontvangen via email:
> 
> _"We hebben op dit moment geen koppeling naar een publieke API. We zijn aan het kijken of we dit als wens door willen geven naar onze software bouwer van 21QUBZ (we hebben ca. 5 personen die soortgelijke wensen hebben)"_
> 
> Kortom, hoe meer mensen dit melden bij BAR, hoe meer kans we hebben dat ze dit gaan realiseren.

Meteen ook een mail gestuurd, had net al reactie.

In de mail geven ze aan bezig te zijn dit mogelijk te maken.

**Comment by heyajohnny** [comment]
@P4tje haha... Mij hebben ze nog nooit teruggemaild 😢 . Maar hopelijk krijgen we het via de officiële manier voor elkaar.

**Comment by 0xi3** [comment]
Mail teruggekregen:

Hartelijk dank voor uw e-mail.
 
We hebben op dit moment geen koppeling naar een publieke API.
We zijn aan het kijken of we dit als wens door willen geven naar onze software bouwer van 21QUBZ.
 
Ik hoop u voldoende te hebben geïnformeerd.

**Comment by JvdBBBB** [comment]
Ik heb dezelfde vraag gesteld. Kijken of er inmiddels een positieve reactie op komt.

**Comment by heyajohnny** [comment]
@JvdBBBB Top! Thnx

**Comment by stephansande** [comment]
> Mail teruggekregen:
> 
> Hartelijk dank voor uw e-mail.
> 
> We hebben op dit moment geen koppeling naar een publieke API. We zijn aan het kijken of we dit als wens door willen geven naar onze software bouwer van 21QUBZ.
> 
> Ik hoop u voldoende te hebben geïnformeerd.

Ik heb hetzelfde antwoord gekregen op deze vraag. Hopelijk wordt deze "wens" snel geïmplementeerd. De app is echt een achteruitgang.

**Comment by heyajohnny** [comment]
Als het goed is zou alles weer moeten werken

**Comment by 0xi3** [comment]
Gft heeft inderdaad weer een datum. De rest (nog) niet. Heb al herstart, wacht morgen even af :)

Thanks! Hebben de een nieuwe API gefixt? Of heb je het op een andere manier geregeld?

**Comment by heyajohnny** [comment]
Ja, dezelfde als voor RNM, alleen met een andere key. Degene van RMN was al een tijdje geleden gefixt, dus dacht laat ik eens even speuren naar BAR en toen kwam ik de andere key tegen. Helaas is het niet via de officiele weg gegaan, maar hopelijk blijft dit zo werken. Zojuist heb ik papier, pbd en rest ook toegevoegd, want die hebben een andere benaming dan bij RMN. Als het goed is zou het nu allemaal goed moeten staan

**Comment by 0xi3** [comment]
Ik zie het, werkt perfect!

**Comment by ashwin2101** [comment]
Bedankt allemaal, papier en gft zijn weer zichtbaar

**Comment by ToonzDev** [comment]
@heyajohnny Hi, I am Toonz, the developer of the afval app on the Eneco Toon thermostat. Good job on fixing the BAR interface. Are you ok if I use your trashapi for BAR users of my app as well?

**Comment by heyajohnny** [comment]
@ToonzDev Hi Toonz, of course you can use it, it's open and free. You probably already found it, but [Here](https://trashapi.azurewebsites.net/index.html) you can see all the endpoints and test it. Good luck!
