### ISSUE TITLE
Gemeente Eindhoven - niet volledig ondersteund

### ISSUE THREAD

**Issue by DutchJaFO** [heyajohnny/afvalinfo#358]
Dit is geen fout van de applicatie an sich, maar lijkt vooral aan de combinatie van Cure (de afvalverwerker) en Afvalinfo website te liggen.
Cure verwijst mij met mijn locatie mooi door, maar vervolgens is er alleen maar info over nabij gelegen glasbakken e.d. te vinden.

Dit is wat ik zie als ik mijn postcode/huisnummer invoer :
![image](https://user-images.githubusercontent.com/39138434/216761266-db2f4b58-4011-450c-bfa5-293d0882df92.png)

Dit suggereert dat de lokatie ook in deze add-on goed herkend wordt, maar dat er vervolgens geen zinnige informatie teruggeleverd wordt.

Er is een Cure-app volgens deze website :
https://www.cure-afvalbeheer.nl/afvalkalender/afvalkalender-eindhoven/
Maar ook deze geeft geen kalender data voor de ondergrondse rest-afvalconteiner en bovengrondse de papier-container op mijn lokatie.

**Comment by heyajohnny** [comment]
@DutchJaFO Ik denk dat je het beste contact op kunt nemen met de gemeente of met Cure afvalbeheer. Ik haal namelijk mijn gegevens ook gewoon van Cure en als het daar al niet goed staat, dan krijg ik het hier ook niet goed. Waarschijnlijk klopt er gewoon iets niet in de administratie van Eindhoven/Cure. 

Een andere optie die je kunt proberen is om een postcode huisnummer dicht in de buurt te gebruiken die wellicht wel werkt. 

Ik sluit dit issue weer, aangezien ik hier helaas niets aan kan doen :(

**Comment by DutchJaFO** [comment]
klopt. Heb het ook gemeld, maar dacht ik post het ook hier voor het geval anderen daar tegenaan lopen. Ik verwacht geen oplossing, want ik had een jaar geleden ook al gezien dat er geen datums stonden. Je zou denken dat ze het zelf ook wel zien daar bij Cure/Afvalinfo.
