### ISSUE TITLE
attributen voor restafval entiteit Land van Cuijk

### ISSUE THREAD

**Issue by GertJanArts** [heyajohnny/afvalinfo#359]
Het lijkt erop alsof de attributen voor restafval niet goed wordt opgehaald. Voor plastic en GFT werkt het wel.
Het betreft de gemeente "Land van Cuijk" postcode 5443
![image](https://user-images.githubusercontent.com/20320533/217220545-92418775-1452-4774-a450-7ca4595a48d9.png)
Dank

**Comment by heyajohnny** [comment]
@GertJanArts Voor de postcode 5443AB 4 zie ik voor aankomende week nog geen restafval op de officiele afvalkalender.
Het klopt dan dat je deze waarschijnlijk ook niet in afvalinfo ziet. Waarschijnlijk komt deze sensor vanzelf weer goed te staan zodra de gemeente de pagina weer ververst heeft:
https://www.gemeentelandvancuijk.nl/afvalkalender/5443AB/4
