### ISSUE TITLE
Cleanprofs

### ISSUE THREAD

**Issue by Dennisd80** [heyajohnny/afvalinfo#361]
Is het mogelijk om cleanprofs te integreren ?

**Comment by Didel** [comment]
@heyajohnny Waarschijnlijk moet dit wel te doen zijn. Het formulier op https://crm.cleanprofs.nl/search/planning is daar prima voor te gebruiken, het is alleen jammer dat de uitvoer volledige HTML is. Ik heb met een werkende postcode en huisnummer kunnen bevestigen dat dit (mits op de opgegeven postcode en huisnummer daadwerkelijk een CleanProfs abonnement is afgesloten) netjes de planning teruggeeft (in de div met class `.datatable-wrap`) :

```
POST /search/planning HTTP/1.1
Host: crm.cleanprofs.nl
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Content-Length: 31

zipcode=1234AB&street_number=123
```

(uiteraard moet `zipcode=1234AB&street_number=123` worden aangepast met juiste postcode / huisnummer combinatie).

**Comment by Laho19** [comment]
@Dennisd80  Heb je wellicht dit zelf al toegepast? Zo ja, hoe?

**Comment by heyajohnny** [comment]
Ik ga dit na mijn vakantie 18 mei oppakken en integreren. @Didel Thnx voor de extra info!
Heeft een van jullie toevallig een werkende postcode? (huisnummer kom ik zelf wel achter i.v.m. privacy)

**Comment by Laho19** [comment]
> Ik ga dit na mijn vakantie 18 mei oppakken en integreren. @Didel Thnx voor de extra info! Heeft een van jullie toevallig een werkende postcode? (huisnummer kom ik zelf wel achter i.v.m. privacy)

7642KB

**Comment by heyajohnny** [comment]
Ik heb zojuist een nieuwe versie uitgerold waarbij de Cleanprofs data geïntegreerd is.
Onder resources in je configuration.yaml moet je nog wel het onderstaande toevoegen, wil je de reinigingsdata voor gft en restafval willen kunnen zien.
```
- cleanprofsgft
- cleanprofsrestafval
```

Laat maar weten of alles werkt zoals verwacht

**Comment by CharlPels** [comment]
Werkt supper maar je mist er nog 1 cleanprofspbd hier maken ze namelijk ook de plastic bak schoon :)

**Comment by CharlPels** [comment]
Hoi,

is idd plc of beter PLC.

**Comment by heyajohnny** [comment]
@CharlPels Top! Dan zou het moeten werken

**Comment by Rocker20** [comment]
Chef top werk weer!! Cleanprofs ook toegevoegd, alleen nu valt mij op dat in de vakantie mijn container niet schoon gemaakt wordt volgens hun kalender. Echter staat deze wel in de schoonmaakdagen van home Assistant. Wil je eens kijken of je hier wat op kunt verzinnen?

**Comment by CharlPels** [comment]
Oke dus moet cleanprofsplc toevoegen?

**Comment by heyajohnny** [comment]
@CharlPels sorry mijn fout. Je hoeft niets aan te passen. CleanprofsPbd zou hem op moeten pakken, alleen was je ophaaldata nog gecached.

**Comment by Rocker20** [comment]
> @Rocker20 Als je mij een postcode kan geven, dan kijk ik even waarom dit bij jou niet klopt

7609ee

**Comment by Rocker20** [comment]
> @Rocker20 Als het goed is voegt hij de data nu niet meer toe

Top!! Hou het in de gaten als ik thuis kom😃

**Comment by Rocker20** [comment]
> @Rocker20 Als het goed is voegt hij de data nu niet meer toe

De vakantie is nu al verdwenen uit de attributen dus dat is mooi! Bedankt voor de moeite 😃

**Comment by heyajohnny** [comment]
Top! Volgens mij werkt dit nu goed. Ik sluit het issue

**Comment by Rocker20** [comment]
> Top! Volgens mij werkt dit nu goed. Ik sluit het issue

Meld me wel weer als nodig is 😉
