### ISSUE TITLE
Gemeente Noardeast-Fryslân en Dantumadiel 

### ISSUE THREAD

**Issue by gzoodsma** [heyajohnny/afvalinfo#364]
Deze twee gemeenten hebben een eigen afval ophaal dienst. Ook een eigen app, https://play.google.com/store/apps/details?id=nl.opzet.zcalendar.offalapp

**Comment by heyajohnny** [comment]
Volgens mij moeten deze al gewoon werken. Zie [hier](https://github.com/heyajohnny/afvalinfo#readme)

**Comment by gzoodsma** [comment]
Ik krijg er niets op binnen. Heb de entities er wel tussen staan in HA.
Volgende week vrijdag is de groene container aan de beurt, maar dat geeft
hij niet aan. Zie bijlage.



Op za 25 feb. 2023 09:55 schreef heyajohnny ***@***.***>:

**Comment by heyajohnny** [comment]
Voor postcode huisnummer 9104DT 2 in dantumadiel krijg ik gewoon data binnen:
![image](https://user-images.githubusercontent.com/20553716/221359292-a2a9314a-9775-4d65-8dcf-1200f09396ce.png)
