### ISSUE TITLE
Schiedam papier verkeerd

### ISSUE THREAD

**Issue by Marsarex** [heyajohnny/afvalinfo#365]
Hi Guys, ik heb de afvalinfo al een tijd meedraaien in m'n Home Assistant maar het valt me op dat papier structureel verkeerd staat.. Enige idee hoe dit kan? 

Thanks alvast!

sensor:
  - platform: afvalinfo
    id: thuis
    resources:
    - type: gft
      friendly_name: Groente Fruit en Tuinafval
    - type: pbd
      friendly_name: Plastic Blik en Drankkartons
    - type: papier
      friendly_name: Papier
    - type: trash_type_today
      friendly_name: Afval voor vandaag
    - type: trash_type_tomorrow
      friendly_name: Afval voor morgen
      location: "schiedam"
      postcode: "3124XJ"
      streetnumber: "XX"
      diftarcode: ''
      streetnumbersuffix: ''
      dateformat: '%d-%m-%Y'
      locale: 'nl'
      timespanindays: 365
      notrashtext: 'geen'

**Comment by heyajohnny** [comment]
Voor huisnummer 11 lijkt dit gewoon te kloppen:
![image](https://user-images.githubusercontent.com/20553716/221682947-59817301-7d70-4181-806d-527ea3ec9774.png)

**Comment by Marsarex** [comment]
Ja, rechts zie je de pagina van Irado en daar staat het ook goed.. Maar wanneer ik het in m'n home assistant laat zien, zegt ie dit : 
![image](https://user-images.githubusercontent.com/122054750/221790367-38c2e420-fbb4-4a13-b8c0-2ec07ef03dc4.png)

**Comment by heyajohnny** [comment]
Dan zou er inderdaad iets in de config niet goed staan. Waarschijnlijk een tabje verkeerd of een typfout oid.
Anders moet je even je huidige config backuppen en [deze](https://github.com/heyajohnny/afvalinfo/blob/master/example/configuration.yaml) proberen. Pas hierin je adresgegevens aan en verwijder eventueel wat je niet nodig hebt en probeer het dan nog eens.

**Comment by Marsarex** [comment]
Bedankt, er bleek inderdaad iets niet goed te staan... Met de code van jou en wat aanpassingen staat het nu goed 👍 

![image](https://user-images.githubusercontent.com/122054750/221809571-cbd22a0d-e8d1-425e-96db-b486c7b9b18d.png)

Dank voor je snelle reactie!
