### ISSUE TITLE
RMN not working any more?

### ISSUE THREAD

**Issue by Didel** [heyajohnny/afvalinfo#367]
Hi,

I received an error similar to the one described in #366 , except the problem didn’t resolve itself within a few hours (in fact, it doesn’t seem to work for multiple days already). Configuration is correct (hasn’t been changed, always worked fine until recently) and copied from the example. I don’t want to share my address details, but our waste is handled by RMN (https://www.rmn.nl/) . Their website shows they are transitioning to a new app, perhaps the API used by Afvalinfo doesn’t work properly any more? When entering the zipcode and house number from the configuration in https://21burgerportaal.mendixcloud.com/p/rmn/landing/ , it works fine. You can test using `3706BB`, number `55` (a public facility nearby)

**Comment by hasniek** [comment]
Hetzelfde probleem hier. Ik ben ook afhankelijk van RMN. In onze gemeente zijn ze deze week overgestapt naar een nieuwe app. Sindsdien heb ik deze problemen.

**Comment by heyajohnny** [comment]
Ja, dit is hetzelfde probleem als issue [357](https://github.com/heyajohnny/afvalinfo/issues/357)
Helaas kan dit nog wel even duren voordat dit weer werkend is. De gemeenten zijn helaas niet zo meewerkend. Wellicht kan ik nog een poging wagen om de site uit te lezen, maar ik weet dat dit enorm veel tijd gaat kosten, omdat er nogal wat redirects, cookies en keys worden gebruikt, wat ik zo op het eerste gezicht kon zien. De app is helaas ook niet uit te lezen. Zojuist een poging gewaagd, maar zodra er een proxy wordt geforceerd, dan laadt de app niet meer :(

**Comment by imdos** [comment]
I've found the new RMN app and did some certificate unpinning with frida and http toolkit. The new URL is for and adress in IJsselstein for example:
3402ta 17

https://europe-west3-burgerportaal-production.cloudfunctions.net/exposed/organisations/138204213564933597/address/206321157929710806/calendar

Please let me know if you require some others which reside within the same region to check if the scripts can be rewritten.

P.S. I'm fluent in Dutch; but don't know which language is preferred.

**Comment by rik1984** [comment]
I could test Gemeente Bunnik in the same RMN region. Can you find out the URL?

**Comment by imdos** [comment]
Sorry; heeft nog iets werk nodig. Er is een authenticatie token benodigd. Ik heb hier al iets van informatie gepost.
https://github.com/xirixiz/homeassistant-afvalwijzer/issues/232

**Comment by rik1984** [comment]
Ah verkeerd begrepen, ik houd het in de gaten!

**Comment by Didel** [comment]
@heyajohnny It looks like a solution has been found in https://github.com/xirixiz/homeassistant-afvalwijzer/issues/232#issuecomment-1498616173 🎉

**Comment by heyajohnny** [comment]
@Didel Thnx for the update. The RMN gemeenten should work again. Please let me know if all work as expected

**Comment by Didel** [comment]
@heyajohnny Awesome! Indeed, since 2 hours ago the sensors contain the proper data again! 🎉  I will close this issue, thanks for the quick fix!
