### ISSUE TITLE
Gemeente Terneuzen pbd 

### ISSUE THREAD

**Issue by garenor** [heyajohnny/afvalinfo#368]
The pbd date is unknown for gemeente Terneuzen. Running latest version.

**Comment by heyajohnny** [comment]
This is a bit weird... The API returns REST, but the website of deafvalapp says it's PMD+. (See The example PMD+/REST with date 20-03-2023)
![image](https://user-images.githubusercontent.com/20553716/224070280-aef21855-244b-40d6-81c6-e0ccf16f6c4b.png)
![image](https://user-images.githubusercontent.com/20553716/224070781-da721c5f-a916-4891-b6e5-1f74f95fcf9f.png)

I Just pushed a fix for terneuzen to see the REST as pbd

Please let me know if it works

**Comment by garenor** [comment]
It works… Thank you very much!!
