### ISSUE TITLE
krijg geen info vanuit Gemeente venlo

### ISSUE THREAD

**Issue by janss028** [heyajohnny/afvalinfo#369]
Momenteel krijg ik geen gegevens terug vanuit de afvalwijzer gemeente Venlo (mijn postcode is 5935RE)

![image](https://user-images.githubusercontent.com/79377231/226283235-41bdced3-46c2-48b4-9538-2076e1e25888.png)

**Comment by heyajohnny** [comment]
De afvalkalender bij de gemeente Venlo zelf is kapot. Ik zag het gisteravond al en had een hoopje dat de gemeente dit vandaag al opgelost zou hebben. Kijk maar: Dit test adres werkt helaas niet meer.
https://www.venlo.nl/mijn-afvalkalender/5935RE/45

Ik zal de gemeente even mailen. Waarschijnlijk hebben ze dit zo weer aan de praat

**Comment by heyajohnny** [comment]
> Beste meneer / mevrouw,
> 
> Hartelijk dank voor uw e-mail. Wij sturen deze door naar een van onze medewerkers.
> 
> Bij onduidelijkheden, opmerkingen of vragen over uw bericht, nemen wij contact met u op.
> 
> Met vriendelijke groet,
> 
> Gemeente Venlo
> 
> Dit is een automatische ontvangstbevestiging. U kunt niet reageren op deze mail.
