### ISSUE TITLE
Please add: Kesteren

### ISSUE THREAD

**Issue by pietke** [heyajohnny/afvalinfo#37]
Could you add the place Kesteren this is a place in Neder-Betuwe?

**Comment by heyajohnny** [comment]
I'll try to add it, but I can't promise you if it will work.
Avri only returns a PDF as result, so I have to filter out the data from that PDF and don't know if that's possible in a relatively short time.
I know they also have an app, but that thing doesn't even work on my phone...

**Comment by heyajohnny** [comment]
Note to myself: Try Tika for pdf extracting / reading

**Comment by heyajohnny** [comment]
Somehow, at sometime I already added it, but probably while solving another issue. You can use Kesteren. Enjoy ;

**Comment by pietke** [comment]
Thank you for all the work! I am very happy with this integration :)
