### ISSUE TITLE
Restafval werkt niet voor gemeente Eemsdelta

### ISSUE THREAD

**Issue by JBSDM** [heyajohnny/afvalinfo#370]
Ik krijg Restafval niet binnen in de gemeente eemsdelta. gft en papier doen het wel.

**Comment by heyajohnny** [comment]
Is grijze container toevallig restafval en geen pbd? (Hij staat momenteel gekoppeld aan pbd, maar kan hem aan restafval koppelen uiteraard)
![image](https://user-images.githubusercontent.com/20553716/227345416-19352e67-6a00-4e38-a92a-fa4b97b00a61.png)

**Comment by JBSDM** [comment]
Het is inderdaad restafval.

**Comment by heyajohnny** [comment]
Top! Zojuist aangepast naar restafval. Laat maar weten of het werkt

**Comment by JBSDM** [comment]
Dank, staat er nu weer goed in inderdaad top!
