### ISSUE TITLE
Afvalinfo in gemeente Goes broken

### ISSUE THREAD

**Issue by robsonke** [heyajohnny/afvalinfo#373]
With the following settings:
```- platform: afvalinfo
  resources:
    - gft
    - papier
    - restafval
    - trash_type_today
    - trash_type_tomorrow
  location: goes
  postcode: 4481CP
  streetnumber: 28
  dateformat: "%d-%m-%Y"
  locale: "nl"
  timespanindays: 365
```

getting this error but the actual exception isn't logged:
Error occurred. Please check the address with postcode: '4481CP' and huisnummer: '28''' on the website of your local waste collector in the gemeente: 'goes'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

It's going on for a few weeks now but always worked fine in the past.

**Comment by heyajohnny** [comment]
@robsonke Ik heb zojuist een update doorgevoerd. Laat maar weten of alles werkt zoals verwacht

**Comment by robsonke** [comment]
Thanks a lot, it's working again 👍
