### ISSUE TITLE
Tietjerksteradeel not working

### ISSUE THREAD

**Issue by Arnoudd** [heyajohnny/afvalinfo#374]
Tietjerksteradeel isn’t working. When is use PC 9251TL I’m not getting anything back.

**Comment by Arnoudd** [comment]
My address does work on the official link. (Number 9).
Gft, rest and oud papier is collected

**Comment by heyajohnny** [comment]
It should work again. Probably the official data wasn't available and gave 0 results. That data was cached, and not refreshed yet. I cleared it manually and run your address again. It should have data now

**Comment by heyajohnny** [comment]
Yeah the info is a bit mixed about the naming, but I'll add Tytsjerksteradiel also as an option. I'm closing this issue
