### ISSUE TITLE
Gemeente Venray: PMD zakken not reported

### ISSUE THREAD

**Issue by lokonli** [heyajohnny/afvalinfo#375]
It seems for Gemeente Venray PMD zakken are not reported.
(GFT and restafval are reported correctly)

**Comment by heyajohnny** [comment]
I've fixed the issue, but your data is still cached. If you can wait (max) 7 days it will automatically be fixed or if you give me your zipcode (housenumber not needed) I can manually clear the cache. Please let me know...

**Comment by lokonli** [comment]
Thanks!
5803KG

**Comment by lokonli** [comment]
Yes, it's working. Thanks!
