### ISSUE TITLE
getwholeyear variable issues na HA 2023.04.1 update

### ISSUE THREAD

**Issue by bafplus** [heyajohnny/afvalinfo#377]
Dit is mij en andere opgevallen na laatste HA 2023.04.1 update (maar kan ongeralateerd zijn).
Na deze update krijgen alle sensoren geen data meer muv de eerstvolgende.
Na het toevoegen van de getwholeyear: false variable in configuration.yaml krijg ik wel data maar blijven alle atributen op onbekend staan.
Zet ik timespanindays op True dan pas komt alle data goed in de sensoren te staan.
Het lijkt er voor mij op dat zodra die op False staat hij maar enkele dagen vooruit kijkt ipv de 365 dagen ookal heb je die als timespanindays: 365 in de configuration.yaml opgegeven.

**Comment by Sholofly** [comment]
Ik heb hetzelfde issue, als ik getwholeyear op true zet werkt het inderdaad ook weer. Alleen de Diftar niet.

**Comment by heyajohnny** [comment]
Ik heb zelf mijn HA ook vandaag een update gegeven en zag dat er enkele sensoren niet goed meer werken. Wellicht dat het iets met de unit_of_measurement te maken heeft. Ik zal vanavond kijken wat ik kan vinden...

**Comment by heyajohnny** [comment]
Ik heb zojuist een nieuwe versie gemaakt en heb 'timespanindays' verwijderd. Volgens mij wil je eigenlijk altijd zover mogelijk in de toekomst kijken en is dit gewoon een onding wat ooit eens in het verleden is ontstaan. Tevens heb ik nog een extra check op een mogelijk lege array gedaan, waar hij in mijn testomgeving een error op gaf. Laat maar weten of na deze update weer alles werkt zoals verwacht

**Comment by bafplus** [comment]
Bedankt! We gaan m testen!

Op za 6 mei 2023 om 21:23 schreef heyajohnny ***@***.***>:

**Comment by bafplus** [comment]
Helaas! Ik krijg enkel de eerstvolgende met een datumwaarde. Alle andere sensoren worden wel geupdate maar blijven onbekend.
![Screenshot 2023-05-06 23 08 00](https://user-images.githubusercontent.com/6432986/236646660-51a30248-8422-450c-ae2c-afc4c4a5af21.png)
![Screenshot 2023-05-06 23 07 46](https://user-images.githubusercontent.com/6432986/236646661-eeaefe2e-7c56-4ffa-b85e-74af6ba7f5d6.png)

**Comment by bafplus** [comment]
Poging gewaagd de timespan te overrulen omdat ik vermoedt dat die op bv 2 dagen staat, maar krijg dan een error tijdens configcheck dat de variable "timespanindays" niet meer geaccepteerd wordt in de config.
Dus bij iedereen die die waarde nu WEL in zijn config heeft en nu de integratie update kan niet meer herstarten omdat HA dat wijgert door de issue tijdens de configcheck.

**Comment by Vabis1010** [comment]
Had ik hier ook. Gelukkig verholpen met de backup. Dacvht dat het sinds gister weer goed liep. Nou niet meer dus. Denk toch dat die timespanindays zijn funktie heeft. Na de backup staat hij er gewoon weer in en geen probleem met herstarten.

**Comment by heyajohnny** [comment]
@bafplus heb je misschien een postcode voor mij, dan kan ik het wellicht beter reproduceren? Huisnummer is niet nodig.

**Comment by Vabis1010** [comment]
4661et

**Comment by bafplus** [comment]
4844vp

Op zo 7 mei 2023 09:34 schreef heyajohnny ***@***.***>:

**Comment by heyajohnny** [comment]
Ik zal vanavond wel even kijken vanaf welke versie hij stuk gaat. Ik heb nu echt geen idee waarom het stuk is. Er wordt ook geen error omhoog gegooit. Hij pakt nu echt alleen de eerste sensor en daarna zegt ie 'bekijk het maar'. In de code voegt ie ze wel netjes aan een lijstje toe, maar de update voor de data van deze sensors wordt gewoon niet uitgevoerd, alleen voor de eerste.

**Comment by Vabis1010** [comment]
Net de update gedaan naar 1.1.1.2 geen verandering

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bafplus** [comment]
Hij doet het! En ook weer niet :-)

Vandaag opende ik HA en alle data waren beschikbaar!
Oftewel, het probleem heeft zich over de tijd vanzelf opgelost.

Maarrr...doe ik dan weer de laatste update komt het probleem terug.
Ik vermoedt dat dit ook weer met de tijd zichzelf oplost maar ik hoe dat nog even in de gaten.
![Screenshot 2023-05-07 13 06 14](https://user-images.githubusercontent.com/6432986/236673991-2f141156-926c-4ab4-8cde-7b37b566add7.png)
![Screenshot 2023-05-07 13 05 54](https://user-images.githubusercontent.com/6432986/236673995-01266859-8c6c-4646-b281-35409b5d38a9.png)
![Screenshot 2023-05-07 13 05 09](https://user-images.githubusercontent.com/6432986/236673997-8cceef98-f4eb-4d62-be85-9f0222ff54df.png)

**Comment by bafplus** [comment]
Ik heb een vermoeden dat de eerste "update data run" na een update vastloopt en enkel de gft sensor van data voorziet. Als dan de dagelijkse (?) update van de data gedraait wordt worden wel alle data opgehaald en hersteld alles zich weer. Is er een manier om deze geplande (ik vermoed) dagelijkse update handmatig te starten om dit te testen?

**Comment by bafplus** [comment]
OPGELOST!

Na enkele uren zijn alle sensoren van data voorzien!
Oftewel, het probleem lost zich vanzelf op binnen enkele uren.

**Comment by Vabis1010** [comment]
Hier ook alle data weer terug. Nog maar even afkijken of het goed blijft voor op produktienuc te updaten.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mister86NL** [comment]
> OPGELOST!
> 
> Na enkele uren zijn alle sensoren van data voorzien! Oftewel, het probleem lost zich vanzelf op binnen enkele uren.

Serieus? Dit is toch geen oplossing? Met de maandelijkse releases (welke ik vaak in de avonduren doe) heb ik de eerste 4 uur (zo lijkt het op basis van mijn eigen intel.) geen valide informatie voor o.a. notificaties/TTS meldingen etc.etc..

Niet updaten is ook geen optie dus dit is verre van opgelost imho :)

**Comment by Mister86NL** [comment]
/
![IMG_0034](https://user-images.githubusercontent.com/64736335/236696049-5ed67fbd-fee6-49a8-8ca6-f6380d35bedd.jpeg)

**Comment by Vabis1010** [comment]
Het werkt weer toch.. Hebben ze even tijd om rustig alles na te kijken. Heb de afvalinfo op mijn productie nuc nog niet geüpdatet. Die draait nog normaal. Test pc wel geüpdatet en werkt nu ook.

**Comment by Mister86NL** [comment]
> Het werkt weer toch.. Hebben ze even tijd om rustig alles na te kijken. Heb de afvalinfo op mijn productie nuc nog niet geüpdatet. Die draait nog normaal. Test pc wel geüpdatet en werkt nu ook.

Dat *iets* weer werkt zegt niet dat *iets* is opgelost, want jij update nu ook je productienode niet, wat precies mijn punt ook is :-)

**Comment by Vabis1010** [comment]
Wel ha geüpdatet alleen afvalinfo update niet.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mister86NL** [comment]
> Wel ha geüpdatet alleen afvalinfo update niet. Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
> […](#)

Heb net even HA gerestart en zie hier:

![IMG_0037](https://user-images.githubusercontent.com/64736335/236697083-93026c61-2d7a-4399-a6d0-1093eef9e9c9.jpeg)

(Restafval staat bij mij bovenaan in de .yaml, vandaar dat deze geladen wordt.)

ik durf te wedden dat GFT en PBD over ~4 uur tevoorschijn komen ;)

**Comment by Vabis1010** [comment]
Heb jij de afvalinfo ook geüpdatet?

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by heyajohnny** [comment]
Rustig iedereen 😉 
De kids lagen zojuist op bed en heb even gekeken wat er aan de hand was. Waarschijnlijk is er in een van de nieuwe HA versies iets in de timing van de 'init' en/of 'update' methodes gewijzigd waardoor er al door de sensoren werd gelopen voordat alle data binnen was. Nu heb ik de code aangepast, zodat hij eerder de data ophaalt. Als het goed is zou alles weer moeten werken als voorheen met de nieuwe versie (1.1.3)

**Comment by Vabis1010** [comment]
Werkt weer goed. Update gedaan en data kwam vrijwel gelijk binnen. Bedankt voor het vele werk.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mister86NL** [comment]
Hier ook. Goed bezig @heyajohnny!

**Comment by Sholofly** [comment]
@heyajohnny Bij mij gaat ie nog niet goed. Wellicht door de Diftar?

![image](https://user-images.githubusercontent.com/901632/236771208-cc5d8323-a5e5-42a6-a5fa-b93b72786ef5.png)

**Comment by bafplus** [comment]
Heb je ook de laatste v1.1.3 update gedaan?
Bij mij werkt hij nml wel (maar ik heb dan weer geen diftar)

Op ma 8 mei 2023 om 10:09 schreef Rudolf Offereins ***@***.***

**Comment by Sholofly** [comment]
Yes, dat heb ik. Gemeente Oldebroek (8097 PC)

**Comment by bafplus** [comment]
> 8097 PC

Als ik die check op https://4fv4l.nl/ krijg ik helemaal geen data.
Lijkt er dus op dat hier iets anders mee aan de hand is.
Het beste kun hier even een losse issue voor aanmaken

**Comment by Sholofly** [comment]
@bafplus  Dank voor het checken maar Ik krijg wel data voor mijn adres daar. Ook voor restafval.

**Comment by heyajohnny** [comment]
@Sholofly Zonder diftar werkt het in ieder geval:
![image](https://user-images.githubusercontent.com/20553716/236892246-13abecb1-2093-4bd3-a117-69edb2f8fc90.png)

**Comment by heyajohnny** [comment]
@Sholofly Ik heb zojuist een nieuwe versie gemaakt. Ik durf alleen niet te zeggen of de diftar gegevens het doen. Zou je kunnen laten weten of dit ook weer werkt?

**Comment by Sholofly** [comment]
@heyajohnny Helaas, nog geen diftarinformatie. Kan ik wat doen om het bijv. lokaal te testen? Ik ben graag van dienst.

**Comment by heyajohnny** [comment]
Zojuist een nieuwe versie uitgerold. Laat maar weten of de diftar info hiermee weer terug is.

**Comment by heyajohnny** [comment]
Ik sluit het issue, omdat er al enige tijd geen reactie is geweest en dit issue al aardig uit de klauwen is gelopen qua grootte. Mochten er alsnog problemen zijn, dan kan er een nieuw issue aangemaakt worden
