### ISSUE TITLE
Error after last update afval info date 6 may.

### ISSUE THREAD

**Issue by nicokars** [heyajohnny/afvalinfo#379]
Logger: homeassistant.config
Source: config.py:938
First occurred: May 6, 2023 at 22:48:45 (1 occurrences)
Last logged: May 6, 2023 at 22:48:45

Invalid config for [sensor.afvalinfo]: [timespanindays] is an invalid option for [sensor.afvalinfo]. Check: sensor.afvalinfo->timespanindays. (See /config/configuration.yaml, line 572). Please check the docs at https://github.com/heyajohnny/afvalinfo

HAS version: 5.2
Use this code for three years.. had no problems..

- platform: afvalinfo
    resources:
      - type: pbd
        friendly_name: Plastic Blik en Drankpakken
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: XXXX
    postcode: XXXX
    streetnumber: X
   dateformat: '%A (%d %b)'
    locale: 'nl'
    timespanindays: 365
    notrashtext: 'geen'

**Comment by JBakers** [comment]
Timespanindays is removed and n last update

**Comment by nicokars** [comment]
all fixed,
thx for the fast action and update

**Comment by AarvdH** [comment]
At my place (Alkmaar) since update this morning I only get info on Groente Fruit en Tuinafval. All the others are status unknown. I have been waiting since 11:00 this morning, nothing chages in the status.
Bit no errors in the logs, Site Alkmaar is in the air and giving dates.
