### ISSUE TITLE
Please add: Heerenveen

### ISSUE THREAD

**Issue by puytr** [heyajohnny/afvalinfo#38]
Dear developers,
I've made an annual Google calender with manual entries for the waste collection. It would be great if you could add Heerenveen to this component. The waste collector is omrin. This is the link to their website (from which you can download a pdf file...). https://www.omrin.nl/bij-mij-thuis/afval-regelen/afvalkalender

Thanks,
Richard

**Comment by heyajohnny** [comment]
I've just added Omrin, including Heerenveen to Afvalinfo.
Please let me know if it works. Enjoy :)

**Comment by heyajohnny** [comment]
I'm closing the issue. If it doesn't work you can create a new issue or reopen this one
