### ISSUE TITLE
Diftar werkt niet

### ISSUE THREAD

**Issue by Sholofly** [heyajohnny/afvalinfo#383]
Ha @heyajohnny, Diftar werkt niet. Ik heb geen aanpassingen gedaan aan de config. Maar ik krijg voor mijn restafval geen waarden meer. OP de originele site van afvalinfo werkt het nog wel.

![image](https://github.com/heyajohnny/afvalinfo/assets/901632/4d4b134b-d768-45eb-96a4-a09076b9a6f4)
![image](https://github.com/heyajohnny/afvalinfo/assets/901632/16e1cadb-937a-4b08-bba0-dc083791215d)

**Comment by heyajohnny** [comment]
@Sholofly Bij mij werkt hij wel met de adresgegevens (die jij mij waarschijnlijk in het verleden hebt gegeven):
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/a6be7e86-bcc8-40dc-91af-3c635ab549e8)
Welke versie van Afvalinfo gebruik je? 1.2.1 of hoger zou gewoon moeten werken

**Comment by Sholofly** [comment]
Welke config options heb je nu aanstaan?
