### ISSUE TITLE
GFT for Blink (Son) remains "unknown"

### ISSUE THREAD

**Issue by cowbalt** [heyajohnny/afvalinfo#384]
hey,

it looks like GFT for Blink  (gemeente Son en Breugel) is not reporting anything anymore. 
It's not listed on your test calendar either, so looks like something was changed in their backend? 
you can try postcode 5691 AE / 56

error: false
friendly_name: GFT
year_month_day_date: null
last_update: null
days_until_collection_date: null
is_collection_date_today: false
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null
icon: mdi:recycle

Cheers
Martin

**Comment by heyajohnny** [comment]
I've changed the whole mapping system on the back-end and it should be fixed. Please let me know if it now works as expected

**Comment by cowbalt** [comment]
looks good to me 👍 

error: false
friendly_name: GFT
year_month_day_date: 2023-06-06
last_update: 02-06-2023 08:55
days_until_collection_date: 4
is_collection_date_today: false
last_collection_date: null
total_collections_this_year: null
whole_year_dates: null
icon: mdi:recycle

issue can be closed :)
