### ISSUE TITLE
Hellevoetsluis (https://www.mijnafvalwijzer.nl/)

### ISSUE THREAD

**Issue by Torenvalk** [heyajohnny/afvalinfo#385]
Hi,

Would it be possible to integrate also Hellevoetsluis (part of Voorne aan Zee, a new municipality since 1-1-2023 (Brielle, Hellevoetsluis and Westvoorne) to the list of municipallities?
The pick-up dates of Hellevoetsluis are listed at https://www.mijnafvalwijzer.nl/
By the way...the cleanprofs integration works nice.

Thanks in advance

**Comment by heyajohnny** [comment]
You can use 'voorne aan zee' as location.

**Comment by Torenvalk** [comment]
Seems to work perfectly for both the carbage types and cleanprofs.
Thank you for the quick response
