### ISSUE TITLE
Config flow for afvalinfo

### ISSUE THREAD

**Issue by jasperslits** [heyajohnny/afvalinfo#386]
I started working on a Config flow for afval info integration. 

Before creating a PR I need to get the entity name translations to work, so "Paper" shows in English and "Papier" in Dutch. 
All the plumbing is there but the sensor translations don't seem work. I work with HA exclusively in English but still like to deliver it clean.  

The sensors to use is a multi select: 
<img width="419" alt="image" src="https://github.com/heyajohnny/afvalinfo/assets/30024136/910aff9f-4b85-4afd-9507-b77ac01de8b0">

After a config flow setup, all configured addresses are showing up. I am defaulting to 'home' but ideally that gets a translation too. 

<img width="1016" alt="image" src="https://github.com/heyajohnny/afvalinfo/assets/30024136/7698b2a4-14b3-4bbc-867f-286e683969b7">

Code sits under https://github.com/jasperslits/afvalinfo/tree/master/custom_components/afvalinfo but needs a bit of polishing

It creates the sensors and they work but it's only tested with a net new entry and not yet with YAML based config.

Work in progress but I expect it needs a couple of days more.   

High level summary of changes:
* Created strings.json for translations
* Create config_flow for config flow
* Updated __init__.py for set up
* Updated iot_class and config_flow = True in manifest.json
* Removed sensors.py framework setup
* Created en.json + nl.json translation files

**Comment by heyajohnny** [comment]
I just started my holiday today. I'll look at it in a couple of weeks. Sorry...

**Comment by jasperslits** [comment]
Ok, FYI I've managed to fix the entity translations too. We can discuss next steps for PR when you're back

**Comment by jasperslits** [comment]
@heyajohnny : any interest still in this config flow?

**Comment by heyajohnny** [comment]
@jasperslits Yes, I'm sorry for the delay. I was totally lost in some other projects I'm working on. 
Before your issue/request I didn't even knew what a config flow was, but I found out some basic info:

> A Home Assistant Config Flow is a framework within the Home Assistant automation and control platform that simplifies the process of adding and configuring new integrations and devices to your Home Assistant setup. Home Assistant is an open-source home automation platform that allows you to control and automate various smart devices and services in your home.
> 
> The Config Flow feature was introduced to make it easier for users to set up integrations with different devices, services, and platforms without manually editing configuration files. It provides a user-friendly interface for configuring integrations, where users can input the necessary information, such as authentication credentials, API keys, or device-specific settings, in a step-by-step manner.
> 
> Here's how a typical Home Assistant Config Flow works:
> 
> Discovery: Home Assistant may automatically discover new devices or services on your network or offer a list of available integrations that can be added.
> 
> User Interaction: When you choose to add a new integration, Home Assistant presents you with a user interface (UI) for configuring the integration. This UI is generated based on the integration's Config Flow definition and typically includes fields for inputting required information.
> 
> Validation: As you input information, Home Assistant may perform validation to ensure that the data is correct and complete. If there are errors or missing information, it will prompt you to correct them.
> 
> Authentication: If necessary, the Config Flow may guide you through the authentication process required for the integration. This might involve logging in to an external service or generating API keys.
> 
> Confirmation: Once you've completed the configuration steps, the Config Flow will provide a summary of the settings you've entered. You can review and confirm these settings before finalizing the integration.
> 
> Integration Setup: After confirmation, Home Assistant will set up the integration and add the devices or services to your Home Assistant dashboard, making them accessible for automation and control.
> 
> The use of Config Flows simplifies the onboarding process for various devices and services and makes it more accessible for users, even those who may not be comfortable editing configuration files manually. It also ensures a consistent and user-friendly experience for integrating new components into the Home Assistant ecosystem.
> 
> Keep in mind that the availability of Config Flows depends on the specific integration and version of Home Assistant you are using, as integrations need to be developed to support this feature.

Is there anything I can do to help you? Or do you already have it fixed in your branch? And how / where do you find existing 'config flowed' integrations? I'm totally new to this, so maybe you can point me to the right direction.

**Comment by jasperslits** [comment]
I have it working with the Config Flow (see also earlier screenshot), I realized I didn't create a branch but committed against master for it but will redo the changes. 

The part that I haven't been looking into is dealing with existing YAML based config entries. Debugging is a bit tedious as the init part happens upon HA restart so with every change to the code you need to restart HA as there's no reload option (yet).

With the translations done, I am not sure if it breaks existing automations that checks specific values. 

I'll try to make a proper PR later this week and add some new screenshots to this issue. 

For now the help needed is just on the testing.

**Comment by MTijn** [comment]
Just checked your version out on my installations, worked like a charm for me.

**Comment by jasperslits** [comment]
Closed as PR #396 is merged
