### ISSUE TITLE
Restafval ontbreekt voor Noardeast-Fryslan en Dantumadiel

### ISSUE THREAD

**Issue by gzoodsma** [heyajohnny/afvalinfo#387]
Sinds een tijdje ontbreekt restafval in de kalender van Noardeast-Fryslan en Dantumadiel. GFT en papier staan er nog wel in.

**Comment by heyajohnny** [comment]
De restafval zou weer moeten werken. Laat maar weten of dat ook zo is.

**Comment by gzoodsma** [comment]
Ja, doet het weer hoor

Op di 25 jul. 2023 20:42 schreef heyajohnny ***@***.***>:
