### ISSUE TITLE
no longer garbage schedule for Eindhoven 

### ISSUE THREAD

**Issue by samimasad** [heyajohnny/afvalinfo#388]
Hi
Garbage collection schedule "example"
Eindhoven 5627CX Belforthof 4 , no longer there

**Comment by samimasad** [comment]
it works for streetnumber 4 but not for 8

**Comment by heyajohnny** [comment]
Ik should be working again. Probably some outage @ the local trash collector when fetching the data. I cleared the cache and now it has the data again.
