### ISSUE TITLE
Please add: Rotterdam

### ISSUE THREAD

**Issue by lopmar** [heyajohnny/afvalinfo#39]
The source of the data: http://afvalkalender.container-beheer.nl/
Thanks!

**Comment by heyajohnny** [comment]
According to the site you provided there are no pickup dates for collecting waste.
Maybe you can give me a link with a postcode and number with pickup dates, because I can't find any.

**Comment by lopmar** [comment]
It does not work for all postcodes indeed. 
The shortest link that works seems to be (Example Postcode 3065KA):

http://afvalkalender.container-beheer.nl/#/menuitems/320/all/view?visiblefilters={"320":{"mapsearch":{"search_string":"3065KA"}}}

After clicking in Afvalkalender (southwest), the dates in plain text appear in the foreground.

Thanks again.

**Comment by heyajohnny** [comment]
Note to myself: Mijnafvalwijzer also supports Rotterdam :)

**Comment by heyajohnny** [comment]
I've just added Rotterdam. Please let me know if something doesn't work
