### ISSUE TITLE
Restafval en PBD werkt niet meer venlo

### ISSUE THREAD

**Issue by dartsangelow** [heyajohnny/afvalinfo#390]
De entititeiten van afvalinfo voor venlo de restafval en Pbd tonen onbekend

**Comment by heyajohnny** [comment]
Dit zou weer moeten werken nadat de cache is ververst (< 7 dagen). Als ik je postcode weet, kan ik de cache handmatig legen, waardoor het weer zou moeten werken

**Comment by dartsangelow** [comment]
Dankjewel voor je reactie,

Mijn postcode is 5924AT

Alvast bedankt!

Op di 26 sep. 2023 17:42 schreef heyajohnny ***@***.***>:

**Comment by heyajohnny** [comment]
Zojuist de cache voor 5924AT geleegd
