### ISSUE TITLE
Gemeente Winkel 1731XB

### ISSUE THREAD

**Issue by Zorro-Ed** [heyajohnny/afvalinfo#392]
Hello HeyaJohnny,
Could you give me a hand with the configuration of the gemeente Winkel? Noord Holland.
It is not listet in de gemeentes and can't find the gemeente in the lookup page. Should I take something nearby or is Winkel not supported (yet)
The afvaldienst is HVC overthere
Thank you!

Hans.

**Comment by heyajohnny** [comment]
Volgens mij hoort de plaats Winkel bij de gemeente "hollandse kroon"

**Comment by Zorro-Ed** [comment]
Thanks,, that was it.
