### ISSUE TITLE
Verkeerde info papier en pbd

### ISSUE THREAD

**Issue by abctje** [heyajohnny/afvalinfo#393]
Sinds een tijdje wordt in mijn HA de informatie niet correct weergegeven. Op 23/11gaf afvalwijzer aan dat PAPIER zou worden opgehaald. Dit was echter PBD. Nu geeft afvalwijzer aan dat op 27/11 PBD wordt opgehaald, terwijl dit PAPIER moet zijn. Op de betreffende web pagina van de gemeente staat de informatie wel correct. Dingen worden door elkaar gehaald in afvalinfo?

Ik kan niet vinden wat ik fout heb, ligt dit aan mijn config?

Hieronder mijn config:
sensor:
  - platform: afvalinfo
    id: Norg
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: kerstboom
        friendly_name: Kerstboom
      - type: pbd
        friendly_name: Plastic Blik en Drankkartons
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: textiel
        friendly_name: Oude Kleding
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    location: noordenveld
    postcode: 9331BV
    streetnumber: Prive!
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
    notrashtext: 'Geen afval'

**Comment by heyajohnny** [comment]
Ik zal morgen eens kijken wat er aan de hand is.

**Comment by abctje** [comment]
Thanx!

Net nog even weer vergeleken: Dit is van de mijnafvalwijzer.nl waar de gemeente naar verwijst:

maandag 04 december
Groente, Fruit en Tuinafval
donderdag 07 december
Plastic, Metalen en Drankkartons (PMD)
maandag 11 december
Restafval
donderdag 21 december
Plastic, Metalen en Drankkartons (PMD)
vrijdag 22 december
Papier en karton

In HA staat het net weer andersom:
Papier op 7/12
Plastic op 22/12

De rest van het afval staat goed.

**Comment by abctje** [comment]
Alles verwijderd en opnieuw aangemaakt, het staat nu wel goed! Misschien toch ergens ene typo.

Ontzettend bedankt! "ME HAPPY"!!!
