### ISSUE TITLE
Data kloppen sinds een week niet meer

### ISSUE THREAD

**Issue by jurgen2005** [heyajohnny/afvalinfo#394]
Voor de gemeente Breda klopt er helaas niets meer van, geen enkel ophaal moment komt overeen.

**Comment by zoeperman** [comment]
ook voor de gemeente midden drenthe niet

**Comment by weirdo1971** [comment]
gemeente Lansingerland klopt ook niet meer; Komende 2 weken zit ik met een uitpuilende GFT container vanwege verkeerde info ;-(

**Comment by heyajohnny** [comment]
Auch... Ik ga morgen kijken waarom deze gemeenten de boel stiekem hebben veranderd

**Comment by erwin-online** [comment]
Voor Roosendaal klopt het ook niet meer (gelukkig heb ik nog de Afvalwijzer android app die vandaag een melding gaf)

**Comment by heyajohnny** [comment]
Dit is heel vreemd... @jurgen2005, @zoeperman , @weirdo1971 , @erwin-online 
Kunnen jullie je adres controleren in [https://4fv4l.nl](https://4fv4l.nl/)?
Bij al mijn testadressen van de gemeenten die jullie op hebben genoemd lijkt de data gewoon te kloppen. Ik wil daarom ook even weten of het probleem bij de achterliggende data of zich in HA bevindt

**Comment by zoeperman** [comment]
voor mij ook niet
volgens 4fv4l.nl
![image](https://github.com/heyajohnny/afvalinfo/assets/46575676/32266455-f296-4773-b5a2-326fabaa9750)
volgens mijnafvalwijzer
![image](https://github.com/heyajohnny/afvalinfo/assets/46575676/d1754180-af39-458f-9e39-6f79221dce84)

**Comment by heyajohnny** [comment]
Hebben jullie misschien een postcode voor mij, dan kan ik wat gerichter zoeken, omdat het niet overal fout lijkt te gaan.

**Comment by jurgen2005** [comment]
Ja! dat is apart, als ik het huisnummer van de buren intik klopt het wel!

**Comment by zoeperman** [comment]
hoi, nu klopt er helemaal niets meer van :( ook die van de buren niet....
ik heb je een mail met adres data kan je zelf even kijken/testen

**Comment by jurgen2005** [comment]
nee inderdaad, hier hetzelfde resultaat, mijn eigen adres én van de buren klopt niet meer

**Comment by erwin-online** [comment]
Ik zie via https://4fv4l.nl nog verschillen in data tussen mijn buurman en mij (zelfde postcode alleen ander huisnummer dus), dan kan het toch niet aan de Home Assistant config liggen? Overigens kloppen beide ophaaldata dan niet.
Asl ik via https://4fv4l.nl met mijn postcode en huisnummer **1** invul dan krijg ik wel de juiste ophaaldata terug.
Misschien dat andere ook even kunnen testen met huisnummer 1 en de juiste postcode via https://4fv4l.nl ?

**Comment by heyajohnny** [comment]
Hmm... Het lijkt erop dat mijnafvalwijzer moedwillig foutieve data teruggeeft als de aanroep vanaf https://trashapi.azurewebsites.net/ komt. 

Elk willekeurig adres (die mijnafvalwijzer gebruikt) lijkt een resultaat terug te geven. Ook niet bestaande adressen. Soms het juiste resultaat, soms niet.

**Comment by QuaySo** [comment]
Ook voor Assen komen de data niet overeen. Mijnafvalwijzer laat andere data zien dan 4fv4l.

**Comment by weirdo1971** [comment]
> Bedankt voor het checken! Hebben jullie misschien een postcode voor mij waar je foute data op terug krijgt. Dan kan ik wat gerichter zoeken, omdat het niet overal fout lijkt te gaan.

2665dg 235 Ik heb even gecheckt met andere nummers en die gaan allemaal fout.

**Comment by QuaySo** [comment]
Viezedata geeft bij mij de juiste data, trashapi geeft foutieve data

**Comment by erwin-online** [comment]
Ik krijg verschillende resultaten terug maar beiden kloppen helaas niet. Heb mijn gegevens/screenshots naar heyajohnny gestuurd.

**Comment by zoeperman** [comment]
@heyajohnny  lijkt erop dat de vieze data nu goede data terug stuurt, voor mij dan. Maar als ik de postcode van mijn ouders invul, zelfde gemeente alleen andere ophaal data dan geeft hij mijn data weer terug. Dus lijkt nog niet goed te gaan.

**Comment by heyajohnny** [comment]
Ik heb zojuist mijn code aangepast, zodat deze niet meer de website doorleest, maar de API van mijnafvalwijzer. Het zou nu volgens mij goed moeten gaan. Laat maar weten of dit ook het geval is.
(Diftar durf ik zo niet te zeggen of deze correct werkt, omdat deze nog steeds afhandelijk is van de website en niet de mijnafvalwijzer API)

**Comment by zoeperman** [comment]
4fv4l.nl lijkt nu weer te kloppen inderdaad, en ook die datums staan nu weer in mijn HA :)
super bedankt

**Comment by erwin-online** [comment]
Heb even snel in HA gekeken en de datums lijken idd weer te kloppen. Dank je wel voor de moeite en fix!

**Comment by altserg** [comment]
Bij me klopt het ook voor 2 adressen

**Comment by heyajohnny** [comment]
Ik sluit het issue. Mocht er toch nog iets niet kloppen, graag een nieuw issue openen, want deze  is wel heel erg groot geworden.
