### ISSUE TITLE
Error on 2023.12.0b1 & all sensors unavailable

### ISSUE THREAD

**Issue by hmmbob** [heyajohnny/afvalinfo#395]
Seeing an error I haven't seen before. Running 2023.12 beta 1.

```py
2023-12-01 09:23:25.296 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalinfo platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/afvalinfo/sensor.py", line 144, in async_setup_platform
sensor_type = resource["type"].lower()
~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by hmmbob** [comment]
In #beta on Discord the following is given as reason for this error:

> because `resource` changed from a dict to a list

**Comment by hmmbob** [comment]
@heyajohnny Kleine ping omdat morgen 2023.12 gereleased wordt en dan de hele HA goegemeente gaat updaten ;-)

**Comment by heyajohnny** [comment]
@hmmbob Ik had helaas wat problemen met mijnafvalwijzer gemeenten die ik eerst op moest lossen. Ik hoop deze nog vandaag / morgen te bekijken en te fixen

**Comment by hmmbob** [comment]
No worries, ik kan ook prima zonder - het was meer dat ik vanaf morgen een kleine stortvloed verwacht ;-) 

Laat maar weten als je test-hulp nodig hebt.

**Comment by Rep-Hueman** [comment]
quick workaround that works for me in HA 2023.12
adjust the following:

afvalinfo/sensor.py
Old!:

137    for resource in config[CONF_RESOURCES]:
138        # old way, before 20220204
139        if type(resource) == str:
140            sensor_type = resource.lower()
141            sensor_friendly_name = sensor_type
142        # new way
143        else:
144            sensor_type = resource["type"].lower()
145            if "friendly_name" in resource.keys():
146                sensor_friendly_name = resource["friendly_name"]
147            else:
148                # If no friendly name is provided, use the sensor_type as friendly name
149                sensor_friendly_name = sensor_type
150
150        # if sensor_type not in SENSOR_TYPES:

Temp - quick workaround  (change to):

137    for resource in config[CONF_RESOURCES]:
138        # old way, before 20220204
139        if type(resource) == str:
140            sensor_type = resource.lower()
141            sensor_friendly_name = sensor_type
142        # new way
143        else:
144            sensor_type = resource.lower()
145            sensor_friendly_name = sensor_type
146
147        # if sensor_type not in SENSOR_TYPES:

**Comment by dennisbrouwer91** [comment]
Jep, het is inderdaad kapot na de 2023.12 update!

**Comment by Homeassistjoenka** [comment]
when come the fix? on this problem

**Comment by heyajohnny** [comment]
Ik heb zojuist een update doorgevoerd. Let wel op! Deze moet via config flow geconfigureerd worden (Uitleg staat in de Readme). De sensor moet ook uit de configuration.yaml gehaald worden. Laat maar weten of dit lukt.

Wellicht mist er nog iets in de Readme of de nieuwe config flow. Mocht dit zo zijn, graag een nieuw issue aanmaken daarvoor. Thnx

**Comment by Homeassistjoenka** [comment]
super bedankt, voor de snelle fix  dit is perfect nu

**Comment by heyajohnny** [comment]
Ik sluit dit issue, aangezien dit probleem is opgelost.
