### ISSUE TITLE
Updates to documentation - config flow

### ISSUE THREAD

**Issue by jasperslits** [heyajohnny/afvalinfo#397]
I think with the config flow being introduced in the latest release, it's good to get rid of the configuration.yaml configuration examples + references in the documentation. 

I didn't bother testing configuration.yaml to config flow and just started with a clean sheet. I am happy to help with some new texts how the config flow and how you can add multiple addresses, but not sure if you had anything in mind.

I dont know the uptake of this integration but starting from scratch and removing any configuration.yaml entries seems the cleanest. 

Something which doesnt work (yet) is a reconfigure of the flow, e.g. you selected 3 sensors and wanted to have a 4th one. Instead of reconfiguring and seeing the existing ones you now need to delete + recreate it. So that's good to comment as a limitation as obviously that doesnt apply to YAML based config.

**Comment by zoeperman** [comment]
in the configuration.yaml you could give the output a friendly name.
is this still possible in the config flow?
like originaly i had this:
    resources:
      - type: pbd
        friendly_name: Oranje container

**Comment by jasperslits** [comment]
You can change the name in the UX like with any sensors. 
The config flow simplifies the set up process at the expense of the flexibility of the config yaml.

**Comment by heyajohnny** [comment]
@jasperslits If you have any suggestions on how to improve the documentation, feel free to let me know or open a pull request

**Comment by jasperslits** [comment]
You updated all documentation since I created the PR for the config flow, so it looks all good now.
