### ISSUE TITLE
PBD info mist gemeente Zwolle (ROVA)

### ISSUE THREAD

**Issue by michelotten** [heyajohnny/afvalinfo#399]
Zojuist geupdate naar versie 2.0.2 en m’n config in configuration.yaml weggegooid en via de nieuwe weg de sensoren opnieuw toegevoegd.

voor GFT en papier krijg ik netjes het verwachtte resultaat, maar PBD blijft op ‘onbekend’ staan.
Gemeente Zwolle (ROVA) postcode 8016..

**Comment by michelotten** [comment]
Eerstvolgende PBD afhaling is 3 januari 2024. Wellicht heeft het met de jaarovergang te maken?

**Comment by heyajohnny** [comment]
@hmmbob dit komt door een aanpassing bij deafvalapp. Zou bij het ophalen van nieuwe data weer moeten werken

**Comment by michelotten** [comment]
PBD komt nu netjes door met afhaaldatum 3 januari 2024. Zal ik deze maar sluiten, of wil je ‘m toch open houden @heyajohnny?

**Comment by heyajohnny** [comment]
Ik sluit het issue wel. Rova had ik al omgebouwd naar de API. Blijkbaar hadden ze de dagen nog niet aangevuld voor volgend jaar, maar nu wel. Thnx voor het laten weten dat het weer werkt!
