### ISSUE TITLE
future request

### ISSUE THREAD

**Issue by compujunk** [heyajohnny/afvalinfo#4]
Allereerst bedankt voor het toevoegen van Vianen (vijfherenlanden)

Ik gebruikte voorheen Garbage-Collection met Garbage-Collection-card, nadeel daarvan was dat je handmatig de datums van ophalen moest invullen, geen api dus en vooral met feestdagen niet nauwkeurig, maar je had wel het voordeel dat je het zo kon instellen dat hij x aantal dagen van te voren weergaf wat er opgehaald werd. (was zelf in te stellen) de rest liet hij niet zien. ook kon je verschillende icons en kleuren toe voegen.

Dat was een mooie oplossing. Is het mogelijk dat we bij afvalinfo ook zoiets kunnen verwachten?
Dan zou het helemaal een perfecte toevoeging zijn.

**Comment by heyajohnny** [comment]
Kleurtjes en Icons ben ik (voorlopig) niet van plan om toe te voegen. Dit vind ik meer de taak van "ui-lovelace.yaml"

Het niet tonen en iets van 'over x aantal dagen' wordt het opgehaald. Een soort van aftellen in plaats van een datum tonen ben ik nog wel van plan te maken.

Een tijdsindicatie kan ik helaas niet geven, omdat het voor mij een hobby project is, waar ik niet altijd mee bezig kan zijn.

Ik laat de melding open staan en plaats een update, zodra ik hier mee aan de slag ga.

**Comment by compujunk** [comment]
Bedankt voor je antwoord ik wacht het af.

**Comment by heyajohnny** [comment]
Zojuist een optie toegevoegd waarin je op kunt geven hoeveel dagen in de toekomst gekeken kan worden. 

Als je van vandaag uit gaat (12-02-2020) en je stelt bij de optie "timespanindays" de waarde "10" in, dan krijg je alleen resultaat terug t/m 22-02-2020. 

Als bijvoorbeeld oud papier 21-02-2020 opgehaald wordt, dan krijg je gewoon het resultaat te zien, maar als bijvoorbeeld gft op 23-02-2020 opgehaald wordt, dan krijg je daar geen resultaat van. Indien er geen resultaat is, wordt ook het Attribuut "Hidden" op "True" gezet.

Wellicht heb je hier al wat aan :)

**Comment by compujunk** [comment]
ik ga het uit proberen. bedankt alvast

**Comment by heyajohnny** [comment]
Ik heb het attribuut "Hidden" naar "hidden" gewijzigd.
Er zijn nu ook 2 extra attributen.
-days_until_collection_date.    This will return the number of days between today and the collection date.
-is_collection_date_today.      This will return true if the collection date is today and false if the collection date is not today.

Ik denk dat dit wel voldoende is om zo via een If else constructie in 'Lovelace' het een en ander te kunnen filteren.
