### ISSUE TITLE
Please add: De Fryske Marren

### ISSUE THREAD

**Issue by hhidsinga** [heyajohnny/afvalinfo#40]
Would be great if you could add de Fryske Marren

Content can be received from (example):
https://www.afvalalert.nl/kalender/8493LL/1/

It includes the following places:

    Akmarijp
    Bakhuizen
    Balk
    Bantega
    Boornzwaag
    Broek
    Delfstrahuizen
    Dijken
    Doniaga
    Echten
    Echtenerbrug
    Eesterga
    Elahuizen
    Follega
    Goingarijp
    Harich
    Haskerhorne
    Idskenhuizen
    Joure
    Kolderwolde
    Langweer
    Legemeer
    Lemmer
    Mirns
    Nijehaske
    Nijemirdum
    Oldeouwer
    Oosterzee
    Oudega
    Oudehaske
    Oudemirdum
    Ouwster-Nijega
    Ouwsterhaule
    Rijs
    Rohel
    Rotstergaast
    Rotsterhaule
    Rottum
    Ruigahuizen
    Scharsterbrug
    Sint Nicolaasga
    Sintjohannesga
    Sloten
    Snikzwaag
    Sondel
    Terhorne
    Terkaple
    Teroele
    Tjerkgaast
    Vegelinsoord
    Wijckel

**Comment by heyajohnny** [comment]
Note to myself: westerkwartier also uses afvalalert

**Comment by heyajohnny** [comment]
I've just added De Fryske Marren / De Friese Meren. Please let me know if it works

**Comment by heyajohnny** [comment]
I'm closing the issue. If it doesn't work, reopen the issue or create a new one

**Comment by hhidsinga** [comment]
It works! Great!
