### ISSUE TITLE
Oldebroek | No rest afval data, showing as Papier

### ISSUE THREAD

**Issue by Sholofly** [heyajohnny/afvalinfo#401]
Hi,

My rest afval sensor has the name Papier on initialize of the sensor. It als has the state 'Unknown', unlike the others that are working fine.

![image](https://github.com/heyajohnny/afvalinfo/assets/901632/64ef9b74-9f89-4e96-878c-db3993e9d2ad)
If you want my details, please contact me!

**Comment by Rikkie80** [comment]
Same for Veldhoven

**Comment by hmmbob** [comment]
And my place as well

![image](https://github.com/heyajohnny/afvalinfo/assets/33529490/08402f74-b5f7-4d60-b7f4-e117e309b42f)

**Comment by heyajohnny** [comment]
Should be fixed in v2.0.4 that I've just released

**Comment by hmmbob** [comment]
Translation is indeed fixed. No data yet (it errors out), but I guess that might be unrelated

**Comment by Rikkie80** [comment]
Indeed an error occurred while setting up (of course with correct postal code and number entered):

Error occurred. Please check the address with postcode: 'XXXXYY' and huisnummer: 0000'' on the website of your local waste collector in the gemeente: ''. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

**Comment by hmmbob** [comment]
> Indeed an error occurred while setting up (of course with correct postal code and number entered):
> 
> Error occurred. Please check the address with postcode: 'XXXXYY' and huisnummer: 0000'' on the website of your local waste collector in the gemeente: ''. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

That's due to #405. If you fill in the name of your gemeente, it'll work

**Comment by Sholofly** [comment]
Ha @heyajohnny, Trasnlation is fixed now. Unfortunately my Restafval sensor still shows no data, while my AfvalWijzerApp still shows a next date:

![image](https://github.com/heyajohnny/afvalinfo/assets/901632/117fb14b-9208-428a-880d-0c18b22a4909)

**Comment by heyajohnny** [comment]
@Sholofly The back-end data looks fine now and the Kadaster API is accepting my requests again. It should work now. Please let me know if it works again for the Restafval date
