### ISSUE TITLE
Feature request: Friendly names in ‘today’ and ‘tomorrow’ sensors

### ISSUE THREAD

**Issue by lenwar** [heyajohnny/afvalinfo#402]
I would like to make a feature request.
It would be nice if the ‘today’ and ‘tomorrow’ sensors would return the given name of the relevant sensor rather than the standard items ‘gft’, ‘pbd’, etc.

For example. I named my pbd-sensor ‘Plastic, Metaal, Drankkartons’ (which is what they name it over here. It’s probably different for each gemeente)

I could of course make template sensors for this purpose, but I think it would be cleaner if the Integration would take care of this :)

**Comment by cowbalt** [comment]
+1, I was about to provide the same feedback ;) 
using the state of the sensor in e.g. push messages now returns the standard names rather than the friendly name.

**Comment by zoeperman** [comment]
got the same request :)
https://github.com/heyajohnny/afvalinfo/issues/397#issuecomment-1846069490

**Comment by heyajohnny** [comment]
At the moment it looks to be very hard/not possible to implement this in the config flow (when adding the Afvalinfo entities to Home Assistant).
I think that [this](https://github.com/heyajohnny/afvalinfo/blob/master/README.md#optional-installation-step-3-change-friendly-name) is a fine solution for now. Please let me know if this fixes this friendly name issue.

**Comment by cowbalt** [comment]
heyaJohnny, I think I have to make the request a little more clear. It looks like there was a misunderstanding. 

The sensor for today and tomorrow both return values based on built in names (like pbd). 
This feature request is more about making these two today/tomorrow sensors also aware of the friendly name of the other sensors rather than the built in name. For instance, I use :
{{ states('sensor.afvalinfo_afval_name_of_city_trash_type_tomorrow') }}, which now returns e.g. pbd (built in), and not the friendly name "PMD" which I set on the pbd sensor. 

hope that makes more sense.

**Comment by lenwar** [comment]
If I read that part of the documentation correct, the tomorrow sensor should use the friendly name?

For me this doesn't work?

This is my pbd-sensor, with a new friendly name:
![image](https://github.com/heyajohnny/afvalinfo/assets/3773186/95439de4-5ba9-42e2-9132-8ae00b18bba2)

However, my tomorrow-sensor shows 'pbd'
![image](https://github.com/heyajohnny/afvalinfo/assets/3773186/9de56f97-a3fd-407a-bd01-c81cce503e2e)

**Comment by heyajohnny** [comment]
Oke, I haven't tested it, so that's a bug. I'll try to fix it (hopefully soon)

**Comment by heyajohnny** [comment]
Zou moeten werken in v2.0.8. Laat maar weten of het bij jullie ook allemaal werkt

**Comment by cowbalt** [comment]
works for me now ! 
opgelost ;)
Thanks!

**Comment by lenwar** [comment]
My trash is collected on Fridays, so I can't confirm, but if it works for other people I'm confident it'll work fine.

Thanks!!

**Comment by lenwar** [comment]
Hi,

It works!! 😊
Thanks again!!
