### ISSUE TITLE
Wrong info?

### ISSUE THREAD

**Issue by dennisbrouwer91** [heyajohnny/afvalinfo#405]
Hey,

Just upgraded to v2.x, nice work!
I setup the integration but spotted this in the logs : 

`2023-12-08 13:14:49.944 ERROR (MainThread) [custom_components.afvalinfo.const.const] Error occurred. Please check the address with postcode: '3133MC' and huisnummer: 9'' on the website of your local waste collector in the gemeente: ''. It's p
robably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github
.com/heyajohnny/afvalinfo with details of the location that isn't working`

The "today" and "tomorrow" sensors are working, but the separate sensors (for instance the "papier" one) are not. Any info on what might be going on?

**Comment by heyajohnny** [comment]
Yeah... The kadaster probably blocked my API because of the huge number of requests...
I deleted the 'location' property from the integration, but now it needs to match it with zipcode + house number through the Kadaster API, but they probably said ' enough is enough'

1 request every 2 seconds...
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/52c7e8f2-18a1-43ac-bcd2-c40217a6ed76)

Probably need to re-add the location. Hope to fix this today/tomorrow

**Comment by heyajohnny** [comment]
I already have some caching mechanism, but i need to change it a bit. This wasn't an issue before, because you always needed to define the location.

**Comment by heyajohnny** [comment]
50000 requests  in half a day... So yes it's the kadaster limit:
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/1122d504-7014-48cc-ba7a-d73aaa237e7f)

**Comment by hmmbob** [comment]
filling the "municipality" field with the info you previously put in "location" in your yaml, fixes the error for me. 

(de naam van je gemeente dus invullen)

**Comment by heyajohnny** [comment]
I think I've fixed the caching issue. For known addressess it should work again. For new addressess it probably works again tomorrow when the Kadaster resets my API limit

**Comment by horve000** [comment]
Until the this update all worked fine. Now i get no info at all. Filled in Postalcode, Housnumber and city. But in the attributes all entities show "Error  True" i live in Tilburg.

**Comment by heyajohnny** [comment]
@horve000 Your issue had to do with [this](https://github.com/heyajohnny/afvalinfo/issues/394)
I missed some mappings while rewiriting the module. It should work again somewhere today/tomorrow when the caching is cleared

**Comment by heyajohnny** [comment]
I'm closing this issue, because the kadaster API issues are fixed along with the missing mappings for mijnafvalwijzer
