### ISSUE TITLE
Clear sensors

### ISSUE THREAD

**Issue by Rocker20** [heyajohnny/afvalinfo#409]
At the moment some sensors are in English (for container today and tomorrow) while the other sensors are in Dutch. It would be nicer if everything was in the same language.

**Comment by heyajohnny** [comment]
Do you have any suggestions on how you want to see the translations?
These are the English translations currently {"name": "[translated value]"}:
```
"afvalinfo_cleanprofsgft": {
	"name": "Cleanprofs GFT"
},
"afvalinfo_cleanprofspbd": {
	"name": "Cleanprofs PBD"
},
"afvalinfo_cleanprofsrestafval": {
	"name": "Cleanprofs Restafval"
},
"afvalinfo_gft": {
	"name": "GFT"
},
"afvalinfo_grofvuil": {
	"name": "Grofvuil"
},
"afvalinfo_kca": {
	"name": "KCA"
},
"afvalinfo_kerstboom": {
	"name": "Kerstboom"
},
"afvalinfo_papier": {
	"name": "Papier"
},
"afvalinfo_pbd": {
	"name": "PBD"
},
"afvalinfo_restafval": {
	"name": "Restafval"
},
"afvalinfo_takken": {
	"name": "Takken"
},
"afvalinfo_textiel": {
	"name": "Textiel"
},
"afvalinfo_trash_type_today": {
	"name": "Trash type today"
},
"afvalinfo_trash_type_tomorrow": {
	"name": "Trash type tomorrow"
}
```

**Comment by Rocker20** [comment]
I would like to see afvalinfo_trash_type_vandaag and afvalinfo_trash_type_morgen insteed of afvalinfo_trash_type_today or afvalinfo_trash_type_tomorrow

**Comment by heyajohnny** [comment]
I've just published a new version with more logical default translations. The custom translations (which you can define when adding the sensors) will be made through this issue, so i'm closing this one:
https://github.com/heyajohnny/afvalinfo/issues/402
