### ISSUE TITLE
Please add: Veldhoven

### ISSUE THREAD

**Issue by Rikkie80** [heyajohnny/afvalinfo#41]
Please add Veldhoven
Calendars for Veldhoven (5500 - 5509) can be found via "afvalinfo.nl"

**Comment by olia-bn** [comment]
I second Veldhoven!

**Comment by heyajohnny** [comment]
Note to myself: https://www.veldhoven.nl/afvalkalender/5506BB-41

**Comment by heyajohnny** [comment]
I've just added Veldhoven. Please let me know if it works. Enjoy :)

**Comment by heyajohnny** [comment]
I'm closing the issue. If it doesn't work properly please let me know
