### ISSUE TITLE
Sensors slaan komende ophaaldagen over

### ISSUE THREAD

**Issue by hmmbob** [heyajohnny/afvalinfo#410]
De ophaaldagen van deze week komen niet terug in de sensors (Gemeente Maashorst, 'de afval app'). Plaatjes zeggen meer:
![image](https://github.com/heyajohnny/afvalinfo/assets/33529490/76895334-e774-439b-9d8d-140a11d7a984)
![image](https://github.com/heyajohnny/afvalinfo/assets/33529490/fa4d413a-c4da-47f3-95cb-e1b120e59f88)

**Comment by heyajohnny** [comment]
Ik zal eens kijken wat er nog fout gaat. Notitie aan mezelf: [link deafvalapp](https://dataservice.deafvalapp.nl/dataservice/DataServiceServlet?service=OPHAALSCHEMA&land=NL&postcode=5406VN&straatId=0&huisnr=2&huisnrtoev=)

**Comment by freggel2** [comment]
Ja, hier ook. Ik kwam er gisteren achter (17-12-2023)
Vandaag op 18-12-2023 moet het plastic naar buiten maar hij geeft aan dat de eerstvolgende datum op 30-12-2023 is.
En het restafval, GFT en papier zijn de eerstvolgende data pas in het nieuwe jaar.

![afbeelding](https://github.com/heyajohnny/afvalinfo/assets/86834188/6817cacb-88dd-45af-ac27-e1705304b159)

**Comment by hmmbob** [comment]
Mocht het helpen met zoeken @heyajohnny; volgens mij was vorige week alles nog correct. Misschien een code change sinds die tijd?

**Comment by heyajohnny** [comment]
Waarschijnlijk bij deafvalapp een code change geweest, want zelf heb ik niets aangepast voor deafvalapp locaties. (Einde/begin van het jaar veranderen ze vaak wat, want dan zijn ze toch al nieuwe data aan het toevoegen)

**Comment by heyajohnny** [comment]
Het zou morgen ergens weer goed moeten staan (dan is de cache geleegd). Laat maar weten of het morgen of later weer werkt

**Comment by hmmbob** [comment]
Will do, dank je wel!

**Comment by freggel2** [comment]
Het is weer hersteld. Zojuist een melding gehad dat het restafval morgen aan de straat moet.
En de rest van de data klopt ook weer. Sowieso bedankt.

**Comment by hmmbob** [comment]
Jep, werkt hier ook weer. Mijn automations hadden nog niet getriggerd, maar dat bleek te komen door https://github.com/heyajohnny/afvalinfo/commit/36962656e190b744c615a626f67fe9177cf19e18 - de data van de sensors klopt gewoon weer. Thanks!
