### ISSUE TITLE
Papier geeft niks terug sinds update

### ISSUE THREAD

**Issue by JBSDM** [heyajohnny/afvalinfo#411]
Ik krijg de datum voor Papier niet meer terug voor de gemeente Eemsdelta (dit werkte nog wel toen ik de YAML config gebruikte)
Enig idee?

**Comment by heyajohnny** [comment]
eemsdelta is overgestapt op Omrin zie ik. Als het goed is moet je ergens morgen (als de cache geleegd is) weer goede data krijgen. Laat maar weten of dat ook zo is

**Comment by JBSDM** [comment]
Het werkt weer😁 Top!
