### ISSUE TITLE
Sinds v2.0.8 geen entity statussen meer

### ISSUE THREAD

**Issue by GertJanArts** [heyajohnny/afvalinfo#412]
Sinds de nieuwe versie van afvalinfo (v2.0.8) hebben de entiteiten geen status meer (gemeente Land van Cuijk)
Dank voor je werk en hulp!
![image](https://github.com/heyajohnny/afvalinfo/assets/20320533/8d669a2a-2f2c-4876-93d1-13ba465fc47d)

**Comment by heyajohnny** [comment]
Voor dit jaar zijn er waarschijnlijk geen ophaaldagen meer. Ik heb de code aangepast, zodat hij ook alvast naar volgend jaar kijkt. Dit zou morgen ergens moeten werken als de cache is geleegd. Laat maar weten wanneer/of dit het geval is

**Comment by GertJanArts** [comment]
@heyajohnny, dat was inderdaad de oplossing. Thanks. Keep up the good work !!!!!!!
