### ISSUE TITLE
AfvalInfo start niet meer

### ISSUE THREAD

**Issue by janss028** [heyajohnny/afvalinfo#413]
Naar de laatste update (19-12-2023: 16:30 uitgevoerd) start AfvalInfo niet meer. Bij het controle van een restart krijg ik de volgende melding:
![image](https://github.com/heyajohnny/afvalinfo/assets/79377231/10c9cbdd-343e-4e93-84b7-d9c387a403f7).

Dit is het stukje in de configuration.yaml:
  - platform: afvalinfo
    resources:
      - type: gft
        friendly_name: Groente Fruit en Tuinafval
      - type: papier
        friendly_name: Papier
      - type: restafval
        friendly_name: Restafval
      - type: trash_type_today
        friendly_name: Afval voor vandaag
      - type: trash_type_tomorrow
        friendly_name: Afval voor morgen
    diftarcode: ""
    location: venlo
    postcode: 5935RE
    streetnumber: 45
    streetnumbersuffix: ""
    dateformat: "%d-%m-%Y"
    locale: "nl"
    timespanindays: 365
    notrashtext: "geen"

![image](https://github.com/heyajohnny/afvalinfo/assets/79377231/c1f76937-b630-4ffd-922e-7e41b0a0d351)

**Comment by FitzJac** [comment]
Lezen?
https://github.com/heyajohnny/afvalinfo#breaking-changes-for-upgrading-from-v1xx-to-v2xx

**Comment by heyajohnny** [comment]
@janss028 Zie comment van @FitzJac .Je moet afvalinfo uit je configuration.yaml halen en de stappen in de Readme volgen

**Comment by heyajohnny** [comment]
Ik sluit het issue
