### ISSUE TITLE
Gemeente Assen gaat naar een andere afvalwijzer

### ISSUE THREAD

**Issue by wimd68** [heyajohnny/afvalinfo#414]
De gemeente Assen stapt over van de afvalwijzer op de AfvalApp. Ik zie daardoor vanaf januari niets meer staan in de kalender. Is dit te verhelpen?

**Comment by heyajohnny** [comment]
Zojuist assen aangepast naar de nieuwe kalender. Dit zal waarschijnlijk morgen ergens gaan werken. Laat maar weten wanneer het werkt

**Comment by wimd68** [comment]
Dank, ik zie de nieuwe data nu!
