### ISSUE TITLE
Gemeente het hogeland not working anymore

### ISSUE THREAD

**Issue by JohnWoldijk** [heyajohnny/afvalinfo#416]
Hi,

In this new version gemeente 'het hogeland' isn't working anymore. Can you please add /fix this one. I also tried the https://4fv4l.nl/ site to test, but there's also no data available. (I've deleted the old sensor in configuration.yaml)

Thanks in advance

Regards John

**Comment by heyajohnny** [comment]
I get the data from their iCal on their website. They haven't updated it yet

**Comment by heyajohnny** [comment]
The iCal has data now, but they totally changed the format of the iCal file. I've updated my code to match the new iCal.
Please let me know if it works. It should work somewhere tomorrow when the cache is cleared.
Supported trash types: gft, grofvuil, restafval, takken

**Comment by heyajohnny** [comment]
I'm closing the issue. If it still doesn't work you can create a new one

**Comment by JohnWoldijk** [comment]
It's working... perfect!!!!
