### ISSUE TITLE
Is de taal veranderd?

### ISSUE THREAD

**Issue by TheGabeMan** [heyajohnny/afvalinfo#417]
Hi,
Niet 100% zeker maar volgens mij was voor de laatste grote update alles in het nederlands en ik keek toevallig vandaag en zag vanochtend op mijn dashboard engelse teksten:
![image](https://github.com/heyajohnny/afvalinfo/assets/4741637/578ba9f0-2c0a-4a26-a5e6-c60e03157c93)

Ik zie nu dat de entites allemaal in het engels zijn:
![image](https://github.com/heyajohnny/afvalinfo/assets/4741637/086b6737-36f5-4a59-963b-c007168d1aa8)

Komt dit doordat ik HA in het engels draai als taal?
![image](https://github.com/heyajohnny/afvalinfo/assets/4741637/ced03bc0-95a6-48d5-8736-8a4d4f0a35c1)

Ik kan de entities hernoemen en dan verschijnen ze wel weer in NL.

Dus weet niet of het echt een issue is, dan gooi maar meteen dicht :-)

**Comment by heyajohnny** [comment]
Het was eerst inderdaad in het Nederlands. Nu kijkt hij inderdaad naar de taalinstellingen van HA. Hernoemen is een oplossing, of de taal aanpassen van HA. 

Ik sluit het issue weer
