### ISSUE TITLE
Where to change the date format?

### ISSUE THREAD

**Issue by imregmelig** [heyajohnny/afvalinfo#418]
Thank you for this integration. It's great to have this available for the household :-) 

I may be overlooking something basic, but where can one change the date format? I have followed the install to the letter and it works fine. However, there is nothing in configuration.yaml, yet everything is working. What happens when I add the example config to configuration.yaml to the currently working integration? Should there be an option somewhere to alter the date-format? Where is it stored after install? Thanks for helping out.

**Comment by heyajohnny** [comment]
The integration isn't via the configuration.yaml anymore, but via the HA config page, so nothing is stored in the configuration.yaml  
When adding the afvalinfo integration you can set the date format:
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/a0d44c6f-4717-47c5-884f-65d4dc004fa9)

**Comment by imregmelig** [comment]
Thank you for following up. It's clear this is done during install. I guess a welcome feature would be to be able to change this after install. When you're not familiar with setting the date in its format it takes a few times to get it right.

**Comment by heyajohnny** [comment]
I might look at it in the future. You can make a new issue with a request for this feature if you like.

**Comment by nighto** [comment]
Hi, how to make this configuration show up again? I also have it set already but for whatever reason it does not show up in HACS again when choosing "Update information" or "Redownload". Do I need to completely remove it and install it again to configure the date format? Thanks

**Comment by heyajohnny** [comment]
@nighto 
I don't understand. You can just do a reconfigure and change the date format:
![image](https://github.com/user-attachments/assets/6b0c82d6-fbec-4565-bf46-23beb71c3851)
I've just tested it and works fine on my system. 
If the sensor somehow doesn't work anymore you can always delete it and reinstall it. A restart also does wonders sometimes

**Comment by nighto** [comment]
I wasn't finding the option, thanks for sharing @heyajohnny.

For the people from the future googling this (like I did), you need to go to Settings > Devices & Services > Afvalinfo, then on the middle of the screen you'll see Integration entries, click on the three dots and Reconfigure.
