### ISSUE TITLE
Woerden (and Oudewater) not working anymore (new app/website)

### ISSUE THREAD

**Issue by henryvandevorst** [heyajohnny/afvalinfo#419]
Afvalinfo nog working anymore for Woerden and Oudewater. They changed to a new app and website:

https://woerdenoudewatermodules.ximmio.com/?companyCode=06856f74-6826-4c6a-aabf-69bc9d20b5a6&moduleName=calendarGeneric&community=woerden)

App op iOS is “Afval Woerden en Oudewater”. 
Is it possible to connect the Afvalinfo integration to the new site?

**Comment by heyajohnny** [comment]
I'll look at it tomorrow evening

**Comment by heyajohnny** [comment]
I've just updated the code. It should be working again somewhere today/tomorrow when the cache is cleared

**Comment by henryvandevorst** [comment]
Everything is working again! Thx!
