### ISSUE TITLE
"please first test your address over here."  malware?

### ISSUE THREAD

**Issue by PuckStar** [heyajohnny/afvalinfo#422]
When going to the site: https://4fv4l.nl/
I get this warning:
![image](https://github.com/heyajohnny/afvalinfo/assets/19824801/ff9201d2-f589-4d56-9cc9-e5f73731ecee)

**Comment by heyajohnny** [comment]
Thanks for reporting! 
This is a very minimalistic site and I don't know why it's flagged as phising. 
Maybe a React package I use is flagged. 

I'll try to look into it soon, because the HA config generation part of the site is no longer needed and can be removed. Maybe the warning will go away when I remove that.

**Comment by PuckStar** [comment]
> Thanks for reporting! This is a very minimalistic site and I don't know why it's flagged as phising. Maybe a React package I use is flagged.
> 
> I'll try to look into it soon, because the HA config generation part of the site is no longer needed and can be removed. Maybe the warning will go away when I remove that.

I imagined it must be something like that and didn't really assume you're hosting malicious things on purpose :).
Thanks for looking into it and thanks for your Afvalinfo repo!

**Comment by heyajohnny** [comment]
@PuckStar I've removed the HA generating part of the site. Can you please check again if it's still flagged as phishing?

**Comment by PuckStar** [comment]
> @PuckStar I've removed the HA generating part of the site. Can you please check again if it's still flagged as phishing?

Hi, I checked a few times last days but it's still showing the same warning. Not sure if Malwarebytes needs to scrape your site again and it may take more days or even weeks, before it happens.

**Comment by heyajohnny** [comment]
I'm closing this issue, since there's not much I can do about it. I'm only using these packages that are not very fancy:
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/b32ca788-ead3-4ff2-a1f1-0c5214e813aa)
