### ISSUE TITLE
Error loading attributes 

### ISSUE THREAD

**Issue by tacopiek** [heyajohnny/afvalinfo#423]
![Screenshot_2024-01-06-09-13-54-92_c3a231c25ed346e59462e84656a70e50](https://github.com/heyajohnny/afvalinfo/assets/8972667/4bcad5aa-3905-4fb9-846e-8251cdf63e47)

I keep getting error when adding attributes, i have already completely removed the integration and did a new setup but it keeps giving errors. I have checked the postal code and number in the afval app and there it fully works and shows the correct dates.

**Comment by heyajohnny** [comment]
Maybe create a new entry with a different identifier (see screenshot) and see if that works:
![Screenshot_2024-01-07-14-08-39-991_com android chrome](https://github.com/heyajohnny/afvalinfo/assets/20553716/9fb5323e-cf74-403c-8e5e-56afc01a85b6)

**Comment by tacopiek** [comment]
> Maybe create a new entry with a different identifier (see screenshot) and see if that works: ![Screenshot_2024-01-07-14-08-39-991_com android chrome](https://private-user-images.githubusercontent.com/20553716/294759878-9fb5323e-cf74-403c-8e5e-56afc01a85b6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTA5NjgsIm5iZiI6MTcwNDY1MDY2OCwicGF0aCI6Ii8yMDU1MzcxNi8yOTQ3NTk4NzgtOWZiNTMyM2UtY2Y3NC00MDNjLThlNWUtNTZhZmMwMWE4NWI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE4MDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNWE3ZDVkYmIzYzllNTBjZDRmOTA5NGFjMTAxOGVlMTVlNjA3NjEzMGU0ZTc1N2E5OTc2ZTNiMDU3MDJiMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1J4BcWYe0KUFgyiO661T9XcqmQr5sx7pG367h2rbpqg)

Tried this already:( unfortunately doesnt work.

**Comment by heyajohnny** [comment]
Do you have any errors in your log?
Did you remove afvalinfo from your configuration.yaml (if you updated it from v1 to v2)?

**Comment by tacopiek** [comment]
> Do you have any errors in your log? Did you remove afvalinfo from your configuration.yaml (if you updated it from v1 to v2)?

No errors in the log, and yes removed the yaml config lines.

**Comment by heyajohnny** [comment]
Then I don't know what the problem could be. The last thing that you could consider is deleting the database. (It will automatically be recreated)

**Comment by PuckStar** [comment]
Did you add the correct sensors? There are 2 types of sensor from what I can remember, maybe you have to pick the other one?

**Comment by tacopiek** [comment]
> Then I don't know what the problem could be. The last thing that you could consider is deleting the database. (It will automatically be recreated)

 How do i delete the database? 
I tried all of the sensors, it still isn't working :(

**Comment by PuckStar** [comment]
When you check that address on https://4fv4l.nl/ you can see that Restafval is not included.
When I look here: https://afvalkalender.sliedrecht.nl/ also there is no date for Restafval. Only for the other types.
So it seems like that info is not available already from the Municipality.
Are there fixed dates for that Restafval kliko? Or how does it currently work for you?

Do the sensor for PMD or GFT work properly?

**Comment by tacopiek** [comment]
Oke the issue for me is fixed, i also filled in the municipality name in home assistant and now all the sensors work.
I do have GFT / Restaval / Papier in my municipality which is found ont he 4fv4l website you mentioned ;) 
I was triggered to test with filling in the municipality from this website, which is not clearly documented in the manual. 
thnx for pointing me in this direction!

**Comment by heyajohnny** [comment]
Can you mail me your zipcode (and housenumber)? It could be a bug, because it should work without filling in the municipality. My email is heyajohnny at gmail dot com.

**Comment by heyajohnny** [comment]
@tacopiek Thx for the mail. It was indeed the special characters (character encoding) that was the problem for both Noardeast-Fryslân and Súdwest-Fryslân. 

I've updated the code and it should work now without supplying the municipality

**Comment by johanb7** [comment]
I have this same issue, I've updated to the last version but no change. Also from Súdwest-Fryslân

**Comment by johanb7** [comment]
Where do it put that in? I’m only able to add postalcode and house number.

**Comment by heyajohnny** [comment]
@johanb7 I think that the problem is fixed. Probably had something to do with the special character encoding on Azure with both Noardeast-Fryslân and Súdwest-Fryslân that worked just fine on my local machine, but not on Azure.

**Comment by johanb7** [comment]
Yes, after the update it worked. thanks
