### ISSUE TITLE
Automation met afvalinfo 

### ISSUE THREAD

**Issue by JBSDM** [heyajohnny/afvalinfo#424]
Hallo,

Ik probeer een automatisering te maken dat Home Assistant mij een dag van tevoren om 18:30 een notificatie stuurt met de afvalinfo integratie, maar hij notificeert niet. Heb jij toevallig zoiets al eens gebouwd? Ik probeer de days_until_collection_date te gebruiken.

**Comment by heyajohnny** [comment]
Zelf doe ik eigenlijk niets met automations. Ik heb alles nog vanuit het verleden in Node-red gemaakt en dat werkt prima, dus heb me nooit verdiept in de automations van HA. Wellicht zoiets:
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/b4ec3a34-5a15-4807-8eca-26b4e2081340)
of zo (ik denk dat deze beter zou werken):
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/e9dcfd21-4e7f-440a-a210-6443c73df9c1)

**Comment by heyajohnny** [comment]
Het is alweer even geleden dat dit issue is gemaakt. Ik neem aan dat het gelukt is. Ik sluit dit issue
