### ISSUE TITLE
Gemeente Schiedam

### ISSUE THREAD

**Issue by hofvanta** [heyajohnny/afvalinfo#425]
Municipality Schiedam shows unknown for Bulky Waste. Since January the PMD has changed to Bulky Waste. The 4fv4l.nl site show the correct information. Already removed reboot and reinstalled the integration without result. Keep (for Bulky/grofvuil) 'unknown' state. The  other sensor (paper and bio) working fine.

**Comment by heyajohnny** [comment]
@hofvanta can you please email me your address @ 'heyajohnny at gmail dot com' so I can see what's wrong.
When I checked my test address for Schiedam I don't see any wrong data.

**Comment by heyajohnny** [comment]
If 4fv4l.nl gives you the right information, then it's something local at your HA. Maybe delete your database and reboot HA. That should work
