### ISSUE TITLE
Hattem werkt niet meer

### ISSUE THREAD

**Issue by llewy** [heyajohnny/afvalinfo#428]
https://trashapi.azurewebsites.net/Trash?Location=hattem&ZipCode=8051LV&HouseNumber=12&ShowWholeYear=false&DiftarCode=1&GetCleanprofsData=false

8051LV12 werkt sinds een tijdje niet meer, op de Rova website nog wel; https://inzamelkalender.rova.nl/nl/8051LV/12/

**Comment by heyajohnny** [comment]
Het resultaat van de Rova API hebben ze aangepast, waardoor mijn code kapot ging.
https://www.[rova.nl/api/waste-calendar/upcoming?postalcode=8051LV&houseNumber=12&addition=&take=150](https://www.rova.nl/api/waste-calendar/upcoming?postalcode=8051LV&houseNumber=12&addition=&take=150)
Zojuist alles aangepast en getest. Alles zou morgen ergens weer moeten werken als de cache van mijn API weer geleegd is. Laat maar weten als het weer werkt

**Comment by llewy** [comment]
Werkt alweer, thanks voor de snelle fix!
