### ISSUE TITLE
Issue with house number addition

### ISSUE THREAD

**Issue by hasniek** [heyajohnny/afvalinfo#429]
My 'afvalinfo' gives no data.
Have tested this at https://4fv4l.nl/ with my own address. Our address has 'A' as an addition.
This one gives an error as a result. In the past this did work.

Also tested without addition, then this does work.

**Comment by heyajohnny** [comment]
Looks like it's working just fine on this test location 2311AN 86 A. Maybe you could mail me the specific address that's not working so I could look into it (heyajohnny at gmail dot com)?

**Comment by xtrmenl** [comment]
Don't know if the issues are linked but per today the residual waste can't be checked anymore
nor in ha as via the website mentioned Above

**Comment by heyajohnny** [comment]
@xtrmenl can you give me the municipality/gemeente where the residual waste is interpreted as pbd?

**Comment by xtrmenl** [comment]
Ooststellingwerf 8431

**Comment by heyajohnny** [comment]
@xtrmenl residual waste should be working again somewhere tomorrow

**Comment by heyajohnny** [comment]
I'm closing the issue, since  the original issue is probably solved
