### ISSUE TITLE
Please add: Apeldoorn

### ISSUE THREAD

**Issue by randybnl** [heyajohnny/afvalinfo#43]
The source of the data: https://www.circulus-berkel.nl/afvalkalender/
Thanks!

**Comment by heyajohnny** [comment]
Note to myself: Circulus Berkel = Apeldoorn. Bronckhorst. Brummen. Deventer. Doesburg. Epe. Lochem. Voorst. Zutphen

**Comment by heyajohnny** [comment]
https://afvalkalender.circulus-berkel.nl

**Comment by heyajohnny** [comment]
I've just added all locations for Circulus Berkel. Sorry it took so long. Enjoy and please let me know if all works fine ;)

**Comment by randybnl** [comment]
It works like a charm, thank you! :)
