### ISSUE TITLE
"Het hogeland" giving errors

### ISSUE THREAD

**Issue by pieqiek** [heyajohnny/afvalinfo#430]
It seems that the plugin is having issues with "Het hogeland", on the 4f4l page, it also gives an error.
![image](https://github.com/heyajohnny/afvalinfo/assets/67140828/dc7a7e42-8781-4f42-908f-ad30cfbce839)

At the 4f4l, this is the output:
![image](https://github.com/heyajohnny/afvalinfo/assets/67140828/662cda62-07c0-48da-9201-1789a7ecf37b)

According to the website https://hethogeland.nl/afval/afvalkalender/afvalkalender-2024, there is data beeing returned.
Could you help out fixing this?

**Comment by heyajohnny** [comment]
Er waren wat aanpassingen doorgevoerd bij het hogeland. Zojuist alles weer gefixt. Laat maar weten of alles weer werkt

**Comment by pieqiek** [comment]
Coffee is on it's way!
