### ISSUE TITLE
Feature request: Calendar

### ISSUE THREAD

**Issue by schieska** [heyajohnny/afvalinfo#431]
Is it possible to extend this integration that it creates a calendar entity?

**Comment by heyajohnny** [comment]
I'll look into it when I have some spare time. I really don't know if it's possible or not.

**Comment by asterix778** [comment]
Isnt is possible for you to create an automation that would trigger on de state change from each depending trash type and let it run the service create calendar event?

**Comment by heyajohnny** [comment]
@schieska You  can also download the .ics ical calendar events from my website (in the upper right corner of) [https://4fv4l.nl](https://4fv4l.nl/) and import it in your calendar. I think that this solves the issue:
![image](https://github.com/user-attachments/assets/0abe1d46-127d-4e17-8cbb-09bfaf77ccd2)
