### ISSUE TITLE
Problem with the restafval eniteit

### ISSUE THREAD

**Issue by Freekwie** [heyajohnny/afvalinfo#432]
Hi 

The addon works good 
Butt the restafval eniteit doesnt appear in the list of eniteits 
![image](https://github.com/heyajohnny/afvalinfo/assets/18539468/95e6bd2f-c7ec-4f0a-97b9-de0351660c11)

The place is live is Gemeente Montfoort 

i hope you can fix it 
or is it a problem at my end ?

**Comment by heyajohnny** [comment]
[I think you forgot to add it in the installation step 2:](https://github.com/heyajohnny/afvalinfo?tab=readme-ov-file#installation-step-2)
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/55160950-248c-4234-a8cc-5ca79384977b)
