### ISSUE TITLE
Integration stopped working for Sliedrecht

### ISSUE THREAD

**Issue by joelvdgraaf** [heyajohnny/afvalinfo#433]
Hi, The integration for afvalinfo has stopped working for the place Sliedrecht.
I've been using the integration for some years without issue, but at some point in time (I guess this year) it has stopped. Even at https://4fv4l.nl/ the data cannot be retrieved. 
Can you find what has caused the issue?
For more details please contact me. Thank you!

**Comment by heyajohnny** [comment]
There was an unannounced URL change in the API for Sliedrecht. I've updated the URL and looks like it's working again. Please let me know if it works at your end.

**Comment by joelvdgraaf** [comment]
Yes, everything works like a charm! Thanks for the quick response and fix!
