### ISSUE TITLE
no sensors after adding new location

### ISSUE THREAD

**Issue by adrie-rasp** [heyajohnny/afvalinfo#434]
no sensors when new location is added
The field sensor data was empty

website shows data 
2394AC house Nummer 1

can you assist

**Comment by heyajohnny** [comment]
It's not a real address so it shows no data:
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/731dc2c3-dc23-4d18-b832-a0dc7e3a71c4)
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/19bed9bf-d915-4c5e-a8a7-8c6ed99f773b)
