### ISSUE TITLE
Integration stopped working for 'S-Hertogenbosch

### ISSUE THREAD

**Issue by jngl61** [heyajohnny/afvalinfo#435]
Hi,
I read the issue about the integration not working for sliedrecht and that 4fv4l.nl didn't have a result either. 
My long-standing integration for 'S-Hertogenbosch doesn't work anymore either.  
4fv4l.nl does not give any results. The notification is: "Fout bij ophalen van data. Geen resultaten gevonden"
Is this the same issue as with sliedrecht or is there something wrong with my installation since the last update last week? 
Thanks in advance

**Comment by maffiabaas** [comment]
I have the same issue since today.

**Comment by VelocityMaximus** [comment]
If it uses the afvalstoffendienstkalender.nl as source: the certificate is expired at the 7th of april

**Comment by heyajohnny** [comment]
Looks like it's working just fine now with my test address... Can someone confirm this? @jngl61 @maffiabaas @VelocityMaximus

**Comment by maffiabaas** [comment]
Yes it is working again!

**Comment by jngl61** [comment]
Yes, without any adjustment it is working again. Sorry for reporting this issue

**Comment by heyajohnny** [comment]
@jngl61 no problem! I'm closing this issue then...
