### ISSUE TITLE
Restafval not working in Oldebroek

### ISSUE THREAD

**Issue by JasringStw** [heyajohnny/afvalinfo#437]
It seems the restafval sensor is not working for Oldebroek (8096BR / 2) The test webinterface does show these dates but the integration does not for a while now. Also restafval is not shown for today or tomorrow is it is scheduled.

my Home Assistant and integrtion is fully up-to-date

**Comment by heyajohnny** [comment]
It should work just fine:
https://[trashapi.azurewebsites.net/trash?Location=&ZipCode=8096BR&HouseNumber=2](https://trashapi.azurewebsites.net/trash?Location=&ZipCode=8096BR&HouseNumber=2)
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/8b1d4d48-f34f-402c-9425-1939a6ff90c5)
Make sure that you've added the Residual waste/Restafval when adding the integration:
![image](https://github.com/heyajohnny/afvalinfo/assets/20553716/456b1503-c2ce-437a-bf4a-a993886c6e01)

**Comment by JasringStw** [comment]
re-added the whole integration and indeed it seems to work again. don't know why it didn't before. but solved for now.
