### ISSUE TITLE
No data coming in.

### ISSUE THREAD

**Issue by accountant73** [heyajohnny/afvalinfo#440]
Hi

Misschien doe ik iets fout maar de status van alle sensoren blijven op Unknown staan na 2 dagen. Atributes " volgende ophaalmoment"  geeft dit ook aan. Wat zou het kunnen zijn?

**Comment by heyajohnny** [comment]
Ik neem aan dat je gewoon de installatie stappen hebt doorlopen? 

Kan je wat meer informatie geven over je adres? Wellicht een postcode (en als het even kan een huisnummer waarop het niet werkt).
Welke afvaltypes heb je geselecteerd om weer te geven?

**Comment by DaWacko87** [comment]
Hallo @heyajohnny,

Zojuist kwam ik er ook achter dat ik sinds een week geen data meer ontvang. Wanneer ik op www.4fv4al.nl mijn adresgegevens invul krijg ik een foutmelding. Het betreft de gemeente Echt- Susteren.

**Comment by heyajohnny** [comment]
@DaWacko87 Ik zie inderdaad dat Echt-Susteren onderwater ineens een andere API gebruikt. Het lijkt op de opzetkalender. Ik zal kijken of ik dit weer rechtgetrokken krijg

**Comment by heyajohnny** [comment]
Als het goed is zou Echt-Susteren weer moeten werken

**Comment by DaWacko87** [comment]
Hij doet het inderdaad weer. Dankjewel voor de snelle reactie!

**Comment by heyajohnny** [comment]
Oke, thnx! I'm closing the issue then
