### ISSUE TITLE
Almere

### ISSUE THREAD

**Issue by Rowdy2811** [heyajohnny/afvalinfo#444]
Hello,
In Almere they have combined the residual waste and plastic, 
I no longer see this in the information. 
<img width="243" alt="image" src="https://github.com/heyajohnny/afvalinfo/assets/49291262/92ddc37a-15e6-4df3-9163-802caed9c1aa">
is it possible to look at this? 
I have added a printscreen from the Almere agenda

<img width="814" alt="image" src="https://github.com/heyajohnny/afvalinfo/assets/49291262/e6df4424-98ae-4e0e-9da6-353cf46be3a2">

**Comment by heyajohnny** [comment]
I've made a fix. The dates should occur for both pbd and restafval.
Please let me know if all works as expected

**Comment by Rowdy2811** [comment]
Hello Johnny,
Thank you for the fix.
I can see the date now.
<img width="246" alt="image" src="https://github.com/user-attachments/assets/f20176a6-11c4-416d-a73b-e20d6e81726d">
