### ISSUE TITLE
Afvalinfo werkt niet voor gemeente Tilburg

### ISSUE THREAD

**Issue by Floris039** [heyajohnny/afvalinfo#448]
De info heeft een tijdje gewerkt. Nu klopt deze niet. Er staat dat morgen textiel wordt opgehaald maar eigenlijk wordt morgen papier & plastic opgehaald (duobak)

Postcode 5071 AG

**Comment by heyajohnny** [comment]
Note to myself: problem = dhm
https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=5071AG&street=&huisnummer=1&toevoeging=&app_name=trashapi&platform=web&afvaldata=&langs=nl

Also need to changee + test this fix again
https://github.com/heyajohnny/afvalinfo/issues/444

**Comment by heyajohnny** [comment]
@Floris039 Als het goed is zou het morgen ergens weer goed moeten werken, als de cache is geleegd. Laat maar weten of dit ook zo is.

**Comment by Floris039** [comment]
Ja hij werkt! Top bedankt!
