### ISSUE TITLE
Gemeente Meppel stopped working 

### ISSUE THREAD

**Issue by Wesleyl89** [heyajohnny/afvalinfo#453]
It seems gemeente Meppel stopped working. If I check https://4fv4l.nl/ it looks like it can't get any data

Postal; 7944NN, number 7

**Comment by heyajohnny** [comment]
Meppel changed from provider Ximmio to MijnAfvalWijzer. I've just updated the provider. Please let me know if all works again.

**Comment by Wesleyl89** [comment]
Nice, it works again! Thanks for the quick response!
![image](https://github.com/user-attachments/assets/fb4e959e-0d84-4a31-93e3-22d641a0aa78)
