### ISSUE TITLE
Gemeente Beek (Limburg) stoped working

### ISSUE THREAD

**Issue by stein1998** [heyajohnny/afvalinfo#454]
It seems gemeente Beek stopped working. If I check https://4fv4l.nl/ it looks like it can't get any data. 

Postal; 6191HW, number 25

**Comment by heyajohnny** [comment]
The problem is at the source (RWM):
![image](https://github.com/user-attachments/assets/1649b1c0-a541-4211-8836-44373077fbe1)
There are just no pickup dates for your address. I think you should contact RWM or your gemeente for this problem.
