### ISSUE TITLE
Only English garbage names.

### ISSUE THREAD

**Issue by jayjayvm** [heyajohnny/afvalinfo#455]
Even though I have clicked the box in settings NL, I do not see "PMD, Groen or others" no Dutch names, I only get hard to use English garbage descriptions like "Biodegradable waste, Residual waste".

How-to solve this?

Problem solved, by renaming, only problem remaining is that in our place during the summer months not only the regular schedule is running, but they always collect GFT, so there are two collections a day.

**Comment by heyajohnny** [comment]
It's because your HA language is set to English. You can overwrite the names:
https://github.com/heyajohnny/afvalinfo?tab=readme-ov-file#optional-installation-step-3-change-friendly-name
