### ISSUE TITLE
Entities halen geen data op

### ISSUE THREAD

**Issue by robbavel** [heyajohnny/afvalinfo#456]
Integratie geinstaleerd volgens documentatie

last update blijft verversen
komt verder geen data binnen.
error: true

5151AB 12

**Comment by heyajohnny** [comment]
Dat klopt. Het adres bestaat ook niet...
![image](https://github.com/user-attachments/assets/cf7168f7-06c1-44b9-b3ad-bfcdc171d26f)

**Comment by robbavel** [comment]
Excuus!

Ik bedoelde 5121KB (zo heb ik hem ook geconfigureerd)

**Comment by heyajohnny** [comment]
5121KB 12 lijkt het gewoon te doen:
![image](https://github.com/user-attachments/assets/0e022eaf-6138-4c79-9755-91e3f9149661)
Ben je niet iets [vergeten](https://github.com/heyajohnny/afvalinfo?tab=readme-ov-file#installation-step-2) tijdens het installeren/configureren?
