### ISSUE TITLE
Sensors are empty

### ISSUE THREAD

**Issue by vagy66** [heyajohnny/afvalinfo#457]
Installed the Integration, but the sensors return with no values.
![image](https://github.com/user-attachments/assets/c91c539a-220d-4e64-95d4-7245c26525b2)

What am I doing wrong?

**Comment by heyajohnny** [comment]
I need some more information. Can you give me your zip code? Have you already tried your address in [4fv4l.nl](https://4fv4l.nl) ?

**Comment by vagy66** [comment]
Hi,

yes, I tried it and worked, see below:
![image](https://github.com/user-attachments/assets/7f55322f-d0df-4b26-a33b-1a8e62ce40f1)

**Comment by heyajohnny** [comment]
It should be fixed. There was a bug that was looking up the location from the database, but there was a faulty location in the database and this shouldn't occur anymore. Please let me know if everything works again.

**Comment by vagy66** [comment]
Hi, thanks a lot. 
I see now the dates.

**Comment by 3dmadnessnl** [comment]
Ik heb het zelfde probleem online getest ziet hij de datums  maar niet in ha

**Comment by heyajohnny** [comment]
@3dmadnessnl 
Heb je toevallig een postcode, zodat ik dit wellicht kan reproduceren?
