### ISSUE TITLE
Data hebben een " karakter op het einde erbij gekregen?

### ISSUE THREAD

**Issue by Asgorath777** [heyajohnny/afvalinfo#458]
Het viel mij op dat bij de data van ophaalmomenten er een " karakter op het einde meekomt. Waardoor de data niet meer goed mogelijk als datum herkend wordt. 
<img width="574" alt="Scherm­afbeelding 2024-11-01 om 23 11 23" src="https://github.com/user-attachments/assets/650cf29d-c88e-4e1d-8665-1a5ecaf487e2">

**Comment by heyajohnny** [comment]
Dat is wel bijzonder... Heb je wellicht wat meer informatie voor mij. 
- Welke Home Assistant versie gebruik je?
- Is dit vanuit het niets ontstaan, of na een update / aanpassing van instellingen?
- Zou je een soortgelijke screenshot van de developer tools -> states kunnen maken, zoals deze (met enkele afvalinfo sensors in beeld):
![image](https://github.com/user-attachments/assets/2a2e3182-6481-40bc-a448-a51c0b57aa11)

**Comment by Asgorath777** [comment]
OMG zit er een 'schaam' emotie ergens? Er stond inderdaad een " in het data-format. Snap niet zo goed waarom en hoe, want het is een recent dingetje en ik gebruik de integratie al enorm lang. Maar dat was dus het probleem. Kortom 'User Error' van deze user. Sorry voor het ticket. Ik dacht echt dat het spontaan ontstaan was recentelijk.
