### ISSUE TITLE
Cleanprofs GFT, geen data Alkmaar

### ISSUE THREAD

**Issue by vrolukkevriend** [heyajohnny/afvalinfo#459]
Ik krijg al enige weken geen data meer door voor Cleanprofs GFT in Alkmaar, postcode 1822ME. Ben al door de settings gegaan, maar daar lijkt niets fout te staan.

**Comment by heyajohnny** [comment]
De API is aangepast. Ik zal deze binnenkort updaten. Note to myself:
https://cleanprofs.jmsdev.nl/api/get-plannings-address?zipcode=xxxxxx&house_number=xx&start_date=2024-12-14&end_date=2025-03-31&code=crm

**Comment by heyajohnny** [comment]
@tmudde Zojuist de code aangepast naar de nieuwe API. Voor 2024 en 2025 krijg je nu data. Zou je kunnen laten weten of alles werkt zoals verwacht?

**Comment by tmudde** [comment]
Yep, ik zie weer een datum verschijnen. Dank je wel!!

<img width="388" alt="image" src="https://github.com/user-attachments/assets/5a91f6e0-45d3-48ad-b84c-b1cfd1e88025" />
