### ISSUE TITLE
Missing gft for Westerkwartier

### ISSUE THREAD

**Issue by githubnoobjk** [heyajohnny/afvalinfo#46]
I am missing the gft for Westerkwartier. It is mostly collected in the week that "restafval" is not collected, but not necessary on the same day of the week.

**Comment by heyajohnny** [comment]
It should be working... Maybe it's called different in some locations. What location / city do you use?

**Comment by githubnoobjk** [comment]
Oh I am very sorry. My mistake. I forgot to add that resource
