### ISSUE TITLE
Failed to unload

### ISSUE THREAD

**Issue by tuxick** [heyajohnny/afvalinfo#461]
Can't add/remove sensors, getting "failed to unload". Log says:

`homeassistant.config_entries.OperationNotAllowed: The config entry 'Afvalinfo for home' (afvalinfo) with entry_id 'xx' cannot be unloaded because it is in the non recoverable state ConfigEntryState.FAILED_UNLOAD`

**Comment by heyajohnny** [comment]
What version are you using? Maybe a restart will fix this?
![image](https://github.com/user-attachments/assets/25cf9833-a31b-40d5-8062-61e3e9e7d559)
Please let me know if your issue is fixed?

**Comment by tuxick** [comment]
> What version are you using? Maybe a restart will fix this? 

Removing the integration/plugin and configuring with new settings works.

**Comment by tuxick** [comment]
> Removing the integration/plugin and configuring with new settings works.

Mind, the "failed to unload" issue remains. The only way to reconfigure is reinstall.

**Comment by heyajohnny** [comment]
I've just released a new version (2.1.7). The reconfigure should work again

**Comment by tuxick** [comment]
> I've just released a new version (2.1.7). The reconfigure should work again

Works, thanks!
