### ISSUE TITLE
Sensors empty Maassluis.

### ISSUE THREAD

**Issue by Dennisd80** [heyajohnny/afvalinfo#463]
For some time now the intergration isn't working for me (maassluis, molenwijk) Even cleanprofs, has the same issue.

Today i tried to see what could be wrong and removed the intergration, redownloaded it and re added it to my devices with the correct information. So no postcode, house number or prefix only Gemeente and wijk.

Unfortunately without results, although i did get this error in my log: 

```
Logger: custom_components.afvalinfo.const.const
Bron: custom_components/afvalinfo/location/trashapi.py:105
integratie: Afvalinfo ([documentatie](https://github.com/heyajohnny/afvalinfo), [problemen](https://github.com/heyajohnny/afvalinfo/issues))
Eerst voorgekomen: 23:15:39 (3 gebeurtenissen)
Laatst gelogd: 23:21:16

Error occurred. Please check the address with postcode: '3361AB' and huisnummer: 1'' on the website of your local waste collector in the gemeente: 'maassluis'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working 
```

I tried to do the same on 4fvl.nl but it i get an error: fout bij het ophalen van data, geen resultaten gevonden

**Comment by hvancalker** [comment]
Same error for me in gemeente Het Hogeland: fout bij het ophalen van data, geen resultaat gevonden. Heeft tot paar dagen geleden perfect gewerkt

**Comment by heyajohnny** [comment]
@Dennisd80 Should be working again (untill they decide to change their website again...)

**Comment by heyajohnny** [comment]
@hvancalker This can take some time, because Het Hogeland decided to remove the calendar links from their site and they don't have a omrin api implementation, so i need to make a custom omrin website crawler only for this municipality.

**Comment by Dennisd80** [comment]
> @Dennisd80 Should be working again (untill they decide to change their website again...)

Alll working agina

**Comment by jonteriele** [comment]
@heyajohnny did they change the website again maybe?

I am currently facing the same issue Dennisd80 had.

`Error occurred. Please check the address with postcode: '' and huisnummer: '''' on the website of your local waste collector in the gemeente: 'maassluis'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working`

**Comment by heyajohnny** [comment]
@jonteriele They keep changing their website 👎 
It should work again (for now)

**Comment by jonteriele** [comment]
> [@jonteriele](https://github.com/jonteriele) They keep changing their website 👎 It should work again (for now)

Yeah, I already thought that was the case! Bit frustrating 👎 
But thanks for the fast response and fix @heyajohnny!
