### ISSUE TITLE
Using hass.helpers.entity_registry (deprecated?)

### ISSUE THREAD

**Issue by lenwar** [heyajohnny/afvalinfo#464]
Hi,

I'm getting the following error:

Detected that custom integration 'afvalinfo' accesses hass.helpers.entity_registry, which should be updated to import functions used from entity_registry directly at custom_components/afvalinfo/sensor.py, line 123: entity_registry = hass.helpers.entity_registry.async_get(). This will stop working in Home Assistant 2025.5, please create a bug report at https://github.com/heyajohnny/afvalinfo/issues

Using:
Core 2024.12.5
Supervisor 2024.12.0
Operating System 14.1

**Comment by heyajohnny** [comment]
Thanks! Should be fixed in the new version 2.1.8

**Comment by lenwar** [comment]
Confirmed! 😊
Thanks for the quick fix!
