### ISSUE TITLE
hoe werkt dit?

### ISSUE THREAD

**Issue by ixionline** [heyajohnny/afvalinfo#48]
Hallo,

Ik heb deze module geïnstalleerd en de stappen gevolgd zoals beschreven. Krijg ik nog iets van een kaart te zien wanneer het opgehaald wordt? 

Op dit moment zie ik namelijk niks terug, ook niet wanneer dat zij komen.

Wellicht heb ik iets gemist?

**Comment by ixionline** [comment]
zelf vind ik dit wel mooi gedaan met de iconen e.d.

https://community.home-assistant.io/t/custom-component-afvalbeheer-support-for-multiple-waste-collectors/83437/8

Is dat ook mogelijk voor deze custom component?

**Comment by heyajohnny** [comment]
> zelf vind ik dit wel mooi gedaan met de iconen e.d.

https://community.home-assistant.io/t/custom-component-afvalbeheer-support-for-multiple-waste-collectors/83437/8

Is dat ook mogelijk voor deze custom component?
> 

Via je lovelace config kan je iets soortgelijks voor dit custom component maken ja.

**Comment by heyajohnny** [comment]
> Ik heb deze module geïnstalleerd en de stappen gevolgd zoals beschreven. Krijg ik nog iets van een kaart te zien wanneer het opgehaald wordt?
Op dit moment zie ik namelijk niks terug, ook niet wanneer dat zij komen.
Wellicht heb ik iets gemist?

Ik weet niet wat je voor data in je configuration.yaml file hebt staan...
Zoiets als dit zou moeten werken:
![image](https://user-images.githubusercontent.com/20553716/78166798-a81d0780-744d-11ea-8842-2dddfe01de7f.png)

**Comment by ixionline** [comment]
> 
> 
> > Ik heb deze module geïnstalleerd en de stappen gevolgd zoals beschreven. Krijg ik nog iets van een kaart te zien wanneer het opgehaald wordt?
> > Op dit moment zie ik namelijk niks terug, ook niet wanneer dat zij komen.
> > Wellicht heb ik iets gemist?
> 
> Ik weet niet wat je voor data in je configuration.yaml file hebt staan...
> Zoiets als dit zou moeten werken:
> ![image](https://user-images.githubusercontent.com/20553716/78166798-a81d0780-744d-11ea-8842-2dddfe01de7f.png)

 
![afbeelding](https://user-images.githubusercontent.com/62649521/78178045-541b1e80-745f-11ea-9718-eaa3f30ab160.png)

Wat zou ik dan moeten zien?

**Comment by heyajohnny** [comment]
Je gaat helaas niets zien, aangezien ik voor Cuijk de data van deafvalapp.nl gebruik.
![image](https://user-images.githubusercontent.com/20553716/78181547-e540c400-7464-11ea-8e2e-a2848bc8bb02.png)
