### ISSUE TITLE
Meerlanden werkt niet meer

### ISSUE THREAD

**Issue by rossiexp** [heyajohnny/afvalinfo#49]
Sinds de Meerlanden een nieuwe website heeft geintroduceerd werkt Afvalinfo niet meer.

**Comment by heyajohnny** [comment]
Ze hebben het inderdaad helemaal omgegooid.

Note to myself: 
- same-ish as Meppel
- https://inzamelkalender.meerlanden.nl/

**Comment by heyajohnny** [comment]
I just updated the code. Please let me know if it works again.

**Comment by rossiexp** [comment]
Ja het werkt weer, dank je wel
