### ISSUE TITLE
Enschede

### ISSUE THREAD

**Issue by toudewolbers** [heyajohnny/afvalinfo#5]
Hi, can you please add Enschede?
Like to use this one.

regards, 

Tim

**Comment by heyajohnny** [comment]
Yeah sure... If i now where I can get the data from.

**Maybe you can point me to the right direction?** I did a quick Google search for 'Enschede afvalkalender' and the results are pointing me to 'https://www.twentemilieu.nl/enschede/afval/afvalkalender'.

When I do some random 'postcode' + 'huisnummer' searches for Enschede I'm always getting this result.

> De door u opgegeven postcode valt niet in het werkgebied van Twente Milieu of is een bedrijfsadres. Ga naar de algemene pagina.

**Comment by toudewolbers** [comment]
There is one that works for enschede:
https://www.home-assistant.io/integrations/twentemilieu/
But yours is better so like to use that one. Perhaps you can sneakpeak into this script where he gets the information from. But when i input my code: 7545XD nr 1 for example i get a verry nice page. Would be great to have that.

**Comment by heyajohnny** [comment]
I've added Enschede and a couple of other places to the integration.
For some unknown reason 'postcode' 7545XD 'streetnumber' 1 isn't valid. 
'postcode' 7545XD 'streetnumber' 2 does work...
