### ISSUE TITLE
Please add: Heeze

### ISSUE THREAD

**Issue by jaspervanisterdael** [heyajohnny/afvalinfo#53]

**Comment by heyajohnny** [comment]
Note to myself: 
-Add location as blink
-gemeente Heeze-Leende
https://mijnblink.nl/adres/5591LX:1

**Comment by heyajohnny** [comment]
I've just added all the Blink locations including Heeze.
Please let me know if everything works fine or not ;)

**Comment by jaspervanisterdael** [comment]
hey, it was working fine, but now im getting the following error: 2020-04-27 20:31:11 WARNING (SyncWorker_0) [custom_components.afvalinfo.const.const] Error occurred while splitting data: AttributeError("'NoneType' object has no attribute 'i'")

**Comment by heyajohnny** [comment]
I've updated the logging message. The warning is an indication that probably a certain trash type is not supported on your location. You can see which trash type has this issue now, after you update afvalinfo

**Comment by jaspervanisterdael** [comment]
they were working before. i checked the local trash website, the info isn't
currently available, so that could be the problem...

**Comment by heyajohnny** [comment]
The missing info on the local trash site must be the problem then. Sorry, but there isn't anything I can fix, so you just have to wait 'till the local trash site shows the info again.
