### ISSUE TITLE
Platform error after update eb53a5b

### ISSUE THREAD

**Issue by ManCaveMedia** [heyajohnny/afvalinfo#54]
After the installation of update eb53a5b the configuration checker shows an error:
```
Platform error sensor.afvalinfo - 
No module named 'custom_components.afvalinfo.location.veldhoven'
```

**Comment by heyajohnny** [comment]
I've just pushed an update. It should be working again after the update

**Comment by ManCaveMedia** [comment]
Thanks!
I notice the missing veldhoven.py just after I posted the issue.
Everything seems fine after the new update.

I appreciate all the work you put into this!

**Comment by heyajohnny** [comment]
No problem! It's a nice hobby project and hoping to help a lot of people with it.
