### ISSUE TITLE
Please add Ridderkerk

### ISSUE THREAD

**Issue by 0xi3** [heyajohnny/afvalinfo#55]
Here is where to find the information when they pickup the garbage:
https://bar-afvalbeheer.simmicrosite.nl/afvalkalender

**Comment by heyajohnny** [comment]
Note to myself:
same-ish as almere
Add location as bar. 
Bar is used in Barendrecht, Albrandswaard en Ridderkerk
companyCode: "bb58e633-de14-4b2a-9941-5bc419f1c4b0"

**Comment by heyajohnny** [comment]
I've just added Bar afval including Ridderkerk. Please let me know if all works fine ;)
