### ISSUE TITLE
add Noardeast Fryslân

### ISSUE THREAD

**Issue by hessel-a** [heyajohnny/afvalinfo#56]
Gemeente: https://www.noardeast-fryslan.nl/
Afvaldienst: https://www.omrin.nl/bij-mij-thuis/afval-regelen/afvalkalender

Noardeast Fryslân
Plaatsnamen:		
Aalsum, Anjum, Augsbuurt, Blije, Bornwird, Brantgum, Broeksterwâld, Burdaard, Burum, Damwâld, De Falom, De Westereen, Dokkum, Driezum, Ee, Engwierum, Feanwâlden, Ferwert, Foudgum, Ginnum, Hallum, Hantum, Hantumeruitburen, Hantumhuizen, Hegebeintum, Hiaure, Holwerd, Jannum, Jislum, Jouswier, Kollum, Kollumerpomp, Kollumerzwaag, Lichtaard, Lioessens, Marrum, Metslawier, Moddergat, Morra, Munnekezijl, Nes, Niawier, Oosternijkerk, Oostrum, Oudwoude, Paesens, Raard, Readtsjerk, Reitsum, Rinsumageast, Sibrandahûs, Ternaard, Triemen, Veenklooster, Waaxens, Wâlterswâld, Wânswert, Warfstermolen, Westergeest, Wetsens, Wierum, Zwagerbosch

**Comment by hessel-a** [comment]
Also this is a quick fix. Omrin is in your list. Just update/add the town names.

**Comment by heyajohnny** [comment]
Thnx for pointing this out. I'll try to add it this evening

**Comment by heyajohnny** [comment]
I've just added Noardeast Fryslân. Please let me know if it works.

**Comment by Alfagek** [comment]
I did try to use noardeast fryslan, but i don't get any info.
I did try at location: noardeast fryslan, Noardeast Fryslân, Noardeast Fryslan, and the config down here.

  - platform: afvalinfo
    resources:
      - gft
      - kerstboom
      - pbd
      - papier
      - restafval
      - textiel
      - trash_type_today
      - trash_type_tomorrow
    location: Feanwâlden
    postcode: 9269TP
    streetnumber: 40
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365

**Comment by hessel-a** [comment]
Dit werkt voor mij Mogelijk staan je tabs fout
sensor:
  - platform: afvalinfo
    resources: 
        - gft
        - kerstboom
        - papier
        - pbd
        - restafval
        - textiel
        - trash_type_today
        - trash_type_tomorrow
    # city: noardeast fryslan
    location: noardeast fryslan
    postcode: 9074DL
    streetnumber: 100
    dateformat: '%d-%m-%Y'
    timespanindays: 365

**Comment by Alfagek** [comment]
> Dit werkt voor mij Mogelijk staan je tabs fout
> 
> ```
> sensor:
>   - platform: afvalinfo
>     resources: 
>         - gft
>         - kerstboom
>         - papier
>         - pbd
>         - restafval
>         - textiel
>         - trash_type_today
>         - trash_type_tomorrow
>     location: noardeast fryslan
>     postcode: 9074DL
>     streetnumber: 100
>     dateformat: '%d-%m-%Y'
>     timespanindays: 365
> ```
Bedankt voor je snelle reactie Hessel. 
Had inderdaad wat 'tabs' fout staan.

Maar krijg nu de volgende fout in de logs (ook met het adres wat ik moet gebruiken): 

Error occurred. Please check the address with postcode: '9074DL' and huisnummer: '100' on the website of your local waste collector in the gemeente: 'noardeast fryslan'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

**Comment by hessel-a** [comment]
Wel ff je eigen post code en huisnummer gebruiken. Wat je woont denk niet in Hallum

**Comment by Alfagek** [comment]
> Wel ff je eigen post code en huisnummer gebruiken. Wat je woont denk niet in Hallum

Die had ik ook gebruikt, maar dan krijg ik het zelfde. Vandaar dat ik jou "test" postcode ook had geprobeerd ;-)
postcode: 9269TP huisnummer 40

**Comment by heyajohnny** [comment]
Alleen als je postcode in Omrin werkt, werkt het hier ook.
De rest van Noardeast Fryslan wordt helaas niet ondersteund, omdat de gemeente geen informatie op postcode niveau heeft voor het ophalen van afval.

**Comment by hessel-a** [comment]
Ok. When I see in the list i see  "dantumadeel f" note the "f" on the end. I dont know if that it is a error. Just try both

> > Dit werkt voor mij Mogelijk staan je tabs fout
> > ```
> > sensor:
> >   - platform: afvalinfo
> >     resources: 
> >         - gft
> >         - kerstboom
> >         - papier
> >         - pbd
> >         - restafval
> >         - textiel
> >         - trash_type_today
> >         - trash_type_tomorrow
> >     location: noardeast fryslan
> >     postcode: 9074DL
> >     streetnumber: 100
> >     dateformat: '%d-%m-%Y'
> >     timespanindays: 365
> > ```
> 
> Bedankt voor je snelle reactie Hessel.
> Had inderdaad wat 'tabs' fout staan.
> 
> Maar krijg nu de volgende fout in de logs (ook met het adres wat ik moet gebruiken):
> 
> Error occurred. Please check the address with postcode: '9074DL' and huisnummer: '100' on the website of your local waste collector in the gemeente: 'noardeast fryslan'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

Ok. When I see in the list i see  "dantumadeel f" note the "f" on the end. I dont know if that it is a error. Just try both

**Comment by Alfagek** [comment]
Bedankt Johnny, had inderdaad ook al snel even geprobeerd om Omrin te gebruiken.
Maar helaas word dit niet ondersteunt. Ook wel begrijpelijk, aangezien ik begrepen heb dat het nog steeds een eigen ophaaldienst is van de gemeente Noardeast Fryslân.

Dan word het helaas voor hem geen afval in Home Assistent 

> Alleen als je postcode in Omrin werkt, werkt het hier ook.
> De rest van Noardeast Fryslan wordt helaas niet ondersteund, omdat de gemeente geen informatie op postcode niveau heeft voor het ophalen van afval. Zo te zien werkt je postcode niet in Omrin.

**Comment by Alfagek** [comment]
> Ok. When I see in the list i see "dantumadeel f" note the "f" on the end. I dont know if that it is a error. Just try both
> 
> > > Dit werkt voor mij Mogelijk staan je tabs fout
> > > ```
> > > sensor:
> > >   - platform: afvalinfo
> > >     resources: 
> > >         - gft
> > >         - kerstboom
> > >         - papier
> > >         - pbd
> > >         - restafval
> > >         - textiel
> > >         - trash_type_today
> > >         - trash_type_tomorrow
> > >     location: noardeast fryslan
> > >     postcode: 9074DL
> > >     streetnumber: 100
> > >     dateformat: '%d-%m-%Y'
> > >     timespanindays: 365
> > > ```
> > 
> > 
> > Bedankt voor je snelle reactie Hessel.
> > Had inderdaad wat 'tabs' fout staan.
> > Maar krijg nu de volgende fout in de logs (ook met het adres wat ik moet gebruiken):
> > Error occurred. Please check the address with postcode: '9074DL' and huisnummer: '100' on the website of your local waste collector in the gemeente: 'noardeast fryslan'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working

Thanks Hessel. I did try both. With the F i get the same error in HA Log. Without the F i don't get any error, but i also don't get info.

It's sad for him, but if there isn't a sollution, then he don't have a garbage info in Home Assistent.
