### ISSUE TITLE
Please add Swalmen

### ISSUE THREAD

**Issue by Skottelbraai** [heyajohnny/afvalinfo#57]

**Comment by heyajohnny** [comment]
Note to myself: 
-gemeente Roermond
-Mijnafvalwijzer

**Comment by heyajohnny** [comment]
I've just added Roermond including Swalmen. Please let me know if it works as expected ;)

**Comment by Skottelbraai** [comment]
Roermond Swalmen is working.
Thanks.
Met vriendelijke groet,

F.H.M. Tummers
frank.tummers@ziggo.nl
