### ISSUE TITLE
Difference between sensor.afvalinfo_today and sensor.afvalinfo_today_2

### ISSUE THREAD

**Issue by ManCaveMedia** [heyajohnny/afvalinfo#58]
Not an issue, but didn't know how to ask this.
In my list of entities I have 2 sensors for trash_type_today: sensor.afvalinfo_today and sensor.afvalinfo_today_2
Same for trash_type_tomorrow: sensor.afvalinfo_tomorrow and sensor.afvalinfo_tomorrow_2

Sometimes the trash that gets collected tomorrow is in sensor.afvalinfo_tomorrow and sometimes it's in sensor.afvalinfo_tomorrow_2. This makes it harder to automate a notification, since I have to check both.

Can you please help me understand how these work and why there's two of both (today and tomorrow)?

My setup looks like this:
```
- platform: afvalinfo
  resources:                              # (at least 1 required) gft, papier, pbd, restafval, textiel
    - restafval
    - papier
    - gft
    - trash_type_today
    - trash_type_tomorrow
  city: !secret personal_city             # (required, default = sliedrecht)
  postcode: !secret personal_zipcode      # (required, default = 3361AB)
  streetnumber: !secret personal_number   # (required, default = 1)
  dateformat: '%d-%m'                     # (optional, default = %d-%m-%Y) day-month-year '%a %-d %b'
  timespanindays: 365                     # (optional, default = 365) number of days to look into the future

```

**Comment by heyajohnny** [comment]
Thanks for pointing it out. It was a bug and it should be fixed now. After you update, you should only see:
-sensor.afvalinfo_today
-sensor.afvalinfo_tomorrow

Please let me know if it works.

**Comment by ManCaveMedia** [comment]
Great! It works...
The '_2' sensors are gone.

So it was an issue after all 😀
