### ISSUE TITLE
Please add Haarlem

### ISSUE THREAD

**Issue by HenkSiemer** [heyajohnny/afvalinfo#59]
Or Spaarnelanden

**Comment by heyajohnny** [comment]
Note to myself:
https://afvalwijzer.spaarnelanden.nl/

**Comment by heyajohnny** [comment]
I've just added Spaarnelanden, including Haarlem. Please let me know if all works fine or not ;)

**Comment by HenkSiemer** [comment]
Works like a charm, Thanx.

1 coffee coming your way 😊

 

 

M.vr.gr.

Henk Siemer

 

Van: heyajohnny <notifications@github.com> 
Verzonden: zondag 19 april 2020 20:16 uur
Aan: heyajohnny/afvalinfo <afvalinfo@noreply.github.com>
CC: HenkSiemer <hsiemer@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [heyajohnny/afvalinfo] Please add Haarlem (#59)

 

I've just added Spaarnelanden, including Haarlem. Please let me know if all works fine or not ;)
