### ISSUE TITLE
Please add: Roelofarendsveen

### ISSUE THREAD

**Issue by Jozziej** [heyajohnny/afvalinfo#60]
participating municipalities

Bodegraven-Reeuwijk
Gouda
Kaag en Braassem
Krimpenerwaard
Montfoort
Nieuwkoop
Waddinxveen
Zuidplas

url: https://afvalkalender.cyclusnv.nl/adres/2371AS:1

**Comment by heyajohnny** [comment]
I've just added all locations for Cyclus, including Roelofarendsveen. Please let me know if it all works as expected. Enjoy ;)
