### ISSUE TITLE
Return state 'Today' and 'Tomorrow '

### ISSUE THREAD

**Issue by RubenDijk** [heyajohnny/afvalinfo#61]
Pls add a return state for the sensors 'Today' and 'Tomorrow'

I have now manually added a return state 'geen' (none)
It now returns in home-assistant as 'geen'. (none)
without pairing back, the sensor returns with 'unknown' and an empty field. now i look at the status of the sensor and let it change on an image.

![image](https://user-images.githubusercontent.com/18540436/79110185-29dc3180-7d7a-11ea-95ac-acb59231cedd.png)

`def update(self):
        self.data.update()
        self._last_update = date.today().strftime("%d-%m-%Y %H:%M")
        self._state = "geen"  # reset the state
        tomorrow = (date.today() + timedelta(days=1)).strftime(self.date_format)
        for entity in self._entities:
            if entity.state == tomorrow:
                self._state = (self._state + " " + entity.name.split()[1]).strip().lower()`

**Comment by heyajohnny** [comment]
The return state is an empty string "" when there is no trash to pick up

**Comment by RubenDijk** [comment]
When the state returns with an empty state, the state for home assistant is unknown. it is not possible to change an image on this.

**Comment by heyajohnny** [comment]
I've pushed an update. The return value of the 'Today' and 'Tomorrow' sensors will be "none" if there is no trash to pick up. Will this be a solution for your issue?

**Comment by RubenDijk** [comment]
This would indeed be a solution. 
Thank you for your cooperation and quick response.

**Comment by heyajohnny** [comment]
No problem ;) I'm closing the issue.
