### ISSUE TITLE
please add Vlaardingen

### ISSUE THREAD

**Issue by PanjaTuig** [heyajohnny/afvalinfo#62]
word opgehaald door irado

**Comment by heyajohnny** [comment]
Note to myself:
Ontstaan uit verschillende gemeentelijke reinigingsdiensten, heeft Irado jarenlange ervaring in dienstverlening aan lokale overheden. Op dit moment zijn we actief in de gemeente Capelle aan den IJssel, Schiedam, Rozenburg en Vlaardingen.

https://www.irado.nl/bewoners/afvalkalender

**Comment by heyajohnny** [comment]
I've just added Irado including Vlaardingen. Enjoy ;)
