### ISSUE TITLE
Please add: Zevenaar

### ISSUE THREAD

**Issue by pingelhoek** [heyajohnny/afvalinfo#65]
Can you please add Zevenaar

Source: https://www.mijnafvalwijzer.nl/nl/6903GM/2/

If i look at the app information there are more municipalities:
https://play.google.com/store/apps/details?id=nl.addcomm.afvalwijzer&hl=nl

Aa en Hunze, Albrandswaard, Alkmaar, Altena, Amstelveen, Assen, Barendrecht, Barneveld, Beek, Beekdaelen, Beesel, Bergen op Zoom, Bernheze, Best, Borger-Odoorn, Boxtel, Breda, Brielle, Castricum, De Ronde Venen, De Wolden, De Bilt, Doetinchem, Dongen, Dronten, Duiven, Elburg, Ermelo, Etten-Leur, Geertruidenberg, Gilze en Rijen, Goirle, Halderberge, Harderwijk, Heerhugowaard, Heiloo, Hilvarenbeek, Hoogezand-Sappemeer, Horst aan de Maas, Houten, Kampen, Krimpen aan den IJssel, Lansingerland, Leiden, Leiderdorp, Leudal, Leusden, Loon op Zand, Lopik, Maasgouw, Meierijstad, Menterwolde, Moerdijk, Nijkerk, Noordenveld, Noordwijk, Nunspeet, Oldambt, Oldebroek, Oosterhout, Oss, Oude-IJsselstreek, Oude Pekela, Oudewater, Overbetuwe, Rheden, Rhenen, Ridderkerk, Rijnwaarden-Zevenaar, Rijssen-Holten, Roerdalen, Roermond, Roosendaal, Rotterdam, Rucphen, Scherpenzeel, Sint-Michielsgestel, Sittard-Geleen, Slochteren, Smallingerland, Stadskanaal, Stein, Stichtse Vecht, Teylingen, Tilburg, Tynaarlo, Uitgeest, Utrecht, Utrechtse Heuvelrug, Veendam, Waalwijk, Waterland, Wijk bij Duurstede, Westervoort, Westvoorne, Woensdrecht, Woerden, Zoetermeer en Zoeterwoude

**Comment by heyajohnny** [comment]
I've just added Zevenaar. Please let me know if all works as expected ;)
