### ISSUE TITLE
How to use is_collection_date_today

### ISSUE THREAD

**Issue by johanb7** [heyajohnny/afvalinfo#68]
HI,
How do I use the attribute: is_collection_date_today ?

**Comment by heyajohnny** [comment]
You can use it to do some if / else logic, just like the code below (for another attribute called 'days_until_collection_date').

The 'is_collection_date_today' attribute returns true if the collection date is today and return false if the collection date isn't today.

I personally don't use it, so I don't have a better example than this one below.

> afval_morgen:
		friendly_name: "Afval morgen"
        value_template: >
          {% if state_attr('sensor.afvalinfo_gft', 'days_until_collection_date') ==1 %}
            {{ state_attr('sensor.afvalinfo_gft', 'friendly_name') }}
          {% elif state_attr('sensor.afvalinfo_oud_papier', 'days_until_collection_date') ==1 %}
            {{ state_attr('sensor.afvalinfo_oud_papier', 'friendly_name') }}
          {% elif state_attr('sensor.afvalinfo_pbd', 'days_until_collection_date') ==1 %}
            {{ state_attr('sensor.afvalinfo_pbd', 'friendly_name') }}
          {% elif state_attr('sensor.afvalinfo_restafval', 'days_until_collection_date') ==1 %}
            {{ state_attr('sensor.afvalinfo_restafval', 'friendly_name') }}
          {% else %}
            Niets
          {% endif %}
