### ISSUE TITLE
sensor.afvalinfo_today en sensor.afvalinfo_tomorrow Oud Papier

### ISSUE THREAD

**Issue by dworkin74** [heyajohnny/afvalinfo#71]
Hi,
Deze sensors geven bij oude papier de state "oud"
Kan dit aangepast worden naar "Oud papier" of "Papier"?

**Comment by heyajohnny** [comment]
Ik heb zojuist een fix doorgevoerd. Je zou nu "papier" als resultaat terug moeten krijgen.
Zou je me nog kunnen laten weten of het zo goed werkt? Alvast bedankt.

**Comment by dworkin74** [comment]
Je bent snel! Het werkt goed zo. Dank je.

**Comment by heyajohnny** [comment]
Ja, dit was een kleine bug met een kleine fix en gelukkig snel op te lossen.
Top dat het werkt! ;)
