### ISSUE TITLE
Datum naar Nederlands

### ISSUE THREAD

**Issue by L4ngeFrank** [heyajohnny/afvalinfo#75]
Hey Johnny, allereerst een top addon,!! Maar een wens (van waarschijnlijk vele Nederlanders) is of je de weekdag en maand kunt vertalen in het Nederlands? 

Ik heb het [hier](https://community.home-assistant.io/t/date-formatting/17461/102) al gevraagd. (scroll naar beneden) Maar ben bang dat het lastig wordt aangezien er regelmatig updates zijn en daardoor lastig is om het aan te passen. Is er dus een mogelijkheid dat je dit standaard in de addon kunt integreren?

Thanks voor de reactie en keep up the good work!

**Comment by L4ngeFrank** [comment]
Collega [githubber](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer) Pippyn is er in geslaagd, Misschien mag je het van hem gebruiken? Beter goed gejat dan slecht verzonnen hahaha ;)

**Comment by heyajohnny** [comment]
Bij Pippyn zie ik alleen een vertaling in de dagen van de week.
Maar ik heb wel een idee hoe ik dit kan implementeren. Zowel de dagen van de week alsook de benaming van de maanden.

**Comment by heyajohnny** [comment]
Ik heb zojuist een update doorgevoerd voor vertalingen.
Met de opties:

> dateformat: '%A %d-%B-%Y'
> locale: 'nl'

wordt de datum van vandaag getoond als:
donderdag 30 april 2020

Zie ook de README file, mocht het niet helemaal duidelijk zijn.
Ik hoop dat ik je hiermee geholpen hebt.

Wil je nog even laten weten of alles werkt? Alvast bedankt ;)

**Comment by L4ngeFrank** [comment]
Wat goed dat je dit zo snel hebt opgepakt! HELD!
Helaas gaat er iets niet goed. Bij het opstarten komt de datum netjes in het Nederlands, echter als ik een refresh doe of later de pagina opvraag (PC en tablet) krijg ik dit:
![afval](https://user-images.githubusercontent.com/37044307/80746967-f859b900-8b22-11ea-84ae-a8012d7039f8.png)

**Comment by heyajohnny** [comment]
Ik heb nog een update doorgevoerd. Als het goed is moet hij nu wel blijven werken

**Comment by L4ngeFrank** [comment]
He-le-maal perfect! Topper
