### ISSUE TITLE
can you add Nijmegen?

### ISSUE THREAD

**Issue by rupdo** [heyajohnny/afvalinfo#77]
Hey hoi

Aangezien mn huisgenootjes dit altijd vergeten lijkt me dit super handig 
krijgen ze gewoon een push notification op hun telefoon.

tnx voor het schrijven van de integration love it !!

groetjes Ruben

**Comment by heyajohnny** [comment]
Note to myself: https://afvalkalender.dar.nl/adres/6515BP:33
Dar verzorgt de afvalwijzer voor de gemeenten Berg en Dal, Beuningen, Druten, Heumen, Nijmegen en Wijchen

**Comment by heyajohnny** [comment]
Ik heb zojuist alle locaties van Dar toegevoegd, inclusief Nijmegen ;)
