### ISSUE TITLE
Papier not working for Venlo

### ISSUE THREAD

**Issue by SPLeon** [heyajohnny/afvalinfo#78]
Heya,

First time using this plugin. Really nice, many thanks.
Papier for Venlo gives status unknown.

Also want to know how you can present is as a card? Just add entities card or do you have something fancy?

**Comment by bpwats** [comment]
Same here for Almere:
Entiteit niet beschikbaar: sensor.afvalinfo_restafval
Entiteit niet beschikbaar: sensor.afvalinfo_pbd
Entiteit niet beschikbaar: sensor.afvalinfo_papier

Used to work before latest update / commit.

**Comment by Overlegne** [comment]
Same for Cuijk, only GFT is working for now, no change with last update.

**Comment by heyajohnny** [comment]
> First time using this plugin. Really nice, many thanks.
> Papier for Venlo gives status unknown.

Ahh... I didn't knew that Venlo supported 'Papier'. The Postcode Streetnumber combinations I used for testing didn't had 'Papier'.

I've just pushed a new version. You should see a result for papier now.

> Also want to know how you can present is as a card? Just add entities card or do you have something fancy?

Please look at [lovelace](https://www.home-assistant.io/lovelace/) for UI stuff or browse the Home Assistant forum for support.

**Comment by heyajohnny** [comment]
> Same here for Almere:
Entiteit niet beschikbaar: sensor.afvalinfo_restafval
Entiteit niet beschikbaar: sensor.afvalinfo_pbd
Entiteit niet beschikbaar: sensor.afvalinfo_papier

Works just fine when I test it with this combination:  almere 1317BE 1

**Comment by heyajohnny** [comment]
> Same for Cuijk, only GFT is working for now, no change with last update.

You should get the same results as on [deafvalapp](http://www.deafvalapp.nl/)

**Comment by Overlegne** [comment]
> > Same for Cuijk, only GFT is working for now, no change with last update.
> 
> You should get the same results as on [deafvalapp](http://www.deafvalapp.nl/)

PMD works in deafvalapp, but in HA it shows up as unavailable. I'll look into it tomorrow! Thanks

**Comment by bpwats** [comment]
> > Same here for Almere:
> > Entiteit niet beschikbaar: sensor.afvalinfo_restafval
> > Entiteit niet beschikbaar: sensor.afvalinfo_pbd
> > Entiteit niet beschikbaar: sensor.afvalinfo_papier
> 
> Works just fine when I test it with this combination: almere 1317BE 1

Must have been a different problem, but not in your code. I works again. So please ignore my issue.

**Comment by heyajohnny** [comment]
> PMD works in deafvalapp, but in HA it shows up as unavailable. I'll look into it tomorrow! Thanks
In Cuijk heet het weer net iets anders zie ik. Volgens mij zou het nu moeten werken...

**Comment by SPLeon** [comment]
Heyajohnny,

Papier is working fine now :-) Thanks!.

You can close the issue as I opened it :)
