### ISSUE TITLE
Request: Trash type tomorrow

### ISSUE THREAD

**Issue by 0000vt** [heyajohnny/afvalinfo#79]
Is het mogelijk om een sensor toe te voegen die weer geeft of er morgen een afval ophaal moment is ipv vandaag? Containers zetten we vaak de avond er voor aan de weg, dus dan zou ik het mooi 's avonds kunnen zien in het overzicht.

**Comment by heyajohnny** [comment]
De sensor trash_type_tomorrow bestaat al :)
