### ISSUE TITLE
use other source

### ISSUE THREAD

**Issue by NdS-Research-Facilities** [heyajohnny/afvalinfo#8]
any idea to use https://www.mijnafvalwijzer.nl/nl/3825AL/41
This site has all data in a unified format for some Dutch gemeenten

**Comment by heyajohnny** [comment]
I tried several places, but none of them work.... Only the demo (3825AL/41) seems to work.
Do you have any working Postcode / huisnummer?

**Comment by heyajohnny** [comment]
I'm closing this issue, since you can't provide concrete data
