### ISSUE TITLE
Dates not correctly displayed with locale

### ISSUE THREAD

**Issue by Rikkie80** [heyajohnny/afvalinfo#80]
Integration is working, but date is not correctly displayed with 'locale'. Date is displayed as "EEE 1 MMM". When commenting out locale the date is correctly displayed

My integration:
`- platform: afvalinfo
    resources:
    - pbd
    - gft
    - papier
    - restafval
    - trash_type_today
  city: veldhoven
  postcode: xxxxxx
  streetnumber: xx
  dateformat: '%a %w %b'
  locale: 'nl'
  timespanindays: 365`

**Comment by heyajohnny** [comment]
Can you update to the latest version? I thought I fixed it yesterday, in my latest commit, but I might be wrong. 

Please let me know if it still occurs after you've updated afvalinfo

**Comment by pvermeij** [comment]
I had the same problem. After installing the latest version it is indeed fixed.
Thanks!

**Comment by Rikkie80** [comment]
Yes, indeed it works correctly after installing the latest version. Thanks!

**Comment by heyajohnny** [comment]
Oke, nice! I'll close the issue then.
