### ISSUE TITLE
Platform error sensor.afvalinfo - No module named 'babel'

### ISSUE THREAD

**Issue by tonyschuite** [heyajohnny/afvalinfo#81]
Platform error sensor.afvalinfo - No module named 'babel'

platform HomeAssistant on Freenas with babel installed through pip

**Comment by heyajohnny** [comment]
I've pushed an update. Can you let me know if it's working now?

**Comment by heyajohnny** [comment]
I'm closing the issue. If it still doesn't work, you can open a new issue
