### ISSUE TITLE
Missing village: Uithoorn / de Kwakel

### ISSUE THREAD

**Issue by joop3** [heyajohnny/afvalinfo#82]
Very nice add-on for HA!
Is it possible to add the villages uithoorn / de Kwakel?

Not sure where you get the information from, but if I look at the website of Uithoorn they provide a pdf with the schedule so maybe this complicate things?
https://www.uithoorn.nl/Home/Afval/Afvalkalender

**Comment by heyajohnny** [comment]
I think that I need to disappoint you. The PDF only contains street names and since there is no reference to any postcode street number combination in the PDF I can't match it to a date. Maybe the 'gemeente' Uithoorn is willing to make a decent 'afvalkalender' in the near future, but for now, I'm sorry, but I can't add Uithoorn :(

**Comment by joop3** [comment]
Hmm, was afraid of that, I will send an email to the ' gemeente' to see if they have an alternative.
Thanks for looking into this!

**Comment by heyajohnny** [comment]
Any news?

**Comment by joop3** [comment]
I did (after a month or so) receive feedback (sorry is in dutch):

Wij gebruikten jarenlang de afval-app ‘Recyclemanager’. Het invoeren en bijhouden van de gegevens in de app was tijdrovend voor de gemeente. Maar de kosten werden gedragen door het verpakkende bedrijfsleven.

Uit onderzoek bleek dat onze inwoners voornamelijk de afvalkalender downloaden. Toch hebben wij, toen deze app per 1 januari 2018 werd opgeheven, gezocht naar een andere app. Daar bleken hoge kosten aan te zijn verbonden.

Om de afvalstoffenheffing zo laag mogelijk te houden, hebben wij besloten om geen app meer aan te bieden. Men kan nog steeds de afvalkalender downloaden via de website. Maar de data moet men vooralsnog zelf in de agenda zetten.

How typical, how to overcomplex things :)
So it is basically a no go I'm afraid...

**Comment by heyajohnny** [comment]
And for 2021 it's the same :( I'm closing this issue...
