### ISSUE TITLE
Please add "Terheijden", gemeente "Drimmelen"

### ISSUE THREAD

**Issue by hekomjeheen** [heyajohnny/afvalinfo#86]
Heyajohnny!

Tnx for all the effort!
Please add "Terheijden", gemeente "Drimmelen"

Not sure what i can do for you, but here there is some info: https://drimmelen.nl/afvalinzameling

Hope you doing okay these days!

**Comment by heyajohnny** [comment]
I've just added Drimmelen, including Terheijden.
I'm fine :) Enjoy and please let me know if all works as expected ;)

**Comment by hekomjeheen** [comment]
Perfect! 



Verstuurd vanaf mijn iPhone
