### ISSUE TITLE
Please Add Ouddorp gemeente Goeree Overflakkee

### ISSUE THREAD

**Issue by DotNet2Web** [heyajohnny/afvalinfo#87]
Hi,

Thanks for creating this integration. Is it possible to add the above city to the integration?

https://webadapter.watsoftware.nl/afvalkalender.html

**Comment by heyajohnny** [comment]
I've just added Goeree-Overflakkee including Ouddorp. Enjoy ;) And please let me know if all works as expected

**Comment by DotNet2Web** [comment]
Thanks !!!!

Your the best now I will never forget anymore which dumpster I should place at the road!

Can I use mdi icons in the integration?

**Comment by heyajohnny** [comment]
> Can I use mdi icons in the integration?

I think you're looking for something like this:
https://www.home-assistant.io/docs/configuration/customizing-devices/

**Comment by heyajohnny** [comment]
I'm closing this issue, since the original issue is solved
