### ISSUE TITLE
No Papier info in Barendrecht (BAR

### ISSUE THREAD

**Issue by ashwin2101** [heyajohnny/afvalinfo#88]
state for paper  is unknown.
GTF is working
Timespanindays is 365

When I check at the calendar paper is pickup on monday 29 juni

(https://www.bar-afvalbeheer.nl/afvalkalender)
postcode: 2993 XN ,
housenumber : 2 (not my real number)

**Comment by heyajohnny** [comment]
Strange... Works fine with me.
![image](https://user-images.githubusercontent.com/20553716/82725482-9a616100-9cdd-11ea-8c50-ee173fe5618d.png)

Do you get any warning or error message in your log, about afvalinfo?

**Comment by ashwin2101** [comment]
strange..
I don't see any error, 
In my test enviroment I also get no papier info.

This is mij yaml code:

`  - platform: afvalinfo
    resources:
      - trash_type_today
      - trash_type_tomorrow
      - gft
      - papier
    city: barendrecht
    postcode: 2993XN
    streetnumber: 76
    dateformat: '%d-%m-%Y'
    locale: 'nl'
    timespanindays: 365`

This is the only warning I see in the log
![image](https://user-images.githubusercontent.com/56930394/82763690-c37f1000-9e09-11ea-9ba9-05c2f6e78ae0.png)

**Comment by heyajohnny** [comment]
All works as expected, as far as I can see. There is no data available for your address after May 2020.
Unfortunately I can't retrieve data that isn't there :(
![image](https://user-images.githubusercontent.com/20553716/82796728-52c20d00-9e76-11ea-8fdf-fb6b13035720.png)
![image](https://user-images.githubusercontent.com/20553716/82796564-04ad0980-9e76-11ea-9b01-a66ea6e4d51d.png)

**Comment by heyajohnny** [comment]
I'm sorry, but I'm closing this issue, since I can't fix the missing data. :(

**Comment by ashwin2101** [comment]
No problem, I totally understand, Thank you
