### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Warstomper** [heyajohnny/afvalinfo#9]
Zou het een mogelijkheid zijn om de sensors van een extra attribute/waarde te voorzien welk ON/OFF doen, naargelang het "ophaaldag" is? 

Ik probeer een Hue lamp aan te sturen (Zodat ie blauw/groen wordt op de ophaaldagen) met een Node-red flow, en datums vergelijken (Is de input datum vandaag) in Node-red gaat mijn pet nog (even) te boven. Wanneer ik een On/Off waarde kan uitlezen gaat me dit sowieso lukken :)

**Comment by heyajohnny** [comment]
Ik heb 2 extra attributen toegevoegd:
-days_until_collection_date.    This will return the number of days between today and the collection date.
-is_collection_date_today.      This will return true if the collection date is today and false if the collection date is not today.

Dit zou volgens mij voldoende moeten zijn :)
