### ISSUE TITLE
Wijzigen date format -> Afvalinfo Today werkt niet meer

### ISSUE THREAD

**Issue by JDunnio** [heyajohnny/afvalinfo#91]
Hoi,

Allereerst bedankt voor de geweldige plugin!

Mijn probleem:
Als ik date-format wijzig naar '%A %d %B' (b.v. maandag 25 mei) dan werkt de sensor "Afvalinfo Today" niet meer. Deze blijft dan op 'none' staan.

Is hier een fix voor te vinden?

**Comment by heyajohnny** [comment]
Ik heb zojuist een fix gemaakt. Nadat je afvalinfo hebt ge-updated zou het weer moeten werken.

**Comment by JDunnio** [comment]
Doet het weer! Super bedankt!
