### ISSUE TITLE
HMS Den Haag

### ISSUE THREAD

**Issue by fleshyflat** [heyajohnny/afvalinfo#92]
Zou de afval kalender van den Haag worden toegevoegd?

**Comment by fleshyflat** [comment]
could you please add HMS/Den haag

**Comment by heyajohnny** [comment]
I hope that I can add it soon, but I'm having some trouble with the requests... :(

**Comment by heyajohnny** [comment]
I've just added Den Haag. Please let me know if all works as expected

**Comment by fleshyflat** [comment]
Thanks, it's working
