### ISSUE TITLE
no module named  dateutil

### ISSUE THREAD

**Issue by DotNet2Web** [heyajohnny/afvalinfo#96]
Goodmoring.

Before upgrading HA, I check my configuration to make sure everything is still running like it supposed to do.

Checking before the newest version returned this error:

Failed config
  General Errors: 
    - Platform error sensor.afvalinfo - No module named 'dateutil'

Just to let you know. If there is anything I can do to help out let me know.

**Comment by heyajohnny** [comment]
Thnx!
I've just added python-dateutil as requirement in the 'manifest.json'. That should probably fix it. Maybe you could let me know if the latest update fixes the error? Thnx ;)

**Comment by DotNet2Web** [comment]
Mission accomplished 👍 

[14:43:38] INFO: Checking your configuration against this version...
[14:58:50] INFO: Configuration check finished - no error found! :)
