### ISSUE TITLE
Suez location(s) broken

### ISSUE THREAD

**Issue by mavink78** [heyajohnny/afvalinfo#97]
It looks like Suez changed their website. The full calendar is no longer included at https://inzamelwijzer.suez.nl/adres/{zip}:{housenumber}, but moved to https://inzamelwijzer.suez.nl/adres/{zip}:{housenumber}::/jaarkalender

**Comment by heyajohnny** [comment]
It should still work. Maybe the update broke your configuration.
Have you already changed this in your configuration.yaml?
`city: [city/village name]`
to
`location: arnhem`

For more information, check the README @ https://github.com/heyajohnny/afvalinfo

**Comment by mavink78** [comment]
Interesting, I had changed to the location-based configuration, and received errors retrieving the schedule several times, but today it's working again.
