### ISSUE TITLE
No information since update.

### ISSUE THREAD

**Issue by willsmarthome** [heyajohnny/afvalinfo#98]
Since last update no more informatie abouw REST, PBD, GFT, etc.

**Comment by willsmarthome** [comment]
Solved.

**Comment by willsmarthome** [comment]
beilen was no longer a place, changed to midden-drenthe

**Comment by heyajohnny** [comment]
Good to hear! 
Sorry for the change from city -> location, but it was too time robbing to maintain all the place names.
