### ISSUE TITLE
no data in almere

### ISSUE THREAD

**Issue by ceesie15** [heyajohnny/afvalinfo#99]
Hi there,

I just installed you're plugin using the HACS addon in home-assistant. I added all the config properties like beneath but getting an Nonetype error response:
`
- platform: afvalinfo
  resources:
    - restafval
  location: almere
  postcode: 1336 TT
  streetnumber: 109
`
Do you know what could causing this problem or am i doing something wrong?

Greetz, Frank

**Comment by heyajohnny** [comment]
It seems that it also doesn't work the official site:
https://afvalportaal.2go-mobile.com/modules/53d8db94-7945-42fd-9742-9bbc71dbe4c1/kalender/

![Screenshot_20200607-223316](https://user-images.githubusercontent.com/20553716/83979547-758d0080-a90f-11ea-82f7-51db07c7449b.png)

If it doesn't work on the official site, it also doesn't work here :(

**Comment by ceesie15** [comment]
thanks for your quick response. I'll tell our municipality why it doesn't work.

**Comment by squandor** [comment]
Hi there, i was working with ceesie15 on this matter but when i type in his zipcode on the site it asks which address to use. apparently there are 2 streets with this zipcode and house number. 
Is it possible to set optional an specific street with the options in the plugin?
https://afvalportaal.2go-mobile.com/modules/53d8db94-7945-42fd-9742-9bbc71dbe4c1/kalender/calendar.html?325609&Diadeemstraat---109%20%20%20---1336TT---Almere---
This is his kalender if i am correct. 

Greetings, Squandor

**Comment by heyajohnny** [comment]
@squandor That's probably a f*ckup from Almere.
But... When I checked the address you gave me, I missed some mappings. I've just added some extra mappings (pbd/restafval combination) and (gft without restafval) so it should work now after you update Afvalinfo. 

Enjoy ;)

**Comment by squandor** [comment]
@heyajohnny great thank you we will try it. do we need to change some configs or should it work like the examples?

**Comment by heyajohnny** [comment]
> great thank you we will try it. do we need to change some configs or should it work like the examples?

Should work like the examples
